### ISSUE TITLE
Long Web Content Titles Extend Past Context Box, 1.x issue

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/clay#1011]
Displaying a web content with a long name in a web content display will cause the title to extend pass the context box. This also makes it impossible to edit the web content since the ellipses for web content is off screen. This can be fixed by adding autofit-* to 1.x.

Autofit-* has already been added to Classic Theme but not fully [`54b7a4b`](https://github.com/liferay/liferay-portal-ee/commit/54b7a4befbea2f5fda41cb69c783c7411ef5f14c#diff-f51966f3f2070934065e38ac12841b2a). Being in 1.x will allow clients that use custom theme to obtain this fix.
I also spoke with support regarding Flexbox and the compatibility with IE9. [Support](https://issues.liferay.com/browse/LRSUPPORT-23804?focusedCommentId=1357404&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1357404) They have decided to allow Flexbox so long as it will not lose functionality for IE9 which in this case it does not.
Let me know if you have any questions or comments.
Thank you!

**Comment by fortunatomaldonado** [comment]
The fix for 1.x is found here: https://github.com/liferay/clay/pull/1012

**Comment by pat270** [comment]
Hey @fortunatomaldonado,
I don't think it's appropriate to add this in Clay 1.x. It was never meant to support flexbox. Can we add the autofit stuff in Styled Theme instead of here?

**Comment by fortunatomaldonado** [comment]
Hello @pat270,
I seem to have misunderstood again, I apologize. Yeah I believe adding it to Styled Theme will also work. Thank you for the help!

**Comment by jbalsas** [comment]
Closing here, then!
