### ISSUE TITLE
Clay dropdown markup isn't following the Lexicon guideline when using a radio button or checkbox

### ISSUE THREAD

**Issue by interaminense** [liferay/clay#1044]
Hey guys, 

I'm Adriano, Front-End Engineer of the project Experience Cloud (Cerebro) and an issue has been opened on the jira to fix the problem below:
[https://issues.liferay.com/browse/CEREBRO-992](https://issues.liferay.com/browse/CEREBRO-992)

I saw that clay is not following the pattern defined by lexicon, so I opened this issue here.

Following the lexicon guideline, the dropdown item with radio button and checkbox that is not selected should have the normal weight, but currently it is with the bold weight.

**Clay Dropdown markup**
<img width="256" alt="screen shot 2018-06-27 at 11 10 26" src="https://user-images.githubusercontent.com/12699849/41979612-e346c58e-79fa-11e8-9f5c-951deb6128f2.png">

**Lexicon Dropdown guideline**
<img width="209" alt="screen shot 2018-06-27 at 11 10 40" src="https://user-images.githubusercontent.com/12699849/41979624-e871d5c6-79fa-11e8-96fa-dad6ec7eaa0f.png">

**Comment by matuzalemsteles** [comment]
hey @pat270, can you take a look at this?

**Comment by pat270** [comment]
Hey Guys,

Just sent a fix for this, Thanks!
