### ISSUE TITLE
[clay-charts] "xs" is missing from the state declaration of ChartBase

### ISSUE THREAD

**Issue by kienD** [liferay/clay#1064]
`config.xs` should be equal to `state.xs` but we do not declare "xs" in the state of `ChartBase`.
 
https://github.com/liferay/clay/blob/c01e3e4b83781386f3defbf059570b2a590ffe79/packages/clay-charts/src/ChartBase.js#L335-L354

https://github.com/liferay/clay/blob/c01e3e4b83781386f3defbf059570b2a590ffe79/packages/clay-charts/src/ChartBase.js#L1410-L1437

**Comment by julien** [comment]
Hi @kienD,

Thanks for reporting this!

I know the code might be a bit confusing but we actually map `x` to `xs` in `ChartBase`, which  might have been a good idea some at point.

See: 
https://github.com/liferay/clay/blob/1a70358779cdd10bf5e99ceb0487cb0c88033b0b/packages/clay-charts/src/ChartBase.js#L8-L16

https://github.com/liferay/clay/blob/1a70358779cdd10bf5e99ceb0487cb0c88033b0b/packages/clay-charts/src/ChartBase.js#L300-L303

But it appears that `x` and `xs` expect different types (`String` vs `Object`), so you're right, we need to add `xs` in `ChartBase` and stop "mapping"  `xs` to `x` automatically.

Thanks
