### ISSUE TITLE
ClayCSS: Consider adding a new file that imports only Bootstrap and Clay Mixins for use in Sass files outside of Clay

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1069]
We have `atlas-variables.scss` and `base-variables.scss` that bundles all Clay functions + variables + mixins. We should consider creating a mixin file that bundles functions + mixins so that they can be made available in Sass files outside of Clay. The mixin file should also provide a way for devs to include custom mixins.

**Comment by jbalsas** [comment]
We're at least using this in DXP, so I'll count it as done and move on. We can reopen if necessary.
