### ISSUE TITLE
[clay-charts] Upgrade billboardJS version to 1.5

### ISSUE THREAD

**Issue by kienD** [liferay/clay#1072]
There is a fix for a bug that we need in billboardJS version 1.5.

Do you think it would be possible to upgrade clay-charts to utilize billboardJS 1.5?

**Comment by julien** [comment]
Hi again @kienD,

Just a let you know, I submitted a [pull request](https://github.com/liferay/clay/pull/1074) earlier that updates billboard to 1.5.1.

**Comment by kienD** [comment]
@julien Thanks! 🔥
