### ISSUE TITLE
Tooltip default position

### ISSUE THREAD

**Issue by boton** [liferay/clay#1082]
I find it unnatural that the tooltip's default position is [`Bottom`](https://github.com/liferay/clay/blob/master/packages/clay-tooltip/src/ClayTooltip.js#L380).
I suggest we follow the [bootstrap way of use](https://getbootstrap.com/docs/4.0/components/tooltips/#options)  which defaults to "Top".

**Comment by julien** [comment]
Hey @victorg1991, @marcoscv and @pat270,

When you have a moment could you tell us what you think about this proposal?

Thanks!

**Comment by julien** [comment]
Thanks for the feedback @victorvalle !
