### ISSUE TITLE
Improve the component build process

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1107]
### Disclaimer
It is only natural that we begin to have more components in the future, as our build time begins to increase. We can improve the build process to be faster...

### Proposal
I was thinking a while ago that we could have a `script` to do the build in the root folder, instead of running a `lerna build` that will give the build in each package. We can create the script to take all the packages and perform the build only once with webpack or another... we can still stay with the builds located in the package so that we do not have to run the build of all the packages.

Benefits:

* Build faster
* CI will run faster
* Improves the internal development of components

**Comment by matuzalemsteles** [comment]
hey @julien, Thank you for that. But maybe I have not clarified the right idea. But at the beginning it would be to build all the packages from an instance of the webpack and not go out running a `npm run build` in each package, as lerna does. It would have one more impact on CI and for us at times we need to compile all the packages.

Please let me know if it is still unclear.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, this sounds interesting. For CI, though... If I remember correctly, we shouldn't even need the webpack bundles, since that's not what we use for those tests. We might simply have a more fine-grained configuration so we can run less stuff on CI?

**Comment by matuzalemsteles** [comment]
hey @jbalsas, Yes indeed I think we just need to run `npm run soy` in CI `build` and `compile` will not be necessary, since jest runs babel to transpile everything when it will run the tests, maybe we have redundancies in the CI.
