### ISSUE TITLE
Explore Puppeteer and Puppeteer Recorder for Clay functional tests 

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1108]
With the release of [Puppeteer](https://pptr.dev/) we can use Headless Chrome to run integration and functional tests.

I've recently stumbled across [Puppeteer Recorder](https://github.com/checkly/puppeteer-recorder).

It could be interesting to explore possible usages of this to automate and run functional tests of our components.

**Comment by diegonvs** [comment]
We could try use https://cypress.io in 3.x, what do you think guys @jbalsas @matuzalemsteles @bryceosterhaus?

**Comment by jbalsas** [comment]
I think we have a solid integration workflow right now that's working for the team.

@bryceosterhaus , @kresimir-coko , feel free to reopen or file a new one if still necessary
