### ISSUE TITLE
ClayActionsDropdown is not align the dropdown correctly

### ISSUE THREAD

**Issue by clovisdasilvaneto** [liferay/clay#1118]
Hello everyone,

I'm having a problem when I try to use the ClayActionsDropdown on Liferay forms team. The expected behavior was that the dropdown was aligned by the BottomRight position in my "div container", but actually it's aligning on the BottomLeft position, as is showing in the image bellow:
<img width="326" alt="screen shot 2018-08-28 at 3 14 36 pm" src="https://user-images.githubusercontent.com/4555665/44742253-c71b2100-aad5-11e8-9c67-13d71fd34420.png">

When I went to take a look in the ClayDrodownBase file with @matuzalemsteles , we saw that in the `_handleRenderedPortal` method the dropdown is aligned by using metal-position, and it's predefined to use the `Align.BottomLeft` position, but in my case, the ideal position to align my component would be `Align.BottomRight`, so when I edited this method in my developer tools, it works. Bellow is the result of my expected component behavior after I replace `Align.BottomLeft` by `Align.BottomRight`:

<img width="527" alt="clay" src="https://user-images.githubusercontent.com/4555665/44742165-90dda180-aad5-11e8-9170-6ecf796221a2.png">

I think the dropdown position could have a predefined value, but the developer could also inform the dropdown align position.

**Comment by matuzalemsteles** [comment]
hey @carloslancha, we can open the API so that the devs can decide the preferred position and expose next to the API of `Align` with the component to pass the positions or we can simply define within the component... what do you think?

Something like:
```javascript
preferredAlignedPosition: Config.oneOf(['TopCenter', 'RightCenter'...]).setter('_setPreferredAlignedPosition');
```
