### ISSUE TITLE
out of date docs ?

### ISSUE THREAD

**Issue by arashsc** [liferay/clay#1128]
first of all let me congratulate you for a clean and functional design system.
 i used clay(^2.3.0) to set things up, specifically the vue example, here is the issue:

### navbar web component suggested in docs
```html
<clay-navbar
	items='[
		{"title": "App Section 1", "url": "#1"},
		{"title": "App Section 2", "url": "#1"},
		{"title": "App Section 3", "url": "#1"},
		{"title": "App Section 4", "url": "#1"},
		{"title": "App Section 5", "url": "#1"},
		{"title": "App Section 6", "url": "#1"},
		{"title": "App Section 7", "url": "#1"}
	]'
	spritemap="/images/icons/icons.svg">
</clay-navbar>
```
didin't work at all

### what actually worked after diving deep
```html
<clay-navigation-bar
      items='[
        {"label": "App Section 1", "href": "#1"},
        {"label": "App Section 2", "href": "#2"},
        {"label": "App Section 3", "href": "#3"}
      ]'
      spritemap="/assets/icons.svg">
</clay-navigation-bar>
```

**Comment by matuzalemsteles** [comment]
hey @arashsc, thank you for reporting this! We're working on improving our documentation, if you'd like to keep track of, keep an eye on issue #1111 and feel free to contribute and send PR!
