### ISSUE TITLE
Add Legend Data for Stacked Bar Chart.

### ISSUE THREAD

**Issue by dantasjadson** [liferay/clay#1138]
Currently it's possible to have a legend for each Stacked Bar, but it's not possible to add an amount information, below the column name. It's strongly necessary because the chart should display quantitative data for each column.

Currently 
![currently-error](https://user-images.githubusercontent.com/1027401/44864719-c231ab00-ac56-11e8-8c41-c8d6de5af0b6.png)

Expected result
![expected-result](https://user-images.githubusercontent.com/1027401/44864720-c231ab00-ac56-11e8-8ef8-4abee4906647.png)

**Comment by matuzalemsteles** [comment]
hey @julien, It seems that currently we can only pass to `axisX.tick.values` a `string` or `number`, so they do not have a certain freedom of being able to change or have line breaks... I think we just need to give their freedom to pass an HTML to the values, so they can customize whatever. 

It would have to be made a contribution with **Billboard.js** probably. What do you think?

**Comment by julien** [comment]
Hey @matuzalemsteles, 

I'm not sure about letting users pass HTML because of the way the charts are rendered, as you can see in this screenshot the axis values are rendererd with SVG elements.

<img width="655" alt="Chart axis tick values" title="Chart axis tick values" src="https://user-images.githubusercontent.com/5572/44894762-bf37c880-acf1-11e8-8520-11c7d3807db2.png">

However, I agree that it might be a good idea to ask the **Billboard.js** team what they think about it.

**Comment by jbalsas** [comment]
Based on our past experience, I think they'd be open to accept either a template-like feature or a callback-like one that would allow us to render anything there.

**Comment by julien** [comment]
@jbalsas yes that's also what I was thinking 👍

**Comment by julien** [comment]
I have good news; after asking on Billboard.js's Github, I realised the option was already there.

Here's a example that could be used:

```javascript
const chart = new metal.BarChart({
	axisX: {
		tick: {
			multiline: true
		},
		type: 'category'
	},
	data: [
		{
			data: ['01\nMultiline', '02\nText', '03\nOn', '04\nThe X', '06\nAxis'],
			id: 'x'
		},
		{
			data: [30, 200, 100, 400, 150, 250],
			id: 'data1'
		},
		{
			data: [150, 90, 30, 400, 15, 205],
			id: 'data2'
		},
		{
			data: [10, 30, 130, 200, 50, 20],
			id: 'data3'
		}
	],
	x: 'x'
}, '#chart');
```

Which would render something like this:

<img width="1162" alt="chart" src="https://user-images.githubusercontent.com/5572/44985165-99275800-af7f-11e8-8ef3-72cda4fd7594.png">


@dantasjadson please let me know if this would solve your problem, 

Thanks!

**Comment by matuzalemsteles** [comment]
cc @interaminense

**Comment by dantasjadson** [comment]
Hi, @julien. 

@matuzalemsteles Told me that you talked to billboard team and might be possible to customize the chart for our current need. Then, I'll give you more info regarding this feature in orther to you get more context about our need.

[Take a look on this prototype](https://liferay.invisionapp.com/share/BENUTLLXG6V) and in case of doubts you can leave a comment there.
Thanks in Advance.

CC: @interaminense

**Comment by jbalsas** [comment]
I think this has been discussed internally. 

As far as I understand, we shouldn't try to show values that show in other expected places in the category axis.

**Comment by dantasjadson** [comment]
Right, @julien. I'm closing this issue, we are making some explorations on how to display these type of data and we are thinking about use other kind of chart. Thanks for your support.

CC: @interaminense @matuzalemsteles
