### ISSUE TITLE
results-bar - color contrast in links

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1147]
Contrast is not enough:

![image](https://user-images.githubusercontent.com/7963804/44908153-c32c1080-ad1a-11e8-840d-caa552b45afe.png)

![image](https://user-images.githubusercontent.com/7963804/44908211-f4a4dc00-ad1a-11e8-97a9-5834dc1b92f4.png)

**Comment by atjuan** [comment]
As the color of the bar is provisional right now we can use the primary color for texts in this case.
 #272833

**Comment by matuzalemsteles** [comment]
I'm closing this once it has already been fixed at #1188.
