### ISSUE TITLE
Add the ability to add more than one action in Results Bar

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1151]
The action buttons in ResultsBar can become an extension point so people can add more actions.

<img width="238" alt="screen shot 2018-08-30 at 21 20 24" src="https://user-images.githubusercontent.com/13750819/44916881-2adb5f00-ad0d-11e8-9e64-58c07bf409cf.png">

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@matuzalemsteles, please reopen if you think this is still relevant in the context of our `3.x` components.

Thanks!
