### ISSUE TITLE
Make use of ClayPortal in ClayDropdown configurable

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#1153]
Move dropdown to portal layer can generate semantic/SEO problems because we are breaking the nested items so would be great if we could specify in component dropdown or component which use dropdown if they want to use portal layer or not.

![image](https://user-images.githubusercontent.com/7963804/44981684-9d4d7880-af73-11e8-87ad-8e36615395e1.png)

**Comment by matuzalemsteles** [comment]
hey @carloslancha I remember you were working and sent a PR but had closed, had any reason for not having continued with this?

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@matuzalemsteles, @carloslancha, please reopen if you think this is still relevant in the context of our `3.x` components.

Thanks!
