### ISSUE TITLE
Management-bar / dropdown with portal - Semantic/SEO broken

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1156]
Move dropdown to portal layer can generate semantic/SEO problems because we are breaking the nested items so would be great if we could specify in component dropdown or component which use dropdown if they want to use portal layer or not.

![image](https://user-images.githubusercontent.com/7963804/44981684-9d4d7880-af73-11e8-87ad-8e36615395e1.png)

**Comment by carloslancha** [comment]
Fixed in https://github.com/liferay/clay/pull/1154

**Comment by carloslancha** [comment]
Duplicated: https://github.com/liferay/clay/issues/1153
