### ISSUE TITLE
Please Stop “Fixing” Font Smoothing

### ISSUE THREAD

**Issue by sbaechler** [liferay/clay#1164]
https://www.zachleat.com/web/font-smooth/
http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

While it can be used to manually fix some light text on dark backgrounds on Macs, it should't be used on the entire page. It often leads to overly thin text with smaller weights, such as this example:

If you look at how DirectWrite and Cocoa work on Windows and Mac native elements, they use subpixel AA on normal DPI screens, and default to greyscale on high DPI screens. The same is true with Chrome, which disable subpixel AA when the device DPR is over 2.
Twitter did a similar thing on their site:

```
@media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-resolution: 2dppx) {
	body {
		-moz-osx-font-smoothing: grayscale;
		-webkit-font-smoothing: antialiased;
	}
}
```

**Comment by pat270** [comment]
Thanks @sbaechler, I'll have to look into this.

**Comment by pat270** [comment]
Hey @sbaechler,
I moved font smoothing values to Sass variables and made the Base Theme use the default. Atlas still uses font smoothing `grayscale` and `antialiased`. I don't think I can come up with a one size fits all solution for this as it's largely subjective and depends on the font you are using. These properties do nothing on Windows machines btw.

You can change them to whatever you want using the variables:
```
$body-moz-osx-font-smoothing
$body-webkit-font-smoothing
```

If you want to use font smoothing on HD screens you will need to implement it yourself.

**Comment by sbaechler** [comment]
Great, thank you.
