### ISSUE TITLE
Improve the clayui.com deploy process

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1170]
### Disclaimer
We are currently deploying deploy when it is in `master` or when we need to visualize something, we can improve this by automating our process and defining a detailed workflow.

### Proposal

I thought the following flow, but we can change.

`PR -> Deploy to preview [1] -> Merged in develop branch [2] -> Merged in master branch [3]`

1. Once a PR is submitted with changes to clayui.com the bot will create a preview of the website from that PR commit. This will generate a specific URL for this PR. (Something similar to what reactjs.org does)
2. The `dev` environment for clayui.com, as soon as something is merged into the branch develop a deploy for that environment (` dev.clayui.com? `) Is done. It will help others know what's coming and see changes coming soon in the next release, this also helps us identify problems sooner.
3. Our production environment, nothing new here but can be automated with a bot.

All this workflow we can define with a bot without having to do something manual. It starts ah take away sensation that clayui.com is outdated, with the help also of #1111 and other tasks to be automated....

> **OBS**: I do not know if it would be possible to do scenario 1. with wedeploy... Maybe we can opt for [netlify](https://www.netlify.com/) to do this part of the process, something reactjs.org uses for this step.

**Comment by matuzalemsteles** [comment]
cc @jbalsas @marcoscv @pat270

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, `WeDeploy` introduced [environments](https://wedeploy.com/blog/introducing-wedeploy-environments/). I think we could have
- `dev`
- `prod`
- ideally a new environment per PR, but if not, one called `pr`

@zenorocha, is it possible to create environments programatically so we could automate this? That would be amazing! :)

**Comment by jbalsas** [comment]
I think I can answer that myself, @zenorocha:

> There is currently no way to create new environments from the CLI. To do this, you must go use the Console.

**Comment by jbalsas** [comment]
@matuzalemsteles, let's explore the WeDeploy environments idea... for automation on PRs, maybe we could:
- Create a `pr` environment with a different setup
- Configure gatsby in an inteligent way, so rather than going to `clay-dev.wedeploy.io`, every PR gets sent to `clay-dev/wedeploy.io/pr-123
- Get the bot (git-hook?) to do the automatic push to the `dev` and `prod` branches on merges on `develop` and `master`.

How does that sound?

**Comment by matuzalemsteles** [comment]
hey @jbalsas Awesome!! I think we can explore that.

**Comment by diegonvs** [comment]
It's time to reactivate this discussion because https://wedeploy.com/blog/discontinuing-wedeploy/

**Comment by matuzalemsteles** [comment]
We're using a deploy stream now, so I'm closing.
