### ISSUE TITLE
In ResultsBar, results-for item is always visible

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1176]
Inside the ManagementToolbar, we [render a ResultsBar](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L182) if `isNonnull($totalItems) and ($searchValue or $filterLabels)`

However, in ClayResultsBar, we [always render the results item](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/src/ClayResultsBar.soy#L21) no matter the value of `$searchValue`.

This results when applied (in Liferay Portal) in something like the following screenshot

<img width="1013" alt="screen shot 2018-09-10 at 17 43 07" src="https://user-images.githubusercontent.com/905006/45308118-08252380-b521-11e8-9e1e-230abe72837d.png">

**Comment by matuzalemsteles** [comment]
I think we can move the rules that happens in ManagementToolbar to ResultsBar, so we can have this control more refined and also other products that want only the ResultsBar component, will have to obey the rules of the Lexicon...

**Comment by jbalsas** [comment]
This is following Lexicon, agreed with @victorvalle 😉

**Comment by carloslancha** [comment]
@jbalsas according to the use cases and the component mockups, `x-results-for` should be visible if `search value` OR `filters` are provided.

Sample:
![image](https://user-images.githubusercontent.com/5803434/45617097-8fb6e900-ba71-11e8-8533-8e6be8f38ca5.png)

**Comment by matuzalemsteles** [comment]
hey guys, how do we get on with this?

**Comment by jbalsas** [comment]
I think based on what @carloslancha said, we can close this as `invalid`
