### ISSUE TITLE
Missing Icons in clayui.com

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1177]
It looks like we're currently missing the icon font in https://clayui.com

<img width="492" alt="screen shot 2018-09-11 at 11 48 03" src="https://user-images.githubusercontent.com/905006/45352421-bd56ea80-b5b8-11e8-9b43-4593d9fa275b.png">

**Comment by matuzalemsteles** [comment]
hey @jbalsas, I think this was a bug in the build, can you try giving another deploy?

**Comment by jbalsas** [comment]
I just redeployed and all looks good! 👍
