### ISSUE TITLE
ManagementToolbar ActionItems show if an empty array is passed

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1178]
In the management toolbar, if an empty array is passed as `actionItems`, an empty dropdown is shown. Would it be possible to control this case?

```javascript
ManagementToolbar.STATE = {
    [...]
    actionItems: actionItemsValidator.value([]),
    [...]
};
```

<img width="1121" alt="screen shot 2018-09-11 at 13 22 21" src="https://user-images.githubusercontent.com/905006/45357169-baaec200-b5c5-11e8-9422-7a91337a1ce2.png">

**Comment by matuzalemsteles** [comment]
hey @jbalsas, we can control this, in that when the array is empty the Dropdown will not appear or we can disable it. We have to check this behavior with Lexicon.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, this is the expected Lexicon behaviour. Just now, this is an issue in our implementation, because `actionItems=null` and `actionItems=[]` have different behaviours. 

My expectation is that both should be equivalente in behaviour :)

**Comment by matuzalemsteles** [comment]
hey @jbalsas, send a correction to fixed this in ManagementToolbar but I will create another issue to analyze the other components that also reproduce the same behavior.
