### ISSUE TITLE
When dragging a focused input type="range", some phantom blue boxes appears 👻

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#1179]
When using form control type="range" on latest Chrome, we had a glitch appearing some phantom blue boxes when dragging.

See following GIF: http://recordit.co/n29o05jljY

I'd taken the examples from: http://pat270.github.io/lexicon/content/form-elements/

**Comment by pat270** [comment]
@diegonvs what browser and os were you on? I can't seem to duplicate it in any of my browsers on mac.

**Comment by diegonvs** [comment]
I'm using Chrome 68 on macOS 10.13.6

**Comment by diegonvs** [comment]
I'm using Chrome 68 and Canary on macOS 10.13.6 and I cannot reproduce anymore. I really don't know what happened.

**Comment by diegonvs** [comment]
I'm closing this issue

**Comment by diegonvs** [comment]
I'm reopening because I noticed that it is only possible to reproduce when the `input type=range` is focused. If you want to reproduce, try navigate in using tabs until focus the `input type=range`. :)
