### ISSUE TITLE
Please add version and publication date to the documentation

### ISSUE THREAD

**Issue by chrberndt** [liferay/clay#1203]
Bootstrap's version selector at the top of the page seems a good solution for me.

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)

**Comment by kresimir-coko** [comment]
Can I get some more details on this task? On top of which page, somewhere in the [header](url
![image](https://user-images.githubusercontent.com/24564752/74920454-77689d80-53cc-11ea-8e7c-fad878bfbea0.png)
) of clayui.com? ? Which versions should be included?

**Comment by chrberndt** [comment]
@kresimir-coko please see my comment at https://github.com/liferay/clay/issues/1221#issuecomment-588881128

**Comment by kresimir-coko** [comment]
So, @chrberndt is this task the same as #1221 ? It sounds like it

**Comment by chrberndt** [comment]
That's my understanding, yes.

**Comment by bryceosterhaus** [comment]
closing as duplicate https://github.com/liferay/clay/issues/1221
