### ISSUE TITLE
Management toolbar mobile viewports Clear action must be right aligned

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1226]
The aligntment of the clear action should be right.
This action is now aligned next to the text

![image](https://user-images.githubusercontent.com/21121115/46670351-3f472d00-cbd2-11e8-838e-4f5b92c76d60.png)

Please see: https://liferay.invisionapp.com/share/PVN3QSTHK65#/312223170_0604m

Do not modify other styling things, please.

**Comment by matuzalemsteles** [comment]
hey @pat270, this seems to look like this when it's a smaller screen.

**Comment by pat270** [comment]
@matuzalemsteles @victorvalle You can use the class `tbar-inline-sm-down` to make it align right on screen sizes >= 768px. `tbar-inline-md-down` align right screen size >= 992px.

**Comment by victorvalle** [comment]
@pat270 @matuzalemsteles I see that the documentation says

> In viewports under 576px, the "Clear All" button is no longer anchored to the right of the component and is placed inline just after the last element of the information.

And then there is a comment from Patrick asking
> Can we just have this component behave this way in all screens? I'm running into css/html limitations where I can get it to behave like desktop, but cant get it to work in mobile without moving the button markup.

Do you still have this limitation?
It is a bit strange for us to have it so close in Desktop. But is this happens we can study a solution.
Maybe @atjuan has thought about it further.

**Comment by matuzalemsteles** [comment]
hey @pat270, @victorvalle how do we proceed with this?

**Comment by pat270** [comment]
@matuzalemsteles @victorvalle The rules between the invision link and google documentation is conflicting. The only thing is to allow devs to set the `tbar-inline-*-down` class so they can take it case by case.

**Comment by matuzalemsteles** [comment]
thanks @pat270, so we should leave the `tbar-inline-md-down` as the default, correct? I'll follow through with this and send a PR adding an API that reflects this setting.

**Comment by pat270** [comment]
@matuzalemsteles maybe `tbar-inline-xs-down` is better by default. The Clear All button will at least be aligned right in most screens when there is little content.
