### ISSUE TITLE
Management toolbar results bar style problems

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1227]
![image](https://user-images.githubusercontent.com/21121115/46671605-7cf98500-cbd5-11e8-8459-3a6dc103b2d9.png)

Text formula:
- Right now: X Results for word
- Expected: X results for "**word**"
- Please see that for use semibold is important for Lexicon to emphasize

Labels:
- It is important for us to have the keyword in semibold and the attribute in regular weight.

It is important to apply semibold to have highlights.

**Comment by carloslancha** [comment]
@victorvalle  This can only be achieved through localization in portal, we can't split "x-results-for" and "search value" 'cause it wont be localizable (for a determinate lang the text should be "Search value X results for"). So the key used there has to be "x-results-for-x".
