### ISSUE TITLE
Filter Label Items don't allow HTML inside

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#1228]
To be able to fully apply [the designs](https://liferay.invisionapp.com/share/U6GSO4YW3M5#/screens/291498584_000) we need to be able to add a bit of html to [the labels](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/src/ClayResultsBar.soy#L108).

At the moment we are passing `name: value` but we would like to pass something like `name: <strong>value</strong>`. If we do that the html tags are escaped and rendered as text instead of html.

Thanks!

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, Actually we are supporting this, this is linked to a bug in Metal https://github.com/metal/metal.js/issues/381.

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

Thanks for your response. Does it mean that when that issue is fixed this will be fixed too? If that is the case I will keep an eye on this issue until you guys close it.

Thanks!

**Comment by matuzalemsteles** [comment]
Yes, I'll see if I can see another way to get around this without waiting for this correction, I'll try to work on it later.
