### ISSUE TITLE
Labels padding to be fixed

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1229]
Could you fix the labels' padding, please?

![image](https://user-images.githubusercontent.com/21121115/46746626-b9011880-ccaf-11e8-97f1-5b083a74a1e8.png)

Thanks!

**Comment by pat270** [comment]
@victorvalle I can change the horizontal padding to be 4px and 8px respectively, but the vertical padding doesn't make sense.
Small label height: 10px + 4px + 4px + 1px + 1px = 20px
Large label height: 15px + 8px + 8px + 1px + 1px = 33px

**Comment by victorvalle** [comment]
Change the horizontal, that is what makes sense and what we are requesting. Sorry for not specifying more. I thought it was clear. Sorry for the misunderstanding.

Thanks @pat270 !
