### ISSUE TITLE
IE11 - <a> element is hard to click with child lexicon-icon

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/clay#1242]
We originally added pointer-events:none to lexicon icons here https://github.com/liferay/clay/commit/0bec1327688a0fdafb4cb242535d6163a654c9dc.  This makes sense as lexicon-icons shouldn't have to trigger events however in IE11 the lexicon-icon "covers" the parent element preventing it from being clickable.

https://jsfiddle.net/L430qpmc/7/

EDIT : 

- I realize my example isn't the best but to properly explain the issue : 
The _first image link_ on IE11 can only be clicked by a small sliver of the image.  The expected behavior is being able to click the image link `a` more or less wherever the red background is.  The blue background "blocks" the red from being clicked -- contrast the first image with the second image.

**Comment by pat270** [comment]
Hey @SpencerWoo,

I'm actually ok with removing it, we just need to add the attribute `focusable="false"` to all our svgs. I think the Clay Soy Icon component does, but I don't think it's added in the icon taglib in CE/DXP.

This is a nitpick, but I'm not a fan of linking icons that way. The `a` tag is `inline` by default and doesn't grow with the content inside. If I'm linking an icon I like to change the display on the `a` tag to `inline-block`, `inline-flex`, or `block`. That way the anchor tag grows with the content and is clickable.

There is also a Clay CSS component that will do that for you, but you need to change the width, height and font-size if you want it to be something other than 32px. The font-size property will size the icon for you if you're using a Lexicon icon.
```
<a class="link-monospaced" style="width:50px;height:50px;font-size:50px;">
    <svg class="lexicon-icon"></svg>
</a>
```

**Comment by SpencerWoo** [comment]
@pat270 thank you for the quick response!

- I realize my example isn't the best but to properly explain the issue : 
The first image on IE11 can only be clicked by a small sliver.  The expected behavior is being able to click the `a` more or less wherever the red background is.  The blue background "blocks" the red.

> I'm actually ok with removing 

- Okay sweet, I'll look into adding the focusable attribute in the icon taglib on the Liferay side

**Comment by SpencerWoo** [comment]
Hi @pat270 looking at the code I think https://issues.liferay.com/browse/LPS-71422 added `focusable="false"` to the svgs in taglibs [ATag](
https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/aui/ATag.java#L61), [IconTag](
https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/aui/IconTag.java#L166).  

Assuming that's what we needed, are we good to remove pointer-events:none from lexicon icons?  Or perhaps even just from `<a>` children
```
a .lexicon-icon{
   pointer-events: auto
}
```

Thanks

**Comment by pat270** [comment]
I removed it from `lexicon-icon` should be in when we release and put a new version in DXP.

**Comment by SpencerWoo** [comment]
Awesome, thanks.  Once it's in Master I'll also want to also put it on 1.x for 7.0.x.

**Comment by pat270** [comment]
This isn't an issue in 1.x, there is no `pointer-events: none` declaration on `.lexicon-icon` in 1.x.

**Comment by SpencerWoo** [comment]
If I'm not mistaken isn't 70x using 1.0.28 https://github.com/liferay/liferay-portal-ee/blob/7.0.x/modules/apps/foundation/frontend-js/frontend-js-web/build.gradle#L19 which has https://github.com/liferay/clay/blob/v1.0.28/src/scss/lexicon-base/_icons.scss#L5?  If it isn't in 70x then nvm

**Comment by pat270** [comment]
ugh, you're right. I don't know what to do about https://github.com/liferay/clay/issues/926. Reverting that change will introduce that again. You happen to have a link to the ticket @gregory-bretall was fixing or some example of the bug?

**Comment by SpencerWoo** [comment]
@gregory-bretall https://issues.liferay.com/browse/LPS-81456 tested and removing `pointer-events:none` unfortunately does reintroduce that bug again -- adding a portlet and hovering to view the tooltip.

**Comment by pat270** [comment]
So the only workaround I'm able to find for removing `pointer-events: none;` is to remove/replace the title element from svg's added at https://github.com/liferay/clay/commit/aeac24439c6c4d44c5ddb4df614ace84a280f33a and in the aui:icon taglib https://github.com/liferay/liferay-portal/blame/master/util-taglib/src/com/liferay/taglib/aui/IconTag.java#L211-L213. I'm pretty sure it was added to pass some accessibility test. We might be able to replace title with aria-labelledby. We can do something like:

```
<svg aria-labelledby="uniqueSvgTitle">
    <desc id="uniqueSvgTitle"></desc>
</svg>
```

or

```
<svg aria-labelledby="the-svg-description"></svg>
```

I'm not sure if this will make it pass whatever test we are using. I'm including my references below:

https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements
https://developer.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/

/cc @jbalsas @carloslancha

**Comment by SpencerWoo** [comment]
hey @pat270 thanks for this.  I missed your comment but I've come to a similar conclusion -- LPS-81456 is incorrect using `pointer-events: none` to address the tooltip issue.  I think it should be added back to resolve the IE11 issue LPS-86160 and the discrepancy shouldn't be LPS-81456 and LPS-86160 but rather between LPS-81456 and LPS-68726.

**Comment by jbalsas** [comment]
@carloslancha, @marcoscv, could you please weigh in here? I remember we needed the `<title>` attribute in `<svg>` based on what we did on https://issues.liferay.com/browse/LPS-68726

**Comment by marcoscv-work** [comment]
the title in an SVG is needed but only for accessibility validation reasons, we don't need icons focus because they will be associated with a group text, button or title attribute (when it is a link/button).

I'm not sure if this helps to take a solution.

**Comment by marcoscv-work** [comment]
@pat270 We followed this to make the decision to add a title:
https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements

But currently I'm not able to get an error with Axe plugin when I remove the title attribute in an SVG, so if you really need to remove 'title' we can make a deeper look

**Comment by pat270** [comment]
To fix both issues mentioned by @spencerwoo, we need to remove the title element from the svg. 

This is another solution that seems most reasonable:
```
<svg aria-hidden="true" focusable="false" role="img"></svg>
<span class="sr-only">ellipsis-v</span>
```
from https://simplyaccessible.com/article/7-solutions-svgs/.

**Comment by SpencerWoo** [comment]
Okay so it sounds like we're good to remove `pointer-events: none` in Clay to fix this issue https://github.com/liferay/clay/issues/1242 ([LPS-86160](https://issues.liferay.com/browse/LPS-86160)).

And then we're trying to properly fix https://github.com/liferay/clay/issues/926 ([LPS-81456](https://issues.liferay.com/browse/LPS-81456)) without regressing [LPS-68726](https://issues.liferay.com/browse/LPS-68726) by replacing svg `<title>` with accessible alternatives.  Potentially using `<span class="sr-only">` instead?

**Comment by marcoscv-work** [comment]
It is Ok for me

**Comment by pat270** [comment]
@SpencerWoo we should wait for the accessibility changes first.

**Comment by SpencerWoo** [comment]
Okay, then is https://github.com/liferay/clay/issues/1242#issuecomment-434392795 `<span class="sr-only">`  a suitable accessibility replacement for `<title>`?  What about `<desc>`?  

I'm not seeing where `<title>` is advocated in svgs in https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements or [LPS-68726 ](https://issues.liferay.com/browse/LPS-68726) but I'd appreciate figuring this out.

**Comment by blzaugg** [comment]
My $0.02.

I don't feel the bulk, indiscriminate, adding of any type of title/labelledby/etc at the SVG level is helping accessibility. Sure we may pass some test and meet the letter-of-the-law, but we aren't meeting the spirit-of-the-law. Those tests are aids, not targets.

For example, if I've got some user control for, uploading a user avatar. I may want these elements in the button.
 - icon (camera icon)
 - text ("Upload")

But I don't want my screen reading saying:
> Button. Camera Icon. Upload.

More likely, I'd want something like:
> Button. Upload User Avatar.

You can't accomplish this by labeling every SVG. This has to be done on a case-by-case basis, by adding a label to the button element, describing it in context.

Whoever implements the button is responsible to maintain accessibility in that context, not the SVG. The SVG is just an abstract visual aid. You cannot make it accessible abstractly.

**Comment by pat270** [comment]
Ok so I decided to wrap the svg icons in a `span` tag and use aria attributes to announce the icon names. It uses the icon name by default which is mostly unhelpful. I agree with @blzaugg that whoever is implementing the button/link/whatever should be responsible for maintaining accessibility. https://github.com/liferay/clay/pull/1296 just provides a fallback if someone fails to do so.

The way to make links/buttons/whatever accessible is to add an `aria-label` attribute on the `a`, `button`, `whatever element`. For instances where the text inside the element is sufficient for describing the component you can set `decorative` to true in `ClayIcon` which will set the attribute `aria-hidden="true"` on the icon container.

**Comment by marcoscv-work** [comment]
I am not sure what were best place for this comment:
https://github.com/liferay/clay/pull/1224#issuecomment-438599514

**Comment by SpencerWoo** [comment]
Any update on this one?
