### ISSUE TITLE
Table Header fixed

### ISSUE THREAD

**Issue by interaminense** [liferay/clay#1244]
Hey guys,

In the **Analytics Cloud** project, we have a component that uses a table with the clay's markup, however we had to customize this table because we had a need to fix the header as shown the gif below:

![table-header-fixed](https://user-images.githubusercontent.com/12699849/47105781-45b15680-d21b-11e8-92e2-8310c31f7795.gif)

**Is it possible to create a markup in clay to fix the header?**

cc: @fcodias, @oliveiraaraujo

**Comment by pat270** [comment]
Hey @interaminense,

No there is currently no markup/component in Clay for a fixed table header. I know the Lexicon team wanted to implement tables with drag and drop, fixed column, and header but that is somewhere in the backlog.

We can probably add it as long as it's ok with the Lexicon team. In the mean time, if you have  ideas on how to implement it feel free to send a pull or share any ideas you might have.

**Comment by interaminense** [comment]
Hey @pat270, thanks for your answer.

I can send a PR with the adjustment I made to the Analytics table for you. I just need to organize this before.

**Comment by eduardoallegrini** [comment]
Recently I've been reviewing a [sticky-table-column-issue](https://issues.liferay.com/browse/LPS-96291) and I think we should consider also this possibility

I created a [first solution using the `sticky CSS property`](https://codepen.io/eduardoallegrini/pen/NZeZLJ) but it's [not 100% compatible with other browser](https://caniuse.com/#search=position%3A%20sticky)

**Comment by jbalsas** [comment]
Yeah, I was going to say we should work both on `header` and `first-column` stickies since it's an already approved pattern. We have it implemented in liferay-portal already in the old searchContainer, so we need to make sure our new tables retain that behaviour.

**Comment by drakonux** [comment]
Well we don't have a definition for the new table in Clay. But at least we have the solution we gave in https://issues.liferay.com/browse/PTR-956 as the valid one.

**Comment by kresimir-coko** [comment]
This looks like a valid feature, are we going to proceed with this? @jbalsas @drakonux

**Comment by jbalsas** [comment]
Hey @kresimir-coko, friendly reminder that @drakonux is on paternity leave... ping @victorvalle instead

**Comment by victorvalle** [comment]
Hi @kresimir-coko,
This was included in the table specification a long time ago. [Section 11 "Sticky header"](https://docs.google.com/document/d/1PNudTqmS1JCSJwMt_h2CA9QobplxIDfwF7tZsjUpavw/edit#heading=h.7lfe9gutjpv5)

**Comment by pat270** [comment]
Going to close this since we have the frontend data set.
