### ISSUE TITLE
Colors page in Layout/Foundations section

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1248]
Please also include a Color page with the sass variables you have so it is easier for people to follow and understand how colors can be changed. It would have to match the Lexicon page.

**Comment by matuzalemsteles** [comment]
hey @pat270 we have a way to get the variations of a color in Sass following the Lexicon? to be able to document.

I think we only have the main colors. https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/atlas/variables/_globals.scss#L58

**Comment by pat270** [comment]
PR at https://github.com/liferay/clay/pull/2871
Closing this issue in favor of https://github.com/liferay/clay/issues/2734
