### ISSUE TITLE
Clay CSS should support Ruby Sass

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1270]
Hey Team,
This is an issue from the slack chat.

> I have tried to upgrade my liferay theme from 7.0 to 7.1.
My theme contains a .sass files and I need ruby sass.
After upgrade I had this error (where this file is not mine):

> [10:26:09] Starting 'build:compile-ruby-sass'...
> [10:26:10] error build/_css/clay/variables/_bs4-variable-overwrites.scss (Line 11: Invalid CSS after "...nput-margin-x: ": expected expression (e.g. 1px, bold), was "!default;")

> So, I have tried to create an empty sample theme (https://github.com/davideabbatiello/samples/blob/master/sample-theme/package.json) without using gulp upgrade and the error is the same.

This particular issue can be fixed by using node-sass and passing in some config options in the theme task.

How important is it to support Ruby Sass? We will need to modify the Bootstrap source code to fix this bug. If we decide to modify how do we organize our changes vs the Bootstrap repo's?

**Comment by marcoscv-work** [comment]
I think is better if he migrates her .sass to .scss, using an npm plugin or online application like https://www.sassmeister.com

uses .sass instead of .scss is strange, .sass is very old and not common use

on the other hand, In this way, he only needs to do the conversion once
