### ISSUE TITLE
Create ClayMultiSelect Component

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1285]
### Initial implementation

- [x] Send API Proposal #1292 
- [x] Send final component #1351

**Comment by matuzalemsteles** [comment]
hey @victorvalle, The navigation between the labels is not clear to me yet. Just leaving a few points here.

- Can I remove the label when navigating the arrows?
- When to remove the label where the focus should be? on the label before it was removed? in input?
- When navigation occurs by arrows can I remove the label by pressing backspace or enter?

**Comment by victorvalle** [comment]
- Can I remove the label when navigating with the arrows?
Yes
- When to remove the label where the focus should be? on the label before it was removed? in input?
in the input
- When navigation occurs by arrows can I remove the label by pressing backspace or enter?
both
