### ISSUE TITLE
Lexicon CSS Site is out of sync with 1.x

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1342]
From https://github.com/liferay/clay/issues/1252#issuecomment-443843275

Lexicon CSS is on version 1.0.29 but the documentation site is still on 1.0.26.

**Comment by pat270** [comment]
https://github.com/jbalsas/lexiconcss/pull/3

**Comment by jbalsas** [comment]
I've merged and published `1.0.29`. I've also created https://github.com/liferay/clay/issues/1401 so we look for ways to integrate that site in this repo for easier maintenance.
