### ISSUE TITLE
Upgrade Bootstrap to 4.1.x

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1347]
Some themes we are migrating use new classes added in BS 4.1.3

**Comment by pat270** [comment]
Would you guys be ok with Bootstrap 4.1.1? The classes `.text-white-50` and `.text-black-50` were actually added in 4.1.0. There's a change in 4.1.2 that moved hover and focus styles for `.close` into the selector `.close:not(:disabled):not(.disabled)` that made it too specific (takes 3 classes to overwrite it). It forces us to add unnecessary work arounds to overwrite it. I think it would be better to submit a fix to the Bootstrap repo and update to 4.1.4 or whenever it gets merged.
