### ISSUE TITLE
ClayToast and ClayStripe close methods doesn't work as expected

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#1379]
All the logic of the closing animation is in ClayAlertBase and it's not being called through close method in ClayToast and ClayStripe. We need to refactor all this to improve the logic.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@matuzalemsteles, @carloslancha, please reopen if you think this is still relevant in the context of our `3.x` components.

Thanks!
