### ISSUE TITLE
Cards as Navigation Elements

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1436]
In data-related patterns, a common enough scenario is to expect some types of gestures to produce a top-bottom navigation. For example, it might be expected that "double-clicking" a card in a card grid or a row in a table navigates to the edition view of the item that was interacted.

To make this simpler, we should add some APIs to card to allow specifying:
- The `navigationURL` or `href` of the component
- The `navigationGesture` that should trigger this behaviour.

**Comment by matuzalemsteles** [comment]
hey @jbalsas I do not know if I understood the idea of ​​creating these new APIs, for the Cards example, we have the `itemClicked` event and also the `href` API. Would not that help cover those cases?

**Comment by pat270** [comment]
I'm going to add some variants to cards so we can achieve the interaction in the image below.
![image-2019-01-31-18-09-16-739](https://user-images.githubusercontent.com/788266/53760264-36077700-3e77-11e9-9a5b-01184bb533cc.png)
https://issues.liferay.com/browse/LEXI-485
