### ISSUE TITLE
Investigate user of linter for following REUSE.software best practice guidelines

### ISSUE THREAD

**Issue by wincent** [liferay/clay#1466]
I'm creating this to split out the conversation from #1451.

The basic idea is to ensure consistent, concise license headers across all files. @silverhook provides a detailed overview of the recommendations in [this comment](https://github.com/liferay/clay/pull/1451#issuecomment-456384580). There is [a "reuse" linter](https://gitlab.com/reuse/reuse) that can be used to check for compliance. I also posted [this comment](https://github.com/liferay/clay/pull/1451#issuecomment-456703326) about my experimentation with the ["eslint-plugin-notice" plugin](https://www.npmjs.com/package/eslint-plugin-notice), which may be a viable alternative that would integrate well with our existing linting.

So the goal of this issue would be to:

1. Investigate and select tooling to enforce the best practices in an automated way.
2. Roll out the best practices across this repo, using that tooling.

**Comment by jbalsas** [comment]
I think `eslint-plugin-notice` sounds like a great starting point, at the very least to help consistency with the mandate about `Include licensing header in source code`.

Reading through @silverhook's [policy explanation](https://github.com/liferay/clay/pull/1451#issuecomment-456384580) one thing stuck out in the `Include the license text` section:

> It should be perfectly enough to have the license text just in one location:
>
>- either in LICENSES/LicenseRef-BSD-3-Clause-Liferay.txt – especially if there are other licenses in the repo (BTW, the LicenseRef- prefix is used in SDPX to indicate an non-standard license, we use it here together with the -Liferay suffix, because the BSD licenses need to be modified to include the copyright holder);
>- or if it really just one license and we don’t expect to pull code that’s under a different license it can simply be in LICENSE.txt

As of right now, this project has dependencies on `metal` (which on its own will have the same licensing) but depends on its own on other projects that might not (`metal-promise`, `metal-soy` might be the bigger offenders there). New components like [DatePicker](https://github.com/liferay/clay/pull/1440/files#diff-eae742ffea8810a8ed8153cda1c1ed29R23) seem to be pulling others like [`moment`](https://github.com/moment/moment) on top of `react` and `react-dom`. [ColorPicker](https://github.com/liferay/clay/pull/1427/files#diff-79c9a686f65b777110a0e65bc7111c8eR17) does the same, but with [`tinycolor`](https://github.com/einaros/tinycolor) instead.

With this in mind... I assume we'd need to collect all incoming licenses in that `LICENSES` folder?

Also... I assume some might not be compatible, so maybe we'd need some type of [license-checker](https://github.com/davglass/license-checker) to keep _bad_ packages away...

**Comment by wincent** [comment]
One minor consideration is that if we put the top-level license in a "LICENSE.txt" or similar file then [GitHub should be able to autodetect it](https://help.github.com/articles/licensing-a-repository/#detecting-a-license). And it will show in the project header:

![header](https://user-images.githubusercontent.com/7074/51595145-564a2a80-1ef6-11e9-9e87-5d1450c4fa83.png)

And if you click on that you see detailed info:

![detailed](https://user-images.githubusercontent.com/7074/51595135-50ece000-1ef6-11e9-9f87-df3851fead2c.png)

I don't know if autodetection would work in a "LICENSES/" subfolder with a custom name; I'm guessing probably not. Not a deal-breaker, but something to bear in mind.

**Comment by matuzalemsteles** [comment]
hey @wincent Can we say this is done?

**Comment by wincent** [comment]
I think so. "eslint-plugin-notice" is delivering 80% of the value of the "[reuse](https://gitlab.com/reuse/reuse)" linter at 1% of the cost.

**Comment by silverhook** [comment]
I think we can leave it at that for now, yes. (Although I’m still unconvinced why we need to write and maintain our own linter.)

We’re currently working with REUSE to make the 3.0 spec easier to comply with, so we this should count as “good enough” until the 3.0 spec is out. If we need to tweak anything, we can still do that later.

One big change that we’re trying to make happen is to vastly simplify the MIT/BSD licenses use case (see https://github.com/fsfe/reuse-docs/issues/16)

**Comment by wincent** [comment]
> I’m still unconvinced why we need to write and maintain our own linter

We're not writing or maintaining our our linter: we're using ESLint, which is pretty much the defacto linter in the JS community ([6.7+ million weekly downloads](https://www.npmjs.com/package/eslint)) and an ESLint plugin, eslint-plugin-notice, which has [8k+ weekly downloads](https://www.npmjs.com/package/eslint-plugin-notice). Leveraging these is basically "free" for us because they are so well integrated and supported within the frontend ecosystem.

**Comment by silverhook** [comment]
I understand that. I’m referring to the fact that then we have to keep track and (re)implement (at least the) linter part of the `reuse` tool.

BTW, if that is our desired course of action (it seems it is), it would be a great gift to the REUSE community, if we contributed our ESLint plugin to the project. I’m happy to help test the logic behind our REUSE linter ESLint plugin once the REUSE Spec 3.0 is finalised.
