### ISSUE TITLE
ClayMultiSelect: adding item only from autocomplete list or "select" button

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1479]
There are cases in which we want to add items only from trusted sources. This means, we want to avoid that use could introduce anything in the multiselect (typing Enter or ","), and we want to allow only items selected from the Autocomplete list or the "select" button.
See use case in portal: https://issues.liferay.com/browse/LPS-87549 
UX proposal will be uploaded in https://issues.liferay.com/browse/LPS-89900

**Comment by carloslancha** [comment]
https://github.com/liferay/clay/issues/1767
