### ISSUE TITLE
ClayMultiSelect: forbidden characters 

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1480]
Add the possiblity to define if there are characters that we do not want to allow in the input field. 
We have this in the TagSelector taglib in portal.

**Comment by matuzalemsteles** [comment]
hey @ambrinchaudhary, I think we can provide an API that makes it possible to add Regex, but we'll have to think about how the behavior will be when regex matches...

cc @victorvalle

**Comment by victorvalle** [comment]
@ambrinchaudhary @matuzalemsteles  How possible is to do that with the different languages we manage in Liferay. Do we do it in other places in portal?

**Comment by matuzalemsteles** [comment]
On the use cases in the portal I'm not sure, but it is possible to do this using regular expressions with unicode...

**Comment by victorvalle** [comment]
We could definitely look for character subsets that cover all languages, in this way we skip the rest. I'm gonna need to take a look at the languages that we support in portal to give you an answer

**Comment by wincent** [comment]
Also worth noting the tradeoffs of using a blacklist (allow anything except disallowed characters) vs a whitelist (only permit allowed characters). Generally whitelists are "safer" if the reason for restricting the input is related to security. On the other hand, blacklists are less like to break unanticipated but legitimate use cases. I don't know what the motivation is here, so I can't speak to which approach is the right one (although if in doubt, whitelisting is a good default approach).

**Comment by victorvalle** [comment]
Actually one of the main problems here is that we allow many things in Portal.

**Tags:**
The Tag Name cannot contain the following invalid characters: & ' @ \ ] } : , = > / < [ { % | + # ` ? " ; / * ~.

**Categories:**
Allow every char

**Other possible uses:**
If you use it for sharing via email I'm sure you would like to have "@" so we would have to provide flexibility

So I don't know that is best, provide rules o leave it open so anyone can create their own black/white list.

I see the best option as to leave it open to the purpose and align it with the purpose you have. If you are using ClayMultiSelect for tags bring the same restrictions tags app provides in Portal. For email the same. And of course, adapt to the behavior of "," and intro that the component provides.

What do you think?

**Comment by carloslancha** [comment]
I'd go with @matuzalemsteles proposal of whitelist regex, allowing everything if nothing is passed. We need to keep components as flexible as possible.

Thanks!

**Comment by matuzalemsteles** [comment]
hey guys, thanks for the suggestions... Yes the proposal of a regex whitelist is best for those cases, I'll go with that and let it implement its own rule.
