### ISSUE TITLE
Implement Clay Time Picker

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1484]

**Comment by matuzalemsteles** [comment]
hey @victorvalle, you could explain better how is the use of the time zone, it should be according to the user settings or according to the location that is provided by the browser.

**Comment by victorvalle** [comment]
The one provided by the portal I guess.
Maybe @jbalsas can help us better.

**Comment by matuzalemsteles** [comment]
Thanks @victorvalle! Hey @jbalsas we can just leave an API to pass this information to ClayTimePicker, what do you think?

**Comment by jbalsas** [comment]
Sounds good, @matuzalemsteles !
