### ISSUE TITLE
Improve clayui.com deployment process

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#1506]
Up until a couple of months ago, we were using the GitHub integration in WeDeploy to deploy our clayui.com site. We are trying to move away from that setup that requires admin permissions on the repos and move to wedeploy cli which does not.

We should update our deploy scripts to use that other approach instead.

See https://wedeploy.com/docs/deploy/getting-started/ for some reference into how to use `we deploy`.

**Comment by diegonvs** [comment]
Related #1170
