### ISSUE TITLE
Extend Clay Dropdown Menu to support custom triggers

### ISSUE THREAD

**Issue by pei-jung** [liferay/clay#1513]
We're looking to create a dropdown menu for the user's avatar, like this
<img width="212" alt="screen shot 2019-02-07 at 11 20 03 am" src="https://user-images.githubusercontent.com/5168351/52437681-5b999e80-2acc-11e9-9827-6159a8e4223b.png">

The user avatar can be either an image or a text div with the user's initials. Currently, the clay dropdown menu taglib only allows a text or a lexicon icon. We'd like to be able to use custom triggers for the dropdown menu.

/cc @matuzalemsteles @jbalsas

**Comment by carloslancha** [comment]
Hey @pei-jung !

Actually you can already do that, either with `soy`, `js` or with portal tags. This is an example using tags:

```
<liferay-util:buffer
	var="userSticker"
>
	<clay:sticker
		icon="picture"
		shape="circle"
	/>
</liferay-util:buffer>

<clay:dropdown-menu
	dropdownItems="<%= dropdownsDisplayContext.getDefaultDropdownItems() %>"
	label="<%= userSticker %>"
/>
```

`label` param gets strings or html so you can do what you need. I'm creating another issue to make configurable the caret icon of the trigger so you can hide it.

Would that work for you?

**Comment by pei-jung** [comment]
@carloslancha Perfect, that's exactly what I need! I'll give that a try. Thank you!

And for the caret icon, I think it can be hidden by passing the `hide` class to the `triggerCssClasses` attribute right?

**Comment by pei-jung** [comment]
Never mind. The `triggerCssClasses` is not just for the caret icon. Please make the caret icon configurable. Thanks!

**Comment by carloslancha** [comment]
@pei-jung done! https://github.com/liferay/clay/pull/1515

**Comment by carloslancha** [comment]
I'm releasing a new Clay version to update portal with it.

**Comment by pei-jung** [comment]
Great, that was fast! 👍 Thanks so much! I'll close the ticket.

**Comment by pei-jung** [comment]
@carloslancha can you update the taglib once the new clay version is in portal?

**Comment by carloslancha** [comment]
@pei-jung sure, it's part of the update process, I'll let you know when it's done.

**Comment by pei-jung** [comment]
Ok, thank you
