### ISSUE TITLE
ClayMultiSelect: delete icon ("x") near labels is too big

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1522]
The delete icon is too big. Check Lexicon patterns. 
<img width="461" alt="multiselect delete icon" src="https://user-images.githubusercontent.com/8373764/52556804-e260bb00-2ded-11e9-8543-ad5a18328546.png">

**Comment by pat270** [comment]
@ambrinchaudhary can you link me to the LPS ticket if there is one?

**Comment by ambrinchaudhary** [comment]
See Lexicon page: https://lexicondesign.io/docs/patterns/labels.html (Removable label). 
@victorvalle is there any other specification for this we should be aware of?

**Comment by victorvalle** [comment]
You can find the specification [here](https://www.figma.com/file/02DVhuHVTDbzaMjNM7IUKWp0/lexicon?node-id=1384%3A0)
