### ISSUE TITLE
Heatmap Midday Represented as Midnight and Visa Versa

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#1534]
12am should be changed to 12pm between 11am and 1pm.

https://lexicondesign.io/docs/patterns/Charts/chart-heatmap.html

![should-be-12-pm](https://user-images.githubusercontent.com/18121278/52592671-9b35f280-2e0c-11e9-881b-2ced5f17e49b.JPG)

**Comment by duracell80** [comment]
On the flipside ...

10pm and 11pm are followed by 12am not Midday.
![should-be-12-am](https://user-images.githubusercontent.com/18121278/52592826-02ec3d80-2e0d-11e9-9bfd-9d4268c63eeb.JPG)

**Comment by duracell80** [comment]
The Heatmap Chart is a visual representation of the data using *colors < "shades and sizes" to indicate the values.

**Comment by julien** [comment]
Hi @duracell80 

I didn't really understand this last comment.

Since this seems related to the lexicon website it might be a good idea starting a discussion on their repo which you can find here: https://github.com/liferay/lexicon-site

Thanks!

**Comment by duracell80** [comment]
Ah gotcha on the page on Clay for the heatmap the visual grid has blue dots that change in size rather than color.
