### ISSUE TITLE
Add infrastructure to easily have accessible demos

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#1562]
I am gonna look into using Framer X, but if that doesnt work out for design then I think the next approach would be to look into using Storybook.

**Comment by diegonvs** [comment]
One benefit from storybook is to be able to use addons like this:

- https://github.com/storybooks/storybook/tree/master/addons/a11y
We could check accessibility easier :)

Hey @marcoscv-work, did you had seen that before?

**Comment by thektan** [comment]
I somehow clicked into this page...but "storybook" caught my eye and I wanted to add I've been using storybook for developing search portlet components and it's been really nice to use.

Along with the nice add-ons, like the one Diego mentioned, they even have a command to easily publish a static site. Here's a link to the official docs on it: https://storybook.js.org/docs/basics/exporting-storybook/ And also short tutorial with continuous deployments on Netlify https://www.learnstorybook.com/react/en/deploy/.
