### ISSUE TITLE
Clay v1.0.30

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/clay#1563]
Hi, can we publish Clay v1.0.30 for https://github.com/liferay/clay/pull/1481 for 70x?  

If not, can I have insight on the timeline for the next release, thanks.

**Comment by pat270** [comment]
@SpencerWoo I'll cut a new release today

**Comment by pat270** [comment]
Should be available now https://github.com/liferay/clay/releases/tag/v1.0.30
