### ISSUE TITLE
Clay Multi Select filters out valid results

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#1571]
We have connected `clay-multi-select` to an autocomplete that returns results based on different fields (user name and user email). However we just want to display the user name in the labels. Since the email is not included in the label, [the filter function of the data provider](https://github.com/liferay/clay/blob/2.x-develop/packages/clay-data-provider/src/ClayDataProvider.js#L189) filters out the result which should be displayed.

For example if we search for `example` we expect the following result from the backend: `{user: 'someone', email: 'example@example.com'}` but we just want to display the name `someone`. Since `example` is not included in `someone` the suggestion is not displayed.

It would be nice if we could pass a boolean to disabled the filtering, since in our case is being done in the backend.

Thanks!

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, I do not know if I understood correctly what you want to do, let me know if I understood right, you want to disable the default autocomplete? if so, you can do something like this:

```javascript
new metal.ClayMultiSelect({
	dataSource,
        helpText,
        spritemap,
	events: {
		'inputChange': (e) => e.preventDefault(),
	},
}, '#default-block');
```

This way you can deactivate the default autocomplete filtering and if you need you can create your own filter.

You can do the same for `dataChange` if you are using `query`, as may be the case with you.

```javascript
new metal.ClayMultiSelect({
	dataSource,
        helpText,
        spritemap,
	events: {
		'inputChange': (e) => {
                     e.preventDefault();
                     // e.target.filteredItems = e.target._dataSource...
                 },
	},
}, '#default-block');
```

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

Thanks for the quick response. 

I have tried what you suggested but that disables the autocomplete, completely 😄 . I just need to disable [the filtering](https://github.com/liferay/clay/blob/2.x-develop/packages/clay-data-provider/src/ClayDataProvider.js#L190) you guys do based on the query. What I want is to display all the results that the backend provides even if the label does not contain the query.

Does that make sense to you?

Thanks!

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, I think this makes sense but maybe you would have to just implement a makeup on top of the data that comes from the backend to match the markup that [shows the marked characters](https://github.com/liferay/clay/blob/2.x-develop/packages/clay-data-provider/src/ClayDataProvider.js#L194-L198) or you can create your own **ClayAutocomplete.Item** `deltemplate` to render the items.

Something like that:
```javascript
new metal.ClayMultiSelect({
	...
	events: {
		'dataChange': (e) => {
			e.preventDefault();

			if (e.data) {
				e.target.filteredItems = e.data.map(({name}, index) => {
					return {
						index,
						matches: name.split('').map((e) => {
							return {
								value: e,
							};
						}),
						score: 0,
						value: name,
					};
				});
			} else {
				e.target.filteredItems = [];
			}
		},
	},
        ...
}, '#default-block');
```

If we compare the current filter it already does almost this (If we compare the results they are the same) then I do not know right... I will go as is the current implementation.

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

I followed your advice an seems to work fine. 

Have a look at [the pull request](https://github.com/brianchandotcom/liferay-portal/pull/68304).

In any case, I still think it would be nice to have a friendlier way to do this

Thanks a lot!

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, yes maybe this specific use case we should do something on our side but I'm just making sure that the `filter` is already doing what you are thinking, I think we can add an API to disable the filter by default and only do something like above. I'll leave this issue open so we can track down and come up with a solution. Thanks!

Just one question, the values ​​are appearing correctly? I think Autocomplete needs [`matches`](https://github.com/brianchandotcom/liferay-portal/pull/68304/files#diff-d531bfbcfb878cce8f16d21a80a16ba8R61) to be able to render correctly or you have created some `deltemplate` to customize it?

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles, 

That sounds good.

And yes, we are using [a custom template](https://github.com/liferay/liferay-portal/blob/6e54c08d9300849e4a9930ab3486b81eb3912779/modules/apps/sharing/sharing-web/src/main/resources/META-INF/resources/Sharing.soy#L134-L149) that's why we don't need matches.

Thanks!

**Comment by 4lejandrito** [comment]
And now that you mention, in our deltemplate we need to duplicate the `<li>` and the `<a>` wrapping the suggestion. 

Don't you think it would be better just allow overriding what's inside the `<a>`? This way we would just need to this:

```
{deltemplate ClayAutocomplete.Item variant="'sharingUser'"}
	{@param data: ?}

	{call ClaySticker.render}
		{param size: 'lg' /}
		{param imageSrc: $data.data.portraitURL /}
		{param shape: 'circle' /}
	{/call}
	<strong>{$data.data.fullName}</strong> {$data.data.emailAddress}	
{/deltemplate}
```

The other way you are at risk of people breaking the autocomplete if they forget to add the `<li>` and the `<a>` with the index and the onclick handler.

**Comment by matuzalemsteles** [comment]
Maybe, my concern is when someone needs to customize `<li />` or `<a />` but we can evaluate this as an option, I'll see it this afternoon or tomorrow. Thanks!
