### ISSUE TITLE
ClayMultiSelect: helpText is hidden when there are filtered items

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1575]
This is visually weird. Everything under the multiselect component is moved because the helpText dissapears. See attached gif
![claymultiselect_autocomplete_helptext](https://user-images.githubusercontent.com/8373764/53090588-349d8c80-3510-11e9-9071-4c41111b51f5.gif)

**Comment by ambrinchaudhary** [comment]
I would remove the condition you have to show the helpText (ClayMultiselect.soy): 
`			{if not $isVisible}
				<div class="form-feedback-group">
					<div class="form-text">
						{$helpText}
					</div>
				</div>
			{/if}`

**Comment by matuzalemsteles** [comment]
hey @pat270 can you look at this? I had to always remove the helptext so that I could show the dropdown correctly. I guess I did not have a markup with the Multi Select with autocomplete.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, is the dropdown using a `portalElement`? The dropdown should be rendered outside of the component root element to avoid these type of issues...

**Comment by matuzalemsteles** [comment]
hey @jbalsas, I wanted to avoid using `portalElement` here, we were having problems with it, especially for use cases with Modal #1184.

**Comment by jbalsas** [comment]
You can't run away from the problems, @matuzalemsteles! Not using `portals` for these type of components usually ends up in a loong list of different clipping/scrolling issues... see the just created one at https://github.com/liferay/clay/issues/1576

**Comment by matuzalemsteles** [comment]
Hey @jbalsas I understand that these problems can be caused, but I'm just making sure that we have other solutions, using `portalElement`, we would always have to add in a container in the top of the body so as not to risk the element not appearing, I do not know how is inside the portal, but we can look at it to solve these problems...

**Comment by pat270** [comment]
@matuzalemsteles This is the first time I'm seeing a dropdown menu with the multi select thing. We can get it to work as is just need to re-arrange the markup a little bit. I also need to add a style for `dropdown` inside an `input-group-item`. The markup would go:
```
<div class="input-group input-group-stacked-sm-down">
	<div class="input-group-item">
		<div class="dropdown dropdown-full">
			<div class="form-control form-control-tag-group">
				...
			</div>
		</div>
		<div class="form-feedback-group">
			...
		</div>
	</div>
	<div class="input-group-item input-group-item-shrink">
		...
	</div>
</div>
```

**Comment by matuzalemsteles** [comment]
@pat270 thanks, I think this could be solved by using `portalElement` but it will break the CSS, it will not have the dropdown size according to the input (we would have to control this via JS), then no I know if we should go with the use of **portalElement** but we have other cases that could break without it as Chema said above.

**Comment by pat270** [comment]
@matuzalemsteles I'll probably add the CSS only way anyway, just in case something pops up in the future.

**Comment by matuzalemsteles** [comment]
I'm closing this, `portalElement` will be added via issue #1576.
