### ISSUE TITLE
ClayAutocomplete inside a Modal

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#1576]
When the autocomplete list is rendered inside a Modal, shouldn't it be displayed above any element? So we avoid the scroll that appears in it. 

<img width="661" alt="screenshot 2019-02-20 at 14 06 48" src="https://user-images.githubusercontent.com/8373764/53094033-52232400-3519-11e9-9ce3-3bdb87fbbea5.png">

**Comment by ambrinchaudhary** [comment]
Also, could we set a maxHeight property for the dropdown, so we do not have a large list of elements?
In this case the scroll should appear only in the dropdown, not in the modal.

**Comment by matuzalemsteles** [comment]
hey @ambrinchaudhary, yes I think this is a problem I will follow Lexicon standards in regards to this, does this sound good to you? I'm going to open another issue to track this issue.

See https://docs.google.com/document/d/15r6t5Maiavg7ggxE8ulTATTuyqGVaq75yj9p-zfsQqU
