### ISSUE TITLE
Management toolbar action buttons trigger click event when disabled

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1577]

**Comment by AliciaGarciaGarcia** [comment]
The behavior is reproducible on the actions menu but seems resolved on the toolbar.
The open issues are:
https://issues.liferay.com/browse/LPS-90735
https://issues.liferay.com/browse/LPS-90352

Thanks

**Comment by AliciaGarciaGarcia** [comment]
@4lejandrito

**Comment by matuzalemsteles** [comment]
I'm closing this once this fix has entered 2.x, if that still reproduces, please reopen.
