### ISSUE TITLE
Autocomplete Dropdown should add a scroll

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1579]
hey @pat270 can we add the `inline-scroller` class to the autocomplete dropdown to get to that result? Are we getting off the markup?

- The list must have an scroll from when there are more than 4 elements.

See https://docs.google.com/document/d/15r6t5Maiavg7ggxE8ulTATTuyqGVaq75yj9p-zfsQqU

**Comment by pat270** [comment]
@matuzalemsteles I can namespace it like I did with the date picker dropdown menu that way we can easily change it in the future or create one offs.

**Comment by matuzalemsteles** [comment]
Sounds good to me, so let's wait for the Date Picker to be merged so we can go with it, okay?

**Comment by pat270** [comment]
That's good with me.

**Comment by pat270** [comment]
@matuzalemsteles the markup will be:
```
<ul class="autocomplete-dropdown-menu dropdown-menu">
    ...
</ul>
```
