### ISSUE TITLE
ClayMultiSelect: Placeholder doesn't disappear

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#1601]
Hi guys,

The multi-select should behave as a standard input. The placeholder must disappear when a  user adds a label. 

<img width="1080" alt="screenshot 2019-02-25 at 14 59 55" src="https://user-images.githubusercontent.com/21216422/53343223-208ecc00-3910-11e9-86bd-42cf08a99bae.png">

Thanks

**Comment by carloslancha** [comment]
Hey @drakonux in the multi select documentation we have nothing about placeholders, so we can't tell if this is expected or not. @victorvalle could you please take a look and update the docs if needed?

Thx.

**Comment by victorvalle** [comment]
We've never plot any example with placeholders but never asked to stop its usage. So please make it available.
@drakonux @carloslancha

**Comment by carloslancha** [comment]
Closing, waiting for definition. Thx.
