### ISSUE TITLE
ClayMultiSelect: Whitespace in Placeholder

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#1602]
Hi guys,

It seems there is a whitespace between the hint text. 

<img width="683" alt="screenshot 2019-02-25 at 15 12 49" src="https://user-images.githubusercontent.com/21216422/53343414-a1e65e80-3910-11e9-981c-5c6ef0d324ad.png">

Thanks

**Comment by carloslancha** [comment]
Hey @drakonux in the multi select documentation we have nothing about placeholders, so we can't tell if this is expected or not. @victorvalle could you please take a look and update the docs if needed?

Thx.

**Comment by carloslancha** [comment]
Closing, waiting for definition. Thx.
