### ISSUE TITLE
ClayMultiSelect: Using a string with commas

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#1603]
Hi guys,

If a user pastes a string separated with commas. The behavior is unexpected. 

![tags-commas](https://user-images.githubusercontent.com/21216422/53343892-b1b27280-3911-11e9-8158-87b28f4a1de3.gif)

Thanks

**Comment by matuzalemsteles** [comment]
hey @drakonux, I can not reproduce this in the latest version, you can try to upgrade to the most current `2.x-develop` commits to check. Thanks!

**Comment by drakonux** [comment]
Sorry Matu, I'm checking it again. I keep you posted.

**Comment by matuzalemsteles** [comment]
No problem, let me know if you were able to reproduce and tell me what the steps were. 🙂

**Comment by wincent** [comment]
Just cross-referencing some previous discussion about commas [here](https://github.com/liferay/clay/pull/1449#discussion_r248754426).

**Comment by victorvalle** [comment]
So there are two different things here:
1. The example is not working well here but in Portal the behavior is right.

2. In that definition, there is something that is not totally right and we would like to now if its possible to implement. When pasting a string such as "a, b, c" we would like this outcome [a][b][c]. Even if there is no comma at the end of the string or the user doesn't press enter. Would that be technically possible?

**Comment by matuzalemsteles** [comment]
hey @victorvalle, 

> 1\. The example is not working well here but in Portal the behavior is right.

What example are you referring to? the comma use case reported by @drakonux?

> 2\. In that definition, there is something that is not totally right and we would like to now if its possible to implement. When pasting a string such as "a, b, c" we would like this outcome [a][b][c]. Even if there is no comma at the end of the string or the user doesn't press enter. Would that be technically possible?

We can do this. Can you update the documents with these new changes?

**Comment by matuzalemsteles** [comment]
hey @drakonux, I'll close this issue as it is not reproducible and new comma usage changes will be tracked at #1604.
