### ISSUE TITLE
Multi-select must discard label if a non-valid character is found

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1604]
Multi-select component has an open list of non-valid chars.
Text pieces containing non-valid chars should not shape a label.
Example:
Non-valid chars list: "-"
Text string to paste: a, b, c-d, f
Expected outcome: [a][b][f]
c-d must be discarded in the creation

I found this happening in blogs: so either the component is wrong or the component use in blog creation is not stating the non-valid chars list.

**Comment by matuzalemsteles** [comment]
The MultiSelect does not validate the input values ​​by default, as discussed here #1480, we recently added the `allowedCharacters` (#1549) API which allows validating these values ​​but they eliminate the invalid characters, in this case it do something like:

1. Past: `a, b, c-d, f`
2. Result: `[a][b][cd][f]`

**Comment by victorvalle** [comment]
Ok, I will document is a this.
