### ISSUE TITLE
Sorting icon in reverse order

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1606]
Sorting icon is in reverse order both in table header and management toolbar.

- Arrow up means Ascending. So values must be order A to Z
- Arrow down means Descending. So values must be ordered from Z to A.

Changed in the documentation.

**Comment by boton** [comment]
This only fixes the tooltip (text) but the icon continues wrong.

Current: The class `order-arrow-down-active` decreases the color of the arrow down.
Expected: The class `order-arrow-down-active` increases the color of the arrow down or decreases the color of the arrow up.

https://github.com/liferay/clay/blob/b4084168ad7b5d3f992401769c7f21b03a524421/packages/clay-css/src/scss/components/_icons.scss#L22-L32

/cc @drakonux @marcoscv-work

**Comment by victorvalle** [comment]
Sort toggle button: The arrow identifies the sorting order depending on the selected option inside Filter and order dropdown. The main attribute, usually the name, states the default sort parameter.
- This button appears in case that we have the Filter and Order option
- AZ is up, ZA is down. The button must always show the current state, not the future.
- The tooltip for this button: “Reverse sort direction”
