### ISSUE TITLE
ClayTable: managing the active state in a different way (on rows)

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#1610]
At the moment the state "active" on rows is managed passing "selectable" as true on the entire table component and defining item.selected as true.
That adds a checkbox that, if clicked, triggers the events `change`.

What would be nice to have are:
- a modifier on the row that responds to item.selected
- the possibility to detect a click on the entire row (now it is possible only handling the single cells via `_handleCellContentClick`) 

Thank you guys! :)

cc: @marco-leo

**Comment by matuzalemsteles** [comment]
hey @FabioDiegoMastrorilli, I do not quite understand your proposal about `item.selected` in row. For now I'm going with the idea of ​​adding another event being triggered when a click happens on the row. But still holding all the other events.

- `rowContentClicked`

Would that be enough to update the checkbox?

**Comment by FabioDiegoMastrorilli** [comment]
Hello @matuzalemsteles :) 
The problem we are facing is that, if we don't rely on checkboxes, we are not able to detect whether a row is selected or not. 

For example: in our design, clicking on a row changes its appearance (obtaining a blue border on the right). With a css class like `active` we can detect the status change (if item.selected == true) and adding our custom style.

**Comment by matuzalemsteles** [comment]
Hmm, I can provide along with the `rowContentClicked` event containing information from the item clicked, I think this might help, but your would still rely on the `selected` item to check the status.

You can use `rowContentClicked` to change the `selected` state of the item and add the `active` class.

I think this is related to #1357 correct? maybe that would solve it...

**Comment by marco-leo** [comment]
Hey @matuzalemsteles yes. Basically, we do need to style the selected row. to highlight in the UI, so we do need an identification somehow
