### ISSUE TITLE
Suggestion : Condense Multiple Toast Messages Into a tabbed indexed rotatory element.

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#1611]
The error messages in Liferay are setup to show one box for each "embedded" message, these also time out and go away. It would be nice to see multiple messages concatenated into a carousel within the toast message when it makes sense to group them and keep them on the screen for the user to review.

For example the broken links messages:
https://issues.liferay.com/browse/LPS-74920

When this functionality  does start working properly and telling the user which links are broken (currently it does not) then it would be a good use case. To take 25 error messages (aka 25 broken link errors) and concatenate them into one toast that stays on the screen for the user to page through using arrows backwards and forwards. 25 error messages is also conservative, ideally if there were 50 broken links the user should be able to have this communicated without a tonne of separate red bars ...

![concat-these](https://user-images.githubusercontent.com/18121278/53512430-5eaefb80-3a88-11e9-83a4-34f90c926e42.JPG)

**Comment by duracell80** [comment]
It's a common design pattern issue that clay could take the lead on also.

Failing that provide in clay a dedicated component for such a situation that would be modal based and place each error as a "card" that is numbered and paged like < 3 of 25 >

<img width="537" alt="modal" src="https://user-images.githubusercontent.com/18121278/53512694-09271e80-3a89-11e9-9f19-446ae0a55592.png">

**Comment by kresimir-coko** [comment]
@victorvalle Does Lexicon have this on the to-do list perhaps? Should @duracell80's team open a request with Lexicon?

**Comment by victorvalle** [comment]
@kresimir-coko we don't have something like that. I haven't seen that need before. In this case, if that issue still happens we would be happy to explore if the team, in this case echo, has not solved it already and wants to go for it.

**Comment by kresimir-coko** [comment]
Alright, I'm gonna close this then due to inactivity by the people responsible for requesting it. In any case, we can reopen it 👍

**Comment by jbalsas** [comment]
I think calling Lee inactive is a bit of a mischaracterisation, @kresimir-coko.

As @victorvalle said, this is not currently covered by the specific needs of the design language, but they'll keep an eye open for such cases to suggest additions like this in the future if needed.

**Comment by duracell80** [comment]
I'd lead a user advocacy group if there was one. I think there's a lot of value in connecting how users experience the product directly to engineering.

This element would be extremely helpful for the layout references validation. When we get a user that has 23 broken document links in web content it would be very helpful for the red bars to tab through each broken link rather than saying "you have broken links ... But we're not going to tell you where they are, even though we know".

**Comment by kresimir-coko** [comment]
@duracell80  I apologize for the me not being clear.

> ...inactivity by the people responsible for requesting it

The quote above was a reference to Victor's comment:

> ...in this case echo, has not solved it already and wants to go for it. We just need their request.

As far as I understand it, they(echo) need to open a request, therefore they are the "people responsible for requesting" in this context.

**Comment by jbalsas** [comment]
> I'd lead a user advocacy group if there was one. I think there's a lot of value in connecting how users experience the product directly to engineering.

I think that would be awesome... not sure if @dgomezg or @AngeloYoun have some more insight about initiatives in that direction.

> This element would be extremely helpful for the layout references validation. When we get a user that has 23 broken document links in web content it would be very helpful for the red bars to tab through each broken link rather than saying "you have broken links ... But we're not going to tell you where they are, even though we know".

Hey @duracell80, that does sound like an interesting case to analyze, and as @victorvalle said, they can investigate that and raise additional requirements for us to implement if needed. I'm going to ping @JorgeFerrer in case he wants to move it within the team.

**Comment by d80wrk** [comment]
Did this get any further in terms of condensing multiple toasts into one toast?

**Comment by wincent** [comment]
@d80wrk: To my knowledge we don't have anything to report at this time, but if this is still of interest to you I'd suggest making a new ticket for it so that we have a clear indication that there is still demand in this area (a closed ticket like this one is unlikely to get updated, even if further work in the area occurs).
