### ISSUE TITLE
Focus style for all the components

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#1616]
We would like to have a simplified and unique focus style for all the lexicon components, our idea is to use 2 outside borders or 2 shadows, one white and one blue. 
This solution would allow the focus to be readable in all the liferay contexts.

Inside ring: $white / #FFF / opacity 1.0 / 2px
Outside ring: $primary / #0B5FFF / opacity 0.5 / 2px

You can see some examples here: 
https://www.figma.com/file/IdKljAjIVLIbFYj38ctWwUJH/focus-state?node-id=51%3A8

cc: @victorvalle

**Comment by marcoscv-work** [comment]
Hey guys, this is a really great accessibility improvement, thanks!
