### ISSUE TITLE
Alert text when a link is inconsistently colored with rest of message

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#1619]
Occurring in Lexicon (DXP 7.0) as well as Clay (DXP 7.1 and 7.2).

Alerts can contain links in DXP, noted when sending an item to the recycle bin. Options are included to undo the action or visit the item via a link. This link is discolored blue.

**Expected**
Link color matches text color, doesn't have to be bold can be underlined or both still but the blue link can cause accessibility issues with contrast if a theme has changed the background shade. Inheriting the text color would be safer.

![alerts-with-links-wrong-text-color](https://user-images.githubusercontent.com/18121278/53596596-aeafc000-3b65-11e9-962e-51b63eafeee0.JPG)
![recycle](https://user-images.githubusercontent.com/18121278/53596607-b5d6ce00-3b65-11e9-8a9e-12342480aeee.JPG)

Inherit color for .alert-link

![inherit-color](https://user-images.githubusercontent.com/18121278/53596884-7197fd80-3b66-11e9-97ab-86ccd40f6c4c.JPG)

**Comment by pat270** [comment]
I think the link color was intended by the Lexicon team, but I don't see an official example on the Lexicon Site.  @victorvalle should have the answer for this.

As for accessibility issues when the background-color is changed, we can't really solve that issue from this end. It would be up to the dev and designer to make sure the colors are compliant. We provide the variables `$alert-{component}-link-color` and `$alert-{component}-link-hover-color` to help customize the colors. You can see and test which variables are available at https://v2-claypaver.wedeploy.io/2.1.12/alert.

**Comment by victorvalle** [comment]
Hi @duracell80 !

I understand your concern about the link text color but the color we have now is correct from an accessibility point of view. It is easier to identify links if they look the same everywhere.

What is less correct is to have Undo, that is an action, as a link. It is in our roadmap to change actions inside labels from links to buttons. We can not compromise a date.

Best regards,
Víctor

**Comment by duracell80** [comment]
That really is a shame because the underline would denote the link. The coloration just looks like a bug.

**Comment by victorvalle** [comment]
Our decision is consistent in all the system and this consistency allows users to identify links.
We don't find this as a bug.

Thanks for reporting!

**Comment by duracell80** [comment]
Thank you, I'll follow up on JIRA as there is inconsistent link styles even in 7.0 as seen in the screen shot.

Is this a Lexicon 1 issue?
