### ISSUE TITLE
When using ClayDropdown with Radios, an event is emitted twice

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#1620]
Steps to reproduce:
- Attach an `itemClicked` listener inside ClayDropdown with radio buttons
- Click inside any generated `<li>` element

You gonna see the event being emitted twice.

@NemethNorbert

**Comment by diegonvs** [comment]
Apparently the `<label>` element is emitting two events, one from `<span>` element and another from `<input>`. When removing this parent element, everything is okay.

**Comment by matuzalemsteles** [comment]
hey @diegonvs this is related to #1618, I'm closing to be able to tracker there. Thanks!
