### ISSUE TITLE
Accordion/Collapsible icon 12x12 instead of 14x14

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1629]
The size of the icon is a bit big and doesn't look well. Could you please change it from 16x16 to 14x14?

Thanks!

**Comment by pat270** [comment]
@victorvalle where are you seeing this? It's been 14px forever. See https://clayui.com/docs/css-framework/satellites/panels.html and http://pat270.github.io/lexicon/content/panels/#accordions-with-open-and-close-icon.

**Comment by victorvalle** [comment]
Sorry @pat270 it has to be 12x12, my mistake.

cc: @atjuan
