### ISSUE TITLE
ClayCSS Add Color Variables Defined in Lexicon

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1649]
https://lexicondesign.io/docs/designPrinciples/colors.html

**Comment by marcoscv-work** [comment]
https://issues.liferay.com/browse/LPS-91496

**Comment by justingolden21** [comment]
Updated link to Lexicon Colors: [https://liferay.design/lexicon/foundations/color/](https://liferay.design/lexicon/foundations/color/)

In case someone stumbles upon this post and finds it useful.
