### ISSUE TITLE
Accordion/collapsible sm size

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1664]
![image](https://user-images.githubusercontent.com/7963804/54213142-37264d00-44e4-11e9-9652-c2152604f8b3.png)

Actually it will be used only in sidebar

Based on:
https://issues.liferay.com/browse/LEXI-537

**Comment by marcoscv-work** [comment]
We could use some helper like 'pb-x' but it would look awful

**Comment by pat270** [comment]
@marcoscv-work The markup for the small size is:
```
<div class="panel-group panel-group-flush panel-group-sm">
  <div class="panel panel-unstyled"></div>
  <div class="panel panel-unstyled"></div>
</div>
```

One thing I forgot to check is if we are using `.panel-unstyled` in 7.x. I'll have to redo that component if we are using that class.
