### ISSUE TITLE
We need a bigger tbar, lg-version

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#1670]
Based on:
https://issues.liferay.com/browse/LPS-91988

**Comment by pat270** [comment]
Hey @marcoscv-work, do you happen to have a screenshot of what "The upper toolbar" is?

**Comment by victorvalle** [comment]
Hi @pat270 
[Design](https://www.figma.com/file/ZA8tKhbvGIJDuZrGx3nS2ACr/lexi-502-upper-toolbar?node-id=0%3A1
)
[Documentation](https://docs.google.com/document/d/1mOs-FmB8xc1xQbtbEHw7pN8LRNFe9UE9RS2Lw01N8Lg/edit)

**Comment by marcoscv-work** [comment]
![image](https://user-images.githubusercontent.com/7963804/54267443-879bba00-4579-11e9-8da5-4d4213e6f309.png)

https://lexicondesign.io/docs/patterns/Toolbars/toolbar-upper.html

The reason we think we can base this component on tbar is that the teams are already using it in portal, but maybe make more sense in a new component (portal teams will not be able to update them for 7.3)

What do you think?

**Comment by pat270** [comment]
@marcoscv-work There are a lot of items stuffed in the upper toolbar. How will it look in mobile? If the teams have already implemented the component and can't update them for 7.3, do we really need this in Clay CSS?

**Comment by marcoscv-work** [comment]
Really good questions. @victorvalle what do you think?

**Comment by victorvalle** [comment]
@marcoscv-work @pat270 I'm not sure if we need this in Clay.
This is just guidelines that we provide to the teams to build their own bars. In this case, Lexicon only provides a bar with padding and that is all. They are responsible for how the bar looks in different portraits. This is what they requested, a bit of guideline and total freedom.

**Comment by pat270** [comment]
I would say lets not add it, unless we are implementing more of these and want a place to make the markup consistent for the component. I think it would also work better as a `navbar` variant there are more options to resize, break to new line, hide/show stuff in mobile.

**Comment by pat270** [comment]
I'm closing this since it doesn't seem like we need to implement it in Clay CSS. Feel free to reopen it if we do. @marcoscv-work @victorvalle
