### ISSUE TITLE
Paginator text modification

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1694]
Please remove "entries" or "items" word as it doesn't add value.
Please remove it from the selector and from the specification text that says the dataset portion being showed.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as `2.x` that are not `type:bug` since `2.x` is in maintenance and we won't be proactively be taking these ones.

Please @victorvalle, reopen if this is important or if it affects our new `3.x` components so we can plan work for it.

Thanks!
