### ISSUE TITLE
User Card Update

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1713]
https://issues.liferay.com/browse/LEXI-503

We need to update the user card to avoid text inside the sticker. 

1. Stickers shouldn't allow text in order to improve accessibility and language changes.
2. As in the latest documentation update the sticker size should go from a minimum size of 48px to a maximum size of 80px.
3. Use the User Icon inside the sticker a a placeholder when the User Image is not provided.

**Comment by matuzalemsteles** [comment]
hey @pat270 should not Stickers accept text only on the User Card or anywhere?

**Comment by pat270** [comment]
@matuzalemsteles I want to say no text in stickers but @victorvalle needs to confirm. In my opinion, it might be a good idea to leave the ability to have text in stickers.

**Comment by matuzalemsteles** [comment]
Thanks @pat270. 

hey @victorvalle the icon can still be customized on a User Card.
