### ISSUE TITLE
heading problem at list row

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1731]
We have a heading problem in list title where the title is coded as an h4.

![image](https://user-images.githubusercontent.com/21121115/55140852-55718700-5139-11e9-87d9-d4b3f97c369c.png)

Title size should be 14px semibold (600) #272833
Moreover subtitle is wrong and should be 14px regular (400) #6B6C7E

**Comment by matuzalemsteles** [comment]
The heading was removed from the documentation through #1755. @pat270 Are CSS changes already fixed? The site already has some time that has not been updated with recent clay-css changes.

**Comment by pat270** [comment]
@matuzalemsteles @victorvalle The style issues aren't in Clay CSS. The reason why Clayui.com looks different is because the markup is only using `<li class="list-group-item list-group-item-flex"></li>` instead of:
```
<ul class="list-group">
    <li class="list-group-item list-group-item-flex"></li>
</ul>
```

**Comment by matuzalemsteles** [comment]
Thanks @pat270 I'll take care of updating this on clayui.com
