### ISSUE TITLE
Bring card-page-equal-height class to image, user, file cards

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1741]
Hi, we would like this class from the latest cards to be applied in all cards:

card-page-equal-height

This is really good and helps us solving some unexpected situations we encountered when teams applied for the other normal cards.

Thanks!

**Comment by pat270** [comment]
@victor.valle https://github.com/liferay/clay/pull/1715 should cover this, but the component teams need to follow a specific markup pattern. If the card is wrapped in a `<div>` or any element, the equal height won't apply.

**Comment by pat270** [comment]
This already exists with:
```
<ul class="card-page card-page-equal-height">
  <li class="card-page-item col-6">
    <div class="card">...</div>
  </li>
  <li class="card-page-item col-6">
    <div class="card">...</div>
  </li>
</ul>
```
