### ISSUE TITLE
Autocomplete suggestions height doesn't seem to be consistent with Lexicon definition

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#1742]
See [this jira comment](https://issues.liferay.com/browse/LPS-92790?focusedCommentId=1747641&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1747641).

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, this was resolved through issue #1579 and the PR was sent through #1735. I'll close this since it relates to #1579.

**Comment by 4lejandrito** [comment]
Awesome! Thanks @matuzalemsteles!
