### ISSUE TITLE
ClayMultiSelect: The focus of the item comes back from where it left off when I clicked out of the dropdown and back to navigate from the input

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1796]
When I'm browsing via Tab in Dropdown and I click outside the dropdown and then I come back with the focus on the input element and start again to navigate through the dropdown:

**Expected behavior**
Focus on the first dropdown item

**Current Behavior**
Focus on the last item in the previous navigation

**Comment by kresimir-coko** [comment]
Closing because it's an issue related to 2.x
