### ISSUE TITLE
ClayMultiSelect and ClayAutocomplete: Dropdown is kept open when it is not focused on the component

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#1797]
The focus behavior in MultiSelect is strange, when I type some value in the input and I have the Dropdown open and I click outside the component or I go to another form for example, the focus is maintained and the dropdown is still open.

The behavior when I only have some value typed but the dropdown is closed by not having a suggestion, when I click away or lose the focus the value of the input is erased and I no longer have focus on the component, I'm not sure if it should be the same for the case above.

**Comment by kresimir-coko** [comment]
Closing because it's an issue related to 2.x
