### ISSUE TITLE
CreationMenuDropdown not fully localized

### ISSUE THREAD

**Issue by balazssk** [liferay/clay#1860]
Hi @carloslancha , @matuzalemsteles ,
I've noticed that the CreationMenuDropdown's  "more" label is not localized, I've tracked it down to this point :

https://github.com/liferay/clay/blob/2.x/packages/clay-dropdown/src/ClayCreationMenuDropdown.soy#L171

https://issues.liferay.com/browse/LPS-94122

Can you please help fix this?
Thanks

**Comment by matuzalemsteles** [comment]
hey @balazssk, Thanks for tracking, I'll take care of it.
