### ISSUE TITLE
Update the React Billboard package version

### ISSUE THREAD

**Issue by interaminense** [liferay/clay#1864]
Hey guys, I would like to update the React Billboard package version because this new version is including some parameter fixes that are passed to the charts. See the change log below.

https://github.com/planttheidea/react-billboardjs/releases/tag/1.5.2

**Comment by jbalsas** [comment]
We're exploring a change in how we integrate and distribute charts, so discarding this for now as we'll likely do something else

/cc @bryceosterhaus, @kresimir-coko
