### ISSUE TITLE
ClayCard needs option to pass in tabindex attribute to the container

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1871]
Lexicon Design has Card for Navigation which has focus styles. We need to be able to pass in the `tabindex` attribute or allow the card container to use an `<a>` tag.

<img width="329" alt="card-for-navigation" src="https://user-images.githubusercontent.com/788266/56322692-9e0bd700-611e-11e9-8608-20eed1f8b901.png">

**Comment by matuzalemsteles** [comment]
I'm closing this once it was fixed with the implementation in React #2007
