### ISSUE TITLE
Management Toolbar dropdown style breaks on small screens

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#1883]
On small screens the last element loses its spacing leaving the text too close to the bottom. 

See: 

![Screen Recording 2019-04-22 at 11 23 58](https://user-images.githubusercontent.com/1937354/56494198-ccf4c500-64f1-11e9-930c-fe2152ded3cd.gif)

Thanks!

**Comment by pat270** [comment]
@4lejandrito Can you provide more info about how to get the Google Doc, Slide, Sheet links to show? I just rebuilt master and I can't duplicate it. My guess is something portal side is causing that issue, I already see some inconsistencies between ClayCSS `dropdown-menu` markup and the add button `dropdown-menu` CSS.

**Comment by 4lejandrito** [comment]
Hi @pat270,

You can just fill [this configuration form](http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_factoryPid=com.liferay.document.library.google.drive.configuration.DLGoogleDriveCompanyConfiguration&_com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_mvcRenderCommandName=%2Fedit_configuration&_com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_pid=com.liferay.document.library.google.drive.configuration.DLGoogleDriveCompanyConfiguration) with 3 random values. Just having them will make those icons visible.

**Comment by pat270** [comment]
@4lejandrito ok I can see it now. This is a firefox only issue. I can do a workaround for it.

**Comment by 4lejandrito** [comment]
Thanks @pat270!
