### ISSUE TITLE
Use @storybook/addon-viewport on our storybook to check mobile viewports

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#1899]
When using this addon, we could check if our components are being rendered correctly in mobile viewports.
- https://www.npmjs.com/package/@storybook/addon-viewport

**Comment by bryceosterhaus** [comment]
What do you think of just using the browser devtools for that instead? Wasn't sure if this added anything more than what is already available in most browser's dev tools.

**Comment by diegonvs** [comment]
It's just to avoid going use DevTools but I agree that we don't need more one devDependency :)
