### ISSUE TITLE
ClayUI.com - link from Clay Forms Hierarchy page to Lexicon Form Hierarchy page is broken

### ISSUE THREAD

**Issue by reinrl** [liferay/clay#1925]
On https://clayui.com/docs/components/forms/forms-hierarchy.html#clay-sidebar, the link labeled "Forms Hierarchy Pattern" points to a 404 - instead, it should point to https://liferay.design/lexicon/core-components/forms/forms-hierarchy/.

**Comment by matuzalemsteles** [comment]
Closing this, the changes are in the air 🎉
