### ISSUE TITLE
Change initial delay for Tooltips

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#1988]
**Is your feature request related to a problem? Please describe.**
Currently, the tooltip is shown in 0 seconds. That's fast and annoy users. We could add a time delay. 

![0s delay](https://user-images.githubusercontent.com/21216422/57880400-ee11b280-781e-11e9-9af7-ee20f611c14d.gif)

My hypothesis basis is when the pointer remains stationary users have stopped and are trying to guess what the UI element is about. That's the moment to show a tooltip.

IMO, we are not showing the tooltip when the pointer remains stationary. Instead, the event is triggered once the pointer enters in the UI element.

**Describe the solution you'd like**
I would like to have a delay of **0.5s** when the event is triggered.

![0 5s delay](https://user-images.githubusercontent.com/21216422/57880429-fff35580-781e-11e9-936d-898aa27106e4.gif)

**Describe alternatives you've considered**
Values from **0.3s** - **0.5s** would be acceptable. 

On the other hand. I would like to set different times for different user scenarios:

1. **Initial** . The time the pointer must remain stationary for the tip to appear. The default time is 0.5 seconds.

2. **Reshow**. The time the pointer must remain stationary as the pointer moves from one target to another. The default time is 0.1 seconds.

3. **Removal**. The time after which the tip is automatically removed. The default time is 5 seconds.

**Additional context**
The current fade animation **0.15s** is still valid.

**Resources**
[MS Tooltips and Infotips](https://docs.microsoft.com/en-us/windows/desktop/uxguide/ctrl-tooltips-and-infotips)
[NNG Tooltip Guidelines](https://www.nngroup.com/articles/tooltip-guidelines/)

**Comment by drakonux** [comment]
cc\ @boton @victorvalle @marcoscv-work

**Comment by drakonux** [comment]
Ei @jbalsas and clay team have you reviewed this idea? or considered it for 3.x?

**Comment by matuzalemsteles** [comment]
I am closing this since we only implemented for 3.x #2347.
