### ISSUE TITLE
Add the vertical-fluid for the image of the card component

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2015]
Related to the ticket https://issues.liferay.com/browse/LPS-95717

The image of the standard card has this markup by default

`<img alt="thumbnail"class="aspect-ratio-item-center-middle aspect-ratio-item-fluid" src="/images/thumbnail_coffee.jpg" />`

I'd like to be able to change the class `aspect-ratio-item-fluid` into `aspect-ratio-item-vertical-fluid` passing a parameter when I call it from the Portal

**Comment by matuzalemsteles** [comment]
hey @carloslancha maybe look again at #1591, #1568. What do you think?

**Comment by carloslancha** [comment]
Closing as duplicate: https://github.com/liferay/clay/issues/1568
