### ISSUE TITLE
Autocomplete dropdown list not working on arrow up and down

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#2018]
The autocomplete list is only working with the tab but it is not possible to navigate with arrow keys. This would be very nice to have.
The arrow keys right now address the scroll interaction.

**Comment by matuzalemsteles** [comment]
I had thought it was for us to remove this and just add the tab navigation. I think we had a mismatch of information. See #1840

**Comment by diegonvs** [comment]
#2129 will fix that ;)
