### ISSUE TITLE
Create a searchbox for Icon's symbols on CSS > Components > Icons

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2029]
Would be nice filter all the available symbols on Icons documentation.
Current view:

<img width="857" alt="Screen Shot 2019-05-29 at 15 22 31" src="https://user-images.githubusercontent.com/7663513/58581299-9d8a5400-8225-11e9-88e8-38de63ca0159.png">

/cc @matuzalemsteles

**Comment by diegonvs** [comment]
As discussed in https://github.com/liferay/clay/pull/2027#discussion_r288566450

**Comment by bryceosterhaus** [comment]
Not sure a search here will solve our problem, unless we alias icons to other types of names. For example, the musical note icon, I would probably type in "music" or "note" to the search, and nothing would appear. I might conclude that it doesn't exist, but the problem was that I needed to search for the "audio" icon.

If we just add a search that filters the icon name, its still gonna be hard to use and no better than the default browser search. So I think if we add this, we need to make sure and add "aliases" for each icon.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus good point, I think if we add it we will have to add aliases that are easy to find for the icons. We'll have a little work, but I think it's worth it.

**Comment by kresimir-coko** [comment]
I'm thinking of picking this one up next, but I couldn't find the `Icons` referenced in `https://github.com/liferay/clay/blob/master/clayui.com/content/docs/components/css-icons.md` as `[foreach Icons]`. I'm still figuring out how to properly search for things in the repo :smile:

**Comment by matuzalemsteles** [comment]
hey @kresimir-coko, don't worry. When we have such syntax in `md` files, we usually create gatsby plugins to handle them. You can find this in particular at `gatsby-remark-foreach-icons`.

**Comment by kresimir-coko** [comment]
Can you confirm @eduardoallegrini ? I was planning on starting work on this today.

**Comment by kresimir-coko** [comment]
[Here](https://gist.github.com/kresimir-coko/011bd192f55529930feb23c9313a0cc6) I've gathered all the icon names and added empty values for aliases. In case someone else didn't wanna do the busywork of compiling them.

**Comment by drakonux** [comment]
Hey guys! yeah @eduardoallegrini maybe this can help. 

We have a [catalog](https://docs.google.com/spreadsheets/d/1Dc_hyiGodSlJHfGx8V1B5ezQgcbZkZzS_93aLn8VxIU/edit?usp=sharing) with all the icons, theirs names and metaphors / related terms. 

FYI. We created it to help designers to find icons using Figma and to help us to see conflicts between metaphors.

**Comment by kresimir-coko** [comment]
@bryceosterhaus can you give me some advice on which approach to take for this. I have a json that I exported from the [catalog](https://docs.google.com/spreadsheets/d/1Dc_hyiGodSlJHfGx8V1B5ezQgcbZkZzS_93aLn8VxIU/edit?usp=sharing) containing all the icons and their aliases. I couldn't figure out a proper way of connecting the search functionality with the DOM in the markdown file.

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)

**Comment by esanzp** [comment]
Closing is as it is already merged
