### ISSUE TITLE
Use Prettier to format SCSS

### ISSUE THREAD

**Issue by wincent** [liferay/clay#2037]
We're using Prettier in liferay-portal now to format JS and SCSS files. Because the clay-css SCSS files end up getting copied around inside portal (eg. in themes; random example: apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/css/clay/mixins/_position.scss ) it would be nice if they were formatted the same way.

For now, I am going to add an exclusion so that Prettier in liferay-portal doesn't try to check or format those Clay files, but it would be nice if we got Prettier to format SCSS in this repo too (currently it is only used to format JS, AFAIK). This might be a change that we want to make on both the "2.x-develop" branch and "develop".

@pat270, @carloslancha, @matuzalemsteles, @bryceosterhaus

**Comment by wincent** [comment]
At least one gotcha we'll have to be mindful of: there is [a bug](https://github.com/prettier/prettier/issues/5967#issuecomment-498636530) in Prettier's SCSS printer with respect to handling of comments. At least for now, we may have to avoid trailing comments.

**Comment by matuzalemsteles** [comment]
I would not mind adding to our CSS, but I think the comments will be accurate now as we will add SASSDoc and also create an integration with next.clayui.com to show the API's.

**Comment by pat270** [comment]
@wincent we can update our scss to to follow Prettier's formatting. The only problem we might have is with Bootstrap. They use something called `stylelint`.

**Comment by wincent** [comment]
@matuzalemsteles: yep. It's not that we can't have comments; it's just that we need to be careful that *trailing* comments don't lead to broken formatting. We might have to use line-before comments instead.

@pat270: just so you know, no hurry on this: I have [a PR up for liferay-portal](https://github.com/brianchandotcom/liferay-portal/pull/74081) that tells it to ignore everything with "clay/css" in the path, so this is something that we can get to when it fits in without our priorities.

**Comment by jbalsas** [comment]
Removing the `2.x` label so we only consider applying this to `3.x`. With our work on SCSS and stylelint, maybe it's time to revisit this?

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)
