### ISSUE TITLE
Change branch structure for consistency with other projects

### ISSUE THREAD

**Issue by wincent** [liferay/clay#2043]
As per suggestion [here](https://github.com/liferay/liferay-frontend-guidelines/pull/14#discussion_r290828549).

The idea is, work will move to these two branches as described in that PR:

- "master"
- "2.x"

with accompanying "stable" and "2.x-stable" branches for hotfixes and book-keeping.

In terms of urgency, I don't think this is urgent to have this this instant, but it would be nice in the name of "eventual consistency" 😂

**Comment by matuzalemsteles** [comment]
I remember we had a problem when the issues were closed as soon as the commits entered the master, causing a confusion people thought was already available for use right away. With this, the branch develop and the `next-release` label were created and only closed when it entered the master and the release exited.

I think today does not have this problem anymore, but just to not forget it.

**Comment by bryceosterhaus** [comment]
This sounds good to me. I'm assuming when we release 3.x, we will also have a branch for that?

**Comment by wincent** [comment]
I think that's right @matuzalemsteles. In practice, when we've been cutting weekly (or more) releases of Clay, which means that the lag time between an issue closing and it being on NPM is low. There will always be some lag anyway between NPM publish and land-in-liferay-portal anyway, so I think the only way to be 100% sure that something is out is you see it under "[releases](https://github.com/liferay/clay/releases)" *and* you have seen the corresponding Clay update get merged in liferay-portal.

@bryceosterhaus: The post-3.x end state would be:

- master: for 3.x development
- stable: always pointing at latest 3.x release
- 2.x: for 2.x maintenance releases (relatively fewer of those)
- 2.x-stable: always pointing at lastest 2.x release

So it isn't a large change in this repo because it is already using a similar structure. It is mostly just about alignment and consistency with other projects, and a slight reduction in friction because "master" is the `git` and GitHub default, and is used in the majority of places out there.

**Comment by matuzalemsteles** [comment]
> I think that's right @matuzalemsteles. In practice, we've been cutting weekly (or more) releases of Clay, which means that the lag time between an issue closing and it being on NPM is low. There will always be some lag anyway between NPM publish and land-in-liferay-portal anyway, so I think the only way to be 100% sure that something is out is you see it under "releases" and you have seen the corresponding Clay update get merged in liferay-portal.

Yes, you're right. Maybe we can add the PR link that does the update of Clay in the liferay-portal in the corresponding release, it can help people to track. I think with this we can kill the use of `next-release` that in this context does not make sense anymore.

**Comment by bryceosterhaus** [comment]
@wincent what would be the flow for when we hypothetically start and release a v4 or v5?

**Comment by matuzalemsteles** [comment]
@bryceosterhaus I think it would be:

- Creates `3.x` and `3.x-stable` branch
- `master` with active 4.x development
- `stable` with the last release of the master.

and so would the next versions.

**Comment by wincent** [comment]
@matuzalemsteles: yep, that's right. Another thing to bear in mind: as we've discussed in other tickets, we:

- (a) want to (actually) follow semver from now on;
- (b) want to make a big effort to avoid making breaking changes...

Which means that hopefully we won't be updating the major version very often. Of course, the branching guidelines aren't inviolable laws of the universe; if we find that maintaining these maintenance branches isn't working out, we can re-evaluate. But in the context of Clay and liferay-portal, I think the most likely cadence will be to bump the Clay major version at most once per year (ie. the same cadence as annual DXP releases).

**Comment by bryceosterhaus** [comment]
sounds good to me

**Comment by matuzalemsteles** [comment]
To finish this is missing:

- [ ] Rename `1.x-develop` to `1.x-stable`
- [ ] Rename `2.x-develop` to `2.x-stable`
- [ ] Rename `develop` to `stable`

To realize this change, we also have to start following the processes:

- Use `1.x` for maintenance and `1.x-stable` with the latest stable version of `1.x`.
- Use `2.x` for maintenance and `2.x-stable` with the latest stable version of `2.x`.
- Use `master` for active v3 development.
- Use `stable` with the last stable release of the master.

It will no longer be necessary to use the `next-release` label, as soon as the PR enters the main development branches they will be closed, to identify the launches check the [Releases](https://github.com/liferay/clay/releases) tab, to verify if the version has entered the Portal, we have to add the PR link that is taking care of it within Release note of the corresponding version.

**Comment by wincent** [comment]
> - [ ] Rename `1.x-develop` to `1.x-stable`
> - [ ] Rename `2.x-develop` to `2.x-stable`
> - [ ] Rename `develop` to `stable`

Are you sure?

Current:

- 1.x = last stable release
- 1.x-develop = development of next release

Future:

- 1.x = development of next release
- 1.x-stable = last stable release

So I would have expected that we'd go:

- 1.x -> 1.x-stable
- 1.x-develop -> 1.x

Not:

- 1.x-develop -> 1.x-stable

Of course, right now `1.x` and `1.x-develop` are pointing at the same commit, so it doesn't matter much. Likewise for `2.x` and `2.x-develop`. I just want to make sure there's no confusing though.

And given that you can't rename branches on GitHub, the actual operations we're talking about are:

- Create 1.x-stable: `git push origin 1.x:1.x-stable`
- Delete 1.x-develop: `git push origin :1.x-develop`
- "Create" 1.x: [no action required; already pointing at the right commit]

Same on the 2.x side. And on the master side you've already synced "master" and develop, so all we have to do is:

- Create stable: `git push origin master:stable` (of course, this won't really be actually "stable" until the first release.
- Delete develop: `git push origin :develop`

Does that sound about right?

**Comment by matuzalemsteles** [comment]
Yeah, I ended up going that route by becoming simpler to understand, I understand that the development branches will be `1.x` and `2.x` I went down this path of 'renaming' because the commits are pointed for the same now.

**Comment by matuzalemsteles** [comment]
This is done! Thanks @wincent
