### ISSUE TITLE
yarn build doesn't work on node v12

### ISSUE THREAD

**Issue by brunofarache** [liferay/clay#2053]
`yarn build` doesn't work when using node version 12 or above.

gulp 3 doesn't work well with node 12, see:

https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)

**Comment by p2kmgcl** [comment]
Same thing happens with node 14. Which version of node should we be using? It seems to work with node 10

**Comment by jbalsas** [comment]
Yeah, `@clayui/css` depends on `gulp@3` for the test site, so I guess that's where the issues is coming from.

https://github.com/liferay/clay/pull/3362 should get us closer to removing the `gulp` dependency, I think... right @bryceosterhaus?

**Comment by bryceosterhaus** [comment]
@jbalsas yeah thats correct, there are issues with gulp + newer node versions, but only for clay-css. The other packages should build fine.

@p2kmgcl do you need to build it on node 14 for a specific reason? We can try to prioritize this if its a road block for something.

**Comment by jbalsas** [comment]
I think they're simply running `yarn build` from the root to trigger everything, instead of independent packages. And since that does `lerna build`,  it will choke when it gets to build `clay-css`.

**Comment by p2kmgcl** [comment]
@bryceosterhaus nope, I don't need to use node 14, it was the version I had installed by default :sweat_smile:
But it's no problem to switch to node 10 :)

**Comment by bryceosterhaus** [comment]
@p2kmgcl sounds good! We are slowly trending towards getting rid of the gulp dependency, but until its fully removed, we need to build clay-css with node 10

**Comment by kresimir-coko** [comment]
Is this still a problem @bryceosterhaus after #3362 has been merged?

**Comment by bryceosterhaus** [comment]
@kresimir-coko yeah this is still an issue for as long as we have `gulp` used in clay-css. I think we can just keep this open in case others run into this issue

**Comment by matuzalemsteles** [comment]
I'll close this in favor of #4132, we'll soon start working on simplifying the `clay-css` build flow to allow us to use the latest versions of Node.js and lessen our dependencies. Thanks guys!

**Comment by brunofarache** [comment]
👀

**Comment by nhpatt** [comment]
To whom do those eyes belong? ^ Do you know him? :)

**Comment by brunofarache** [comment]
Sorry I meant 🎉, I can finally build clay with my favorite node version 😂

**Comment by bryceosterhaus** [comment]
@brunofarache, I am so excited you have decided to be our number 1 user now! "Elastic built with ClayUI" 😍  😂
