### ISSUE TITLE
line-clamp mixin

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2058]
It is already used in Liferay portal so I think we should provide a mixin from Clay
https://github.com/brianchandotcom/liferay-portal/pull/74340

Browser support has improved a lot:
https://caniuse.com/#search=line-clamp
![image](https://user-images.githubusercontent.com/7963804/59342293-ca506800-8d09-11e9-9e52-4b16813296c8.png)

Currently, it works in Firefox nightly (version 68) even with -webkit prefix:
![image](https://user-images.githubusercontent.com/7963804/59342328-db00de00-8d09-11e9-9497-6a1328949616.png)
from: http://jsfiddle.net/danield770/DpQ7e/30/ (don't look at :after)

**Comment by pat270** [comment]
@marcoscv-work The way to use the mixin is:
```
.my-line-clamp-element {
  @include clay-line-clamp(3);
}
```
sometimes the `line-height` for an element is different compared to the base document (e.g., 1.2 instead of 1.5):
```
.my-line-clamp-element {
  @include clay-line-clamp(3, 1.2);
}
```
