### ISSUE TITLE
[@claui/link] Proposal for outline and monospaced new displayTypes

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2073]
There aren't any ways to compose `outline` or `monospaced` links with the current ClayLink

<img width="328" alt="Screen Shot 2019-06-18 at 17 10 57" src="https://user-images.githubusercontent.com/7663513/59716267-114bcb00-91ec-11e9-8623-363a17d17db4.png">

One possible solution is adding `outline`  and `monospaced` as `displayType` too.

**Comment by bryceosterhaus** [comment]
I'd probably add those options as individual props. If we add to as a displayType, we couldn't allow both outline and monospaced at the same time. We also need to add `secondary` as a display type.

**Comment by diegonvs** [comment]
Submitted here: https://github.com/liferay/clay/pull/2098
