### ISSUE TITLE
Clay CSS Management Bar Navbar Text should break to new line

### ISSUE THREAD

**Issue by pat270** [liferay/clay#2085]
https://issues.liferay.com/browse/LEXI-477

Lexicon Team:
I think that using M, K.. is not possible for language reasons.

Therefore, I would suggest that for long texts we break lines. The solution above doesn't work well for different languages I would say. This is something very difficult to control.

**Comment by matuzalemsteles** [comment]
hey @pat270 do we have to apply this change to the component too? to add `nav-item-shrink`?

**Comment by pat270** [comment]
@matuzalemsteles Yes I think it's a good idea. It should still work without it, but might cause issues if there is a long number like 100,000,000,000,000.

**Comment by matuzalemsteles** [comment]
Oh yes, I think we can add to prevent this, even though I think it's almost rare to happen.
