### ISSUE TITLE
[next.clayui.com] Make example codes collapsible

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2102]
/cc @matuzalemsteles

**Comment by kresimir-coko** [comment]
Do we have an idea on how this should look in the UI?

**Comment by bryceosterhaus** [comment]
@kresimir-coko we don't have any official mock ups or anything. I would think another icon next to the "copy" button would be sufficient. Perhaps one that toggles between a chevron icon point down and then sideways.  Check out the panel interactions for collapsing for inspiration, https://clayui.com/docs/components/Panel.html

**Comment by diegonvs** [comment]
When I created this issue I was minding about reduce the "readable" size of some CSS Examples, take a look on Dropdown CSS/Markup example: https://clayui.com/docs/components/drop-down.html

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)

**Comment by bryceosterhaus** [comment]
Fixed in https://github.com/liferay/clay/pull/2839
