### ISSUE TITLE
Inconsistent export naming

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2104]
I've seen we have an inconsistent approach to export naming while testing `3.0.0-milestone.1` (which looks quite good).

Maybe I've just been lucky, but I've seen differences between `Icon` and `Select`.

### clay-icon/src/index.tsx
```javascript
const ClayIcon: React.FunctionComponent<IProps> = ({

[...]

export default ClayIcon;
```

### clay-select/src/index.tsx
```javascript
import Select from './Select';
import SelectWithOption from './SelectWithOption';

export {SelectWithOption as ClaySelectWithOption};
export default Select;
```

I'm not 100% sure what's the right approach, but if you use the React DevTools in our own [stories](https://storybook-clayui.netlify.com), you can see the difference. The first one is marked as `ClayIcon` while the other two are un-namespaced.

![Screen Shot 2019-06-21 at 14 40 12](https://user-images.githubusercontent.com/905006/59923057-b3f58b00-9432-11e9-9231-f563ae9659c7.png)
![Screen Shot 2019-06-21 at 14 40 17](https://user-images.githubusercontent.com/905006/59923058-b3f58b00-9432-11e9-8081-2907dbc0c691.png)
![Screen Shot 2019-06-21 at 14 40 27](https://user-images.githubusercontent.com/905006/59923059-b3f58b00-9432-11e9-8655-0751170b5381.png)

Not saying this is super important, but in case it's something worth fixing.

**Comment by matuzalemsteles** [comment]
hey @jbalsas yeah, this is a problem. Thanks for finding this 🙂. I'll add that to our next release.
