### ISSUE TITLE
lerna publish is broken

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2105]
Yesterday I tried to make the release using `lerna publish` but faced some peculiar problems due to the way we structure the monorepo of v3.

- We move all the common dependencies to the root. Almost all components do not have `devDependencies`.
- Most `devDependencies` and `dependencies` for components are between common components or dependencies, most are `classnames`.

In this way most of the components do not exist a `node_modules` nor one with symbolic link for the babel for example.

The problem: when running `lerna publish` it uses `npm publish` and executes `prepublishOnly` commands. Then things fail because we do not have `node_modules` in some packages and even if it does, it does not have a `babel` symbolic link to run in `npm` environment. I'm wondering if we should create some script that does publish using yarn. Thoughts?

**Comment by bryceosterhaus** [comment]
I think we may have to set up lerna to use yarn for publishing and not npm

**Comment by matuzalemsteles** [comment]
Actually it's already configured https://github.com/liferay/clay/blob/master/lerna.json#L5, I'm thinking this is forcing the use of npm... or we ended up updating lerna without realizing it which had changes in the configuration...

**Comment by wincent** [comment]
Not sure if this will be an easy solution, but one thing that immediately leaps out at me is that all of those `prepublishOnly` scripts should be using `yarn build && yarn build:types`, not `npm run build && npm run build:types`.

**Comment by matuzalemsteles** [comment]
Hmm yeah, I did not realize that. This is strange, even when you run `yarn publish` it does not run` npm`... when it runs `prepublishOnly`. I'll investigate this in more detail and test on our next milestone.

**Comment by matuzalemsteles** [comment]
hey guys, doing what @wincent said solves the problem, sorry about that haha ​​😅 thanks
