### ISSUE TITLE
Add keyboard functionality for autocomplete

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2107]
We need to enable arrow keys and return key at a minimum for autocomplete and dropdown instances.

**Comment by andresfulla** [comment]
I have a use case related to this. I'm using `@clayui/dropdown` component. It's related to how the focus behaves on this element.

When the user is focused on the component rendered by the `trigger` prop, then opens the dropdown by hitting the spacebar, (once tab is pressed again) the next focused element is not inside the dropdown body. The focus just moves out of the dropdown.

I'd like the focus to move into the elements inside the dropdown and only then move to whatever is next to the dropdown.

**Comment by bryceosterhaus** [comment]
Fixed https://github.com/liferay/clay/pull/2122. Will also be implemented with high-level autocomplete component

**Comment by bryceosterhaus** [comment]
Fixed https://github.com/liferay/clay/pull/2122. Will also be implemented with high-level autocomplete component
