### ISSUE TITLE
[next.clayui.com] Main sections not needed

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2114]
Main sections for:
- React Components
- CSS
Are not needed.

It causes a strange page refresh when you only want to expand the section and see the items in this section, not to navigate to that main section.

![navigationIssue_2](https://user-images.githubusercontent.com/7963804/60011253-b3026a80-9679-11e9-8eaa-569f0fd58983.gif)

**Comment by matuzalemsteles** [comment]
hey @marcoscv-work, this was intentional, maybe not the best experience... The intention of having the main sections is to give an introduction to CSS and React Components. I plan to add the foundations that will take the React Components and explain how you can go further with it. The same, I wanted to do with CSS. Related #2113

**Comment by marcoscv-work** [comment]
I see and it could make sense but I think users will see the arrow which means you are going to expand the section, and probably you not expect a refresh and page change because it not happening in other sections like:
**Get Started, Foundations, Contributing and Migration**

So for consistency, I would simplify by removing these sections and if an introduction is needed we could make it in the landing page

**Comment by matuzalemsteles** [comment]
Yes I understand, it really is not something good. These sessions would be a bit big and technical stuff, so it's probably something we do not want to put on the landing page. Maybe we can do the same as https://www.gatsbyjs.org/docs/guides does, it works great. What do you think?

![](http://g.recordit.co/8q1r66dPuC.gif)

**Comment by marcoscv-work** [comment]
It could be fixed by your example in gatsbyjs.org/docs/guides but we would need to make two link areas, the first one for section link and the second one to open the sections.
For now, we have removed the content on those pages so we can close the issue and we will work on the solution if finally, we need to create general sections
