### ISSUE TITLE
Unnecessary metal dependencies

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2115]
After installing clay `3.0.0-milestone.1`, I saw some spurious metal dependencies pop up in our `yarn.lock` file which should be no longer necessary.

In particular, it looks like we don't need:
- [clay-data-provider#metal-uri](https://github.com/liferay/clay/blob/master/packages/clay-data-provider/package.json#L33)
- [clay-dropd-down#metal-position](https://github.com/liferay/clay/blob/master/packages/clay-drop-down/package.json#L35)

Additionally, we're depending on `metal-clipboard` in our site, which maybe we could simply replace by it's big-brother [clipboard.js](https://clipboardjs.com/)

**Comment by bryceosterhaus** [comment]
Are you saying we need to get rid of these and find alternatives, or that we don't need them because they are unused?

We are using `metal-position` for the `Align` logic and `metal-uri` is being used for its url tools for our data provider hook.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, I didn't see them being used... I just realized I was looking for `metal-*` usages  in `*.js` files which of course will fail to detect them in `.ts*` :)

Now that we've stablished they're in use, it could be interesting to analyze if the funcitonality they provide is worth keeping those as separate modules with the overhead it generates. We're already trying to consolidate usages of `metal-plugins` within `liferay-portal` so we can discontinue those packages and reduce our maintenance overhead.

**Comment by matuzalemsteles** [comment]
Hmm, I find the use of `metal-position` very useful, probably what we use most here. `metal-uri` maybe we can use another lib if we find that only we are using it from outside the portal.

Or maybe we can move those implementations to here... just for internal use. But it would increase the maintenance surface.

**Comment by matuzalemsteles** [comment]
I'm closing this now that we have removed the metal dependencies from our components. #2764
