### ISSUE TITLE
Priority Thread Icons need to be renamed

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#2119]
This issue is related to this ticket and the comment from Victor Valle: https://issues.liferay.com/browse/LEXI-300

We need a better naming for the icons: 

announcement -> megaphone-full
sticky -> pin-full
urgent -> bell-full

**Comment by matuzalemsteles** [comment]
hey @pat270 I ended up adding so that this change is made only in `3.x` what do you think? or we should send it to 2.x as well.

**Comment by pat270** [comment]
@matuzalemsteles I think 3.x only is the right thing to do. We can note it as a breaking change for those upgrading from v2 to v3.

**Comment by matuzalemsteles** [comment]
Yes, we have to start writing a migration guide to CSS, but I do not think we have much. Do you have any idea of ​​the things we can start writing?

> Edit: @emiliano-cicero If this needs to go into 2.x we can duplicate the icons with different names.

yeah, that's a great idea.

**Comment by marcoscv-work** [comment]
@victorvalle @emiliano-cicero Is this so important to make a breaking change?
About the use of "-full" do you mean the icon is filled?

**Comment by emiliano-cicero** [comment]
@pat @matuzalemsteles @marcoscv 

We would like to have consistency for the icons naming and I created this issue because this three should be named with a description of the icon shape as we did with "bolt, bell" and other icons. 

From my perspective you should have freedom to decide if it's better to apply it to 2.x+ or 3.x+.

The "-full" on the other hand, comes directly from clay with other icos that are filled such as: warning-full, question-circle-full, exclamation-full.

**Comment by eduardoallegrini** [comment]
We should consider the idea of separate the icons from Clay and create an independent library where we can rename the icons updating the version

**Comment by victorvalle** [comment]
This request was already done. I don't know what was the final decision.

**Comment by jbalsas** [comment]
> From my perspective you should have freedom to decide if it's better to apply it to 2.x+ or 3.x+.

Breaking changes are really annoying. It can be hard to track down who's using icons that suddenly disappear. Customers might be using them too, and making it hard for them to upgrade is not a good idea.

> We should consider the idea of separate the icons from Clay and create an independent library where we can rename the icons updating the version

This wouldn't address the problem. We used to offer an icon with a name. Stop doing that, no matter from where will cause a disruption somewhere which, if possible, should be avoided.

I think we can duplicate the icons. Document that the old name is deprecated and will be removed, and ideally, only show the icon with the newer name.
