### ISSUE TITLE
High-level Management Toolbar component

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2155]
See example of [API in v2.x](https://github.com/liferay/clay/blob/2.x-stable/packages/clay-management-toolbar/src/ClayManagementToolbar.js#L296).

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus we have a similar issue #1945, I think we can still keep it in `v3.0.0-milestone.2`, I'll be working on it.

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus I'm going to close the other issue in favor of this, I've been taking a look I think we'd better keep this in `v3.0.0-milestone.3` anyway, why will we need the ClayDropDown high-level API.

**Comment by matuzalemsteles** [comment]
Fixed #2225
