### ISSUE TITLE
Create Slider component

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2157]
See https://liferay.design/lexicon/core-components/forms/slider/

**Comment by marcoscv-work** [comment]
https://docs.google.com/document/u/1/d/1BYPt1ZClWIeyy7NCQO2XMZ87NyHCzWJjGO3YNh7CcZk/edit?usp=sharing

**Comment by marcoscv-work** [comment]
on review!

**Comment by matuzalemsteles** [comment]
Just reopening because we will still work on the components.
