### ISSUE TITLE
ClayDropdown with `searchable`: breaks when inside a form tag.

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2164]
This is a different case from the Forms team, the DropDown is within the context of a form and when it is rendered by the server using the taglibs, the searchable is inside a `<form>` tag and the DropDown is inside another tag `<form>` this is breaking some rules.

The quick hint here is to add a new API, like `wrapSearchable` or `useSearchableWithForm`, which says whether you want to wrap the input with a form or not.

**Comment by brunobasto** [comment]
Thanks, @matuzalemsteles. This actually happens whenever the dropdown is rendered inside a form and the `searchable` prop is set to `true`. Being a component, it could be rendered anywhere following developer desire. I don't think it should include that form by default as the possibility of rendering it inside a form is arguably high and then we got an invalid markup as form inside form is not valid html.

**Comment by matuzalemsteles** [comment]
Fixed in #2166.
