### ISSUE TITLE
Bug: Clay pagination shows incorrectly at certain edge case

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#2180]
This is with @clayui/pagination v3.0.0-milestone.1

![image](https://user-images.githubusercontent.com/14063502/60827096-46e93180-a164-11e9-8b04-8c86967e2d63.png)

**Comment by bryceosterhaus** [comment]
Thanks for finding this. Submitted a fix, https://github.com/liferay/clay/pull/2183
