### ISSUE TITLE
Inconsistent use of Tooltip on Table according to Lexicon

### ISSUE THREAD

**Issue by crcarlo** [liferay/clay#2201]
In [this](https://clayui.com/docs/components/table/table.html) section that has the examples of the Table component on clayui.com the "Title" field of each row shows a tooltip while hovering on it.

The "Dos and Don'ts" section of the "[Popovers and Tooltips](https://liferay.design/lexicon/core-components/popovers-tooltips/)" page in Lexicon's documentation reports "Use tooltips on elements that trigger an action, such as button icons." and the provided example discourages an use like the one that is present on clayui.com, since it's not an element that triggers any action.

In my opinion the guideline provided by Lexicon is incorrect because a tooltip should show a hint wherever the informations directly provided by the element aren't enough, like in the trimmed title in the table.

Anyway, since Clay should implement Lexicon's guidelines I'm reporting this here so you might raise this doubt to the Lexicon's team.

**Comment by matuzalemsteles** [comment]
hey @crcarlo thanks for tracking this! hey @drakonux what do you think about it?

**Comment by drakonux** [comment]
Hi everyone!!!

I agree with @crcarlo. Lexicon is missing an example for trimmed text using ellipsis.

I've created a ticket: [LEXI-644](https://issues.liferay.com/browse/LEXI-644) to add a new example and review the rules written (as he said, the purpose of tooltips is to help the user when the information provided is not enough).

Thanks for your help!!!
David

**Comment by matuzalemsteles** [comment]
Thanks a lot @drakonux!
