### ISSUE TITLE
[@clayui/drop-down] Pressing tab does not pass focus to dropdown

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/clay#2205]
Probably because of portals, if you press `tab` having focus on the dropdown trigger element, focus does not jump to the dropdown menu, but goes through the rest of the document.

Focus should jump to the first item of the dropdown when pressing tab, or, if that is not possible, should jump automatically when the dropdown is opened.

**Comment by matuzalemsteles** [comment]
hey @p2kmgcl we've just implemented this for the `ClayDropDownWithBasicItems` component that will be release in `milestone.2` this week. We still have to decide if we will expose the `useFocusManagement` hook. What do you @bryceosterhaus?

Related #1987

**Comment by bryceosterhaus** [comment]
I think it'd be appropriate for `ClayDropDownWithBasicItems ` to utilize `useFocusManagement `

**Comment by matuzalemsteles** [comment]
hey @p2kmgcl I'm closing this since we are implementing on our high level components. Feel free to reopen if you think we have more things to discuss. Thanks!
