### ISSUE TITLE
[next.clayui.com] Add the TOC and Introduction titles

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2210]
A few weeks ago, I changed the table-of-contents style, in order to make it sticky in desktop, I also added the titles "Table of contents" (not visible in desktop) and "Introduction" to improve the content, you can see it here
https://next.clayui.com/docs/components/autocomplete.html

This was just a test, if you think it's a good change we should add those title to all the pages

**Comment by kresimir-coko** [comment]
Hey @eduardoallegrini I can't see this anymore on the site you linked, perhaps if you make a PR so we can take a look at the Deploy Preview.

**Comment by eduardoallegrini** [comment]
I think we can close this for now, if needed I'll reopen it
