### ISSUE TITLE
Create high-level table component

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2212]
likely should have:
- predefined markup for headers
- configurable row renderer via `rowRenderer` prop
- default row markup
- paginated

We may also want to consider a few different types of defaults for rows.

Also should consider inline-editable fields

**Comment by matuzalemsteles** [comment]
This is a big component, so I'm wondering if it makes sense to create "intermediate" high-levels and we can put it all together. For example, `TableWithEditableRow`.

About `Paginated` I'm not so sure about that, what are you thinking about that?

**Comment by bryceosterhaus** [comment]
Im fine with breaking up into smaller chunks.

For the paginated part, I just threw that in there cause I thought we would need it. I havent looked too much into table yet, just wanted to get a ticket made with some general ideas I think we would need.

**Comment by matuzalemsteles** [comment]
Oh ok, maybe the paginated part can be composed with PaginationBar

**Comment by matuzalemsteles** [comment]
I'm removing this component from this `milestone.3` release, we need to discuss more about it.

**Comment by jbalsas** [comment]
Discarding this for now since most of the work was done in DXP... I'll create a new one with better insights and requirements when ready!
