### ISSUE TITLE
Create high-level modal

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2213]
Not sure how we should go about this exactly, possibly a global action you can call to open a modal with content.

**Comment by matuzalemsteles** [comment]
Maybe we can build a `ClayModalProvider` with Context API so that devs can only use one Modal to display the information and API can be the same as we have at low levels, something like `renderHeader`, `renderBody`,` renderFooter`...

**Comment by bryceosterhaus** [comment]
@matuzalemsteles thats sort of what i was thinking as well.

**Comment by matuzalemsteles** [comment]
Fixed #2276
