### ISSUE TITLE
ClayCSS: Use of background images url for icons

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2232]
In order to use something similar to font-awesome we could create classes with img src to each icon, some work of replacement icons could be much easier for us and for customers

https://codepen.io/marcoscv/pen/voxaJp
It works in IE11

We already have the mixing lx-icon() but it includes the SVG inline.

**Comment by matuzalemsteles** [comment]
I really enjoy moving to using the class icons that looks a lot better.

I've been observing some problems with the current usage we have of `<svg> <use>`, it becomes more evident with components in React, but you can see that when a component renders (in this case it removes it from dom and adds it again) some element with icon and then do it constantly for some reason icons are always requested, odd that in cases like in the storybook examples these new requests are not cached. I may be wrong about this and it is a normal browser standard, but that seems strange to me.

**Comment by jbalsas** [comment]
Hey guys, I'm not entirely against this but I'd like to see more concretion in a proposal and it's pros and cons with our current approach.

It seems Bootstrap is going for `svgs` for their [v5 icons](https://github.com/twbs/bootstrap/pull/29092) approach.

Thinks I'd like to see:
- How does this approach compare with svgs in terms of customization? colours, fills....
- What's the correct markup for this? Is it `<i>`, `<span>`...?
- How do we handle this efficiently? Can we use positions in the spritemap so we don't load each svg independently?

**Comment by pat270** [comment]
We can't change the color of the icon using this method.

**Comment by marcoscv-work** [comment]
After some experiments with mask-image, I can say that yes, the current approach is more flexible, and we need icons in at least two colors so from my point of view we can discard this experiment
