### ISSUE TITLE
ClayButtonWithIcon as trigger of a ClayDropdown doesn't trigger the Dropdown

### ISSUE THREAD

**Issue by andresfulla** [liferay/clay#2234]
When doing something like this:
```jsx
...
<ClayDropDown
  trigger={<ClayButtonWithIcon>Click here!</ClayButtonWithIcon>}
  active={active}
  onActiveChange={setActive}
>
...
```

Clicking the `ClayButtonWithIcon` doesn't trigger the Dropdown, as a regular `ClayButton` would do.

Example in Codesandbox https://codesandbox.io/s/claydropdown-1qesp

**Comment by matuzalemsteles** [comment]
hey @andresfulla thanks for tracking that down.
