### ISSUE TITLE
Typescript autocompletion is no longer working

### ISSUE THREAD

**Issue by andresfulla** [liferay/clay#2235]
Since we updated our components to `3.0.0-milestone.2` VS Code is no longer helping me to write components with props autocompletion. That was a productivity boost, so I'm missing it. Thanks!

**Comment by matuzalemsteles** [comment]
hey @andresfulla I'm glad it helped a lot, but it stops working is a bit weird, we didn't change anything in the typescript types distribution. I need to investigate further to make sure we break. Thanks for that!

**Comment by diegonvs** [comment]
Hey @andresfulla,

I was getting this error in past but probably was a bug with VScode, I'm currently using [VScode - Insiders](https://code.visualstudio.com/insiders/) and It solved for me.

**Comment by andresfulla** [comment]
Thanks! I just installed VS Code Insiders and still does not work for me. So I'll leave it open.

**Comment by jbalsas** [comment]
Didn't seem to work for me either... maybe it's the extension or sth?

**Comment by matuzalemsteles** [comment]
Thanks guys for reporting, I'm marking this with a bug now.

Basic components that had no dependencies between components were working with types, now the components with Clay package dependencies are broken, because types are generated based on the package names inside the lib folder, something like this:

```
./lib/clay-icon/index.d.ts
./lib/clay-button/index.d.ts
./lib/index.js
```

So we can correct the types paths in these packages or we can stop typescript from generating types of these dependencies, I'll investigate this later. Thanks for that again this was possibly already broken in other components and versions.

**Comment by jbalsas** [comment]
I've removed the `is:open` trigger from our exalate sync setup... commenting here to see if at least this gets picked up and the jira issue gets closed

**Comment by andresfulla** [comment]
I had some weird behaviour yesterday with VS Code, and I think it has to do with this.

Whenever I rename a file, and I let **VS Code** perform a refactor on the js files that import that file, not only I get the nicely done refactor , I also get a **prefix `./node_modules/` on all `@clayui`** imports. Weird uh.

I'll open a different issue if this keeps happening, but I'm pretty sure is related to this.

**Comment by wincent** [comment]
@andresfulla: When you open this (maybe you have already, but I couldn't find it), please mention @p2kmgcl as well — we were discussing this in the weekly guild chat and he reports exactly the same problem with the unwanted "node_modules" prefix.

**Comment by andresfulla** [comment]
> I had some weird behaviour yesterday with VS Code, and I think it has to do with this.
> 
> Whenever I rename a file, and I let **VS Code** perform a refactor on the js files that import that file, not only I get the nicely done refactor , I also get a **prefix `./node_modules/` on all `@clayui`** imports. Weird uh.
> 
> I'll open a different issue if this keeps happening, but I'm pretty sure is related to this.

I can no longer reproduce this renaming issue in VS Code. But VS Code keeps complaining in `ClayButton` or `ClayButton`.

**Comment by matuzalemsteles** [comment]
hey @andresfulla we haven't released the changes yet, it was just merged into the master, you can follow the next release here https://github.com/liferay/clay/milestone/10.

**Comment by bryceosterhaus** [comment]
@andresfulla do you still run into this at all? I was looking into something similar in #2775

**Comment by andresfulla** [comment]
I am not having any problems now.
