### ISSUE TITLE
Create ClayToastList high-level

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2252]
Something like:

```jsx
<ClayToastList
​​    items={[
​​        {autoClose: true, message: 'Failure to add item', type: 'error'},
​​        {autoClose: false, message: 'Name is invalid', type: 'error'},
​​    ]}
​​/>;
```

What do you think @bryceosterhaus @matuzalemsteles?

**Comment by matuzalemsteles** [comment]
Is this component required? We have to be careful not to go out creating too many components and puff up Clay, creating is much harder to depreciate, if we have a clear need for that component we can go back to that again.

**Comment by diegonvs** [comment]
I gonna wait to implement this one since we need to think more about a more useful API. I gonna take the missing milestone components.
