### ISSUE TITLE
Apply data attributes to the link instead of the parent element

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#2253]
Hi!

We are building the creation menu of the management toolbar using this code:

```java
creationMenu.addDropdownItem(
  dropdownItem -> {
    ...

    Map<String, Object> data = new HashMap<>();
    
    data.put("senna-off", "true");

    dropdownItem.setData(data);

    ...
});
```

We expect `data-senna-off` to be added to the `<a>` generated inside the management toolbar creation menu. However it ends up being added in the anchor's parent element.

Is this intended behaviour? If so, is there any way we can achieve what we want?

Thanks!

@aliciagarciagarcia

**Comment by matuzalemsteles** [comment]
hey @4lejandrito yeah this is expected since you need `data-senna-off` to add to items so it is likely that they need to be a `button` right? internally you can remove `href` and [DropDown will render a `ClayButton` instead of ClayLink](https://github.com/liferay/clay/blob/2.x-stable/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L500).

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

The problem is that we need them to be links instead of buttons because they hit portal URLs that then redirect to an external service.

**Comment by matuzalemsteles** [comment]
Hmm, this is a bit confusing what is the problem with sennajs in this case? since it will still redirect or are you prevent default navigation?

**Comment by 4lejandrito** [comment]
Hi @matuzalemsteles,

The problem was caused by [LPS-99416](https://issues.liferay.com/browse/LPS-99416) which was reverted by [LPS-100022](https://issues.liferay.com/browse/LPS-100022). So we are good now.

However I still think data-attributes passed to the `dropdownItem` should be applied to the interactive element (anchor or button) instead of the parent element.

Regards

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as `2.x` that are not `type:bug` since `2.x` is in maintenance and we won't be proactively be taking these ones.

Please @4lejandrito, reopen if this is important or if it affects our new `3.x` components so we can plan work for it.

Thanks!
