### ISSUE TITLE
Adds a `truncate` property for ClayTable.Cell

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2279]
The most part of the use cases of `ClayTable.Cell` component is using a `string` as a child. However, We currently can't turn this string truncated.
See the following [paragraph](https://github.com/liferay/clay/blob/master/packages/clay-table/src/Cell.tsx#L78) element that is being applied when passing a string as a child.

**Comment by matuzalemsteles** [comment]
hey @diegonvs why this issue? You can describe the problem more here.

**Comment by diegonvs** [comment]
Edited!
