### ISSUE TITLE
Forward References of ClayLink

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2280]
Some Routing libraries like `next/link` doesn't allow pass `ClayLink` due to a missing reference for it.

/cc @ygorcosta @matuzalemsteles

**Comment by bryceosterhaus** [comment]
Duplicate of https://github.com/liferay/clay/issues/2250 ? also PR just sent upstream for this, let me know if I am missing something.

**Comment by matuzalemsteles** [comment]
Fixed #2281
