### ISSUE TITLE
Management Toolbar: New extension points

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2292]
**Description**
We received a request from team-commerce: [LEXI-663](https://issues.liferay.com/browse/LEXI-663). 

We have studied it and we concluded that for the sake of flexibility, the Management Toolbar (MT) should cover more scenarios.

**Request**
We would like to have two extension areas for the MT. These two areas must support any kind of component and structure within. 

![BASE](https://user-images.githubusercontent.com/21216422/63416924-ac396f00-c400-11e9-9c8a-f571ea8daed6.png)

These areas are placed on both sides of the input search.

![BASE + SEARCH](https://user-images.githubusercontent.com/21216422/63417084-e86ccf80-c400-11e9-8542-545a32651b75.png)

For more details please read the [definition doc](https://docs.google.com/document/d/1J1IyxWm4GdCDhp7RG9Uz-MOgMc4NPTEl_f7vTtvQeNQ/edit?usp=sharing) 

**Example**
![MT + SELECTION](https://user-images.githubusercontent.com/21216422/63416387-9c6d5b00-c3ff-11e9-9d6b-e34290aa4cad.png)
_Selection + Area with buttons_ 

**Alternatives we've considered**
We've considered adding a new variation for the MT. However, the commerce scenario is one more of the cases our products could have.

![image](https://user-images.githubusercontent.com/21216422/63417592-e0615f80-c401-11e9-8df8-c02866a227d1.png)
_Commerce scenario_

**Stakeholders**
- Marco Leo (team-commerce)
- Ryan Connolly (team-commerce)
- David Aragonés (team-lexicon)

**Comment by matuzalemsteles** [comment]
hey @drakonux looking at these Commerce use cases, it looks pretty different from how we have it today and what we're doing for #2225. So we will have to build a base component (low-level for our term) that allows developers to compose with any of their components but having the base.

Something like that:
```jsx
<ClayManagementToolbar>
	<ClayManagementToolbar.ItemList>
		<ClayManagementToolbar.Item>
			// code
		</ClayManagementToolbar.Item>
		<ClayManagementToolbar.Item expand />
	</ClayManagementToolbar.ItemList>
</ClayManagementToolbar>

<ClayResultsBar>
	<ClayResultsBar.Item expand />
</ClayResultsBar>
```

What do you think @bryceosterhaus? I can add this already in PR #2225 or we can merge it as it is and make a new release of `alpha` next week.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I'd probably lean to merge now and add this API later. Just so we can get some more use cases published and allow people to play with it.
