### ISSUE TITLE
Quick actions in ClayList always visible

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#2295]
I saw in the documentation this:
```
showQuickActionsOnHoverboolean = true

Flag to indicate if action items should be shown on hover. Defaults to `true`
```

But if I change this property to `false`, quick actions disappear. Is there a way to always show these quick actions?

I'm currently using `ClayButton` components inside `ClayList.ItemField` to do this:
<img width="318" alt="current-variants" src="https://user-images.githubusercontent.com/15845466/63424434-b82c2d80-c40e-11e9-9d54-31fdd99039f1.png">

Thanks :)

**Comment by matuzalemsteles** [comment]
hey @dgarciasarai this is his expected behavior, in fact this is tied to CSS always showing quick actions when there is a hover in the list, I think to get to your use case you would have to modify CSS to always be visible to unless @pat270 has some class that does that.

**Comment by pat270** [comment]
@dgarciasarai 
Quick Actions aren't meant to be used in that way. They are similar to dropdown menus. If you want a set of actions to always display you can try creating extra fields with a button in each.  The output should look like:

```
<li class="list-group-item list-group-item-flex">
  <div class="autofit-col autofit-col-expand">Variant 1</div>
  <div class="autofit-col">
    <button>1</button>
  </div>
  <div class="autofit-col">
    <button>2</button>
  </div>
</li>
```

**Comment by dgarciasarai** [comment]
If there isn't any property to do it with quick actions, I'll keep doing it as you suggest.
Thanks :)
