### ISSUE TITLE
ClayPaginationWithBar with dependency circular

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2300]
`ClayPaginationWithBar` is importing `ClayPagination` from the `index` file and this is breaking when it is being used inside the Portal, it seems that the Bundler has problems with circular dependencies.

The `default` import is something like `ClayPagination.default.default.ClayPagination` and in the transpiled code only `ClayPagination.default` this breaks React because it is not a valid component.

**Comment by wincent** [comment]
> We have circular dependencies support, so we should investigate this, see if we missed something here

I was able to add a circular dependency in https://github.com/liferay/liferay-portal/commit/31f9beca59c7ac9b1c42d3e34a842167cb8313d7 at least (at the level of package dependencies).
