### ISSUE TITLE
Adding a 'Clear All' option for form multiselect

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#2335]
Hi! Feature request here. Was wondering if it would be helpful to add an option to 'clear all' inside form's multiselect, like how react-select has one (https://react-select.com/home).

Thanks!

**Comment by drakonux** [comment]
Hi everyone! thanks @oliv-yu 

Well, @matuzalemsteles the request makes sense and it should be good for the system to add it. 

Lexicon has to document the proposal for Clay team. So please @oliv-yu could you create a request ticket in [LEXI](https://issues.liferay.com/projects/LEXI/summary) project? Indicating your team, a use case and your proposal if you don't mind (a screenshot, details, etc.)

Thanks!!

**Comment by drakonux** [comment]
Hi everyone,

The definition document is ready (see [LEXI-670](https://issues.liferay.com/browse/LEXI-670)). Please @oliv-yu validate it.

**Comment by oliv-yu** [comment]
@drakonux Looks very good! Thank you for drafting it out.

**Comment by pat270** [comment]
@matuzalemsteles I need to change the markup for Multi-select to accommodate the design for clear all and loading indicator on multiple lines. This is a breaking change.

**Comment by matuzalemsteles** [comment]
Oh ok. @pat270 so we should change this to 3.x just.

**Comment by marcoscv-work** [comment]
Hey guys! do we know for what version of Liferay portal it's needed this change?
If we want this for 7.2 we would need to make it in some way for 2.x too.

@oliv-yu could you help with this?

**Comment by matuzalemsteles** [comment]
Hmm, hey @marcoscv-work I think we would have to do it for 2.x anyway, because the Portal master is using 2.x. My concern is that this will be a breaking change, we will probably also have to update MultiSelect with Metal.js, maybe this is not a problem.
