### ISSUE TITLE
Create a centralized document to define the z-index in Clay

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2339]
We need a reference document where we can consult and define all the z-index values among the Clay's components

This is a part of the first investigation in the portal https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L1932-L1948

**Comment by wincent** [comment]
Some places we define `z-index`s that I know of, in addition to the one that @eduardoallegrini already shared:

```
	// 0-200: Theme Developer
	// 200-400: Portlet Developer
	// 400+: Liferay

	Liferay.zIndex = {
		ALERT: 430,
		DOCK: 10,
		DOCK_PARENT: 20,
		DRAG_ITEM: 460,
		DROP_AREA: 440,
		DROP_POSITION: 450,
		MENU: 5000,
		OVERLAY: 1000,
		POPOVER: 1600,
		TOOLTIP: 10000,
		WINDOW: 1200
	};
```

https://github.com/liferay/clay/blob/40fdedf2737018780e0aac0e48d885e1d5a536c8/packages/clay-css/src/scss/variables/_globals.scss#L107

```
// Z-Index Variables

$zindex-alert-notifications: 5000 !default;
$zindex-input-group-hover: 3 !default;
$zindex-input-group-focus: $zindex-input-group-hover + 1 !default; // 4
$zindex-navbar-collapse-absolute: 500 !default;
$zindex-navbar-overlay: 450 !default;
$zindex-navbar-toggler-focus: 525 !default;
$zindex-sidenav: $zindex-fixed + 5 !default;
```

https://github.com/twbs/bootstrap/blob/v4.3.1/scss/_variables.scss#L673

```
// Z-index master list
//
// Warning: Avoid customizing these values. They're used for a bird's eye view
// of components dependent on the z-axis and are designed to all work together.

$zindex-dropdown:                   1000 !default;
$zindex-sticky:                     1020 !default;
$zindex-fixed:                      1030 !default;
$zindex-modal-backdrop:             1040 !default;
$zindex-modal:                      1050 !default;
$zindex-popover:                    1060 !default;
$zindex-tooltip:                    1070 !default;
```

https://github.com/liferay/liferay-portal/blob/b78699548ea14ed24ee84da25de5888ad53d0ee1/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/css/_variables.scss#L35-L53

```
$draggableItemZIndex: 977;
$dragSourceZIndex: 977;
$floatingToolbarZIndex: 976;
$floatingToolbarPanelZIndex: 989;
$fragmentEditableFieldTooltipZIndex: 975;
$fragmentEntryLinkContentHoverZIndex: auto;
$fragmentEntryLinkContentZIndex: 0;
$fragmentEntryLinkZIndex: 5;
$managementBarZIndex: 971;
$portletTopperZIndex: 2000;
$shimZIndex: 9999;
$sidebarCardPlusButtonZIndex: 6;
$sidebarCardZIndex: 5;
$sidebarSectionZIndex: 4;
$sidebarZIndex: 972;
$topperActiveZIndex: 3;
$topperHoverZIndex: 2;
$topperZIndex: -1;
$translationStatusListZIndex: 977;
```

I  wouldn't be surprised to find others hiding in liferay-portal that I haven't seen yet.

**Comment by jbalsas** [comment]
So, documentation doesn't work for this. You can have as much docs as you want, they all tend to get lost/unread/forgotten...

In particular, we have a lot of code where:

```
.something {
    zIndex: 245;
}
```

No documentation can explain the rationale of all those `zIndex` and there's no way for us to track and enforce proper usage.

By having a map we can both better see motive, like:

```
.something {
    zIndex: $ZINDEX_MODAL + 45;
}
```

We can even enforce through a lint rule that `zIndex` values should be bound to a `$ZINDEX` variable for reference.

Can you explore if something like this would be possible on top of bootstraps variables, @pat270?

**Comment by jbalsas** [comment]
Hey @pat270, indeed they are, but we do have a specific ordering here, don't we? Those values in `portal` are driven by our decisions here and their need to stack on top of our defaults. By being able to consume ours, it should make it easier for our apps developers to find the right depths.

**Comment by jbalsas** [comment]
Ah, got it!

Just our CSS zIndexes in a way that could be consumed. We have a similar stack over here. I'd expect we'd change those in portal to use our references and some offset. That way, they have something to latch onto, rather than blindly increasing zindexes :)
