### ISSUE TITLE
Impossible to hide order direction icons in the management toolbar

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2343]
From https://issues.liferay.com/browse/LPS-100311

`2.x`

There is no way to hide order direction icons in the management toolbar.

For example, in the Web Content administration there is an option to order by Relevance(content score, calculated by the Search Engine), but in this case order direction is always fixed, there should be no way to change order direction.

We need a Management Toolbar taglib attribute to be able to control visibility of the order direction icons.

/cc @pavel-savinov, @carloslancha

**Comment by matuzalemsteles** [comment]
If you don't pass `sortingOrder` to `ManagementToolbar` it will not render the icon. Wouldn't that solve the problem or do you want to change the icon and other props?

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, if I understood correctly... there is `sortingOrder` and `sortingURL`, because that also affects other places. There's just no way make the sorting go away from https://github.com/liferay/clay/blob/2.x/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L733.

@pavel-savinov, can you confirm?

**Comment by matuzalemsteles** [comment]
Yeah, just above this line is a check, so I'm assuming you don't want to render the sorting order element. https://github.com/liferay/clay/blob/2.x/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L722

**Comment by jbalsas** [comment]
Huh, maybe you're right... maybe we already implemented it and simply failed to surface it on portal... 🤔 

We'll take a closer look tomorrow and get back here with an answer!

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, I took a look today with @pavel-savinov.

Passing an empty string to `sortingOrder` does the trick, but since the only valid values are `"asc"` and `"desc"`, JS complains about invalid values.

We need to either make a null check in the template or accept empty string.

Could you add this so we can get it out with the next release?

Thanks!

**Comment by matuzalemsteles** [comment]
Hmm, @jbalsas this is weird because default `sortingOrder` is optional and doesn't have a default value, so you could pass, `null`, `undefined` or nothing that would work well ([JS](https://github.com/liferay/clay/blob/2.x/packages/clay-management-toolbar/src/ClayManagementToolbar.js#L624)[Soy](https://github.com/liferay/clay/blob/2.x/packages/clay-management-toolbar/src/ClayManagementToolbar.soy#L118)). The same is true within our implementation of the Portal.

**Comment by jbalsas** [comment]
@pavel-savinov confirmed `null` works for this case. 

Thanks @matuzalemsteles!
