### ISSUE TITLE
Modal isn't closing when clicking outside when not added size parameter

### ISSUE THREAD

**Issue by interaminense** [liferay/clay#2349]
**Step to reproduce:**

Using the storybook, select the size `none` to make the error happen.
https://storybook-clayui.netlify.com/?path=/story/claymodal--default

**Comment by matuzalemsteles** [comment]
Thanks @interaminense, this will be fixed with the entry of #2344.

**Comment by interaminense** [comment]
Thanks, @matuzalemsteles! You are fast!!

**Comment by matuzalemsteles** [comment]
Fixed #2344
