### ISSUE TITLE
Border colors for for "do" and "dont" appear very similar to deuteranopic people

### ISSUE THREAD

**Issue by holatuwol** [liferay/clay#2362]
### Steps to reproduce

1. Install a browser extension or desktop tool that allows you to view a page or site as if you had color blindness
2. Configure the extension or desktop tool to let you view pages with a deuteranopia setting
3. Visit https://liferay.design/lexicon/core-components/actions-definition/
4. Observe that the "do" and "dont" lines look very similar in color (very little contrast)

**Comment by pat270** [comment]
Hey @holatuwol,

This issue should be filed at https://github.com/liferay/lexicon-site.

/cc @drakonux

**Comment by ethanbustad** [comment]
https://github.com/liferay/lexicon-site/issues/206
