### ISSUE TITLE
error Unknown workspace "clay-css".

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#2364]
Following the README to start storybook by running 
`yarn workspace clay-css run build && yarn storybook`
I get the error:
`error Unknown workspace "clay-css".`

**Comment by matuzalemsteles** [comment]
hey @carloslancha, you can try: `yarn workspace @clayui/css run build && yarn storybook`?

**Comment by julien** [comment]
@matuzalemsteles yes that seems to work, thanks!

**Comment by carloslancha** [comment]
We just need to update the README.md then. Thx!
