### ISSUE TITLE
Review modal sizes

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2367]
I'm not sure if we had a strong reason to not use the sizes defined by Lexicon.

https://liferay.design/lexicon/core-components/modals/

![image](https://user-images.githubusercontent.com/7963804/64122275-6b970980-cda1-11e9-8ac7-dfe87352017e.png)

**Comment by pat270** [comment]
@marcoscv-work there was no strong reason. The specs weren't clearly defined a while ago and never got notified when they did.
