### ISSUE TITLE
MultiSelect onInputBlur callback needed

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#2371]
In portal exists the requirement for the multiselect of adding the tag item when the input is blured, so we need to add `onInputBlur` to the API. Maybe adding `onInputFocus` too would be a good idea.

**Comment by matuzalemsteles** [comment]
hey @carloslancha you can pass an `onFocus` or `onBlur` directly through the API, we pass all `otherProps` to the input, the component extends from `React.HTMLAttributes<HTMLInputElement>`.

**Comment by wincent** [comment]
@matuzalemsteles: He can pass them, and they'll get spread in [here](https://github.com/liferay/clay/blob/4d073827a40ef5e5c24372670d8d36e5cd0ba19a/packages/clay-form/src/InputWithMultiSelect.tsx#L209), but then immediately overwritten [here](https://github.com/liferay/clay/blob/4d073827a40ef5e5c24372670d8d36e5cd0ba19a/packages/clay-form/src/InputWithMultiSelect.tsx#L211) and [here](https://github.com/liferay/clay/blob/4d073827a40ef5e5c24372670d8d36e5cd0ba19a/packages/clay-form/src/InputWithMultiSelect.tsx#L217).

**Comment by matuzalemsteles** [comment]
Oh yeah, I had forgotten about that. I think we can check for these props and call them from within functions.

Algo assim:
```js
onBlur={event => {
	onInputChange(
		event.target.value.replace(',', '')
	);
	if (onBlur) {
		onBlur(event);
	}
}}
```

**Comment by bryceosterhaus** [comment]
PR: https://github.com/liferay/clay/pull/2375
