### ISSUE TITLE
Provide Algolia Docsearch for 3.x website

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2372]
Currently, when searching for an item on next.clayui.com, Algolia searches it on 2.x's(clayui.com) indexed website.

We must send an email to Algolia for creating new credentials for 3.x website.

**Comment by matuzalemsteles** [comment]
@diegonvs as soon as we move `next.clayui.com` to `clayui.com` we will use the current one from `clayui.com`. We do not need to request a new credential for `next.clayui.com`, this is temporary.
