### ISSUE TITLE
ClayLabels focusing has unexpected results in InputWithMultiselect

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#2376]
QA on Search team pointed out a few bugs regarding the focus of the labels on InputWithMultiselect. Is the current behavior expected? Curious about the standards for accessibility, and I thought I would bring them up here, in case they were not discussed before. 

https://issues.liferay.com/browse/LPS-100506
- On removing an item in the input, the focus shifts directly to the close button of the item next to it.

https://issues.liferay.com/browse/LPS-100507
- The focus should be on the close button instead of on both the button and the entire label.

**Comment by matuzalemsteles** [comment]
Hey @oliv-yu thanks for bringing up these questions!

> On removing an item in the input, the focus shifts directly to the close button of the item next to it.

This is a bug we have already tracked and we are correcting, the expected case is to remove the Label and focus back to the input.

> The focus should be on the close button instead of on both the button and the entire label.

The expected behavior would be to focus only on the label.

Hey @drakonux could you confirm that what I am saying here is correct or if we need to review some things.

**Comment by marcoscv-work** [comment]
Hey guys, I suppose we changed the native behavior for some reason but I really think we should go back and not try to make a text element get the focus and let buttons be buttons and receive the focus from the beginning, same behavior than by using the mouse.

The only thing I think we should add is a correct name for the button which removes the label: "`remove " + label-name + " label`"

I've created an example here:
https://codepen.io/marcoscv/pen/BaBJBaa

You can use it with a screen reader

**Comment by drakonux** [comment]
I agree with @marcoscv-work . I was talking about this with him this morning and what he says it makes total sense. 

Thus now tab order must jump from remove button to remove button instead from label to label as the old documentation says.

**Comment by matuzalemsteles** [comment]
Thanks guys for the explanations, you can confirm how will continue the removal of labels in the behavior of when the input is empty and when pressing the backspace it focuses the label and when pressing again removes the label.

Just to keep it more centralized, we can add all these documented changes, we can lose it at any time, and our source for validating our components is tied to documents in Drive.

**Comment by drakonux** [comment]
When the input is empty and the backspace key is pressed, remove the last label and the previous remove button gets the focus. Then:

- If the user presses **enter key** or **backspace** the label is removed. 
- If the user types. The input starts to work as it usually does.  

Additional behavior. When the label is removed, the screen reader should say: 

`"label-name removed"`

About documentation. As I talked with @jbalsas Lexicon is here to help you. You can talk with the team and decide how you would like to track these changes (using a new doc, updating the old doc, etc) just open a request and explaining me the way we can help you.

**Comment by marcoscv-work** [comment]
After a conversation with @Chema by now, we will not provide assertive messages, so we need a previous confirmation before a remove, so I propose:

The same behavior we can see here:
https://storybook.clayui.com/?path=/story/clayform--inputwithmultiselect

With the difference that the button to remove will have the focus, not the label. In this way, we can read "Remove Item-name" before confirm by the backspace key or enter.

**Comment by matuzalemsteles** [comment]
Focus changes for MultiSelect were submitted with PR #2398. I'm closing it! This fix will be released together with `v3.0.0-alpha.1`.

**Comment by oliv-yu** [comment]
Thanks everyone, so glad to hear this is fixed! 😃
