### ISSUE TITLE
ModalBody height fixed to 160px if Iframe

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#2395]
![image](https://user-images.githubusercontent.com/44569796/64350304-bfe7f680-cff8-11e9-943b-f56280e9b691.png)

In case we use modals to display iframes, the body height is fixed to 160px which quite a small height. This doesn't work well with most of our use cases

Note: the issue disappear on full-screen modals.

**Comment by pat270** [comment]
@FabioDiegoMastrorilli what kind of behavior would you like to see? Lexicon Team has no definition for this. I could add a modifier class on `modal` to make a modal expand to the full height of the browsers window.

Something like:
<img width="563" alt="modal-iframe" src="https://user-images.githubusercontent.com/788266/64373978-b306db00-cfd7-11e9-9e4a-19531459c806.png">

**Comment by FabioDiegoMastrorilli** [comment]
@pat270 a full screen modifier and a large one would be helpful :) 

I don't know if it is possible, but even changing the default height might be a solution if doesn't break anything.

From what I've seen so far 450px fits well with most of our designs.

**Comment by drakonux** [comment]
From our point of view, the body height of a modal window should not be fixed. Product teams should be able to set a height value with a default height preset or choose to let it grow as the content within defines. 

We can consider to redefining the different sizes or behaviors if you need (open a request in LEXI).

ps. could we have a default height value??

**Comment by FabioDiegoMastrorilli** [comment]
Hi @drakonux , in some scenarios we don't know exactly the height of the content so we should rely on fixed height. A set of presets would be very useful for us

**Comment by pat270** [comment]
@FabioDiegoMastrorilli @drakonux I added fixed height modals with arbitrary heights. We can change them once we figure out what we need. The classes `modal-height-full` (window height), `modal-height-sm` (250px), `modal-height-md` (450px), `modal-height-lg` (650px), `modal-height-xl` (800px) can be added to `modal` to apply the respective styles.

**Comment by FabioDiegoMastrorilli** [comment]
@pat270 perfect! :) Thank you
