### ISSUE TITLE
ClayCSS add a deep merge function

### ISSUE THREAD

**Issue by pat270** [liferay/clay#2403]
Sass only provides a shallow merge function, `map-merge`, that doesn't merge nested maps. This makes extending nested maps impossible. All properties must be redeclared when extending a nested map.
```
$var: (
  link: (
    hover-color: black,
  ),
);

$var: () !default;
$var: map-merge((
  color: black,
  link: (
    color: blue,
  ),
), $var);
```
Output: `(color: black, link: (hover-color: black))`
Output should be: `(color: black, link: (color: blue, hover-color: black))`

**Comment by duracell80** [comment]
For anyone running into compile errors with map-deep-merge. Be careful with the _clay_variables.scss file in the src of your theme. I had a $btn-link : #00558C; which was causing this error ... Error: argument `$map2` of `map-deep-merge($map1, $map2)` must be a map.

It could happen with any variable, some of these are not namespaced or isolated enough to prevent human error.
