### ISSUE TITLE
[next.clayui.com] Quick actions misaligned in ClayList and icon missing

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2405]
Icons misaligned in:
https://next.clayui.com/docs/components/list.html?#quickactionmenu
![image](https://user-images.githubusercontent.com/7963804/64536254-13b84f80-d319-11e9-87a8-635a090d571c.png)

![image](https://user-images.githubusercontent.com/7963804/64536102-c89e3c80-d318-11e9-9e41-0f436ab26844.png)

![image](https://user-images.githubusercontent.com/7963804/64536027-a60c2380-d318-11e9-9ae7-eaefdfcb2665.png)

Some icon missing in complex list:
https://storybook.clayui.com/?path=/story/claylist--complex
![image](https://user-images.githubusercontent.com/7963804/64536198-f5525400-d318-11e9-8a7e-878da3ac5f90.png)

Design and markup look correctly in clayui.com:
https://clayui.com/docs/css-framework/satellites/list_groups.html

**Comment by diegonvs** [comment]
* We need more investigation for solving this quick actions alignment issue 😞 . Apparently, We're using the same markup.

* The icon is not missing, only [2 quick actions](https://github.com/liferay/clay/blob/master/packages/clay-list/stories/index.tsx#L187)(with the symbols of `trash` and `cog`) were passed.

**Comment by marcoscv-work** [comment]
I've copied the <ul> markup in next.clay and it looks good, maybe we missed some markup or class name

![image](https://user-images.githubusercontent.com/7963804/64598299-c939e000-d3b7-11e9-9a07-66bbfb35e3fc.png)
