### ISSUE TITLE
Clay CSS 3.x remove deprecated variables

### ISSUE THREAD

**Issue by pat270** [liferay/clay#2416]
There are a lot of variables that were deprecated in 2.x. We need to remove them in 3.x.

**Comment by jbalsas** [comment]
As much as I wanted to do this, I think we need to hold this off until `4.x`. If we do (and remove some existing breaking changes in `3.x`, we could just use `3.x` indistinctly for clay components v2 and v3.

Otherwise, we might need to pick, and v3 will probably end up in the losing side.

**Comment by pat270** [comment]
@jbalsas ok not a problem, going to close this.

**Comment by jbalsas** [comment]
Fastest turnaround ever 😂
