### ISSUE TITLE
Clay: Remove duplicated icons (export-import and embed)

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2419]
## Proposal
Lexicon would like to not have similar icons in the Icon library. We propose to remove:

1. export-import icon

![import-export](https://user-images.githubusercontent.com/21216422/64684106-c8bb4b00-d484-11e9-939c-123046cb056f.png)

2. embed icon

![embed](https://user-images.githubusercontent.com/21216422/64684103-c8bb4b00-d484-11e9-8c7b-902e1ed60279.png)

And we suggest to use instead:

1. order-arrow

![order-arrows](https://user-images.githubusercontent.com/21216422/64684105-c8bb4b00-d484-11e9-9c2a-46bb58a909d0.png)

2. code

![code](https://user-images.githubusercontent.com/21216422/64684104-c8bb4b00-d484-11e9-9572-29efe8efae86.png)

## Additional Information
In fact, we have already removed them from our ui kit in Figma. So we can guarantee product designers won't use them in the future.

**Comment by jbalsas** [comment]
Just for reference, we should remove the icon from our documentation, but for now we shouldn't remove the symbol to avoid visual regressions

**Comment by jbalsas** [comment]
Just from docs for now, please 🙏
