### ISSUE TITLE
ClayDataProvider: caching issues on IE11

### ISSUE THREAD

**Issue by brunofarache** [liferay/clay#2420]
In IE11, caching is very persistent.

If the `link` prop is the same, IE11 will always get from cache. It doesn't matter if the user reloads the page, IE11 doesn't make a XHR again.

Data provider has a cache configuration, which is disabled by default. IE11 doesn't respect this configuration as it will always cache.

In order to avoid this I need to add to `fetchOptions` the following headers:

```
headers: {
    'Cache-control': 'no-store',
    'Pragma': 'no-cache',
    'Expires': 0
}
```

`Cache-control` is not enough.

Not to mention the credentials header required by IE11 as well: `credentials: 'same-origin'`.

My suggestion is to add some pre-defined configuration that will make data provider work on IE11:

```
fetchOption: {
    ...IE11Options
}
```

As people starts using data provider more in DXP, this will save time from QAs and developers.

**Comment by jbalsas** [comment]
I think we should be able to provide this on the portal side at https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/fetch.es.js

And then use https://github.com/liferay/clay/issues/2261 to make sure `ClayDataProvider` uses it

**Comment by kresimir-coko** [comment]
Is this still a problem @jbalsas @brunofarache, or has it been dealt with on the portal side, coupled with #2261?

**Comment by matuzalemsteles** [comment]
Well, currently we already provide an API for custom `fetch` and we have plans to move the Data Provider to DXP so we can provide unique headers if needed, I'll close that since we have a custom `fetch` to support this.
