### ISSUE TITLE
Verify clay-color-picker for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2440]
- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by jbalsas** [comment]
Currently, `color-picker` has a dependency on `@clayui/form` that is undeclared.

In [`Custom.tsx`](https://github.com/liferay/clay/blob/master/packages/clay-color-picker/src/Custom.tsx#L7) but in [`package.json`](https://github.com/liferay/clay/blob/master/packages/clay-color-picker/package.json#L28-L34)

**Comment by jbalsas** [comment]
Found this while playing around with combined sliders and color-picker at https://codesandbox.io/s/clay-component-demo-y6trl

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility
 basics** 
  - This component can have more complex controls by keyboard but most basic would be: Focus on the color button which has text on `sr-only` with the current color, then we press key enter and colors dropdown-menu appears, next tabulñation should go to the first dropdown-menu color, and when we chose one by pressing enter the  dropdown is closed and the focus goes back to the color button, where the text has changed with the new color selected.
  - Now the keyboard behavior is this: ![color-picker-accessibility](https://user-images.githubusercontent.com/7963804/65158889-84571e80-da33-11e9-97f8-bc54978bf1b4.gif)

**Comment by diegonvs** [comment]
> Currently, color-picker has a dependency on @clayui/form that is undeclared.

Fixed by: https://github.com/liferay/clay/pull/2513

**Comment by jbalsas** [comment]
Additionally, the picker trigger is missing a `type="button"` attribute. This causes that, if the component is inserted inside a form, trying to pick a colour will trigger the form submission.

See https://codesandbox.io/s/blazing-glitter-qdxg4
