### ISSUE TITLE
Verify clay-card for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2442]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Is there anything about the public API that you would change?

No.

> Is the naming of the available props clear?

Yes.

**Comment by eduardoallegrini** [comment]
I tried these:
- ClayCardWithUser
- ClayCardWithHorizontal
- ClayCardWithInfo
- ClayCardWithNavigation

And they are good
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics**

About the APIs
- Shouldn't we add the [`indeterminate` variantion](https://next.clayui.com/docs/components/forms/checkbox.html#api-indeterminate)?
- Some API should have a "depends on", for example:
  - In `ClayCardWithInfo`, `symbol` doesn’t work if image is defined
  - In `ClayCardWithNavigation`, `horizontalSymbol` doesn’t work if `spritemap` is missing

**Comment by diegonvs** [comment]
> Shouldn't we add the indeterminate variation?

We just followed Lexicon examples. At least for me, I didn't saw any case with indeterminate checkbox variation

BTW, @bryceosterhaus @matuzalemsteles, would be a good idea to add a property like `checkboxProps`?

**Comment by diegonvs** [comment]
> In ClayCardWithInfo, symbol doesn’t work if image is defined
> In ClayCardWithNavigation, horizontalSymbol doesn’t work if spritemap is missing

Would be a good idea add warnings for it?
