### ISSUE TITLE
Verify clay-drop-down for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2446]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by eduardoallegrini** [comment]
- [x] **HTML**
- [x] **CSS**
- [ ] **Accessibility basics** 
  - in the [default example](https://storybook.clayui.com/?path=/story/components-claydropdown--default) the disabled link is  still selectable with keyboard

![image](https://user-images.githubusercontent.com/46778114/65313094-1a09bf80-db94-11e9-8d6d-b849673b070a.png)

  - in the [w/ ClayDropDownWithItems example](https://storybook.clayui.com/?path=/story/components-claydropdown--w-claydropdownwithitems) adding `disabled`to the button create a block for the keyboard navigation

![image](https://user-images.githubusercontent.com/46778114/65313170-36a5f780-db94-11e9-9e1e-ea7e02e7073d.png)

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I think this issue with the disabled item might come from the new implementation of FocusScope. The disabled attributes were just working yesterday I think

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus I will send a fix to `DropDown`, FocusManager follows the default behavior, we have to add the `disabled` attribute to the element, for now we are just adding `disabled` to `className`.

**Comment by matuzalemsteles** [comment]
I will close this since we have released and fix a fix for Disabled focus problem, we will send a patch release for this component soon with this fix.
