### ISSUE TITLE
Verify clay-form for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2447]
_Verify for each component within form_

- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by carloslancha** [comment]
# About MultiSelectInput

## Naming
There's some param names that seem inconsistent for me. Now the component can receive `onInputChange` that affects to the input element, but also `onBlur` and `onFocus`, that also affects to the input element. Other than that it can receive any other param not defined and just rendered vía `{...otherProps}`, for example `onClick`.

So we could end up with something like:
```
<MultiSelectInput
       onClick="...."
       onInputChange="..."
       onBlur="..."
       onFocus="..."
/>
```
and all of them are referring to the same input, but looks confusing to me. I'd suggest to rename `onInputChange` to `onChange`.

## High Level MultiSelect
One of the last things we've done with this component is to split it in low level components, but right now if we want to replicate what we had before (a MultiSelect with a label, the Clear All button, help text, select button...) we need to write something like:

```
<ClayForm.Group className={!isValid ? 'has-error' : ''}>
    <label>{'Composed MultiSelect'}</label>

    <ClayInput.Group>
    <ClayInput.GroupItem>
        <ClayMultiSelectInput
            inputName="myInput"
            inputValue={value}
            items={items}
            onInputChange={setValue}
            onItemsChange={setItems}
            spritemap={spritemap}
        />

        <ClayForm.FeedbackGroup>
        <ClayForm.Text>{'Simple help comment..'}</ClayForm.Text>
        </ClayForm.FeedbackGroup>

        {!isValid && (
        <ClayForm.FeedbackGroup>
            <ClayForm.FeedbackItem>
            <ClayForm.FeedbackIndicator spritemap={spritemap} symbol="info-circle" />

            {'You made an error'}
            </ClayForm.FeedbackItem>
        </ClayForm.FeedbackGroup>
        )}
    </ClayInput.GroupItem>

    <ClayInput.GroupItem shrink>
        <ClayButton displayType="secondary" onClick={() => {}}>
        {'Select'}
        </ClayButton>
    </ClayInput.GroupItem>
    </ClayInput.Group>
</ClayForm.Group>
```

This is probably a lot of boilerplate for the most common use in portal of the MultiSelect, so maybe is a good idea to create a high level component for this.

## Items objects

Right now `items` prop accepts a list of strings but we have to accept a list of objects `{ label: 'label', value: 'value'}` due most of the times the value needed to send via form differs from the label to show.

## Clear All button

Clicking Clear All button removes all the selected items and clears the input value. The rest of the component behaves like a controlled component but not this part. I think we should admit an `onClearAllButtonClick` so the parent component could take care of it.

**Comment by bryceosterhaus** [comment]
These are all great! The only one I would hesitate on is the high-level component. I think its likely the best route for us to go, but I want to be really cautious about over-offering high-levels at initial release.

**Comment by carloslancha** [comment]
Nice, I'm opening a new issue only for the multiselect and I'll start working on it to introduces this changes tomorrow 😄

**Comment by matuzalemsteles** [comment]
I agree with Bryce, we can go for now with these low level components and then we can think more about it.

> Clicking Clear All button removes all the selected items and clears the input value. The rest of the component behaves like a controlled component but not this part. I think we should admit an onClearAllButtonClick so the parent component could take care of it.

Maybe it's the best but if you think about it, it ends up being controlled since it calls `onItemsChange` and` onInputChange`. Do you see another case for him?

**Comment by carloslancha** [comment]
@matuzalemsteles yep, it ends up being controlled but feels weird to me forcing values to that callbacks. @julien @bryceosterhaus what do you think?

**Comment by julien** [comment]
I also think that it's a bit strange that we can "control" what happens in the `onItemsChange` and `onInputChange` callbacks but not when this `ClayIcon` is clicked. I know it ends up calling these two callbacks with predefined values and it seems logical in most cases, but what if we wanted something else to happen?

**Comment by bryceosterhaus** [comment]
I think there might be a few options for this.

1) Add `onClearAllButtonClick` prop, and internally don't do anything for this click other than this callback. This would mean that the user is responsible for clearing the items and providing an empty array as a new prop.
- Drawback is that users are now responsible for the clearing logic.

2) Tell users to "listen" in the `onItemsChange` callback. If they receive and empty array of items, they can assume that it was cleared assuming there was previously more than 1 item.
- Drawback is that users have no way to know when a "clear all" action is taken. I am imagining a user might want some sort of confirmation modal before clearing everything.

3) Similarly to the first, we could have internal logic for clearing all items, and then additionally we provide `onClearAllButtonClick` as an opt-in behavior where they can run any custom logic. This callback would then internally clear the items depending on whether `onClearAllButtonClick` returns true/false.
- Drawback being that depending on  `onClearAllButtonClick`s return, the internal functionality behaves differently.

TBH, I'm not totally sure what is better. Each has its drawbacks. I am partially drawn to leaving `onClearAllButtonClick` out in favor of simplicity, but I also like the third option since it provides more functionality.

**Comment by bryceosterhaus** [comment]
part of me just doesn't like this "clear all" button as a UI pattern lol

**Comment by bryceosterhaus** [comment]
kk I just talked to @diegonvs about it. I think it makes sense to add the prop, but if the user doesn't provide the prop, then we handle the logic internally. Thus the code would look something like

```jsx
// onClick internal logic
onClick={() => {
	if (onClearAllButtonClick) {
		onClearAllButtonClick();
	} else {
		onItemsChange([]);

		onInputChange('');
	}

	if (inputRef.current) {
		inputRef.current.focus();
	}
}}

// custom clear all
const [items, setItems] = useState([])
return (
	<MultiSelect
                items={items}
		onClearAllButtonClick={() => {
			if (confirm('r u sure?')) {
				setItems([]);
			}
		}}
	/>;
);
```

This work for you all?

**Comment by julien** [comment]
@bryceosterhaus yes that looks good to me. Thanks.

**Comment by carloslancha** [comment]
Works for me @bryceosterhaus thx!

Maybe we can make this simpler by defining the default behavior as the prop default?

```
const ClayMultiSelect: React.FunctionComponent<IProps> = ({
	clearAllTitle = 'Clear All',
	closeButtonAriaLabel = 'Remove {0}',
	disabled,
	disabledClearAll,
	forwardRef,
	inputName,
	inputValue = '',
	isValid = true,
	items = [],
	onBlur = noop,
	onClearAllButtonClick = () => { onItemsChange([]); onInputChange(''); }
	onFocus = noop,
	onInputChange = noop,
	onItemsChange = noop,
	onKeyDown = noop,
	onPaste = noop,
	sourceItems,
	spritemap,
	...otherProps
}) => {

....

// clear button
onClick={() => {
	onClearAllButtonClick();

	if (inputRef.current) {
		inputRef.current.focus();
	}
}}
```

**Comment by bryceosterhaus** [comment]
If that works, I'm all for it. Not sure how default values like that work when they are destructured from the same object. But if it works, that looks good to me.

**Comment by matuzalemsteles** [comment]
I sent initial documentation for MultiSelect at #2472, @carloslancha can you handle also adding just a note about it there?

The only concern I have is that people can get this API to get away from this behavior I hope not, so let's see how it will work.

**Comment by eduardoallegrini** [comment]
I found these "inner" components _I hope I didn't miss anyone_
- Checkbox
- Radio
- Input
- InputWithAutocomplete
- InputMultiSelect

- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics**
