### ISSUE TITLE
Verify clay-link for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2450]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by bryceosterhaus** [comment]
We also need to decide on whether ClayLinkContext should be unstable or not. I talked to the Faro team not too long ago and they are waiting on this API or need another option for this.

I think its a simple enough feature that gives developers a lot of power, so I think it makes sense for it to be considered stable. Unless we can think of another means to accommodate for frontend routing frameworks.

**Comment by bryceosterhaus** [comment]
[Here is a demo of how it might be used.](https://codesandbox.io/s/sad-carson-thluj) Also take into account that this is needed for links that are nested within larger components of ours, such as ClayManagementToolbar

**Comment by matuzalemsteles** [comment]
> We also need to decide on whether ClayLinkContext should be unstable or not. I talked to the Faro team not too long ago and they are waiting on this API or need another option for this.

I thought they were already using it, hoping they could give us feedback by testing on their codebase and architecture and checking if that would have other cases that we just didn't cover here.

> I think its a simple enough feature that gives developers a lot of power, so I think it makes sense for it to be considered stable. Unless we can think of another means to accommodate for frontend routing frameworks.

Yes I agree that it is simple, I was just marking it as `unstable` because it is one thing we can not be sure if it will be the best approach. So the only way to verify this was to test this approach in codebase.

**Comment by bryceosterhaus** [comment]
Faro wants to use it, but they aren't comfortable with adopting and making any changes if its labeled "unstable." 🤷‍♂ 

Since the feature is an opt-in one and relatively small, I think we'd be safe labeling as stable as this point. If its not the best approach, we can always add another approach we find that is better, but I do think this is a necessary API for anyone who wants to use frontend routing.

**Comment by matuzalemsteles** [comment]
> Faro wants to use it, but they aren't comfortable with adopting and making any changes if its labeled "unstable." 🤷‍♂

😞

> Since the feature is an opt-in one and relatively small, I think we'd be safe labeling as stable as this point. If its not the best approach, we can always add another approach we find that is better, but I do think this is a necessary API for anyone who wants to use frontend routing.

Ok, I think we can mark it as stable for the final version.

**Comment by bryceosterhaus** [comment]
Update to API: https://github.com/liferay/clay/pull/2470
Demo: https://codesandbox.io/s/sad-carson-thluj

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics**
