### ISSUE TITLE
Verify clay-loading-indicator for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2451]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by bryceosterhaus** [comment]
Demo: https://storybook.clayui.com/?path=/story/components-clayloadingindicator--default

PR for ref: https://github.com/liferay/clay/pull/2469

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - `aria-hidden="true"` can be fine for some scenarios, even if we do not provide loading text but if we are reloading some part of the web what is not ready when the focus pass through I think we should provide information about why in this markup point we don't have yet the expected information, example: `<span class="loading-animation"><span class="sr-only">Loading 'images/page/whatever'</span></span>`

/cc @drakonux

**Comment by matuzalemsteles** [comment]
hey @marcoscv-work we could reach the same result using `<ClayLoadingIndicator aria-label="Loading data" aria-hidden="false" />`, what do you think?

**Comment by bryceosterhaus** [comment]
I just verified with chromevox that `<ClayLoadingIndicator aria-label="Loading data" aria-hidden="false" />` does work. I am going to go ahead and release this package.
