### ISSUE TITLE
Verify clay-management-toolbar for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2452]
- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by bryceosterhaus** [comment]
We might want to consider breaking this into low-level instead of opting straight into high-level. 

Additionally we also should review the current API. I noticed the props extends all three of `DefaultState`, `ResultsBar`, and `ActiveState` and then spreads `otherProps` in multiple places. This is likely going to cause some issues since unwanted props can leak into different components.

**Comment by bryceosterhaus** [comment]
I think we should offer a low-level first with 3.0.0 and it would be consumed something like

```jsx
<ManagementToolbar>
	<ManagementToolbar.Dropdown />

	<ManagementToolbar.Button />

	<ManagementToolbar.Search />

	<ManagementToolbar.Button />

	<ManagementToolbar.Button />

	<ManagementToolbar.Dropdown />
</ManagementToolbar>
```

Faro, app-builder, and segments all have a similar structure of composition.

**Comment by matuzalemsteles** [comment]
Yeah concordo, apenas para abrir um pouco mais as nossas ideias, acho que podemos quebrar mais um pouco a API para flexibilizar, mas fazer dessa forma pode também aumentar um pouco do trabalho.

Algo como isso:
```jsx
```

**Comment by matuzalemsteles** [comment]
Yeah I agree. Just to open up our ideas a bit more, I think we can break the API a little bit more for flexibility, but doing so can also add some of the work.

Something like that:
```jsx
<ClayManagementToolbar>
	<ClayManagementToolbar.ItemList>
		<ClayManagementToolbar.Item>
			// DropDown or button, any
		</ClayManagementToolbar.Item>
		<ClayManagementToolbar.Item expand />
	</ClayManagementToolbar.ItemList>
</ClayManagementToolbar>

<ClayResultsBar>
	<ClayResultsBar.Item expand />
</ClayResultsBar>
```

I see that we can reuse the components we already have and thus remove some of the wrapping that we have to make on top of them.

This is related to #2292

**Comment by bryceosterhaus** [comment]
Yeah I like that API approach. This component also doesn't necessarily need to be released as soon as possible. Its not currently being used by any teams, so we don't have to make it a priority to release it quite yet.

**Comment by matuzalemsteles** [comment]
It might not be so necessary now but the App Builder team wanted to use it but because of a customization above the Creation Menu it can't be used.

**Comment by eduardoallegrini** [comment]
- [x] **HTML**
  - `.label`s should go in the same `tbar-item` and we should change some CSS properties to -manage any number of labels

![image](https://user-images.githubusercontent.com/46778114/65318287-a8367380-db9d-11e9-8125-45b3d2a2315c.png)
![image](https://user-images.githubusercontent.com/46778114/65318347-c2705180-db9d-11e9-9392-82b7b9a0066f.png)

  - The list items `<li>` of the action menu are outside the  `<ul>`

![image](https://user-images.githubusercontent.com/46778114/65318419-d916a880-db9d-11e9-9409-734abeb89ff0.png)

- [x] **CSS**
- [x] **Accessibility basics**
