### ISSUE TITLE
Verify clay-modal for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2453]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Is there anything about the public API that you would change?

I don't really want to change anything about the API but one thing that we could improve (or be asked for by our users) is providing more "documentation" of how the [`useModal`](https://github.com/liferay/clay/blob/fb5fc36303b8fca57d33acea0b3240e735cbfc41/packages/clay-modal/src/useModal.tsx)  hook was implemented  (for example, I "guessed" the use of `setTimeout` had to do with animations, but wasn't 100% sure) and why it's required.

**Comment by matuzalemsteles** [comment]
@julien you are absolutely right, we should document this.
