### ISSUE TITLE
Verify clay-pagination for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2458]
- [ ] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [ ] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
I'm currently using a local project created with `create-react-app` to try the components and ran into this issue 

![2019-09-17-172618_1600x900_scrot](https://user-images.githubusercontent.com/5572/65056164-b05d9b80-d970-11e9-832c-7fbea07b6eb1.png)

Here's the code I was using and I might have forgotten something, but just in case someone can double check

```javascript
import React, {useState} from 'react';
import ClayPagination from '@clayui/pagination';

import '@clayui/css/lib/css/atlas.css';

const spritemap = require('@clayui/css/lib/images/icons/icons.svg');

function App() {
	const [active, setActive] = useState(1);
	const totalPages = 100;

  return (
		<div id="app">
			<ClayPagination
				arial-label="pagination"
				activePage={active}
				onPageChange={setActive}
				spritemap={spritemap}
				totalPages={totalPages}
			/>
		</div>
  );
}

export default App;
```

This one also needs support for extra attributes (it seemed that `aria-label` didn't get passed in my example) so I can send a PR for that

**Comment by carloslancha** [comment]
Yep, I guess all components should accept `...otherProps` and render'em in the main (or more logic) element.

**Comment by julien** [comment]
After speaking with @marcoscv @bryceosterhaus @diegonvs and @eduardoallegrini we think it might be better analysing each component to find a general pattern or at least a good way to support accesibility related attributes. So I'll won't send a PR just right now.

**Comment by matuzalemsteles** [comment]
Publish #2608
