### ISSUE TITLE
Verify clay-panel for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2459]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Is there anything about the public API that you would change?

No.

> Is the naming of the available props clear?

Yes.
