### ISSUE TITLE
Verify clay-popover for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2460]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by bryceosterhaus** [comment]
Note, this component is not released yet. To verify, use our storybook at https://storybook.clayui.com/?path=/story/components-claypopover--popover

**Comment by marcoscv-work** [comment]
To make a complete review of HTML/CSS/Accessibility We would need to see it in context, for example, a button or link which uses the popover triggered in different ways, by pressing the button, on hover, on focus, etc.

**Comment by bryceosterhaus** [comment]
> Is there anything about the public API that you would change?

I would add an additional API to disable the scroll bar for long text. PR: https://github.com/liferay/clay/pull/2505

I would also add a high-level component that we can wrap a "trigger" with so that users don't need to manually implement positioning and hide/show. I think this can be implemented after 3.0.0 though. @matuzalemsteles what do you think?

**Comment by matuzalemsteles** [comment]
> I would also add a high-level component that we can wrap a "trigger" with so that users don't need to manually implement positioning and hide/show. I think this can be implemented after 3.0.0 though. @matuzalemsteles what do you think?

Yeah, I think it would be better to add that after 3.0.0 so we could collect his use cases with the teams and how they do it.
