### ISSUE TITLE
Verify clay-select for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2462]
Should this component live in `@clayui/form`?

- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Should this component live in @clayui/form?

We might ask the rest of the team but I would expect it in the `@clayui/form` package too, good point.

> Is there anything about the public API that you would change?

Not at the moment.

> Is the naming of the available props clear?

Yes.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles what do you think about moving this into `@clayui/form`?

**Comment by matuzalemsteles** [comment]
@bryceosterhaus I have no problem moving to `@clayui/form`, we can go with that.

**Comment by eduardoallegrini** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics**
