### ISSUE TITLE
Verify clay-slider for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2463]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [ ] **Accessibility basics** 
  - **It is not blocking**, but `label & input` always need a relation with `for="ID"` or by using `label {Value: ${value}}`as `aria-labelledby`

**Comment by jbalsas** [comment]
There's currently no documentation for this component in the site, only the storybook... which I would've expected to be at least within forms.

Should we keep this component separated, or aggregated in `@clayui/forms`? This might be used outside as a single element just for other control purposes outside of the classic HTML form

**Comment by jbalsas** [comment]
Behaviour and API works fine, tested together with `color-picker` as https://codesandbox.io/s/clay-component-demo-y6trl

**Comment by jbalsas** [comment]
> Does component accept a ref? Is the ref value what you would expect?

This component does not currently accept a ref... but I'm not sure I expected one anyways

**Comment by jbalsas** [comment]
> Were you able to find documentation for this component? Was it clear?

Found the storybooks, but missing the general docs on the component

**Comment by diegonvs** [comment]
> Should we keep this component separated, or aggregated in @clayui/forms? This might be used outside as a single element just for other control purposes outside of the classic HTML form

I, Matu and Bryce agreed with left this component in its own package due to not bloat ClayForm.

**Comment by wincent** [comment]
> I, Matu and Bryce agreed with left this component in its own package due to not bloat ClayForm.

Do you think it will be clear to users what the rationale for including something (or not including it) in ClayForm are? As far as I can tell, the criterion is something like:

> Include in ClayForm if the component is (or is analogous to) a form element, **except** when we feel that the component would "bloat" ClayForm.

I don't really understand how we decide what constitutes bloat and what doesn't. In this case, the heart of the component is an `<input type="range" />` and that sure sounds like a form component to me.

**Comment by jbalsas** [comment]
> In this case, the heart of the component is an <input type="range" /> and that sure sounds like a form component to me.

That was mainly the reason I asked. On the other hand, that could be considered an implementation detail. Developers wouldn't necessarily need to know this, so the criterion could read something like:

> Include in ClayForm if the component is normally to be used within a `<form>` element.

In this case, I see how a lot of apps could use the `slider` component to control other parts of an application without relying on the `input`-like behaviour.

With all this in mind, maybe a simpler approach would be to split the packages again. On the price of having more packages we avoid this discoverability issue... 🤷‍♂

**Comment by wincent** [comment]
I'd like to understand what the fear of "bloat" means here. Having more packages increases our maintenance and release overhead, and consumers of Clay who really cared about size would be using some kind of tree-shaking, right? In liferay-portal, we'll often want to load most or all of Clay (almost by definition, because the stuff that goes in Clay is stuff that is generally needed).

Is Clay a set of dozens of tiny orthogonal tools intended to be used in isolation, or a single cohesive thing that gives you the means to build UIs that follow Lexicon?

**Comment by bryceosterhaus** [comment]
> Is Clay a set of dozens of tiny orthogonal tools intended to be used in isolation, or a single cohesive thing that gives you the means to build UIs that follow Lexicon?

I think we intend to be _both_. Something that can be used in isolation, but also should work together cohesively as a unit when used together.

As far as what we decide to put into `@clayui/form`, it is definitely subjective and we don't necessarily have a hard and fast rule. But I would probably use a similar line of thinking as Chema noted, "is this typically used within a from or is it often used outside of a form?". For the case of slider, I imagine it would be used in a form but I also think it would more likely be used outside equal amounts, if not more often.

But yeah, its fairly subjective.

**Comment by bryceosterhaus** [comment]
Also, I'm not super concerned with "bloat" in a package. I think you could argue that 6 individual small packages is just as much bloat as one large package.

**Comment by diegonvs** [comment]
> I'd like to understand what the fear of "bloat" means here.

A lot of components in a single package may affect the discoverability, I guess.

As Bryce said:

> As far as what we decide to put into @clayui/form, it is definitely subjective and we don't necessarily have a hard and fast rule.

I totally agree with that.

**Comment by wincent** [comment]
> A lot of components in a single package may affect the discoverability, I guess.

Are people really discovering components by looking through the packages folder in the monorepo? Or searching for words on NPM? I would have thought that they'd mostly be starting from the Clay website.

I'm fine with the decision to put clay-slider wherever you want: I just wanted to tease out the rationale a bit, in the hope of making it as clear, objective and non-arbitrary as possible.

**Comment by diegonvs** [comment]
> I'm fine with the decision to put clay-slider wherever you want: I just wanted to tease out the rationale a bit, in the hope of making it as clear, objective and non-arbitrary as possible.

👍

**Comment by bryceosterhaus** [comment]
> Are people really discovering components by looking through the packages folder in the monorepo?

maybe I'm the only one that does this... just today I was looking through babel's packages lol

Primarily I think we would expect people to find our components through our site or through storybook(which is from our site).
