### ISSUE TITLE
Verify clay-sticker for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2464]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Is there anything about the public API that you would change?

Not at the moment.

> Is the naming of the available props clear?

Yes.

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - Images need always `alt =""`, if we don't have text we need to write `alt =""` to set the image doesn't' have semantic meaning or value

**Comment by bryceosterhaus** [comment]
@marcoscv-work  sticker itself does not render an img tag, the user has to pass that tag as a child, so it will be up to the user to do so. But I think you caught that some of our stories did not include an alt attribute. Ill see about updating all of our stories for this.
