### ISSUE TITLE
Verify clay-table for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2465]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [ ] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by marcoscv-work** [comment]
In the storybook example the kebab-menu is not a button, is it a limitation or a demo issue?
![image](https://user-images.githubusercontent.com/7963804/65135511-57d8dd80-da06-11e9-8a48-336db5a929f6.png)

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - Ensure checkbox has `aria-label` with a meaning label, not something like "Check" It would need to be something like **"Check out / Select + name of the item, by default first info column"**
  - Minor problems with the definition of `table-divider` It not works like table header so it's confusing for screenreaders

**Comment by diegonvs** [comment]
In the storybook example the kebab-menu is not a button, is it a limitation or a demo issue?
> A demo issue, a fix was sent at https://github.com/liferay/clay/pull/2499

**Comment by julien** [comment]
> Is there anything about the public API that you would change?

No

> Is the naming of the available props clear?

Yes
