### ISSUE TITLE
Verify clay-time-picker for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2467]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [ ] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [ ] If this is a form element, does it accept a `name` attribute?
- [x] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by julien** [comment]
> Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.

The component does accept additional HTML attributes, but passing `aria-label` or `aria-hidden` has no effect (i.e. it is not present in the rendered component)

>  If this is a form element, does it accept a name attribute?

It does but it's apparently not used, just like the `aria-*` attributes. 

We talked offline with @bryceosterhaus and we'll need to review that.

> Is there anything about the public API that you would change?

Not at the moment.

> Is the naming of the available props clear?

Yes.

**Comment by bryceosterhaus** [comment]
@julien if you are up for it, you are more than welcome to send a PR fixing this. If you'd rather not, no worries, I can come back through and send one.

**Comment by julien** [comment]
@bryceosterhaus sure, will do.
I'll keep this issue assigned to me until we get that merged in. Thanks

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [ ] **Accessibility basics** 
  - **It cannot be used by screen reader**
  - The component need input descriptions, example: `aria-label="Enter the time in 00:00 format"`
  - If we decide to use only the inputs the buttons to control up and down can be hidden, if not, they also need description
