### ISSUE TITLE
Verify clay-tooltip for 3.0.0 release

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2468]
- [x] Are you able to easily implement a demo of this component? Are there any “gotchas” when implementing? Provide a link to codesandbox for a demo.
- [x] Does the component accept additional HTML attributes? For example, adding an aria attribute to a button.
- [x] Does component accept a ref? Is the ref value what you would expect?
- [x] Does this component allow for different translations?
- [x] If this is a form element, does it accept a `name` attribute?
- [ ] Were you able to find documentation for this component? Was it clear?

Additional Questions:
- Is there anything about the public API that you would change?
- Is the naming of the available props clear?

**Comment by marcoscv-work** [comment]
The module is not published yet?
We cannot use: `yarn add @clayui/button`

**Comment by bryceosterhaus** [comment]
@marco-leo ah yeah you are right, this was added after our last release. You can test and interact with it at https://storybook.clayui.com/?path=/story/components-claytooltip--tooltip

**Comment by marcoscv-work** [comment]
- [x] **HTML**
- [x] **CSS**
- [x] **Accessibility basics** 
  - Sometimes we need a 'tooltip' as a visual help but it does not need to be 'read' for a screen reader, so it wouldn't be a `title` HTML attribute, for example; buttons type icon, but in that case, the button can have an `sr-only` text or `aria-label`.
  I think this is possible with the current component, could you guys confirm it?

**Comment by bryceosterhaus** [comment]
Yeah you should be able to add the `aria-label` to a button or add inner content with `sr-only`.
