### ISSUE TITLE
Size issue when you combine `small="true"`and `displayType="unstyled"` 

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2475]
Size issue when you combine `small="true"`and `displayType="unstyled"` or in CSS:
`btn-sm` and `btn-unstyled`

These classes should not be combined, but the Clay component does not prevent it, so they can be together

https://codepen.io/marcoscv/pen/MWgqQVL

Since btn-unstyled is a reset of button styles, sizes must be reset over other styles

**Comment by matuzalemsteles** [comment]
hey @marcoscv-work and @pat270 just a question about it, could adding this in 2.x cause some kind of regression in people who expected it to work out that way? although this is wrong in our view.

**Comment by pat270** [comment]
@matuzalemsteles yes it can. We could revert it in 2.x if you think people are using it.

**Comment by matuzalemsteles** [comment]
@pat270 I'm not sure if anyone is using it, but it's just a thought.
