### ISSUE TITLE
Basic guidelines to test Clay components

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2478]
Hi guys, I was trying to take a look at the Clay components https://github.com/liferay/clay/milestone/12 and I think the whole process could be confusing if you are not a js-developer

I don’t know if we already have these guidelines somewhere or if these are even correct, I had to guess and read online. So I was wondering, should we add them to our documentation?

## Getting started
> install/update node/npm/react/yarn

I know it’s a basic step but still we should add it to the documentation
> `npx create-react-app [app-name]`

I think this is optional but if you just want to try the component it’s a good start
> `cd [app-name]`

basic, suggested by react but still a good tip
> `yarn add @clayui/[selected-module]`

if you don't have experience with yarn you won't think of this
`npm -i [selected-module]` installs an older version
> `yarn add @clayui/css`

this is a good practice I copy from [bryce’s example](https://codesandbox.io/s/sad-carson-thluj) but it’s not mentioned anywhere
> `yarn start`

basic, suggested by react but still a good tip

## In the App
If you are using the app created by the `npx create-react-app [app-name]`
> Add the example code provided by the Clay website into App.js or index.js

basic, suggested by react but still a good tip
> Add `import "@clayui/css/lib/css/atlas.css";` to your code, after `import React from 'react';`

this is a good practice I copy from bryce’s example but it’s not mentioned anywhere
> Add `import ClayIcon from "@clayui/icon";`to your code, after `import React from 'react';`

this is a good practice I copy from bryce’s example but it’s not mentioned anywhere

## Components
Is there any reason why we are not using a prefix for the API options?

Example: in the [alert component](https://next.clayui.com/docs/components/alerts.html) we are using `title`, `variant`, `spritemap`, etc. shouldn’t we be using `clayTitle`, `clayVariant` or `claySpritemap`?

**Comment by marcoscv-work** [comment]
For the components part:

We have some confusion when we use component attributes what actually are for html like `title`, for example: 
- In alert component `title=""'` is the title of the alert, this part:
  - ![image](https://user-images.githubusercontent.com/7963804/65045099-7a172080-d95e-11e9-88f7-a4e25bac6cdf.png)
- In icon component title is the HTML attribute:

As @eduardoallegrini has mentioned, we could use `clayTitle` and it would be abstracted from the HTML attribute; `title`

**Comment by carloslancha** [comment]
@eduardoallegrini @marcoscv  I agree we should have different props names in this cases like `title` (don't see a reason for not using `variant` or `spritemap`) so we can still use html attributes, but `clayWhatever` for me is definitely not an option.

Maybe `leadTitle`?

**Comment by matuzalemsteles** [comment]
I agree with @carloslancha, there is no reason to prefix `clay` with APIs, I think this case is an exception and we can rename it to better suit the case. I think `leadTitle` might be a good option here.

**Comment by diegonvs** [comment]
For Alert case, I vote for `message` instead of `title`.
