### ISSUE TITLE
ClayNavigationBar links and buttons have a different height

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2526]
During the recent tests, I found out a little bug with the height of the elements
![image](https://user-images.githubusercontent.com/46778114/65321129-b1c2da00-dba3-11e9-8617-daf205d0162e.png)
`links` and `buttons` has a different height (buttons: 29px, links: 32px)

**Comment by matuzalemsteles** [comment]
hey @eduardoallegrini Someone had talked about this before, but we came to the conclusion that it would not be possible to have all the active elements, it seems to happen only when they are active.

**Comment by jbalsas** [comment]
Closing for now as expected based on @matuzalemsteles's comment
