### ISSUE TITLE
Please include new icon Sign-in

### ISSUE THREAD

**Issue by DuuriimaaBargaid** [liferay/clay#2580]
Please include new icon "Sign-in"

<img width="304" alt="Captura de pantalla 2019-10-03 a las 14 21 50" src="https://user-images.githubusercontent.com/36294241/66126186-2c9ae480-e5e9-11e9-8b4c-300d6f2d07d8.png">
Please find the .SVG  file in jira ticket https://issues.liferay.com/browse/LEXI-657

**Comment by victorvalle** [comment]
Please, wait for review

**Comment by emiliano-cicero** [comment]
This icon has been updated and is now reviewed. The SVG inside the Jira Ticket is ready to be included in Clay.
