### ISSUE TITLE
Please include new icon HDD

### ISSUE THREAD

**Issue by DuuriimaaBargaid** [liferay/clay#2582]
Please include the new icon HDD
<img width="317" alt="Captura de pantalla 2019-10-03 a las 14 57 22" src="https://user-images.githubusercontent.com/36294241/66128452-20fdec80-e5ee-11e9-98e6-c8b5427808eb.png">

Please find .SVG file in jira ticket https://issues.liferay.com/browse/LEXI-652

**Comment by victorvalle** [comment]
Please, wait for review

**Comment by emiliano-cicero** [comment]
This icon has been updated and is now reviewed. The SVG inside the Jira Ticket is ready to be included in Clay.
