### ISSUE TITLE
"Cannot convert undefined or null to object" in LoadingIndicator docs

### ISSUE THREAD

**Issue by wincent** [liferay/clay#2606]
The [LoadingIndicator docs](https://next.clayui.com/docs/components/loading-indicator.html) have a couple of issues.

First, down the bottom I see:

> ## API
> Cannot convert undefined or null to object

Bonus, the code uses an unnecessary React fragment:

```javascript
return (
  <>
    <ClayLoadingIndicator />
  </>
);
```

ie. could just be

```javascript
return <ClayLoadingIndicator />;
```

**Comment by bryceosterhaus** [comment]
fixed by https://github.com/liferay/clay/pull/2700
