### ISSUE TITLE
Please include new icon Briefcase

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#2613]
Please include new icon "Briefcase"

<img width="135" alt="Screen Shot 2019-10-10 at 10 33 38 AM" src="https://user-images.githubusercontent.com/21121115/66552337-746dbe80-eb49-11e9-8abe-127a6cf5efb7.png">

Please find the .SVG file in jira ticket https://issues.liferay.com/browse/LEXI-665

**Comment by victorvalle** [comment]
This *must not* replace suitcase icon :)

**Comment by pat270** [comment]
Master: https://github.com/liferay/clay/pull/2623
2.x: https://github.com/liferay/clay/pull/2624
