### ISSUE TITLE
Toast alerts in clayui.com are not contained properly in page

### ISSUE THREAD

**Issue by john-co** [liferay/clay#2618]
- [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?

1. Navigate to https://clayui.com/docs/components/alerts.html
2. Go to Lexicon Core Components > Alerts
3. Scroll down and assert floating toast alert messages spilling over to side nav and over each other
![Selection_010](https://user-images.githubusercontent.com/35235266/66614145-b2d0a100-eb7c-11e9-8498-5907b39717a2.png)

Notes: alerts touch and start to spill over each other at < 1350px, very noticeable spill over at < 1200px, 

## What is the expected result?
alert badges are contained in body of page and adjust to size of web browser such as the toast alerts shown in https://next.clayui.com/docs/components/alerts.html
![image](https://user-images.githubusercontent.com/35235266/66614136-a77d7580-eb7c-11e9-823b-e8400fee2d6b.png)

**Comment by kresimir-coko** [comment]
@john-co I can't reproduce this one anymore on the live site. Here's the screenshot: 
![image](https://user-images.githubusercontent.com/24564752/90620634-00914d80-e213-11ea-9fe9-0de5a7f68a12.png)

Is this still bugged in the way you described in the OP?

**Comment by matuzalemsteles** [comment]
I think this was fixed on the Alerts page in the `CSS/Markup` session.

**Comment by john-co** [comment]
Hi @kresimir-coko , I can't reproduce this issue anymore either.

![Peek 2020-08-19 16-42](https://user-images.githubusercontent.com/35235266/90700596-0b5fd880-e23b-11ea-89a4-81659d20fdff.gif)

Closing issue.
