### ISSUE TITLE
Bot for remember reviewing things in Documentation, check A11y and Refactoring for each Pull Request.

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2625]
## What is your proposal?

- Add a Bot for review Documentation, A11y, and Refactoring when sending a PR.

## Why would adopting this proposal be beneficial?

- Make sure our docs are updated. Make sure about A11y checking when reviewing.

## What are the alternatives to this proposal?

- For now, Idk

**Comment by bryceosterhaus** [comment]
I dont think these are quite necessary yet. Going to close but will reopen if we want to revisit later
