### ISSUE TITLE
Deprecate old milestone packages

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2626]
There are some deprecated packages on the NPM registry, initially, we offered these components in a reserved module but now these ones are included in another package.

Examples: 
- https://www.npmjs.com/package/@clayui/checkbox (outdated since milestone.1)
- https://www.npmjs.com/package/@clayui/radio-group
- https://www.npmjs.com/package/@clayui/select

**Comment by bryceosterhaus** [comment]
This is a good idea. We can add messages like `@claui/checkbox has moved to @clayui/form@v3.0.0`

If no one sees any issue with this, I can go ahead and do this today.

**Comment by diegonvs** [comment]
On DXP side we can include here:

https://github.com/liferay/liferay-portal/blob/ec95b6f0148a8c671dd63a384adb73d5181ab7f7/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JSONDeprecatedPackagesCheck.java#L62

**Comment by diegonvs** [comment]
> This is a good idea. We can add messages like `@claui/checkbox has moved to @clayui/form@v3.0.0`
> 
> If no one sees any issue with this, I can go ahead and do this today.

Yes, would be good :)

**Comment by bryceosterhaus** [comment]
Also added https://www.npmjs.com/package/@clayui/navigation to the list. All four should now show up as deprecated.
