### ISSUE TITLE
Allow disabling ClayColorPicker

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2636]
There's currently **no way to disable the ColorPicker component**. Both the splotch and the input remain enabled at all times.

We have an existing **use case** where **a toggle controls if some color pickers should be enabled** or not and I'm sure there are other such cases. In general form-like components are all nice "disableable" candidates.

As it is right now, we could get away with simply being able to pass `inputClasses` and `splotchClasses` because that's how the other component is figuring out what elements to disable. However, this sounds somehow counter-reactish, so, maybe **an `enabled|disabled` prop**, depending on what we have on other similar components would be the best course of action.

**Comment by wincent** [comment]
> As it is right now, we could get away with simply being able to pass `inputClasses` and `splotchClasses` because that's how the other component is figuring out what elements to disable. However, this sounds somehow counter-reactish

To provide some context here: what the old (non-React) implementation is doing is a `document.querySelectorAll` to find elements in the DOM and mutating them directly. In React we'd obviously just control the disable/enabled state via props — reading/writing to/from the DOM breaks the encapsulation provided by the abstraction of components.
