### ISSUE TITLE
Officially release Clay 3.0.0

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2653]
Finally we come to the official Clay 3.0.0 release announcement, to complete this work we need to do a few things:

- [x] Open an LRIT to create the `v2.clayui.com` domain for github and move the `clayui.com` domain to netlify (https://issues.liferay.com/browse/LRIT-15793 is private)
- [x] Host the current `clayui.com` on `v2.clayui.com`
- [x] Host the current `next.clayui.com` on `clayui.com`
- [x] Make a blog post (Clay blog) announcing the general changes and any other clarification
- [x] Post on Loop a short announcement and direct to blog post

**Comment by bryceosterhaus** [comment]
Just posted the loop announcement, I think this can be closed
