### ISSUE TITLE
[clayui.com] Make the second tab (CSS/Markup) of the components linkable

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2654]
Make the second tab (CSS/Markup) of the components linkable

![image](https://user-images.githubusercontent.com/46778114/67264574-c567a600-f4ab-11e9-95b9-bd5ace508745.png)

At the moment I can not link a CSS/Markup page

**Comment by matuzalemsteles** [comment]
Fixed by #3679
