### ISSUE TITLE
[ClayComponents] Deprecate the .sheet-lg variation 

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2655]
I think we could remove the `.sheet-lg` variation from the components and the examples.
https://clayui.com/docs/components/forms/css-forms-hierarchy.html

We can achieve the same result using the right structure (container, row, col)

Here's an example: https://codepen.io/eduardoallegrini/pen/JjjKgZz

Furthermore the specification from Lexicon seems to say the same

Lexicon Website: https://liferay.design/lexicon/foundations/layout/layout-form/
Lexicon Document: https://docs.google.com/document/d/1zKBEHPLbHiWlz1Xswek9JM_9jrtVNLFS_JeCvoBhzRY/edit#

**Comment by pat270** [comment]
@eduardoallegrini we can remove it. I remember seeing something about it being a specific width in large screens, but I don't see that anymore. We should probably deprecate in 3.x tho.

**Comment by matuzalemsteles** [comment]
hey guys, as it is releasing Clay v3, I would suggest adding a warning info and then removing it completely in v4...

**Comment by eduardoallegrini** [comment]
Just to remind an issue highlighted by @victorvalle was that "we have to update all the usages of `.sheet-lg` in Portal" 

But it doesn't seem a problem
![image](https://user-images.githubusercontent.com/46778114/67669723-c0569b00-f972-11e9-87ac-b28c3cee9f6b.png)

**Comment by pat270** [comment]
@eduardoallegrini I'm going to deprecate `sheet-lg` in 2.x and 3.x. You guys can decide whether to remove it in Portal.
