### ISSUE TITLE
[ClayComponents] Add forwardRef to ClayTable component

### ISSUE THREAD

**Issue by kienD** [liferay/clay#2669]
## What is your proposal?
Add a `forwardRef` to the `ClayTable` component, more specifically, to `ClayTable.Row`.

## Why would adopting this proposal be beneficial?
We're trying to add drag and drop support to table rows but are unable to add the ref required for `react-dnd`.

**Comment by brunofarache** [comment]
We needed for the root ClayTable component and ended up wrapping in a div that had a ref. It was for drag and drop too, but in our case ClayTable as a whole was the drop zone.
