### ISSUE TITLE
Does Clay support a read-only input with success state?

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2687]
## Does Clay support a read-only input with success state?

**Context**
Working on #2144 we talked about read-only states for input boxes and we found that read-only inputs should support success states (see [W3C Forms: Ready Only Inputs](https://www.w3.org/TR/html401/interact/forms.html#h-17.12.2))

Lexicon have solved that requirement with [LEXI-636](https://issues.liferay.com/browse/LEXI-636)

![Read-only success state](https://user-images.githubusercontent.com/21216422/68130111-14d1bb80-ff1b-11e9-9c4b-1afedd4a437c.png)

P.S. Issue related #2425 (new read-only style)

**Comment by pat270** [comment]
<img width="950" alt="readonly-validation" src="https://user-images.githubusercontent.com/788266/68142483-601ca780-fee4-11e9-8a5d-e5e4facdc41b.png">
@drakonux is what readonly looks like in Clay CSS right now. There was no definition when I styled it.

**Comment by drakonux** [comment]
Ei sorry @pat270 my question was more related with the new read-only style #2425 we requested for 3.0. 

I was asking if we currently support in 3.0 the success case with read-only or if else to create a new proposal in Clay.

**Comment by pat270** [comment]
@drakonux I'm guessing we don't but someone else on the team might be able to confirm.

**Comment by matuzalemsteles** [comment]
hey @pat270 @drakonux We support the new read-only style in 3.0 but not the read-only with success case.

**Comment by drakonux** [comment]
Thanks!!! @matuzalemsteles 

I've created a new proposal for that --> https://github.com/liferay/clay/issues/2715 
Closing the ticket. Thanks everyone!
