### ISSUE TITLE
Include new icons: heart-full

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#2690]
Please include this new icon. Find the .SVG in the [jira ticket LEXI-722](https://issues.liferay.com/browse/LEXI-722)
![image-2019-11-04-14-18-35-280](https://user-images.githubusercontent.com/56547676/68134948-261ec600-ff23-11e9-8eae-b102d29f5a56.png)

**Comment by drakonux** [comment]
Hi guys, 

Reviewing [Clayui.com](https://clayui.com/docs/components/icon.html) we didn't find the heart-full icon in the list. Could you check it out please?

Thanks, 
David
