### ISSUE TITLE
Include and replace new icon: times

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#2692]
Please include and replace this new icon. Find the .SVG in the [jira ticket LEXI-725](https://issues.liferay.com/browse/LEXI-725)
![image-2019-11-04-14-09-17-761](https://user-images.githubusercontent.com/56547676/68135669-531fa880-ff24-11e9-8c8c-4b443feeeaed.png)

**Comment by matuzalemsteles** [comment]
Fixed #2703
