### ISSUE TITLE
Twitter icon does not have same way of naming as other Social Icons

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#2697]
Working on [LEXI-723](https://issues.liferay.com/browse/LEXI-723) to create 2 new social icons for Vimeo and Instagram, we have observed that Twitter icon is named differently from other social icons.
For example:
**Facebook**: social-facebook
**Linkedin**: social-linkedin
But **Twitter** ID is: twitter

Would it be possible to change Twitter's ID to social-twitter so that all social icons have the same way of naming?

**Comment by pat270** [comment]
@laugardie yes we can change it. I will deprecate `twitter` and add `social-twitter`.
