### ISSUE TITLE
Read-only input with success state

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2715]
## Proposal
Create a new style for success case in read-only states for input boxes. 

![image](https://user-images.githubusercontent.com/21216422/68330644-e4814d00-00d3-11ea-8841-9436ac55ac6a.png)
## Benefits
We will be complying a [W3 recommendation](https://www.w3.org/TR/html401/interact/forms.html#h-17.12.2) for HTML 4.

## Lexicon definition
Please follow [LEXI-636](https://issues.liferay.com/browse/LEXI-636) definition

**Comment by drakonux** [comment]
😮 I didn't add the rfc label on purpose... ¿?

**Comment by wincent** [comment]
@drakonux: for future reference, if you want to avoid the "rfc" label being applied to things that aren't actually RFCs, you can go straight to: https://github.com/liferay/clay/issues/new (as opposed to https://github.com/liferay/clay/issues/new/choose which is where the "New issue" button takes you).
