### ISSUE TITLE
[ClayCss] Create useful utility classes without the important attribute

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2725]
## What is my proposal?

I think we should recreate some of the utility classes already created in Bootstrap without the `!important` attribute in order to avoid specificity issues

I'm talking about the most common and useful ones: spacing utilities (i.e. margins and paddings, we can add more in the future)

The ideal process would be to not load the Bootstrap spacing utilities and create our own in Clay

**Current**
![image](https://user-images.githubusercontent.com/46778114/68655004-7e5f5480-052f-11ea-9f7f-a6957f2d0522.png)

**Proposal**
![image](https://user-images.githubusercontent.com/46778114/68655774-e95d5b00-0530-11ea-8af1-875c624f7709.png)

Alternatively we could create some Clay classes

Bootstrap Classes | Clay Classes
--- | ---
.mt-5 | .c-mt-5
.mx-auto | .c-mx-auto
.py-lg-1 | .c-py-lg-1

I personally prefer the first solution because it could avoid a future task where we have to change all the usages of the Clay classes since the [Bootstrap team is already evaluating this possibility](https://github.com/twbs/bootstrap/pull/29625)

## Why would adopting this proposal be beneficial?

There are a lot of components and elements that could take advantage of this change: [container-form-lg](https://clayui.com/docs/css/grid.html#container-form-lg), [container-view](https://clayui.com/docs/css/grid.html#container-view), [inline-item](https://clayui.com/docs/css/utilities/inline-item.html), [input-groups](https://clayui.com/docs/components/forms/input.html#groups), [split button groups](https://clayui.com/docs/components/button-group.htm)] and almost all the components that need a spacing

Many Portal's issues could be resolved faster if we could use these utility classes, all the teams and developers are often confused about whether or not use utility classes and they end up using them where they shouldn't or create heavy and redundant css code where it's not necessary

/cc @jbalsas @marcoscv-work @pat270 @matuzalemsteles @drakonux

**Comment by pat270** [comment]
@eduardoallegrini 
Not a good idea for 3.x, removing the `!important` flag in Bootstrap's utilities will cause spacing issues for people already using it that need the specificity.

The second method would be better for backward compatibility, but how do you plan to resolve specificity issues?
```
.my-component .container { padding-top: 1.5rem; }

<div class="my-component">
    <div class="container c-pt-5"></div>
</div>
```
The code above should render `padding-top` on `container` to be `3rem` but because of specificity `padding-top` is still `1.5rem`.

**Comment by eduardoallegrini** [comment]
For the first solution, the thing is they shouldn't be using those classes inside the portal, since all the widgets and components should be customizable with a theme or a custom css. So in my opinion this could be good "breaking-change" to discover and fix where it's necessary.

For the second solution, your example would be the new expected behavior. If you need to customize a certain component and it was built using utility classes, you will need to overwrite them

**Comment by marcoscv-work** [comment]
In CSS everything can be overwritten without apparent sense. If we create our custom classes they would be for our purposes so we can define under what rules they should be used, it could be easy, for example:

- Use `c-` helpers to assign new margins/paddings when the component does not define them.
- If you need to contradict/overwrite component styles (about margin/padding) you must create a modifier

**Comment by pat270** [comment]
@eduardoallegrini We also need to think about others custom implementations using Clay CSS, where specificity matters. I don't agree with removing `!important` as a good change. I'm willing to go with option 2 and add more utilities as needed.

**Comment by marcoscv-work** [comment]
Great! I'm going to merge this PR, we will need to document it and add it to CSS/HTML course
