### ISSUE TITLE
ClayPopover `show` property is not working

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2738]
-   [ x ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

https://github.com/liferay/clay/pull/2737

## What are the steps to reproduce?

Set the property `show` of ClayPopover component to `false`.

## What is the expected result?

ClayPopover don't be shown.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| React | v16.9.0 |

**Comment by matuzalemsteles** [comment]
Hey @pat270 can you tell if we have a `show` modifier class for this case in css?

**Comment by bryceosterhaus** [comment]
cc @pat270 any idea on this?

**Comment by pat270** [comment]
Bootstrap sets `opacity: 0` on `popover` without the `show` class.

**Comment by jbalsas** [comment]
Added to https://github.com/liferay/clay/milestone/15 so we can prioritize it :)
