### ISSUE TITLE
ClayCSS form validation space between icon and text

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#2754]
## Other issues?
-   [ ] I have searched [this issue](https://github.com/liferay/clay/issues/2075) of this repository and the error still happen. Maybe it's an issue with Clay v3.
- [ ] https://issues.liferay.com/browse/LEXI-155

## What are the steps to reproduce?
I'm using form validation: https://next.clayui.com/docs/components/forms/form.html

```
<ClayForm.FeedbackIndicator symbol="exclamation-full" />
	{Liferay.Language.get(
		'an-experience-name-is-required'
	)}
</ClayForm.FeedbackItem>
```

## What is the expected result?
Should be a space between the icon and the error message.

/cc @drakonux

**Comment by pat270** [comment]
Clay CSS assumes there will be white space between the icon and error message. I think soy strips white space. If you need a precise value between icon and text (e.g., 0.5rem) I can fix this in Clay CSS, if you just need some space we should add a space in the Clay Component.

**Comment by dgarciasarai** [comment]
Hey @pat270, of course I can add a margin with Clay CSS but the team faced the same problem in Clay v2 and finally the space was added by default in the component. So it would be great to add that margin or space in the Clay Component (ClayForm.FeedbackIndicator) by default in Clay v3. Thanks.

**Comment by jbalsas** [comment]
I think we probably just need to add `inline-item` and `inline-item-after` somewhere in the component, or you can likely do the same by wrapping the `Liferay.Language.get` in a span and adding those in `className`, maybe...

**Comment by bryceosterhaus** [comment]
Just submitted a fix for this on the component side. I think it makes sense to have a default margin via `inline-item-before`. Check out the storybook deploy to verify, https://github.com/liferay/clay/pull/2762

**Comment by drakonux** [comment]
Hey @bryceosterhaus ! I double-checked the distance between the icon and the text on storybook and it's 8px 🤔

![Wrong Distance](https://user-images.githubusercontent.com/21216422/70690811-c05af200-1cb7-11ea-8894-d4f8f5c251f3.png)

It should be 4px as it's described in [LEXI-155](https://issues.liferay.com/browse/LEXI-155)

**Comment by bryceosterhaus** [comment]
@drakonux ah I see, I just went with using our text utils. Maybe this needs to be added to `form-feedback-indicator` in clay-css then. cc: @pat270
