### ISSUE TITLE
Buttons and links receive focus state when clicked

### ISSUE THREAD

**Issue by jaredgorski** [liferay/clay#2763]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
1. Right-click any link or button on clayui.com

![2019-12-02 15 13 22](https://user-images.githubusercontent.com/36674760/70003040-c6620d80-1516-11ea-9ffc-272b9347f4d7.gif)

## What is the expected result?
Button or link will not receive focus just because it's mouse-clicked

[This should be fixable with a `tabindex` trick.](https://stackoverflow.com/questions/31402576/enable-focus-only-on-keyboard-use-or-tab-press)

**Comment by pat270** [comment]
Hey @jaredgorski,
Good find, this looks promising. We could probably introduce this using some kind of setting in Clay CSS. It would be turned off by default to avoid breaking existing implementations. We would have to move some of the button styles to the `span` tag to avoid the focus border from showing if the click misses the text.

Not sure how Clay Components would handle this, maybe through some property that will wrap the text in `span tabindex="-1"`. Others on the team might be able to give more insight.

**Comment by jaredgorski** [comment]
Thanks for the reply @pat270. We implemented something similar on marble (WeDeploy): https://github.com/LiferayCloud/marble/blob/master/packages/marble-button/src/Button.soy#L100

It's not as polished, but could provide an example as an implementation is considered.

**Comment by pat270** [comment]
@jaredgorski I just sent a pr at https://github.com/liferay/clay/pull/2902. If this gets merged you can enable it by setting `$enable-c-inner: true;` in `_clay_variables.scss` or wherever your variable overwrites are placed.

The pattern is:
```
<button class="btn btn-primary" type="button">
    <span class="c-inner" tabindex="-1">Primary</span>
</button>
```

The only places where focus styles will show on click are in `<input type="">`, `<select>`, checkboxes, radios, toggle switches, and `dropdown-toggle`.

For `dropdown-toggle` Bootstrap JS focuses the element on show, you will need to remove the focus via blur or focus `.dropdown-toggle .c-inner`. I think if using `Clay Dropdown`, you dont need to worry about this, not 100% on it though.
