### ISSUE TITLE
Popover positioning

### ISSUE THREAD

**Issue by andresfulla** [liferay/clay#2768]
## What is your proposal?
Implement positioning for ClayPopover so it can be CSS-independent of its parent.

I quickly implemented this with `React.createPortal` and `metal-align`.

```javascript
const Popover = props => {
  return ReactDOM.createPortal(
    <PopoverComponent {...props} />,
    document.body
  );
};

const PopoverComponent = ({anchor, children, ...rest}) => {
  const popRef = useRef(null);

  React.useLayoutEffect(() => {
    Align.align(popRef.current, anchor, Align.Right, false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, []);

    return (
      <ClayPopover alignPosition="right" ref={popRef} {...rest}>
        {children}
      </ClayPopover>
    );
  };
```

## Why would adopting this proposal be beneficial?

I tried to use the ClayPopover as it is. But I had some trouble because the component that triggers the popover is inside of an element with `overflow: hidden`. So the Popover won't be entirely displayed.
I'm sure that if this comes from Clay out-of-the-box it will be better implemented and address corner cases.

## What are the alternatives to this proposal?
Manual implementation per use case.

**Comment by bryceosterhaus** [comment]
@andresfulla would this fix satisfy your need in this component? https://github.com/liferay/clay/pull/2835#issuecomment-571821282

the other option would be to pass a ref, but I thought that would be more of a "gotcha"
