### ISSUE TITLE
Sub Navigation Bar link doesn't bring user to the actual subtitle they click on 

### ISSUE THREAD

**Issue by calvinctvo** [liferay/clay#2788]
## What is your proposal?
The Sub navigation bar should bring the user to the top of the sub title so the user know they are looking at the right content
## Why would adopting this proposal be beneficial?
For better user experience, since the links only take them to the top of the content, not the sub title.
## What are the alternatives to this proposal?
None

**Comment by bryceosterhaus** [comment]
Hey @Calyasu is this for the clayui docs site?

**Comment by calvinctvo** [comment]
Yes this is for Clayui doc site
![UX Suggestion](https://user-images.githubusercontent.com/51280814/70742847-52bcbf00-1cd3-11ea-8b72-116953f7483d.gif)

**Comment by matuzalemsteles** [comment]
Hey @calvinctvo, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
