### ISSUE TITLE
Search Bar does not work on IE

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2790]
![Search](https://user-images.githubusercontent.com/50709197/70743462-aaa7f580-1cd4-11ea-8a2e-fa0fa4bf9839.png)

-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Go to Docs for Clay v3.0 with Internet Explorer.
Click into the search bar (it can be seen even if you cant see the beginning of it)
Type in a search (letters do fill in).

Nothing Happens.

## What is the expected result?
Search will be executed for whatever you have entered.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| IE |         |

**Comment by jacobcerda** [comment]
I am also having this issue on IE11. This also happens when searching from https://v2.clayui.com/docs/get-started/introduction.html, no search suggestions are showing up.

**Comment by matuzalemsteles** [comment]
Hey guys, this has probably been fixed for the v3 documentation and is working fine now, I will close this ticket but feel free to comment or open a new one.

![Kapture 2020-09-23 at 16 25 35](https://user-images.githubusercontent.com/13750819/94060069-b83cf080-fdb9-11ea-913b-59de0a98aa1f.gif)

> I am also having this issue on IE11. This also happens when searching from https://v2.clayui.com/docs/get-started/introduction.html, no search suggestions are showing up.

As we are using Algolia as our search engine, I think we are only entitled to one API key.
