### ISSUE TITLE
IE Lists in sidebar don't expand/close when clicked on 

### ISSUE THREAD

**Issue by nkkwon** [liferay/clay#2793]
-   [ X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Use IE, go to documentation and click on one of the expandable list and it doesn't open or close.

## What is the expected result?
List will expand to show components inside.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| IE |         |

**Comment by matuzalemsteles** [comment]
I'm closing this since it has already been fixed and it's not being reproducible anymore. Feel free to reopen if it is still reproducible. Thanks!
