### ISSUE TITLE
Incorrect Jump Points on Migration Page 

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2794]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
https://clayui.com/docs/migration/migrate-the-clay-components-from-v2-to-v3.html

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to "Migrate the Clay compoments from v2 to v3.
Scroll down the page abit
Click the following links on the Navigation Bar on the right.

- ClayTable

-ClayModal

-ClayCollapse->ClayPanel

Rather than go to the clicked topic, it goes back to the top of the page.

## What is the expected result?
Page jumps to the clicked topic.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |
| Chrome |         |

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
