### ISSUE TITLE
Mobile Search Bar suggestions drop down text is unreadable

### ISSUE THREAD

**Issue by calvinctvo** [liferay/clay#2795]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?

1. Open any web browser on mobile
2. Go to clay docs site
3. Search for "Card"

## What is the expected result?
user should able to see/read what have been suggested

## Environment

| Tech  | Version |
| Mobile | IPhone X/XS |
| Clay  | v3.0.0  |
| Chrome | latest |

**Comment by calvinctvo** [comment]
P/S: when mobile device rotate horizontally, Search bar suggestions does display the list

**Comment by pat270** [comment]
closing duplicates https://github.com/liferay/clay/issues/2792
