### ISSUE TITLE
Jump Points on Right Nav Bad Don't Exist in Documentation.

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2797]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Go to the Docs for Clay v3.0 with Internet Explorer and you can see that the Navigation Bar on the right that show available subtopics.

Go to Navigation/BaseNavbar
Nav Unstyled shows on the right bar but doesn't exist on the page.

Go to Navigation/Base Nav Pills
Overlay through Using Buttons show up but doesn't exists on the page. 

**Vertical Nav Pills exist but is not listed**

## What is the expected result?
Right Nav Bar shows all available topics on the page.
## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| Chrome |         |

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
