### ISSUE TITLE
Mobile Top Nav Bar doesn't stay still while scrolling horizontally.

### ISSUE THREAD

**Issue by calvinctvo** [liferay/clay#2798]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
1. Open any web browser on Mobile Device
2. Go to clay website
3. Navigate to Components > Date Picker
4. Click on API
5. Scroll left/right horizontally 
## What is the expected result?
Nav Bar should stay still while scrolling horizontally of the Mobile Device.
## Environment

| Tech  | Version |
| Mobile | Iphone X/XS |
| Clay  | v3.0.0  |
| Chrome | latest |

**Comment by nkkwon** [comment]
Issue occurs when there's a table in the documentation bigger than the width of the screen.
