### ISSUE TITLE
Jump Point in Drop Down Component for CSS/Markup incorrect

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2799]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/drop-down.html#alignment-default

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Drop Down
Select CSS/Markup from across the top
Scroll down the page abit
Click Alignment/Default on the Navigation Bar on the right.

Jumps to top of page
## What is the expected result?
Jump to Default Alignment Topic
## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| Chrome |         |

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
