### ISSUE TITLE
Radios Button not formatted correctly/not working on Checkbox

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2800]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/forms/checkbox.html#checkboxes

![RadioFormat](https://user-images.githubusercontent.com/50709197/70754930-52c9b880-1ced-11ea-8f61-c4c1d972467f.png)
## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Forms/Checkbox
Select CSS/Markup from across the top
Observe Radios on the Navigation Bar on the right.

Formatting off. Looks like a type in the code.

## What is the expected result?
A functioning link that matches the rest of the formatting.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
