### ISSUE TITLE
Groups Link on Components/Forms/Input in CSS unresponsive.

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2801]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/forms/input.html#groups

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Forms/Input
Select CSS/Markup from across the top
Scroll down the page abit
Click Groups on the Navigation Bar on the right.

Link at top changes, but does not jump anywhere

## What is the expected result?
Jump to Groups Topic

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |         |

**Comment by Adriverforlife** [comment]
![FormsGroup](https://user-images.githubusercontent.com/50709197/70755439-aee10c80-1cee-11ea-9345-96953d377b78.png)

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
