### ISSUE TITLE
Jump Points In Components/Labels/CSS Incorrect

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2803]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/label.html#label
![ComponentLabel](https://user-images.githubusercontent.com/50709197/70755918-0338bc00-1cf0-11ea-93b6-836612a72ac9.png)

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Label
Select CSS/Markup from across the top
Scroll down the page abit
Click Variations/Simple on the Navigation Bar on the right.

Jumps to top of page

## What is the expected result?
Jump to Simple Variations

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0 |
| React |         |
| Chrome | 78.0.3904.108 |

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
