### ISSUE TITLE
Jump Point in Component/List for CSS/Markup incorrect 

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2804]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/list.html#actions-on-hover
![ListCSS](https://user-images.githubusercontent.com/50709197/70756882-a38fe000-1cf2-11ea-9dff-fdb5bc1be9c6.png)
## What are the steps to reproduce?

Go to the Docs for Clay v3.0.
Go to Components/List
Select CSS/Markup from across the top
Scroll down the page abit
Click Actions on Hover/Anchor or Actions on Hover/Buttons on the Navigation Bar on the right.

Jumps to top of page

## What is the expected result?

Jumps to selected Topic

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |78.0.3904.108|

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
