### ISSUE TITLE
Search Link on Components/Management Toolbar in CSS unresponsive

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2806]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/management-toolbar.html#search
![ManagementToolbar](https://user-images.githubusercontent.com/50709197/70757549-dc30b900-1cf4-11ea-8bf3-762406c3d671.png)

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Management Toolbar
Select CSS/Markup from across the top
Scroll down the page abit
Click Search on the Navigation Bar on the right.

Link at top changes, but does not jump anywhere

## What is the expected result?
Jump to Search Topic

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |78.0.3904.108|

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
