### ISSUE TITLE
Jump Point in Modal Component for CSS/Markup incorrect

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2807]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/modal.html#full-screen-default
![ModalCSS](https://user-images.githubusercontent.com/50709197/70758044-8826d400-1cf6-11ea-9fc7-df8beea84eee.png)

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Modal
Select CSS/Markup from across the top
Scroll down the page abit
Click Fullscreen/Default on the Navigation Bar on the right.

Jumps to top of page

## What is the expected result?

Jump to Default Topic
## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |78.0.3904.108|

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
