### ISSUE TITLE
Jump Points in Popover Component for CSS/Markup incorrect

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2808]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/popover.html#popover-position
![PopoverCSS](https://user-images.githubusercontent.com/50709197/70758925-582d0000-1cf9-11ea-9d27-4beca99bd975.png)

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Popover
Select CSS/Markup from across the top
Scroll down the page a bit
Click any link on the Navigation Bar on the right.

Jumps to top of page

## What is the expected result?

Jump to selected topic.
## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |78.0.3904.108|

**Comment by Adriverforlife** [comment]
Looks like all the links are set to jump to ID popover-{topic chosen} and the ID on each topic is just {topic chosen} without popover-. I imagine most of the other ones are identical to this.

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
