### ISSUE TITLE
Jump Points in Tooltip Component for CSS/Markup incorrect

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2809]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

https://next.clayui.com/docs/components/tooltip.html#tooltip-left
![TooltipCSS](https://user-images.githubusercontent.com/50709197/70759324-da69f400-1cfa-11ea-9435-b9389e2cf1bb.png)

## What are the steps to reproduce?
Go to the Docs for Clay v3.0.
Go to Components/Tooltip
Select CSS/Markup from across the top
Scroll down the page a bit
Click any link on the Navigation Bar on the right.

Jumps to top of page

## What is the expected result?

Jump to selected topic.
## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |
| React |         |
| Chrome |78.0.3904.108|

**Comment by matuzalemsteles** [comment]
Hey @Adriverforlife, Thanks for reporting this. I will close this issue and sort it out by #2814, many issues have been created with the same related issue.
