### ISSUE TITLE
Color Picker/CSS Markup color palette doesn't change color when pick

### ISSUE THREAD

**Issue by calvinctvo** [liferay/clay#2810]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
1. Navigate to Components > Color Picker
2. click on CSS/Markup tab
3. Scroll down to Example
4. Pick a different color
## What is the expected result?
The color user picked should change, but it stays the same as sky blue
## Environment

| Tech  | Version |
| Mobile | Iphone X/XS |
| Clay  | v3.0.0  |
| FF |    latest     |

**Comment by matuzalemsteles** [comment]
hey @calvinctvo this is expected, CSS has no interaction like the components. I'm closing this if something related comes up, feel free to open again.
