### ISSUE TITLE
Dropdown Menu: Checkbox and Radio hover interaction styles inherited

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2811]
## What are the steps to reproduce?

1. Go to [Clay Storybook](https://storybook.clayui.com/)
2. Open ClayDropdown menu item
3. Select Checkbox or Radio 
4. Click "Click me" button

## Current behavior

![checkbox-hover](https://user-images.githubusercontent.com/21216422/70778205-07adb500-1d82-11ea-9b46-b6d01df94b28.gif)

## What is the expected result?
Dropdown item hover or selected interaction styles mustn't be inherited to check boxes and radio buttons

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0  |

**Comment by matuzalemsteles** [comment]
@pat270 Are we probably missing something with markup on components?

**Comment by drakonux** [comment]
Just one more thing. I reported this as a bug but this ticket is an update caused by a review we did due to [LEXI-661](https://issues.liferay.com/browse/LEXI-661) and Lexicon has to change the documentation about this too. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pat270** [comment]
@matuzalemsteles this is an update to the design, I'll update in Clay CSS. It will probably require some markup change to the clay component.

**Comment by pat270** [comment]
@matuzalemsteles Not sure if Clay Dropdown can do this already, the only thing that needs to change is `dropdown-item` needs to to be `dropdown-section` for checkbox/radios. See https://github.com/liferay/clay/pull/2861.

**Comment by matuzalemsteles** [comment]
Thanks @pat270

**Comment by drakonux** [comment]
Hey @pat270 @matuzalemsteles any update with this issue? is it done?

**Comment by matuzalemsteles** [comment]
hey @drakonux, I think we ended up missing this on the track for component corrections, sorry about that. I'll take care of that today.

**Comment by drakonux** [comment]
Thanks @matuzalemsteles
