### ISSUE TITLE
Some documents have wrong ToC jump

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2814]
Many of our documents do not have the correct ToC jump.

Related Issues:

- ~~Jump Points in Tooltip Component for CSS/Markup incorrect #2809~~ (#2878)
- ~~Jump Points in Popover Component for CSS/Markup incorrect #2808~~ (#2878)
- ~~Jump Point in Modal Component for CSS/Markup incorrect #2807~~ (#2878)
- ~~Jump Point in Component/List for CSS/Markup incorrect #2804~~ (#2878)
- ~~Jump Points In Components/Labels/CSS Incorrect #2803~~ (#2878)
- ~~Jump Point in Drop Down Component for CSS/Markup incorrect #2799~~ (#2878)
- Jump Points on Right Nav Bad Don't Exist in Documentation #2797
- ~~Incorrect Jump Points on Migration Page #2794~~ (#2878)
- ~~Search Link on Components/Management Toolbar in CSS unresponsive #2806~~ (#2878)
- ~~Groups Link on Components/Forms/Input in CSS unresponsive #2801~~ (#2878)
- ~~Radios Button not formatted correctly/not working on Checkbox #2800~~ (#2878)
- ~~Sub Navigation Bar link doesn't bring user to the actual subtitle they click on #2788~~ (#2878)

**Comment by eduardoallegrini** [comment]
I would add these
https://github.com/liferay/clay/issues/2210
https://github.com/liferay/clay/issues/2654
