### ISSUE TITLE
ClayManagementToolbar change-view-type button wrong size

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2819]
During the investigation of this ticket https://issues.liferay.com/browse/LPS-104915

In the management-toolbar https://storybook.clayui.com/?path=/story/components-claymanagementtoolbar--w-low-level

I noticed that the bug is caused by the `.dropdown` element that is placed between the `.nav-item` and the `.btn`
![image](https://user-images.githubusercontent.com/46778114/71168118-5497fc80-2256-11ea-8583-34fd628a1d2d.png)

The solution would be to move the `.dropdown` class to the parent element. (the `.nav-item`)

In the Portal the `.dropdown` class has being used twice and one of those is already in the right place
![image](https://user-images.githubusercontent.com/46778114/71165800-c588e580-2251-11ea-865b-8e1a31d22c39.png)

Another issue I found is the double focus/active effect
![image](https://user-images.githubusercontent.com/46778114/71167934-f539ec80-2255-11ea-9417-18c8abe5e238.png)

This can be solved changing the `.btn-unstyled` class into `.btn-link` but it will generate some color and size variation to some elements

Here's a code example of this topic https://codepen.io/eduardoallegrini/pen/VwYpZwe?editors=1000

/cc @marcoscv-work @pat270 @carloslancha @drakonux

**Comment by bryceosterhaus** [comment]
fixed https://github.com/liferay/clay/pull/2834
