### ISSUE TITLE
Vertical Navigation: remove Select behavior

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2821]
## Context

Reviewing [LEXI-688](https://issues.liferay.com/browse/LEXI-688) we found that in mobile version the Vertical Navigation component changes to a [dropdown button](https://liferay.design/lexicon/core-components/buttons/) but it behaves as it were a [Selector](https://liferay.design/lexicon/core-components/forms/selector/). 

![image](https://user-images.githubusercontent.com/21216422/71156790-f90f4400-2240-11ea-9f90-b1e0012b62f3.png)
_The dropdown shows the "five" item selected_

## What is your proposal?

The vertical navigation in mobile version should not show the current level of the navigation. It [should not behave like a Select](https://issues.liferay.com/browse/LEXI-773) component, it's just a button that allow users to toggle the menu. 

Thus, we should not add that Select feature to this component and we should allow to customize the text shown.

## Why would adopting this proposal be beneficial?

Talking with @marcoscv-work makes more sense to make this change for the sake of accessibility.   

## Concerns

Even more, the dropdown button should be customizable by product teams to use it with an icon, icon + caret, icon + text, text + caret or just with text (the most known examples are a menu button using the hamburger icon or just the word "menu")

**Comment by pat270** [comment]
@drakonux does the design need to change from the screenshot? Or you're just looking to swap out Five with an icon or other text?

**Comment by drakonux** [comment]
Hey, @pat270 yes, the screenshot is the behavior we already have and I would like to change it. 

I'm looking to swap out "five" (item selected) with a persistent text defined by the developer/designer ("Menu" by default)

Our direction should be to provide flexibility with the dropdown button (text, icon + text, etc) and let designers decide what they want in each scenario.

**Comment by matuzalemsteles** [comment]
I already made a release of this package that contains the changes from #3639 to resolve this, but it has not yet been to the Portal, I will wait for the launch of 7.3, I'm tracking this.

**Comment by victorvalle** [comment]
Where can I see this implemented? I've tried storybook and clay 3.x but I don't see it.

Thanks!

**Comment by kresimir-coko** [comment]
@victorvalle You need to simulate a phone in the dev tools on storybook to see it
![image](https://user-images.githubusercontent.com/24564752/92458363-90e50180-f1c5-11ea-95b4-3a054205068a.png)
