### ISSUE TITLE
Vertical Navigation: New variant "with Decorator"

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2822]
## What is your proposal?

A new variant for [Vertical Navigation](https://clayui.com/docs/components/navigation/vertical-navigation.html): "Vertical Navigation with Decorator". 

![Vertical Navigation with Decorator](https://user-images.githubusercontent.com/21216422/71244641-4825a980-2313-11ea-95e1-66120be5d44d.png)

## Context
 
We have studied the proposal requested from team-app-builder: [LEXI-688](https://issues.liferay.com/browse/LEXI-688) 

## Demands

This proposal uses the change proposed in #2821  

## Resources 

[Figma file](https://www.figma.com/file/jS6ag5L452ECU7JG8Lj8EA/lexi-688-vertical-navigation-proposal?node-id=0%3A1)
[Definition document](https://docs.google.com/document/d/141prJRHVXVVTNJSLVsGdPZYPtTSUd47T1um3ApRU6jQ/edit?usp=sharing)

## Why would adopting this proposal be beneficial?

About features, there is no difference with the Vertical Navigation component we already have. However, this option adds a different visual aspect that could be a plus for the visual identity of our product range in the company.

**Comment by pat270** [comment]
@drakonux does this need to go in 2.x?

**Comment by drakonux** [comment]
Sorry, 🙏I forgot to specify that. This is just for 3.x

**Comment by pat270** [comment]
@drakonux do the decorations still show in small screens? Don't mind the colors this is just a test.
<img width="374" alt="menubar-decorated-small" src="https://user-images.githubusercontent.com/788266/72394572-95ffb880-36eb-11ea-9129-936b71b23c18.png">

**Comment by drakonux** [comment]
Hey @pat270 

For small screens, in the [definition document ](https://docs.google.com/document/d/141prJRHVXVVTNJSLVsGdPZYPtTSUd47T1um3ApRU6jQ/edit?usp=sharing)we wrote: "_It behaves and looks exactly in the same way as the mobile version for the Vertical Navigation component_". 

What do you think? Should we keep the same design in the reduced version??

**Comment by pat270** [comment]
Thanks @drakonux, I missed the resources section for some reason.

**Comment by drakonux** [comment]
Thanks @pat270 we decided to not include a different design for mobile version to not add visual noise. So for now it's ok to keep that decision.  But I always open to suggestions, so don't hesitate to suggest and we can discuss it.

**Comment by victorvalle** [comment]
Where can I see this implemented? I've tried Clay and Storybook but couldn't find it

**Comment by matuzalemsteles** [comment]
@victorvalle I think it was lost during the implementation in CSS, I think it was only implemented in CSS, so we still need to update the component but it is already available with Markup/CSS. I will reopen, we work on it.
