### ISSUE TITLE
Multiple broken links found on clayui.com

### ISSUE THREAD

**Issue by john-co** [liferay/clay#2837]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide?
1. Navigate to https://clayui.com/docs/components/icon.html
2. Click on:
![screenshot_6](https://user-images.githubusercontent.com/35235266/72010046-fda99580-320b-11ea-82c2-5ee016632bc3.png)

- Page navigates to:
![Selection_061](https://user-images.githubusercontent.com/35235266/72010198-46614e80-320c-11ea-89f7-2c8966be34ee.png)

## What are the steps to reproduce?
Verify broken links, documented in [ClayUI.com Broken Links List](https://docs.google.com/spreadsheets/d/1upQV01S9YEOjXXeFAnEIZmnpoTncBLalZcfsMQ7WecU/edit#gid=0)
## What is the expected result?
All links are not broken

## Environment
http://clayui.com

**Comment by plhnk** [comment]
hey @john-co do you mind to make the gdoc open for anyone to edit? I found a couple others :)

**Comment by john-co** [comment]
Hi @plhnk, of course! permission granted. :)
