### ISSUE TITLE
Clay components for Vue.js

### ISSUE THREAD

**Issue by bicienzu** [liferay/clay#2853]
Are you going to develop the same react components for other frameworks such as  Vue.js?

**Comment by matuzalemsteles** [comment]
Hey @bicienzu we have no plans at this time to develop Clay components to other frameworks. We have some plans to provide the components in Clay for web components, in theory you could use it in Vue, Angular... but this is still under research.

cc @jbalsas

**Comment by jbalsas** [comment]
Hey @bicienzu, as @matuzalemsteles mentioned, we don't have plans to develop the components in other framework than React.

As it's stated in our [philosophy](https://clayui.com/docs/foundations/composing.html), we're structuring Clay as a multilayered API:

> We are delivering Clay as a Multi-Layered API library: low-level, high-level and pure html(@clayui/css). 

That basically means that you can just take the markup and build your own Vue components to output it and use `@clayui/css` to give them styling.

/cc @bryceosterhaus, in case you want to add anything :)

**Comment by jbalsas** [comment]
Closing for now as we won't be implementing this in the near-future.

@bicienzu, feel free to reach out if you attempt this and run into any issues! We'll be glad to assist you! :)
