### ISSUE TITLE
Icons Page: Icons first 

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2854]
<img width="1496" alt="Screenshot 2020-01-15 at 15 22 47" src="https://user-images.githubusercontent.com/21216422/72441469-0b7e8e00-37ab-11ea-9108-28fb7b176dfd.png">

## What are the steps to reproduce?
1. Go to [Clayui.com](https://clayui.com/)
2. Select Components
3. Select [Icon](https://clayui.com/docs/components/icon.html)

## What is the expected result?
I would like to see the icons Clay has at first sight. They are hidden! 

Yes, ClayIcon uses CSS class. They are in the CSS tab. However, I think it would be better to not organize the Icon page formally, as Clay does with all the pages. 

_For me, it's like going to buy tomatoes in the supermarket and look for them in the Vegetable section but  they are not placed there!! because reviewing the nature of tomatoes. They are fruits._ 

ps. Please don't take so seriously this ticket. I'm a grumpy old man :) It's ok as it's currently done.

**Comment by bryceosterhaus** [comment]
Great point, I totally agree. Thanks for creating this!

**Comment by bryceosterhaus** [comment]
Should be fixed by https://github.com/liferay/clay/pull/2892 and currently seen on clayui.com

Let me know if this doesn't meet your expectations, @drakonux.
