### ISSUE TITLE
Same size for headings in "3.x" as in "2.x"

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#2864]
In 3.x we need the same size headers as in 2.x.

![image](https://user-images.githubusercontent.com/7963804/72611397-478c2d00-392a-11ea-888e-b8319dee20df.png)

Portal is not yet ready for the resize in headers that we want, so we will apply it in the future.

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.X  |

**Comment by pat270** [comment]
@marcoscv-work I thought headers were supposed to match Bootstrap sizes a while ago, but since it would break layouts in 2.x we decided only to put it in 3.x. https://issues.liferay.com/browse/LPS-91488

**Comment by jbalsas** [comment]
Yeah, if we want to move to `3.x` in DXP so we can stop backporting everything to `2.x`, we need this reverted because unfortunately we haven't fixed it on Portal side yet and the impact is way too big to let it go :(
