### ISSUE TITLE
Paste Sample Code Feature

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2867]
Based on https://github.com/liferay/clay/issues/2843#issuecomment-574905300:

> My test markup is included at the bottom. You can copy paste it into clayui.com.

It might be a good idea to have some type of "Sandbox" page or feature where we could simply do what @pat270 suggests. That is:
- Go to a page
- A "Paste your HTML Sample" textarea appears
- When pasted, the HTML is injected somewhere to validate the result

Just an idea, feel free to discard it 😉

**Comment by pat270** [comment]
@jbalsas sounds useful, we could toss in some localstorage to make it persist.

**Comment by kresimir-coko** [comment]
Sounds like something that would provide value to the users.

**Comment by matuzalemsteles** [comment]
We had a similar page in v2 but it was for the components, we can try to do the same here but only for the HTML since for the components in React it doesn't make much sense to fight with Codesandbox 😁.

http://v2.clayui.com/try.html

**Comment by jbalsas** [comment]
Hahaha... I forgot we had this!

Yeah, just a simple paste html here and see the result. For the rest we already have storybook and codesandbox and other industry-standard tools, no need for custom development

**Comment by matuzalemsteles** [comment]
Yeah, this page is secret 😆

**Comment by bryceosterhaus** [comment]
Sounds like a great idea to me
