### ISSUE TITLE
Clay service accounts

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#2868]
The intention of this issue is to evaluate the accounts we have in some services that are used for the benefit of Clay and to identify who the owners are so that we can give access to the rest of the team and evaluate the costs.

| Company        | Services           | Free Tier  |
| ------------- |:-------------:| -----:|
| Netlify | deploy previews, deploy clayui.com, storybook | Starter / 300 minutes for build |
| Coveralls | Tests coverage |   Open Source |
| Codesandbox | CI packages | Free so far |
| Travis | CI | ? |

## Netlify

The main reason for this is Netlify, basically the account that hosts Clay's sites, they were active in my personal account on Netlify but just with these projects, a few months ago Netlify changed the way they were charged, started charging for build time . The Starter plan contains only 300 minutes for the build per month, if that amount is exceeded $7 will be charged for another 500 minutes.

<img width="930" alt="Screen Shot 2020-01-21 at 11 46 24" src="https://user-images.githubusercontent.com/13750819/72814355-af50b980-3c43-11ea-88b7-4f9426b82132.png">

We use the Netlify build a lot, we have already reached 120 minutes in just one day, due to our deploy previews that are run every time in any PR, there is no configuration to run the deploy preview only in PRs that modify the file. We are currently taking an average of 500 minutes per month and are being charged an additional $7. The question here is to evaluate how we can move these services to a Liferay account or use the Netlify Teams feature, so it won't get stuck in my account but it will be worth $45/month.

Thoughts?

cc @jbalsas @bryceosterhaus @julien

**Comment by bryceosterhaus** [comment]
@matuzalemsteles yeah you definitely shouldn't be the one with the bill lol. I do think the auto builds and previews we have on every PR are incredibly useful. We could also consider using `now` from zeit, but I'm not entirely sure what that pricing would look like. Regardless of service, I think we need this sort of functionality though.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, as I told @matuzalemsteles, I can take care of the billing. What I need from you is a definite and clear answer on wether this is useful or not and worth paying for so I can figure out what we need to do to get approval :)

**Comment by matuzalemsteles** [comment]
I also agree that the deploy preview is very important for us. It is much better to look at the preview than having to test it locally.

I thought about zeit too, but I was looking at their prices and we would be practically obliged to use the Pro plan which costs $20 but the build time (600 minutes) is very close to the Netlify Starter plan and also the additional time build costs $10 for 600 minutes.

**Comment by bryceosterhaus** [comment]
> a definite and clear answer on wether this is useful or not and worth paying for 

Yes, most definitely. We can also do some work in making sure certain build steps are worth it for CI. But without a doubt I would say its been worth it for what we do have.

**Comment by jbalsas** [comment]
Filed an LRIT ticket asking IT to provision an account... will keep you updated! 🤞

**Comment by bryceosterhaus** [comment]
@jbalsas any update on this? Not a huge rush, but I was hoping to configure the clayui site a bit so that it doesn't build from upstream and would only build based on the newest released version of the site.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus! I was talking to @matuzalemsteles about this the other day. We hit a bit of a block because we don't have a proper engineering operations budget. Jorge was going to look into it but he's on PTO this week, so we'll need to wait at least for a week until I can provide an update.

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus this would be cool, I had this in mind but I didn't find anything like that to configure, I can only change the branch but we don't have a `master-stable` anymore... Did you see anything about it?

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I havent actually looked into it yet, but I'm sure we could configure a GH action to deploy on certain tag names or something. Once we get the service accounts I will dig into it more.

**Comment by bryceosterhaus** [comment]
@jbalsas any update on this? I was waiting on this before I work on some versioning and release process stuff for clayui.com

**Comment by jbalsas** [comment]
We got approval from Legal and Security... waiting for IT to make it final. I'll ping them again today.

**Comment by bryceosterhaus** [comment]
Got access to netlify account, in the process of migrating all sites and builds over

**Comment by bryceosterhaus** [comment]
Got netlify set up with the liferay account now:

|   Site  |   branch |
|-------|---------|
| clayui.com | stable |
| storybook.clayui.com | stable |
| next.clayui.com | master |
| next.storybook.clayui.com (still waiting on dns) | master |

And then all PRs to both stable and master will generate previews

**Comment by bryceosterhaus** [comment]
We no longer use travis and coveralls was migrated to GH actions. I think this issue is resolved. Feel free to re-open or comment if I missed something.
