### ISSUE TITLE
Modal's footer buttons with wrong position in IE11

### ISSUE THREAD

**Issue by marcosapmf** [liferay/clay#2873]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

The bug appears when the modal component is instanced with two footer buttons aligned to right in a Soy template. This only happens in IE11.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v2.18.1  |

**Comment by matuzalemsteles** [comment]
hey @pat270 could you help us with this? I'm thinking of not adding the `modal-item-first` and `modal-item-last` when there are no buttons for the respective places, solving this in the component, but it is strange to have to do this.

**Comment by pat270** [comment]
@matuzalemsteles I can't seem to duplicate this in Clay CSS on my IE11 VM. The way I'm writing the markup is:
```
<div class="modal-footer">
    <div class="modal-item-last">
        <button class="btn btn-primary" type="button">Button Primary</button>
        <button class="btn btn-secondary" type="button">Button Secondary</button>
    </div>
</div>
```

**Comment by matuzalemsteles** [comment]
Hmm, @pat270 maybe this just happens in a Modal with the size `sm`? this was the case with the Forms team, I will try to check again if there is no other CSS that is causing this.

**Comment by pat270** [comment]
@matuzalemsteles I'm not sure, I know we have conflicting CSS in Portal since we have old modal styles from the AUI days. It also could be my version of IE11 is too old (I've had issues with IE11 versions in the past).

**Comment by matuzalemsteles** [comment]
@pat270 i did some tests and this is only happening in 7.2, apparently i can't track any CSS code that is colliding with Clay's, there was only a Forms CSS fixing the size of the Modal but this was not causing it.

<img width="378" alt="Screen Shot 2020-01-28 at 14 44 28" src="https://user-images.githubusercontent.com/13750819/73290149-b1cf8800-41dc-11ea-9fdf-99599baada30.png">

**Comment by pat270** [comment]
@matuzalemsteles can you tell me how to get to that modal, I'll test also.

**Comment by matuzalemsteles** [comment]
@pat270 

1. Go to Forms
2. Create a new Form
3. Add a new language
4. Remove a language (The modal will appear)

**Comment by pat270** [comment]
@matuzalemsteles I see now. I think when I created this I assumed if there were no buttons in `modal-item-first` no markup would be output. I can make it work both ways if I just reverse the styles on `modal-footer`, `modal-item-first`, `modal-item-last`.

**Comment by matuzalemsteles** [comment]
@pat270 hmm, the strange thing is that it works well on the master. I'm asking myself if it was an update we missed.

**Comment by pat270** [comment]
@matuzalemsteles I can reproduce it in Clay CSS 3.x when I use:
```
<div class="modal-footer">
    <div class="modal-item-first"></div>
    <div class="modal-item-last">
        <button class="btn btn-primary" type="button">Button Primary</button>
        <button class="btn btn-secondary" type="button">Button Secondary</button>
    </div>
</div>
```

**Comment by matuzalemsteles** [comment]
Oh no 😱
