### ISSUE TITLE
ClayModal Body should accept custom className or a scroller

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#2887]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
There is no way to provide custom classes to the <ClayModal.Body> component, i.e: 
`<ClayModal.Body className="inline-scroller">` is ignored

## What is the expected result?
The best solution would be that ClayModal shows a scroll when the content in it's body is too large. This is not happening now, and a possible workaround could be to add a custom className to the modal body

**Comment by marcoscv-work** [comment]
Inline scroller is here:
http://pat270.github.io/lexicon/v2.16.2/content/modals/#inline-scroller

We have talked with @drakonux and maybe the modal height behavior in `inline-scroller` is not well defined

**Comment by bryceosterhaus** [comment]
I'm gonna add a `scrollable` prop to Modal.Body to add this class
