### ISSUE TITLE
ClayPaginationBarWithBasicItems doesn't actually implement initialSelectedDelta

### ISSUE THREAD

**Issue by wincent** [liferay/clay#2888]
`<ClayPaginationBarWithBasicItems />` [claims](https://github.com/liferay/clay/blob/f53e37b1d0776821c1a35d93049cb3b63306bfe4/packages/clay-pagination-bar/src/PaginationBarWithBasicItems.tsx#L99) to support a `initialSelectedDelta` prop, but if you try using it you'll see this in the console:

```
Warning: React does not recognize the `initialSelectedDelta` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialselecteddelta` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in div (created by ForwardRef)
          in ForwardRef (created by ClayPaginationBarWithBasicItems)
          in ClayPaginationBarWithBasicItems (created by TableWithPagination)
```

Grepping to see where `initialSelectedDelta` is used in Clay, it turns up no results apart from the interface declaration I linked to at the top. Looks like it was removed in fbb914dc2263f0dd9faeee39675d1ea395c765a6.

Noticed this while running `app-builder/app-builder-web` tests in liferay-portal, because they invoke a component that [tries to use this prop](https://github.com/liferay/liferay-portal/blob/d0fd9753a784b6858e59f2c2f059b9a480bb79c4/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/table/TableWithPagination.es.js#L39). (It also uses another non-existent prop, `initialActivePage`, renamed to `activePage` in fbb914dc2263f0dd9faeee39675d1ea395c765a6.)

**Comment by bryceosterhaus** [comment]
Oh interesting, looks like we forgot to remove it when we made it more controlled. I think you can achieve the same functionality as just setting the `activeDelta` prop.

I'm thinking this component used a previous beta version and never updated. I will go ahead and remove the unused prop from the interface.

**Comment by brunofarache** [comment]
@wincent thank you, I will remove it.

we are not using `initialActivePage` in master:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/table/TableWithPagination.es.js#L35

you were referencing some old commit.
