### ISSUE TITLE
[New] UpperToolbar Component

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2895]
This is a formal request to implement Lexicon's [UpperToolbar](https://liferay.design/lexicon/core-components/toolbars/toolbar-upper/) as a Clay Component.

> Upper toolbar is a guidance pattern to allow designers create their own toolbars for edition with preview pages

![ToolbarUpper](https://user-images.githubusercontent.com/905006/73664413-a3331600-469f-11ea-91aa-ab531287dbe5.jpg)

#### References
- [Lexicon Definition](https://liferay.design/lexicon/core-components/toolbars/toolbar-upper/)
- [app-builder-web::UpperToolbar](https://github.com/liferay/liferay-portal/blob/master/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/upper-toolbar/UpperToolbar.es.js)
- [layout-content-page-editor-web::Toolbar](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Toolbar.js)

/cc @bryceosterhaus, @kresimir-coko, feel free to ping @drakonux for any clarification

**Comment by bryceosterhaus** [comment]
published at https://www.npmjs.com/package/@clayui/upper-toolbar
