### ISSUE TITLE
[New] InputMoveBoxes Component

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#2896]
This is a formal request to **implement [Input Move Boxes](https://liferay.design/lexicon/core-components/forms/radio-check-toggle/#toggle)** (for a lack of a better name) as a Clay Component.

We currently lack documentation proper Lexicon definition and documentation for this component, so this task should start by involving @drakonux and @laugardie in analysis and definition tasks.

<img width="584" alt="Screen Shot 2020-02-03 at 17 01 44" src="https://user-images.githubusercontent.com/905006/73668909-e2189a00-46a6-11ea-87fc-d0225ea7b4ce.png">

#### References
- [Lexicon Definition](https://issues.liferay.com/browse/LEXI-804)
- [AUI Component](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/input_move_boxes.js)
- [JSP Tag](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/input_move_boxes/page.jsp)
- [Usages](https://github.com/liferay/liferay-portal/search?l=Java+Server+Pages&q=liferay-ui%3Ainput-move-boxes)

/cc @bryceosterhaus, @kresimir-coko, feel free to ping @drakonux for any clarification

**Comment by jbalsas** [comment]
I've created the LEXI request so we can have definition and start working on this once that's done. See https://issues.liferay.com/browse/LEXI-804 for more details.

**Comment by kresimir-coko** [comment]
I'll take this one!
