### ISSUE TITLE
Include this new icon: books

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#2905]
Please include this new icon. Find the .SVG in [LEXI-801](https://issues.liferay.com/browse/LEXI-801)

![books 1](https://user-images.githubusercontent.com/21216422/73927662-10c68880-48d2-11ea-9020-e4be1cdcec3f.png)

Thanks!

**Comment by victorvalle** [comment]
Hi guys! when is the next release of clay so we can use it DXP?

**Comment by bryceosterhaus** [comment]
@victorvalle I was planning to make a release tomorrow for clay components. @pat270 do we typically also just release `@clayui/css` with each component release as well?

**Comment by pat270** [comment]
@bryceosterhaus Yes I think that's been the trend.

/cc @matuzalemsteles

**Comment by matuzalemsteles** [comment]
Yes, that's correct. @jbalsas is the master already using the `@clayui/css` package?

**Comment by jbalsas** [comment]
I think so, yes!!

**Comment by bryceosterhaus** [comment]
@victorvalle should be available in `@clayui/css@3.6.0`
