### ISSUE TITLE
Is not possible to define onSubmit on ClayDropdownSearch

### ISSUE THREAD

**Issue by fcodias** [liferay/clay#2910]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
No =(

## What are the steps to reproduce?
onSubmit property is not defined, so, when the user press enter key, submits the form causing a reload and there isn’t an API to customize it.

## What is the expected result?
Will be great if we have an API to define it.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by bryceosterhaus** [comment]
@fcodias just released in `@clayui/drop-down@3.2.0`
