### ISSUE TITLE
ClayVerticalNav low-level composition example is missing on storybook

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2938]
-   [✅] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

An example showing how to use ClayVerticalNav with .Item and .Link composition is missing on our Storybook.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | latest(v 3.0.6) |
| React |         |

**Comment by bryceosterhaus** [comment]
@diegonvs did you have a specific example you needed the low-level API for? I don't think we ever exposed a lower level than the storybook. Is there a circumstance that the existing `ClayVerticalNav` component doesn't cover?

**Comment by kresimir-coko** [comment]
Hey @diegonvs what's the state on this? Can you clarify by answering what @bryceosterhaus asked above?
