### ISSUE TITLE
Clay paginations buttons break inside forms

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#2945]
Sometimes we need to wrap a table inside a form so we can select some items ticking a checkbox in the row and submitting the form.

The problem is that buttons in paginations don't have `type="button"` as attribute, so they submit the form when clicked.

We can't use an `event.preventDefault()` inside a callback because we don't receive an event as parameter: 
```
<ClayPaginationBarWithBasicItems
	{...otherProps}
	onDeltaChange={deltaVal => {
		setPageNumber(1);
		setDelta(deltaVal);
	}}
	onPageChange={setPageNumber}
/>
```

**Comment by bryceosterhaus** [comment]
@FabioDiegoMastrorilli thanks for filing this, I'll add those button types and should be able to have this released next week.

For a work around until then, are you able to use `preventDefault` on the form's `onSubmit` event?

**Comment by bryceosterhaus** [comment]
@FabioDiegoMastrorilli check out this test and let me know if this is what you would expect.

https://github.com/liferay/clay/pull/2946/files#diff-c3787f5289231be9569122215cf5ba56R115

**Comment by FabioDiegoMastrorilli** [comment]
Hi @bryceosterhaus , the pagination is included in a component which we use often inside a form rendered server side.
`e.preventDefault()` actually works but we can't replicate it in all the JSPs that use our component.

**Comment by bryceosterhaus** [comment]
@FabioDiegoMastrorilli  released at https://www.npmjs.com/package/@clayui/pagination/v/3.1.0
