### ISSUE TITLE
Clay CSS add variable $component-focus-inset-box-shadow for inner focus styles

### ISSUE THREAD

**Issue by pat270** [liferay/clay#2954]
@drakonux says that is interesting to have [inner focus styles] to fix possible [overflow] issues, and they, as a designer, are not using it because they are not aware that they can use it.

![inner-focus](https://user-images.githubusercontent.com/788266/75377963-aaf16f00-5887-11ea-9455-fa11655e0849.png)

**Comment by marcoscv-work** [comment]
That's great!

@pat270 do you think it could be interesting to have a helper class to overwrite the focus? For example: `.inner.-focus` wich is added to a button or link and it changes its focus

**Comment by pat270** [comment]
@marcoscv-work we can add it. I think it will be called `.c-focus-inset`. Do you have some examples just for reference?

**Comment by pat270** [comment]
@marcoscv-work I added the utility `.c-focus-inset` to the pr. I would say use it sparingly. It doesn't work on really specific selectors like `.nav-tab .nav-link`. 

I think we should change focus styles on `nav-tab` and `nav-underline` to inset because I'm seeing them stuffed inside sidebars.
