### ISSUE TITLE
Add CI analysis for package size

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#2965]
Stems from https://github.com/liferay/clay/issues/2918

**Comment by bryceosterhaus** [comment]
Having some issues figuring out the best means for accomplishing this.

Currently the main roadblock is permissions and getting the github actions bot to comment on PRs that come from forked repositories. This issues primarily arises due to the limitations of the token generated for gh actions from forks. Currently they only receive a "read" token and are unable to create comments on the PR with that token.

I thought one solution would be to have two different workflows, one that builds the stats table on every PR and uploads the result as an artifact and then a [scheduled workflow](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule) that runs every 5 minutes and downloads the artifacts and comments the results on each PR. However, this ended up not working because downloading artifacts across different runs and workflows isn't possible unless we want to build out our own specific action for this repo.

Any thoughts on a way to get around this or other options available? I've been hitting my head against this one and just can't seem to come to a solid conclusion without having to get too nitty gritty.

**Comment by wincent** [comment]
> Any thoughts on a way to get around this or other options available? I've been hitting my head against this one and just can't seem to come to a solid conclusion without having to get too nitty gritty.

Can we just treat this like any other binary ("yes"/"no") CI job? In other words, forget about adding comments. Run the size comparison, and if it goes up by more than some predefined threshold (which could be as little as 0, or something else like 1%, 5% etc) you "fail" the build and dump an ASCII table of the results into the console output.

We can still merge at our discretion if the size-check action fails, but at least it will be an explicit decision to increase the package size.

I like to start simple, but there is nothing stopping us from making this more sophisticated in the future (eg. defining per-package thresholds, blacklists, whitelists etc) as the need for it becomes clear.

**Comment by bryceosterhaus** [comment]
>  Run the size comparison, and if it goes up by more than some predefined threshold (which could be as little as 0, or something else like 1%, 5% etc) you "fail" the build and dump an ASCII table of the results into the console output.

This is a great idea and token issues shouldnt be an issue. 🥇🥇🥇
