### ISSUE TITLE
 Implement internationalization with "moment.js" receiving only the locale as property in ClayDatePicker

### ISSUE THREAD

**Issue by albinojunior** [liferay/clay#2972]
## What is your proposal?
Implement internationalization with "moment.js" receiving only the locale as property in ClayDatePicker

As suggestion:

Component API: 

```javascript
<ClayDatePicker locale="en" ... />
```

By default ClayDatePicker get dateFormat, firstDayOfWeek, months, timeFormat and weekdaysShort:

```javascript
import moment from "moment/min/moment-with-locales"

const localeData = moment.localeData(locale);

//when not providing a dateFormat get a "L" format by locale
const dateFormat = localeData.longDateFormat("L") // MM/DD/YYYY
const firstDayOfWeek = localeData.firstDayOfWeek() // 0
const months = localeData.months() // ["January", "February", ...]
//when not providing a timeFormat get a "LT" format by locale
const timeFormat = localeData.longDateFormat("LT") // HH:mm a
const weekdaysShort = localeData.weekdaysShort() // ["Sun", "Mon", "Tue", ... ]

``` 

## Why would adopting this proposal be beneficial?
The solution prevents the use of a different version of the moment in user module and the need to retrieve several times: the list of months, days of the week and the starting day of the week for each location. Knowing that the moment library (a dependency on ClayDatePicker) implements a solution that provides this data and only requires locale as a parameter.

**Comment by bryceosterhaus** [comment]
Hey @albinojunior, can you check out this fix and see if it would be sufficient for you? The goal for this is so that you don't have to import and use moment yourself, but you can just utilize the helper function to get the props needed. https://deploy-preview-3043--storybook-clayui.netlify.com/?path=/story/components-claydatepicker--w-getlocaleprops

Making this into a helper function rather than integrating to the API directly gives us more flexibility in how we might upgrade this in the future and so that we don't have to get super tied to moment.js

**Comment by bryceosterhaus** [comment]
Hey @albinojunior, do you use this new helper at all? We are thinking of actually removing it in https://github.com/liferay/clay/pull/3306 since we want to get rid of  `moment.js` since its such a large dependency.

**Comment by albinojunior** [comment]
Hi @bryceosterhaus, my team and I decided to use another solution to our problem even before this helper was implemented. I just proposed this implementation to help others who might have the same problem. So, I think you can procede with removing ```moment.js```, we are not using the new helper.

Thanks for asking!

**Comment by bryceosterhaus** [comment]
@albinojunior Right on, thanks for the feedback!
