### ISSUE TITLE
Can outline labels be change into bold labels?

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#2975]
## What is your question?
I am working on [Lexi-786](https://issues.liferay.com/browse/LEXI-786) to differentiate statuses within the same screen. I would like to know if Clay labels can be modified from outline labels to bold labels as in the image below.

<img width="104" alt="Screenshot 2020-03-04 at 12 17 50" src="https://user-images.githubusercontent.com/56547676/75875148-734c6f00-5e13-11ea-9ffb-0031715cfee1.png">
Does the component already allow this?

**Comment by pat270** [comment]
There is no modifier to change outline to bold. I can add a modifier like `label-inverse`, `label-alt`, or a better name. Wish I could go back in time so I could use `label-outline`.

**Comment by laugardie** [comment]
Yes, it will be great if you can add a modifier to customize the text color, the background color, and the border to change the label into a bold one. :)
