### ISSUE TITLE
ClayLabel don't have an option for truncating texts inside

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2977]
-   [✅] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?

There isn't a way to truncate the text inside the ClayLabel component just using a property like `trucated` on 2.x(https://github.com/liferay/clay/pull/2858)

## What is the expected result?

An option for truncating text inside ClayLabel without passing `text-truncate-inline` to the component. Like:

```jsx
<ClayLabel truncate>{'my lovely label'}</ClayLabel>
```

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.1.0 |
| React | Doesn't matter |

**Comment by kresimir-coko** [comment]
Fixed in [feat(@clayui/label): add prop for inner element attributes #3060
](https://github.com/liferay/clay/pull/3060)
