### ISSUE TITLE
Why checkboxes and radio buttons are 17x17px?

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3026]
## Why checkboxes and radio buttons are 17x17px?
![image](https://user-images.githubusercontent.com/21216422/76991144-65d1d180-6949-11ea-9ddb-7a77d7c27721.png)

This is a friendly question. Reviewing the checkbox/radio button size in [Clay](https://clayui.com/docs/components/forms/checkbox.html) is 17px. In our [Foundations ](https://liferay.design/lexicon/foundations/grid/) page we encourage to use multiples of 8. 

So we need to know if there was a technical reason to do this because people can report it as a bug when maybe it's not.

**Comment by pat270** [comment]
@drakonux even numbered widths and heights made it difficult to center icons. I can revisit to see if this still is the case (I think it is).

**Comment by pat270** [comment]
ok nm what I said, the reason why it was 17px is because I was trying to get the measurements as close as possible to https://liferay.design/lexicon/core-components/forms/radio-check-toggle/#checkbox-group.  We can make it 18px if you want.

**Comment by drakonux** [comment]
> ...We can make it 18px if you want.
Well, I was thinking more on a 16px checkbox/radio to use a multiple of 8. 

 > made it difficult to center icons
We can create a new icon if it's needed and helps or update the current one. 

ps. I think years ago, Lexicon & Clay handled problems to align icons because of the way they are created (512x512px) I'm going to talk with the previous team to understand better that problem.

**Comment by pat270** [comment]
16px works too, I can update it. Don't worry about the icons.

**Comment by drakonux** [comment]
😍 Thanks @pat270 !!
