### ISSUE TITLE
@clayui/css Date Picker RTL icons are backwards

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3029]
Related to #2971, I noticed next month and previous month button icons are pointing the wrong direction.

<img width="276" alt="date-picker-icons" src="https://user-images.githubusercontent.com/788266/77021508-1b018b00-6944-11ea-980e-c0cb08e97e9d.png">

**Comment by jbalsas** [comment]
I'm closing this so we can discuss a more generic approach as part of [RTL Strategy](https://github.com/liferay/clay/issues/3073)
