### ISSUE TITLE
DatePicker: Add forwardRef to the input and add callbacks for change events for the year and maybe month

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#3047]
## What is your proposal?

The idea is to access the input of the DatePicker, apply masking cases, for example. We listen the navigation changes in the date picker:

- Change the year
- Navigate between months
- Change the month

**Comment by matuzalemsteles** [comment]
@bryceosterhaus what do you think? I can work on it. I'm going to use this to apply the changes to the DDM migration 😅.

**Comment by bryceosterhaus** [comment]
I think this makes sense, especially in the case where users might need to change something in their app in response to the non-selected values changing.
