### ISSUE TITLE
Getting Started Link is Broken

### ISSUE THREAD

**Issue by justingolden21** [liferay/clay#3051]
## The Problem

The "Getting Started" link in the README, the basic starting point for most people who arrive at this repository, is a link to a completly empty page.

It links to [the introduction page](https://next.clayui.com/docs/get-started/introduction.html) which is blank:

![image](https://user-images.githubusercontent.com/30274440/77384568-fa21a700-6d42-11ea-866c-2c1effdd97a6.png)

## Steps to Reproduce

Visit the README and click on "Getting Started"

## Expected Result

A useful introduction page with content, not an empty page. Perhaps one of these links would be better:

- https://next.clayui.com/docs/get-started/what-is-clay.html

- https://next.clayui.com/docs/get-started/how-to-use-clay.html

**Comment by bryceosterhaus** [comment]
@justingolden21 thanks for opening this issue! Should be updated now

**Comment by justingolden21** [comment]
No problem, thank you for fixing it so quickly.
