### ISSUE TITLE
Add parent pages for sidebar

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3056]
Currently on the sidebar, we don't have an overview page for each of the sections. I think it would probably be helpful to have short descriptive pages for each of these categories. This would also allow us to have better links, rather than having to go to a specific page right away. For example, if you want to link to the components as a whole, you would likely link straight to Alerts

![Screen Shot 2020-03-24 at 11 57 22 AM](https://user-images.githubusercontent.com/6843530/77465894-a0fb5700-6dc6-11ea-908c-7feab1382622.png)

**Comment by pat270** [comment]
I think this would fix https://github.com/liferay/clay/issues/2793.

**Comment by matuzalemsteles** [comment]
I support 😁, I had done this in the beginning. But they will remove 😞I had an idea at the beginning of using these pages of the session to try to "sell" Clay, explain how it works...

**Comment by kresimir-coko** [comment]
I did some digging around this issue and I couldn't wrap my head around it entirely. I'd like to tackle it but I need some information before I do that.

1. Is the behaviour expected to be the same as [Lexicon's](https://liferay.design/lexicon/foundations/) where the link to the parent page is the same that has the dropdown functionality (eg. clicking on  `Foundation` opens the parent page)?
2. The `order` keyword in Markdown didn't want to cooperate in any of the Markdown files that live in the `components` folder. In case the answer to the question above is negative, it means we want to have a separate page, like `components.md` to serve as the descriptive page of components, but I couldn't order it so it's the first one in the navigation under the `Components` tab
3. If the answer to the 1st question is positive, where is the code that builds the navigation contained? I tried scouring around our codebase but couldn't find it
4. Do these links need to lead to the newly created pages? 
![image](https://user-images.githubusercontent.com/24564752/78018765-bf290000-734e-11ea-99f1-e0ade165a4d7.png)

**Comment by matuzalemsteles** [comment]
hey @kresimir-coko  if I understood Bryce's idea, if we keep the same behavior that I had thinking at the beginning too, we will probably continue like this:

1. Yes, we will follow this behavior.
2. To create a section page we can use the `index.md` files, you can access them via `index.html`, they are already being created but the navigation menu is not linking to it. For example https://clayui.com/docs/components/index.html
3. If you are looking for the navigation menu it is at https://github.com/liferay/clay/tree/master/clayui.com/src/components/Sidebar.
4. Yeah, once we have those sessions, we should aim there.

**Comment by bryceosterhaus** [comment]
Totally agree to what @matuzalemsteles said.

Overall, the goal is have some landing pages for those tabs so that we don't throw people directly into a sub-category yet

**Comment by eduardoallegrini** [comment]
Are we sure we really need these overview pages?

The target of Clay is pretty much devs (Liferay's devs) and they are use to having the information they are looking for right away, so I think we should keep these content light and simple.

When I navigate the website I skip the main page and got directly to what I need using either the Clay website's search bar or the browser search function because it's faster (ctrl/cmd + f)

I would like to propose to change the homepage into a search oriented page (think about Google): logo + search bar + most useful content as small cards - but I think this is another issue :)

**Comment by bryceosterhaus** [comment]
@eduardoallegrini I think they are needed for introductory pages for new users or people who don't frequent clay often. I agree with you in that they need to be light and simple though. I think as long as we have a simple overview of that content, it will help people who havent used clay before.


>When I navigate the website I skip the main page and got directly to what I need using either the Clay website's search bar or the browser search function because it's faster (ctrl/cmd + f)

Yeah I think regular users will often go this route, so I wouldn't expect those users to make much use of the index pages.

**Comment by kresimir-coko** [comment]
What is the state of this issue @bryceosterhaus, should I pick it up again? I think I forgot about it while waiting for a conclusion.

**Comment by bryceosterhaus** [comment]
@kresimir-coko yeah feel free to pick this up again
