### ISSUE TITLE
Move component docs from clayui.com to their respective packages 

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3068]
Instead of having all of our component docs in the clayui.com directory, I think it would make more sense to co-locate the docs with each package. This way the docs get versioned in the same manner as the component itself. This also would provide a lower barrier of entry to updating the docs when we update components. And ideally this move would not change the site at all, but instead clayui.com would compile the docs from each package.

**Comment by jbalsas** [comment]
![hellyeah](https://user-images.githubusercontent.com/905006/77624561-4981f600-6f42-11ea-8402-1f00c5f20fae.gif)

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/clay/pull/3092#issuecomment-606451143

**Comment by pat270** [comment]
Since we are releasing each package individually, I was wondering how we were going to unify the docs to make it easy to consume by Portal users? I'm visioning having to comb through Portal's source to see what version of Clay Autocomplete it's using and matching it to the same Clay CSS version.

**Comment by bryceosterhaus** [comment]
@pat270 Ideally portal should be on the latest release of clay and whatever is latest on clayui.com. The primary goal initially is for the site not to contain docs for features that aren't released yet. As of now, we can't update the site without having it go live. Also by co-locating the docs, we can at least see the history of the docs in the same context of the history of the source code.
