### ISSUE TITLE
@clayui/css remove old jquery plugins

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3070]
Is it safe to remove the old clay-css jquery plugins from 3.x?

https://github.com/liferay/clay/blob/master/packages/clay-css/src/js/collapsible-search.js
https://github.com/liferay/clay/blob/master/packages/clay-css/src/js/nav-tabs-scroll-dropdown.js
https://github.com/liferay/clay/blob/master/packages/clay-css/src/js/side-navigation.js

**Comment by bryceosterhaus** [comment]
yeah I don't see why not, unless you are using them for the clay-css site or dependent on them in any way. We don't use them in any components

**Comment by jbalsas** [comment]
@markocikos, @carloslancha, can you confirm we got rid of usages for all these plugins?

**Comment by wincent** [comment]
At least for side-navigation, I can confirm we moved [*a copy of it* into `frontend-js-jquery-web`](https://github.com/liferay/liferay-portal/blob/e4a8566ba9add6f6093029581845d16c831b6934/modules/apps/frontend-js/frontend-js-jquery-web/src/main/resources/META-INF/resources/jquery/side_navigation.js) for use by clients, and we moved all internal issues to [the jQuery-less implementation](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/side_navigation.es.js).
