### ISSUE TITLE
Is there an easy way to find a list of releases for a Clay component?

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3118]
At the time of this issue, there are 500 releases ordered by date released. https://github.com/liferay/clay/tags also is ordered by release date and we have a tag for each component@version. It would be nice to have a curated list of releases by component if it doesn't exist already.

**Comment by bryceosterhaus** [comment]
Are you thinking like a list per-component? Each component has its own changelog, https://github.com/liferay/clay/blob/master/packages/clay-modal/CHANGELOG.md. Unless you are looking for something else

**Comment by pat270** [comment]
@bryceosterhaus yes that's kind of what I'm looking for. I want to be able to browse the source for a specific release. So for 3.4.0, it would be nice to have a link to https://github.com/liferay/clay/commit/7484d77a10f6c03b2359018bc3d95408456bfb04.

I also noticed that the links in the changelog aren't pointing to the right url.

> @clayui/modal: add low-level componenets for header (7b0074f)

links to https://github.com/liferay/clay/tree/master/packages/clay-modal/commit/7b0074f from the changelog.

**Comment by pat270** [comment]
One more thing, maybe we could update https://github.com/liferay/clay/blob/master/CHANGELOG.md to contain a link to each component's changelog and update `README.md` with a link to the changelog.

**Comment by bryceosterhaus** [comment]
@pat270 check out these changes and let me know what you think. https://github.com/liferay/clay/pull/3127
