### ISSUE TITLE
ClayPanel Header renderProps

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#3123]
## What is your proposal?

There are at least two specific cases where ClayPanel is being discarded to be used due to a limitation of the component to just add a title and not append more items to the Panel's header

Here is the examples: 

#### On App Builder:
![App Builder](https://user-images.githubusercontent.com/7663513/79128731-67d95580-7d7a-11ea-9129-72a7d90f5e64.png)

#### On DataEngine:
<img width="572" alt="Screen Shot 2020-04-13 at 11 32 21" src="https://user-images.githubusercontent.com/7663513/79128798-7b84bc00-7d7a-11ea-8bd4-4869fc6aff55.png">

I would suggest to add a property on ClayPanel component for using renderProps pattern as:

```tsx
<ClayPanel
    collapsible
    renderHeader={
        ({isExpanded}) =>
            (<> {Rule Name 1} <MyDropdown /> <ClayIcon symbol={isExpanded? "angle-down" ? "angle-up")}
        }
/>
    <MyContent />
</ClayPanel>
```

## Why would adopting this proposal be beneficial?
Allow people to have more flexibility on ClayPanel :)

## What are the alternatives to this proposal?
None

/cc @kevenleone

**Comment by kevenleone** [comment]
This feature will help a lot here on App Builder. 
This way we could remove the manual adaptation to the first image be possible directly on ClayPanel.

Great idea @diegonvs

**Comment by bryceosterhaus** [comment]
Hmm yeah this makes sense. This seems like another component where we went sort of in-between high and low level. I think we can make this more low level to provide more flexibility.  We made a similar change in Label recently, https://github.com/liferay/clay/commit/deffd0e09a4a1a274eba4077c6458dd28e62e3ff.

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus I've done a little bit of research on this task today and here's some questions I came up with:

1. Do we want both `ItemBefore` and `ItemAfter` like in Label?
2. Do we need to make a wrapper for [immediate children](https://github.com/liferay/clay/blob/master/packages/clay-panel/src/index.tsx#L106-L137) of the root component like `ItemExpand` in Label?
3. This prop is supposed to be consumed inside the parent component, not the `Header`, correct? I saw `Header` mentioned but in the 1st image the additional content is inside the element that handles collapsing. In the code example provided by @diegonvs it's getting passed to the root component confirming my theory.
4. Is this prop in any way tied to the component being `collapsable` or should it work either way?
5. @diegonvs can you pinpoint which part of the 2nd image you're referencing? Or explain it a bit more so I can understand the use case you're trying to demonstrate.

**Comment by diegonvs** [comment]
> This prop is supposed to be consumed inside the parent component, not the Header, correct? I saw Header mentioned but in the 1st image the additional content is inside the element that handles collapsing. In the code example provided by @diegonvs it's getting passed to the root component confirming my theory.

Sorry, I wrote "Header" just for being more comprehensive but It didn't work 😂 
But the main idea is having a more flexible way to edit the ClayPanel button and his title.

> @diegonvs can you pinpoint which part of the 2nd image you're referencing? Or explain it a bit more so I can understand the use case you're trying to demonstrate.

<img width="629" alt="Screen Shot 2020-04-15 at 11 36 22" src="https://user-images.githubusercontent.com/7663513/79350048-570d1900-7f0d-11ea-975b-9afc519d7a4d.png">

Notice that before the angle down icon, We have a plus button.

**Comment by bryceosterhaus** [comment]
@kresimir-coko I am thinking we need to account for the following uses for the `displayTitle` props.

### not collapsable
```jsx
// If `displayTitle` is a string or a number, we render it like....
<ClayPanelHeader>
	<span className="panel-title">{displayTitle}</span>
</ClayPanelHeader>

// If `displayTitle` is a function or component we render it like....
{displayTitle}
```

### collapsable
```jsx
// If `displayTitle` is a string or a number, we render it like....
<span className="panel-title">{displayTitle}</span>

// If `displayTitle` is a function or component we render it like....
{displayTitle}
```

We also should probably export the panel title as a component as well `ClayPanel.Title`

By doing this we give flexibility to the end user to really do whatever they want with `displayTitle` while also keeping it simple and usable for strings and numbers.

@kresimir-coko 
> Do we want both ItemBefore and ItemAfter like in Label?

No need to add this unless these classes are specified by clay-css, which for panel I don't think they exist.
