### ISSUE TITLE
Add new icons: angle-small

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#3156]
Due to [LEXI-886](https://issues.liferay.com/browse/LEXI-886) we have made a small version of the angle icons:
<img width="172" alt="Screenshot 2020-04-23 at 14 31 07" src="https://user-images.githubusercontent.com/56547676/80099649-18133f00-856f-11ea-9e46-de21228bba20.png">
- icon-angle-down-small
- icon-angle-up-small
- icon-angle-left-small
- icon-angle-right-small

Could you add them? The SVGs are in [LEXI-886](https://issues.liferay.com/browse/LEXI-886)
Thanks!

**Comment by pat270** [comment]
@laugardie I know we currently have icons like `caret-bottom-l` that are smaller, but we can achieve smaller icons by adding padding around the svg. The code:
```
.lexicon-icon-angle-right { padding: 1px; }
```
will make the chevron right 14px. `padding: 2px;` will make it 12px and still maintain a box of 16px. Let me know if this is something you guys would consider, otherwise I can add these.

**Comment by laugardie** [comment]
I see what you mean @pat270 . My main concern with this icon is to keep the visual weight equal to the regular one. So the main problem that I see in that approach for this icon specifically is that the icon is visually adjusted so that it has the same thickness as the regular one. I think if we add the extra padding to the icon, it will lose that thickness.
<img width="746" alt="Screenshot 2020-04-24 at 09 12 01" src="https://user-images.githubusercontent.com/56547676/80184878-b05f0180-860b-11ea-88e4-80c1a46115d7.png">

**Comment by pat270** [comment]
Thanks @laugardie, I'll send these in today.

**Comment by pat270** [comment]
@laugardie I added the icons and see no visual difference between Small with padding and Small visually adjusted.

<img width="175" alt="angle-icon-diff" src="https://user-images.githubusercontent.com/788266/80220063-29545e00-85f8-11ea-9ecc-e8d7e640ccbf.png">

**Comment by laugardie** [comment]
Sorry @pat270 I was on a moving house leave permit on Monday and Tuesday. In the image that you have attached in your comment, small and regular arrows seem the same. There should be a bigger difference in size between the regular and the small icon but keeping the same weight/thickness aspect.
<img width="353" alt="Screenshot 2020-04-29 at 09 28 20" src="https://user-images.githubusercontent.com/56547676/80570836-c863c600-89fb-11ea-8546-33c6c7a7b4e2.png">

**Comment by pat270** [comment]
No problem @laugardie hope everything went well. In the image I posted, the `-small` icons are from https://issues.liferay.com/browse/LEXI-886. I added padding to the normal icons as a comparison and there is no difference.

**Comment by laugardie** [comment]
Sorry, I completely misunderstood your comment. If they are completely the same visually adjusted or adding the padding, you can go for it then. We just need the icon to keep the same weight no matter how.

**Comment by jbalsas** [comment]
As usage goes, it’s probably easier to just have different symbols, si developers have a uniform way of getting icons not a variant of the common case...

**Comment by pat270** [comment]
I was just going to ask in the slack chat. Just wanted to see if it would be worth to save on the spritemap file size.
