### ISSUE TITLE
ClayMultiSelect with AutoComplete not showing when used in ClayModal

### ISSUE THREAD

**Issue by gianmarcobrunialti** [liferay/clay#3185]
-   [ X ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Simply use a ClayMultiSelect component enabling the AutoComplete functionality via `sourceItems` prop, and nest it within the Body of a ClayModal component.

## What is the expected result?
The AutoComplete should show up on top of the Modal body (and within it).

## What is the actual result?
The AutoComplete is in fact behind the ClayModal. Also, overriding the MenuRenderer with a custom one, via ClayMultiSelect `menuRenderer` prop, doesn't do the job, as the div's wrapping it lay out of the ClayModal html structure.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.x.x  |
| React |     16.8.6    |

**Comment by pat270** [comment]
I believe this is a `z-index` issue. Dropdown Menus have `z-index: 1000` and modals have `z-index: 1050`. We place our `dropdown-menu` as a direct child of `body` which means modals will always win over `dropdown-menu`.

I think we can fix this with:
a) Allow passing a custom `z-index` to the `dropdown-menu`
b) A parameter that renders the `dropdown-menu` wherever it was called instead of placing it directly inside the `body` element.

**Comment by gianmarcobrunialti** [comment]
@pat270 Thanks for your reply. At the moment my solution for that of actually altering the `z-index` once the ClayMultiSelect is focus, but it felt a little sketchy as the HTML structure doesn't actually reflect what's in view. For as much as my opinion could count, I'd second option *b*. :)

**Comment by bryceosterhaus** [comment]
Hey @gianmarcobrunialti I am unable to reproduce in codesandbox. Take a look at the demo, https://codesandbox.io/s/romantic-pine-or0cm?file=/src/index.js.

**Comment by kresimir-coko** [comment]
Hey @gianmarcobrunialti can you check out the above demo, and let us know if this is still an issue?

**Comment by gianmarcobrunialti** [comment]
Hello @kresimir-coko , sorry for having kept you waiting on this. In the end it did work, but I still needed to interact with the `.dropdown-menu`'s `z-index`, as that div was spawned outside of the modal. Also, please consider that I needed to build a custom MenuRenderer to accommodate our design needs.

The PR is still open as it's scheduled for a future release.
Invoking Component: https://github.com/marco-leo/liferay-portal-ee/pull/1083/files#diff-fe2abaa4cc9949325443f5a0a0e94e23R71

Custom MenuRenderer Component: https://github.com/marco-leo/liferay-portal-ee/pull/1083/files#diff-7ed9797de3c1f721e080ff682d0dc550R19
