### ISSUE TITLE
Clay CSS move components aspect-ratio, buttons, icons, and type earlier in the import chain

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3191]
See https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/_components.scss.

These components are reused in other components and should be easier to overwrite. For example, we should be able to overwrite `.btn` styles from Alerts with one class (`.alert-btn`) instead of two (`.alert .alert-btn`). The order should be:
```
@import 'components/type';

@import 'components/icons';

@import 'components/aspect-ratio';
@import 'components/buttons';
@import 'components/grid';
...
```

**Comment by marcoscv-work** [comment]
LGTM, I would merge it!
