### ISSUE TITLE
Documentation is lacking for some components in clayui.com

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3197]
We created some new components this year but we haven't taken time to properly document them. I propose we set some time aside and document any components that are lacking proper documentation to get them up to the standard already set by older components.

Here's an example of a well-documented component: [Card](https://clayui.com/docs/components/card.html) vs a not-so-well-documented component: [Localized Input](https://clayui.com/docs/components/localized-input.html).

**Comment by bryceosterhaus** [comment]
Great idea! Would you want to pick up this task and start to create some docs? You could gather ideas form lexicon and other docs sites so that we know what content to include.

**Comment by kresimir-coko** [comment]
Yea @bryceosterhaus I'll pick this up when I finish what's in my current queue. I think assigning it to myself isn't the correct play here because it'll make it look like it's in progress and mess with Exalate.

**Comment by kresimir-coko** [comment]
Here's a table of components that need more documentation.

Component | Comment
------------ | -------------
Application Bar | Missing React Component page
Badges | Missing content
Breadcrumbs | Missing content & API, also headings in Markup/CSS
Charts | Missing Markup/CSS and API
Checkbox | Missing headings in React Component
Dual List Box | Bug in Markdown & missing content
Form | API is mising
Forms Hierarchy | Is this even a component? Maybe move to a different category or under Form? @bryceosterhaus 
Icon | @bryceosterhaus something removed the Markup/CSS page, maybe co-locating caused it
Input | API is missing, probably need to cast the props
Link | API is missing
Loading Indicator | Missing content
Localized Input | Missing content
Management Toolbar | Missing headings
Multi Step Nav | Missing content and user friendly headings
Navigation | #3205 & #3207 
Pagination | Missing content and user friendly headings
Popover | Missing content
Progress Bar | Missing content
Radio Group | Missing content & Markup/CSS page
Select Box | Missing headings
Sidebar | @bryceosterhaus is this even a component that we provide to users? Is [this](https://github.com/liferay/clay/blob/master/clayui.com/src/components/Sidebar/Sidebar.js) what it's trying to describe?
Slider | Missing content
Sticker | Missing headings
Table | Missing headings
Tabs | Missing headings & can probably reduce code example to improve clarity
Timelines | @bryceosterhaus is this a component or just a guideline on how to use something that's not made by Clay?
Time Picker | Missing content & Markup/CSS page
Toggle Switch | Missing content
Tooltip | Missing content
Upper Toolbar | Missing Markup/CSS page
Vertical Navigation | #3205 & #3207 

### Relative amount of work required
Type of work | Amount of work
------------ | -------------
Headings | 1
API | 1
Content | 2
Markup/CSS Page | 3
React Component Page | 3

**Comment by kresimir-coko** [comment]
@bryceosterhaus I made this shiny table to enable some kind of tracking for documentation related issues, I've tagged you in some so please let me know or take a look yourself as to what're your thoughts. Also I haven't opened issues for Adding Markup/CSS & React Component pages for  the components that are missing so that you can let me know if they are necessary.

**Comment by bryceosterhaus** [comment]
Table looks great! Feel free to pick up any of these issues, these will all be really helpful. In regards to your questions...

> Forms Hierarchy | Is this even a component? Maybe move to a different category or under Form?

This is more of a guide of laying out forms. No need for a react specification on this.

> Icons: @bryceosterhaus something removed the Markup/CSS page, maybe co-locating caused it

Yeah I think It may have gotten accidentally removed in the mix of it all. Could you look into adding this back in?


> Sidebar: @bryceosterhaus is this even a component that we provide to users? Is this what it's trying to describe?

No we currently don't provide this component, we are still waiting for requirements https://github.com/liferay/clay/issues/2903

> Timeline: @bryceosterhaus is this a component or just a guideline on how to use something that's not made by Clay?

I don't think we have had a need for this component yet so I wouldn't worry about it right now.

**Comment by kresimir-coko** [comment]
Fixed in PRs listed in the table above
