### ISSUE TITLE
Modal With A Glitch On Its Shadow

### ISSUE THREAD

**Issue by fapires** [liferay/clay#3199]
Hi guys,

I was designing a functionality that is using Clay's modal when I noticed that there is a glitch on the `box-shadow` rendering on the implemented modal on Liferay DXP.

Expected style:
<img width="649" alt="Screen Shot 2020-05-05 at 18 59 48" src="https://user-images.githubusercontent.com/8724228/81120241-a9d16380-8f02-11ea-87c0-b59bd8565037.png">

Current style:
<img width="1163" alt="Screen Shot 2020-05-05 at 18 54 36" src="https://user-images.githubusercontent.com/8724228/81120335-e1d8a680-8f02-11ea-9f26-38d9c5c89e34.png">

It seems there is something clipping the shadow because when I inspect the CSS there is a `box-shadow` applied:
<img width="398" alt="Screen Shot 2020-05-05 at 18 55 39" src="https://user-images.githubusercontent.com/8724228/81120415-0b91cd80-8f03-11ea-871c-77b1a1828d17.png">

**Comment by pat270** [comment]
@fapires is there a box-shadow on `.modal-dialog` or a parent element? Adding a shadow on the parent is the only way I could recreate it.

**Comment by matuzalemsteles** [comment]
hey guys, this is apparently not a problem with Clay this is a problem with Liferay's old modals...

I know @markocikos was working on their migration, @markocikos can you tell if this is in conflict with Liferay's css?

**Comment by pat270** [comment]
@matuzalemsteles is correct. The markup of the Liferay modals is off. The fix is to update the markup or add `.modal-open .dialog-iframe-modal { overflow: visible; }` in Portal.

**Comment by fapires** [comment]
thank you guys for clarifying!

**Comment by pat270** [comment]
No problem. Closing.
