### ISSUE TITLE
Add icon-desktop

### ISSUE THREAD

**Issue by laugardie** [liferay/clay#3200]
Hi guys!
I am working on[ LEXI-882](https://issues.liferay.com/browse/LEXI-882) to include _icon-desktop_ in Clay.
<img width="44" alt="Screenshot 2020-05-06 at 09 16 39" src="https://user-images.githubusercontent.com/56547676/81147313-526eda00-8f7a-11ea-861b-0db1f6802923.png">
Checking the icons in Clay, I have found another icon called desktop.
<img width="232" alt="Screenshot 2020-05-06 at 09 20 48" src="https://user-images.githubusercontent.com/56547676/81147603-eb055a00-8f7a-11ea-956e-210a4250954c.png">
This icon is called _display-content_ in Lexicon.
<img width="197" alt="Screenshot 2020-05-06 at 09 24 16" src="https://user-images.githubusercontent.com/56547676/81147816-6109c100-8f7b-11ea-96c0-4a3d311df4d7.png">
Do you know if the desktop icon in Clay is in use? I would like to know that, to decide if we need to deprecate that icon or to change its name to add the new desktop icon.

**Comment by laugardie** [comment]
I have just found this icon being used in Portal: Control Panel > System Settings. I will leave this ticket open and I will update it with the SVG and all the info today so we can update and add the icons.

**Comment by laugardie** [comment]
I will update the title of the issue to Add icon-desktop.
We will need to:
1. Change the icon-desktop name in Clay to icon-display-content so it matches the Lexicon library.
<img width="196" alt="Screenshot 2020-05-06 at 10 39 26" src="https://user-images.githubusercontent.com/56547676/81156087-e2fee780-8f85-11ea-8000-5f5a9b577924.png">


2. Add new icon: desktop to Clay. Find the .SVG in [LEXI-882](https://issues.liferay.com/browse/LEXI-882)
<img width="124" alt="Screenshot 2020-05-06 at 10 43 08" src="https://user-images.githubusercontent.com/56547676/81156610-67ea0100-8f86-11ea-9fef-d0712009753a.png">
Thanks! :)

**Comment by pat270** [comment]
In Lexicon CSS (1.x), the desktop icon is <img width="35" alt="1 x-desktop" src="https://user-images.githubusercontent.com/788266/81311824-b8bb3180-903a-11ea-941c-29ff74c82334.png" style="vertical-align:middle;">. In 2.x, it was changed to what it is now. In 3.x, we are trying to revert it back. Is it possible for Lexicon to name the desktop icon something else like `icon-display`?

**Comment by laugardie** [comment]
Hey @pat270, you are right and it shouldn't have been changed before in previous versions. But as both icons are going to coexist, in this case, I think that we need to be cautious with the naming. As names are chosen to clearly represent what icons are to simplify use. Using icon-display for the desktop icon and icon-desktop for the one that represents display content can be confusing. As this is not going to cause a breaking change becuase the class that is already in use is going to stay in use but with a different icon, we should reconsider naming the icons properly to avoid future mistakes.
My suggestions are:
<img width="250" alt="Screenshot 2020-05-08 at 10 13 35" src="https://user-images.githubusercontent.com/56547676/81386027-9eee1d00-9114-11ea-9c1f-710038189a3b.png">

**Comment by pat270** [comment]
@laugardie I was thinking about having 3 icons:
<img width="35" alt="1 x-desktop" src="https://user-images.githubusercontent.com/788266/81417944-cf2bc080-9100-11ea-9d30-ba6e35ea4e6a.png"> icon-display
<img width="26" alt="icon-display-content" src="https://user-images.githubusercontent.com/788266/81417974-d81c9200-9100-11ea-8ab1-2952fc3f36e8.png"> icon-display-content
<img width="26" alt="icon-display-content" src="https://user-images.githubusercontent.com/788266/81417974-d81c9200-9100-11ea-8ab1-2952fc3f36e8.png"> icon-desktop (deprecate)

**Comment by laugardie** [comment]
That seems ok for us @pat270

**Comment by jbalsas** [comment]
I'd say we can simply change this to @laugardie suggestion in `3.x` and let the other branches as they are.

In `DXP`, the `desktop` icon is only used to display `display-content`:

```java
private static final String _CATEGORY_ICON = "desktop";

private static final String _CATEGORY_KEY = "display-content";
```

So, maybe the first proposal makes even more sense... but I'm fine with whatever you agree on.

Really hope those metaphors are more stable from now on 😂

**Comment by pat270** [comment]
I'm trusting @jbalsas on this one.

<img width="19" alt="desktop" src="https://user-images.githubusercontent.com/788266/81593948-06a2a300-9375-11ea-8235-927aa0668615.png"> desktop
<img width="18" alt="display-content" src="https://user-images.githubusercontent.com/788266/81593959-0b675700-9375-11ea-9a70-2a0e561c390d.png"> display-content

**Comment by jbalsas** [comment]
Hahaha... @pat270! I actually saw @laugardie agree with you, so go for it!!

**Comment by jbalsas** [comment]
Or talk it through, there's likely no rush to get this in one day earlier. Both options are fine by me!
