### ISSUE TITLE
Add `nav-pills` to ClayNav as a prop and document it for clarity

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3205]
## What is your proposal?
The current implementation of [Nav Pills](https://clayui.com/docs/components/css-nav-pills.html) requires the user to manually add a `nav-pills` class to their `.nav`. That isn't consistent with the rest of Clay, so this is a proposal to add a `navPills` prop to `ClayNav`.

## Why would adopting this proposal be beneficial?
It would provide our users better documentation and consistency when using Nav Pills.

## What are the alternatives to this proposal?
Extending the current documentation and explaining to the users that this approach is sometimes required in Clay.

**Comment by pat270** [comment]
@kresimir-coko just wanted to say `nav-pills` is a Bootstrap component that isn't defined anywhere by Lexicon. I'm good with providing more options, but not sure what the rest of the team thinks about it.

**Comment by jbalsas** [comment]
> [...] just wanted to say nav-pills is a Bootstrap component that isn't defined anywhere by Lexicon

Based on this I'd simply remove that documentation page. Since it's not really a component and just an example on how to achieve a Bootstrap variant using classes.

**Comment by kresimir-coko** [comment]
This issue has grown a bit (in a good way) since I picked it up, I noticed that `ClayNav` isn't properly documented, so `nav-pills` is gonna end up as a sub-heading as an example of usage.
I think that having it as a prop is beneficial (while not adding complexity to the implementation) so I'm gonna propose that as a change in the PR I'm working on related to this issue
