### ISSUE TITLE
Time Picker is missing it's Markup/CSS page

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3218]
Time Picker doesn't have it's Markup/CSS page.

@pat270 Do we have markup for the Time Picker component?

**Comment by kresimir-coko** [comment]
@pat270 this is a reminder to let me know if we have markup for the Time Picker component.

**Comment by jbalsas** [comment]
Hey @kresimir-coko, I'm not sure it makes any sense to have markup example for complex interactive components.

If you wanted, you can simply get the markup from the component itself, which would've been likely approved during development.

In this case, and in line with some other conversations I've seen, less might be more 😉

**Comment by pat270** [comment]
Hey @kresimir-coko, sorry I missed this one. I have Time Picker markup at https://pat270.github.io/clay3-test-site/vclay-table-dd/content/form-elements-time/

**Comment by kresimir-coko** [comment]
As per @jbalsas's comment:
> [...] In this case, and in line with some other conversations I've seen, less might be more 😉

with which I agree, I'm closing this issue.
