### ISSUE TITLE
Upper Toolbar is missing it's Markup/CSS page

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3219]
Upper Toolbar doesn't have it's Markup/CSS page.

@pat270 Do we have markup for the Upper Toolbar component?

**Comment by bryceosterhaus** [comment]
I believe the css content would be similar to https://pat270.github.io/lexicon/v2.16.2/content/tbar/

**Comment by kresimir-coko** [comment]
Decided not to do it, see #3248
