### ISSUE TITLE
Improvements on ClayCard, CardWithNavigation, AspectRatio to help customization

### ISSUE THREAD

**Issue by naraandrade** [liferay/clay#3225]
## What is your proposal?
I would like to suggest some improvements on ClayCard and CardWithNavigation/InteractiveCard about their states props (which is missing at https://clayui.com/docs/components/card.html#states) and alignment of inner elements.

## Why would adopting this proposal be beneficial?
I had some issues trying to achieve a layout (see attached files below) because the InteractiveCard/CardWithNavigation doesn't center the icon when you're not passing a title and description. I ended using the ClayCard.AspectRatio with ClayIcon, but still with some problems about centering vertically.
Plus, I tried using ClayCard to wrap the card with icon and the title and description, but I couldn't achieve the layout expected unless I pass a lot of classes to the ClayCard, so I ended choosing a div instead. I believe that would be much easier if I could just pass a "interactive" prop to the ClayCard, for example.

<img width="530" alt="Captura de Tela 2020-05-14 às 09 55 43" src="https://user-images.githubusercontent.com/60627148/81938045-c6d4f900-95ca-11ea-8ca4-8d9bf053475e.png">
<img width="530" alt="Captura de Tela 2020-05-14 às 09 56 21" src="https://user-images.githubusercontent.com/60627148/81938054-c9375300-95ca-11ea-93ce-5b13835d6dd8.png">

## What are the alternatives to this proposal?
Maybe create other cards according to the needs of usage of the portal. But it's can be tough, since it's not pratical to create one different card for each needed.
Or restructure the components to make them more flexible.

**Comment by pat270** [comment]
This is the markup I would use to achieve what you have from the screenshots.

```
<style>
.my-component-card { box-shadow: none; padding: 0.5rem; }
.my-component-card:hover { text-decoration: none; }
.my-component-card .card { background-color: #f7f8f9; }
.my-component-card .aspect-ratio { padding-bottom: 100%; }
.my-component-card .component-text { color: #6a6c7e; } 
</style>

<ul class="card-page card-page-equal-height">
  <li class="card-page-item col-sm-6">
    <a class="my-component-card card card-interactive" href="#link">
      <div class="card card-type-template">
        <div class="aspect-ratio">
          <div className="aspect-ratio-item aspect-ratio-item-center-middle aspect-ratio-item-fluid">
            <svg></svg>
          </div>
       </div>
      <div class="component-title">Standard App</div>
      <div class="component-text">Create an app to manage the data of an object.</div>
    </a>
  </li>
  <li class="card-page-item col-sm-6">
    ...
  </li>
</ul>
```

You can replace the `a` tag with `<div class="my-component-card card card-interactive" tabindex="0" onclick="do stuff();">`.

From the Clay CSS side of things, I can probably add a new card variant and:
1) update `aspect-ratio` to allow forcing a specific ratio
2) update `component-text` color inside cards
3) update `card-interactive` to take care of edge cases similar to this

**Comment by naraandrade** [comment]
Thank you :) but I already did the layout. The suggestion is just to make it easier to customize those components, in case someone else need it in the future.

**Comment by bryceosterhaus** [comment]
@naraandrade does this fix look right to you? Check out the second card example, https://5ebdb8354c7bc6000747e26c--storybook-clayui.netlify.app/?path=/story/components-claycard--cardwithnavigation

**Comment by drakonux** [comment]
Hey, @naraandrade nice to meet you :) 

Well, @pat270 we need a formal request in [Lexicon ](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=2953) (create request) to study the scenario from the product team that needs this variation. 

It seems very similar to [Navigation card](https://liferay.design/lexicon/core-components/cards/cards-navigation/) as Bryce said it. Using it with some customization they should get the look and feel they want but we need more context of the use case.

**Comment by naraandrade** [comment]
> @naraandrade does this fix look right to you? Check out the second card example, https://5ebdb8354c7bc6000747e26c--storybook-clayui.netlify.app/?path=/story/components-claycard--cardwithnavigation

@bryceosterhaus yes, it solves the problem with centering the icon, thank you.

**Comment by bryceosterhaus** [comment]
@naraandrade, just merged, this fix should be released on Thursday of this week.
