### ISSUE TITLE
TabPanel name is incorrect in ClayTabs component

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#3234]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
It is in the [clayui](https://clayui.com/docs/components/tabs.html) documentation

## What are the steps to reproduce?
Use `ClayTabs` component

## What is the expected result?
`ClayTabs.TabPane` must be renamed to `ClayTabs.TabPanel`

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3  |
| React |    16.12.0     |

**Comment by marcoscv-work** [comment]
Bootstrap changed the name but It would make sense since 'HTML5 semantic' calls this item `role="tabpanel"`

**Comment by bryceosterhaus** [comment]
We based our naming decision on the `.tab-pane` class. We probably want to avoid a rename here in v3.x, but I can add this to our notes for 4.x.

**Comment by pat270** [comment]
Is it possible to make a TabPanel alias that maps to TabPane?

**Comment by bryceosterhaus** [comment]
@pat270 yeah that is possible. I am curious though if this naming is actually a problem though. Does clay need to match semantic html naming patterns? I'm not totally opposed to it, but makes me wonder if we are putting ourself under an unnecessary constraint.

**Comment by pat270** [comment]
@bryceosterhaus I didn't even think about following the `role` attribute. I was thinking calling `TabPanel` was a common mistake. It would be nice to have an alias? I agree with you that we should use Bootstrap's names since the markup is tightly coupled to the component.

**Comment by marcoscv-work** [comment]
of course, it's probably not a problem or a wrong name, but it seems to cause doubts sometimes, so it's something that needs to consider in some way

**Comment by bryceosterhaus** [comment]
Ah I see, that makes sense. Yeah I will go ahead and add an alias for it.
