### ISSUE TITLE
Hide date picker after selecting date

### ISSUE THREAD

**Issue by gabrielwas** [liferay/clay#3262]
## What is your proposal?

Add the possibility of hiding the picker automatically after selecting the date

## Why would adopting this proposal be beneficial?

It could reduce the number of clicks to select a date, and through that, the use of the app would become more organic to the user.

## What are the alternatives to this proposal?

Maybe provide a property to allow this behavior

**Comment by bryceosterhaus** [comment]
@gabrielwas just added props to control the expand functionality. Check out this storybook demo to see an example of manually handling the expand when someone clicks on a date

https://github.com/liferay/clay/pull/3264/files#diff-66c91d2750a8b6f447ea0cd4c032eda5R108

**Comment by gabrielwas** [comment]
@bryceosterhaus Thank you!
