### ISSUE TITLE
Change ClayAlert default autoClose interval to 10000

### ISSUE THREAD

**Issue by wincent** [liferay/clay#3281]
[Lexicon says](https://liferay.design/lexicon/core-components/alerts/) that toasts should stay open for 10 seconds if there is an associated action, or 5 seconds otherwise. But for some reason, our default interval [is 8 seconds](https://github.com/liferay/clay/blob/8b8776107c1858f3517d4508342fa88860d9cde2/packages/clay-alert/src/index.tsx#L17) and has been [ever since we added it](https://github.com/liferay/clay/commit/95342d26307f72a1078afd3d60f61e307bd3d95a). This makes me think that maybe the Lexicon interval changed at some point, or maybe we didn't know what to use as a default — whatever the explanation, what do you think about bumping the default to 10000?

Noticed while reviewing [a PR in liferay-portal](https://github.com/wincent/liferay-portal/pull/297/files) that we have a bunch of components that specify 10000 as an interval, for compliance with Lexicon, and we could simplify all those if we change the default here.

**Comment by matuzalemsteles** [comment]
Hey @wincent, I remember that when we started to migrate to React, we rely on Lexicon documents https://docs.google.com/document/d/1mR8k7TE_5s6wzn94HtM7kB3NYVItDMoi4RkKZ0yRezw/edit (Maybe it became obsolete). Apparently that must have changed and we didn't know! But if this is the new guideline, I don't see why not follow it.

**Comment by kresimir-coko** [comment]
Fixed in #3287
