### ISSUE TITLE
clayui.com needs to have a docs page for JSP taglibs

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3286]
With the addition of JSP code examples (#3280 & #3279) we realized we need to have some guidelines, advice and general docs on how to use Clay components as JSP tags.

Perhaps it will be a heading under the Components page, or a subpage under Get Started.
If anyone has other suggestions feel free to comment.

**Comment by jbalsas** [comment]
What's the equivalent for our other examples?

**Comment by kresimir-coko** [comment]
> What's the equivalent for our other examples?

We have detailed explanation in [How to Use Clay](https://clayui.com/docs/get-started/how-to-use-clay.html) and then each component has an equivalent of `yarn add @clayui/autocomplete` in their frontmatter
