### ISSUE TITLE
@clayui/toolbar package?

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3300]
It might make more sense to create just a basic toolbar package and merge upper-toolbar into that package. This way we could put all the `tbar` classes in toolbar. upper-toolbar could be a high-level component from toolbar.

Stems from this convo, https://github.com/liferay/clay/pull/3248

**Comment by kresimir-coko** [comment]
This sounds neat, I'll make it happen!

**Comment by matuzalemsteles** [comment]
Hey guys, I would expect this to happen in v4, this is a breaking change to package and probably component changes, so I think it should go to v4 or we can create the new toolbar package just being an alias for the rest of the components and add deprecation warnings to use the toolbar in favor.

**Comment by wincent** [comment]
> this is a breaking change

One of the consequences of splitting Clay into individual packages is that it limits options for moving things around, because moving *anything* across package boundaries is likely to cause breakage (at least in the nominal sense, even if we can migrate all the call sites because we control them).

![just-sayin](https://user-images.githubusercontent.com/7074/83422867-7531c880-a42a-11ea-9704-91c54a4157c1.gif)

Of course, if this were all bundled together in one package it doesn't mean that we could move stuff around willy nilly without breaking things, but there would at least be some kinds of internal reorganization that we could do without breakage.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I think we could get away with it not beng in v4 or breaking changes in anything. I would see it as

- **Deprecate** upper-toolbar component at its current version
- **Create** toolbar package and include upper-toolbar in it.

Now technically, I guess you could consider this breaking, but we do have some freedom in this since we control the DXP dependencies.

@wincent yeah I've been contemplating what a `@clayui/all` package might look like... Although, the modularity actually helps us here if we deprecate and move it to another package. We wouldn't really be able to do that in a single package(maybe we wouldn't even have to though lol).

If we go with the deprecate + create path, does that bother anyone if we did that in v3.x?

**Comment by matuzalemsteles** [comment]
@bryceosterhaus when you say `Deprecate` will we add discontinuation notices to the package? if so, I see no problem.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles yeah the idea would be to discontinue development on `@clayui/upper-toolbar` and add a notice, warning, or recommendation to use `@clayui/toolbar`, and move dev over to `@clayui/toolbar`.

**Comment by matuzalemsteles** [comment]
Looks good to me!

**Comment by wincent** [comment]
> If we go with the deprecate + create path, does that bother anyone if we did that in v3.x?

Sounds totally fair.

**Comment by kresimir-coko** [comment]
I'm looking for feedback on the draft PR related to this #3302

**Comment by bryceosterhaus** [comment]
@kresimir-coko just the PR, I am gonna leave my comments here just in clarify the packages goals.

My expectations and steps in creating the package would be...
1. Create `@clayui/toolbar` package
2. Create low-level components based off of the css we have at https://github.com/liferay/clay/blob/master/packages/clay-css/src/content/tbar.html.
    - `Item`, `Section`, `Label`, `Link`, etc..
3. After we establish low-level items, migrate upper-toolbar to  `@clayui/toolbar`. Upper-toolbar may not even need to be its own component anymore either since there isn't really anything specific to it.
4. Replace upper-toolbar uses in dxp with toolbar.
5. Replace references of upper-toolbar package to use components from toolbar. Deprecate the upper-toolbar package.
6. Add toolbar components to management-toolbar and other packages using those classnames (possibly even move management bar into toolbar?).

Thoughts?

**Comment by kresimir-coko** [comment]
Okay @bryceosterhaus if I understand correctly, I did a massive breaking change, I should've created a new package that will, while we don't replace the usages in DXP, live alongside `@clayui/upper-toolbar`. 

While you did give me some clarity and enough to make a 2nd, better draft PR, I didn't get all my questions answered in #3302. @pat270 can you as well take a look at my questions and offer your thoughts on ones related to markup.

**Comment by bryceosterhaus** [comment]
@kresimir-coko I'm not totally sure on some of the questions since its really getting at the lexicon definition of toolbar. I think from where Clay stands, we can group them as we see fit. So I think it makes sense to at least provide low-level `tbar` components first and then start off with stories of how they are use to implement other components like info-bar and upper-toolbar because some of those are just a composition of toolbar low-levels and have no specific classes themselves.

**Comment by bryceosterhaus** [comment]
Sent update at https://github.com/liferay/clay/pull/3325
