### ISSUE TITLE
Clay Link and Button should have props that make it possible to look like the other component

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3301]
After a [lengthy discussion](https://liferay.slack.com/archives/G3JBR21HA/p1590997416006400) with @jbalsas we decided to let others speak for a bit on the topic.

## What is your proposal?
In many places we have Links that look like Buttons, and Buttons that look like Links.
I want to discuss what you think is the proper API for it. 

Right now, for Buttons, we have `displayType="link"`: `<ClayButton displayType="link" />`, which will render a Button that looks like a link, and that's great. We're missing the same functionality for `ClayLink`.

## Why would adopting this proposal be beneficial?
We have plenty of cases in DXP where keeping the functionality of a Button/Link is key, but we want the look of the other component.

**Comment by pat270** [comment]
Maybe this should be a separate issue, but I was thinking it would be a good idea to output the attribute `rel="noreferrer noopener"` when someone uses `ClayLink` or `ClayButton` with the `target` attribute.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes (scroll down to `target`)

**Comment by jbalsas** [comment]
> Maybe this should be a separate issue, but I was thinking it would be a good idea to output the attribute rel="noreferrer noopener" when someone uses ClayLink or ClayButton with the target attribute.

That's a great catch @pat270!! We've had several security reports from customer in the past year regarding this... let's spin off some tasks to make sure we follow this! This needs to be overridable because there are some legit cases, though!

**Comment by bryceosterhaus** [comment]
spin off https://github.com/liferay/clay/issues/3311
