### ISSUE TITLE
Add rel="noreferrer noopener" to ClayLink

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3311]
When someone adds the `target` attribute we should add  `rel="noreferrer noopener"`

**Comment by jbalsas** [comment]
As I mentioned... this should be overridable, in case someone wants it for legit use cases. 

For instance, `noopener` can break authentication schemes that may rely on being able to access `window.opener`. These are certainly slowly disappearing, but just to be safe.

**Comment by kresimir-coko** [comment]
@jbalsas something like a `unsafeTarget` boolean prop, defaulted to false, that will ommit `rel="noreferrer noopener"` from the markup.

**Comment by jbalsas** [comment]
I don't know... maybe just be careful with the implementation and make sure passing in a `rel` prop will override our default properly...

I don't need to be involved in the technical decision, up to you all ;)

**Comment by bryceosterhaus** [comment]
@kresimir-coko I think we could default the rel prop to be `noreferrer noopener`, but allow users to pass in whatever they want to override it.

```jsx
(rel = 'noreferrer noopener') => (
    <a rel={rel} />
)
```
