### ISSUE TITLE
Move upper-toolbar to toolbar package

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3336]

**Comment by kresimir-coko** [comment]
Not sure what the situation with this issue is @bryceosterhaus but I'll work on documentation for @clayui/toolbar since that's something we're missing and it might give you some foundation for this issue.

**Comment by bryceosterhaus** [comment]
@kresimir-coko no situations here, just havent gotten the time to get to this. Feel free to pick it up!
