### ISSUE TITLE
Add Drilldown Component

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3337]
Using [this](https://docs.google.com/document/d/1PVQwknqVIOQhf2JL0kEv0k6WHOExKOskiX-CxxWYRqs/edit) documentation by the Lexicon team we should make a Drilldown component.

**Comment by bryceosterhaus** [comment]
I spent some time on this last week and got decently far until the animations. Here is my work so far, https://github.com/bryceosterhaus/clay/tree/drilldown

I'm on vacation this week, but I will pick it up once I am back if there hasn't been any other progress.

**Comment by kresimir-coko** [comment]
Alright @bryceosterhaus I'll take a look at your implementation and see if I can find some cleaning up and refactoring to do.

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus I've done some cleanup of the Drilldown, and after a [short exchange](https://liferay.slack.com/archives/G3JBR21HA/p1593608032287000?thread_ts=1593608032.286900&cid=G3JBR21HA) with @jbalsas on Slack decided to let you finish it. Here's the couple commits I added after rebasing https://github.com/kresimir-coko/clay/tree/drilldown

**Comment by bryceosterhaus** [comment]
Sounds good! I will pick it back up tomorrow and hopefully have something solid submitted this week

**Comment by kresimir-coko** [comment]
Fixed in #3338
