### ISSUE TITLE
why lexicon become clay？

### ISSUE THREAD

**Issue by fanqi** [liferay/clay#334]

**Comment by natecavanaugh** [comment]
Hi @fanqi ,
We had heard from quite a few people that had a lot of confusion regarding the difference between Lexicon the design language, and the implementation.
Lexicon would be equivalent to something like [Apple's Human Interaction Guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/) and clay can be considered something like the [Cocoa Framework](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/OSX_Technology_Overview/CocoaApplicationLayer/CocoaApplicationLayer.html).

Hopefully that helps clear up any confusion, but of course, let us know if you have any other questions.

Thanks!
