### ISSUE TITLE
Clay API documentation page links targeting http instead of https

### ISSUE THREAD

**Issue by alexandervalencia** [liferay/clay#335]
When clicking any link in the Clay API Documentation there is a flash of styling then most styles are removed and each page looks like this.
<img width="875" alt="2017-04-26 10_11_32-lexicon - alerts" src="https://cloud.githubusercontent.com/assets/22045453/25447307/8c0040e8-2a69-11e7-9a8e-37241b549be7.png">

Manually changing the url to be https instead of http causes all styles to be loaded correctly.

**Comment by yuchi** [comment]
The trick is in the trailing slash :)

```
$ curl -I 'https://liferay.github.io/clay/content/alerts' # no trailing slash, with HTTPS
HTTP/1.1 301 Moved Permanently
# ...
Location: http://liferay.github.io/clay/content/alerts/ # trailing slash, no HTTPS
# ...
```

```
$ curl -I 'https://liferay.github.io/clay/content/alerts/' # trailing slash, with HTTPS
HTTP/1.1 200 OK
# ...
```

**Comment by yuchi** [comment]
- Does work: https://liferay.github.io/clay/content/alerts/
- Does *not* work: http://liferay.github.io/clay/content/alerts

**Comment by pat270** [comment]
That bug probably has something to do with the url stored in the browser's local storage, you can clear it by clicking the reset settings button.

**Comment by alexandervalencia** [comment]
Confirmed: clearing browser cache caused styling files to load properly.

**Comment by blzaugg** [comment]
Well, it doesn't help that our own links don't use the training slash.
![bad links](https://user-images.githubusercontent.com/1626739/30131750-c95ee834-9302-11e7-92b6-9819b762c570.PNG)
