### ISSUE TITLE
Wrong size for text and integer icons

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3351]
Felipe Pires opened us a question related to the size of the text and integer icons in App Builder and Forms (see [LEXI-905](https://issues.liferay.com/browse/LEXI-905)).
![image](https://user-images.githubusercontent.com/21216422/85156222-0e9a1080-b25a-11ea-9d58-7ba80207a962.png)

Reviewing the icon library in [Clay](https://clayui.com/docs/components/icon.html) I found:

_text_
![image](https://user-images.githubusercontent.com/21216422/85153308-5454da00-b256-11ea-871b-fff7968ec533.png)

_text-l_
Not found

_integer_
![image](https://user-images.githubusercontent.com/21216422/85153331-5d45ab80-b256-11ea-9fcc-6835aa41812d.png)

Checking our SVG repository in GDrive I found:

_text_ and _text-l_
![image](https://user-images.githubusercontent.com/21216422/85154957-6cc5f400-b258-11ea-8367-78b741fcd588.png)

_integer_
![image](https://user-images.githubusercontent.com/21216422/85154654-050fa900-b258-11ea-88ff-d4470c97f893.png)

and in the Figma library:

_text_
![image](https://user-images.githubusercontent.com/21216422/85155272-d80fc600-b258-11ea-88e7-b7abb12223f5.png)

_text-l_
![image](https://user-images.githubusercontent.com/21216422/85155316-e362f180-b258-11ea-830e-46f09335c81b.png)

_integer_
![image](https://user-images.githubusercontent.com/21216422/85155197-c1696f00-b258-11ea-9188-11c77cd76dbc.png)

I'm a bit lost with this issue, so... correct me if I wrong:

- **Does Clay miss the big text icon?** [text.zip](https://github.com/liferay/clay/files/4805800/text.zip)
- **I think the integer icon in the Figma library is outdated**
- **I think the integer icon is being rendered correctly in DXP, it just small by design. Isn't it?** We will review it. 

PS. I also have to check with the previous members of Lexicon team. The _number_ icon:

**Clay**
_number_
![image](https://user-images.githubusercontent.com/21216422/85196319-b571c180-b2d9-11ea-8138-2f0cdb342e79.png)

**Gdrive**
![image](https://user-images.githubusercontent.com/21216422/85196333-d5a18080-b2d9-11ea-9af0-701ea8a4af45.png)

**Figma**
![image](https://user-images.githubusercontent.com/21216422/85196342-f073f500-b2d9-11ea-9645-8c015a8de2c3.png)

**Comment by pat270** [comment]
@drakonux not 100% sure when the text icon got smaller, but it was during the 1.x to 2.x update. I can update those.

I'm pretty sure `decimal`, `integer`, `number`, `text`, `textbox` were drawn smaller to fit the UI for 7.1 / 7.2.

**Comment by pat270** [comment]
Also I'm unable to find larger versions of `integer` and `number` icons.

**Comment by drakonux** [comment]
Thanks, @pat270 for your time. I'll talk with Felipe because the information I found also reveals the same you said: some of the icons we mentioned were drawn smaller by design as you said.
