### ISSUE TITLE
ClayLayout remove `col-xs` from the Col component

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#3363]
In the new [Clay Layout Component Col](https://github.com/liferay/clay/blob/master/packages/clay-layout/src/Col.tsx#L65) we are setting `col-xs` as default when `size` is defined but I think we should remove that because when I declare `size` I expect to get `col-{size}` instead of `col-xs-{size}`

You can see it in [this PR](https://github.com/liferay-frontend/liferay-portal/pull/53#issuecomment-648859955)

At this point I'm not sure if we need `col-xs` at all https://getbootstrap.com/docs/4.5/layout/grid/#grid-options

**Comment by bryceosterhaus** [comment]
I think I was thinking that `col-${size}` wasn't really supposed to be used anymore and `col-xs-${size}` should replace it.

@pat270 do you remember anything related to this?

I could be far off on this...

**Comment by kresimir-coko** [comment]
Hey @pat270 just a reminder to check this out so we can maybe fix it.

**Comment by pat270** [comment]
@bryceosterhaus it was the other way around change `col-xs-{size}` to `col-{size}`.
