### ISSUE TITLE
Update Icon: Bold, Italic, Underline

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3364]
Due to [LEXI-970](https://issues.liferay.com/browse/LEXI-970). Lexicon has updated the _bold_, _italic_, _underline_ icons reducing their anchor points and adjusting the height.

![image](https://user-images.githubusercontent.com/21216422/85604211-5ef5e180-b651-11ea-9983-895fab2cba74.png)

Could you update the icons in Clay? Find the SVG's on the ticket.
Thanks!

**Comment by pat270** [comment]
Cross referencing https://github.com/liferay/liferay-ckeditor/pull/70 just in case
