### ISSUE TITLE
@clayui/card is not clickable with keyboard

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/clay#3365]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

[This example](https://codesandbox.io/s/interesting-driscoll-g66ot) uses `ClayCardWithNavigation` with an onClick handler.

I've seen that ClayCard uses a `div` with `role=button` internally when the card should be interactive, and using this markup instead of a regular `button` tag doesn't have the same browser behavior.

## What are the steps to reproduce?

1. Use `ClayCardWithNavigation` with an `onClick` prop.
2. Navigate to the component using keyboard `tabbing`
3. Press `enter`/`space` key

## What is the expected result?

onClick handler is executed.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay Card  | v3.2.1  |
| React | 16.10.2 |

**Comment by p2kmgcl** [comment]
Note: I want to send a PR trying to fix this problem but I'll be on PTO for a week :D

**Comment by bryceosterhaus** [comment]
Good catch on this! I'm also going to be on PTO next week, so if I don't get to this or someone else in the mean time, feel free to send a PR when you get back.
