### ISSUE TITLE
Icon: numbered list RTL

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3366]
Due to [LEXI-925](https://issues.liferay.com/browse/LEXI-925). Lexicon has created a new icon for the RTL version for numbered list icon _list-ol_

![image](https://user-images.githubusercontent.com/21216422/85852722-777d0d80-b7b1-11ea-9e7f-54e66b404508.png)

Please add it to the icon library. Find the SVG on the ticket.
Thanks!

cc\ @carloslancha

**Comment by pat270** [comment]
@drakonux `list-ol-rtl` icon looks different from the regular `list-ol` icon. Is this ok?
<img width="117" alt="list-ol-icons" src="https://user-images.githubusercontent.com/788266/86044354-d97e8280-b9fe-11ea-8e57-12ada51b375e.png">

**Comment by drakonux** [comment]
Wow. I didn't change a thing. I just mirrored the original one I have in the Lexicon GDrive. 

Could you send me the original SVG of _list-ol_? At least I will be able to check which one is correct.

**Comment by pat270** [comment]
Sent via email

**Comment by drakonux** [comment]
See [LEXI-925](https://issues.liferay.com/browse/LEXI-925) for more information. I've replaced the SVG files in the ticket so please use the new icons attached. 

![image](https://user-images.githubusercontent.com/21216422/86124143-ea9cc180-bada-11ea-9924-415916319524.png)
