### ISSUE TITLE
Update Icon: Unordered list icon + new RTL version

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3367]
Due to [LEXI-973](https://issues.liferay.com/browse/LEXI-973). Lexicon has updated the ~~bulleted~~ unordered list icon _list-ul_ and created its RTL version.

![image](https://user-images.githubusercontent.com/21216422/85858746-6d144100-b7bc-11ea-8ecf-fb959a4a8da6.png)

Please add the RTL version to the icon library and update _list-ul_ with the new version reviewed. Find the SVG's on the ticket.
Thanks!

**Comment by drakonux** [comment]
@pat270 Mea culpa. I think I should review this too with https://github.com/liferay/clay/issues/3366 Sorry for the inconvenience, I've got too much on my mind to focus these days :(.

**Comment by pat270** [comment]
@drakonux no worries I'll close the pr for this one

**Comment by drakonux** [comment]
@pat270 I've updated the SVG files on [LEXI-973](https://issues.liferay.com/browse/LEXI-973) please find the new SVG's there.
