### ISSUE TITLE
Date cannot be selected using the keyboard

### ISSUE THREAD

**Issue by linolaoj** [liferay/clay#3368]
-   [ ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Go to https://clayui.com/docs/components/date-picker.html and try to select a date using only the keyboard. After the date-picker expands when pressing _tab_ the focus goes to the next field and the date cannot be selected.
Note: The date-picker HTML is being appended at the end of the page body.
## What is the expected result?
Users should be able to focus on the date-picker using the keyboard.
## Environment
Tested on Chrome and Firefox.
| Tech  | Version |
| ----- | ------- |
| Clay  | v3.4.0  |
| React |         |

**Comment by diegonvs** [comment]
This may be caused because We aren't using FocusScope for handling focus on DatePicker. The DatePicker panel is a portal element and when open it will be attached to document.body.
