### ISSUE TITLE
When navigating on DatePicker via TABS and selecting dates with SPACE, we can multi select days 

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#3374]
-   [✅ ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

Just use the master's storybook: https://storybook-clayui.netlify.app/?path=/story/components-claydatepicker--default

## What are the steps to reproduce?

Open ClayDatePicker using space, then navigate thru dates using TABS and select using SPACE.

You'll notice is possible select multiple dates(at least the UI tells it 😂 )

<img width="547" alt="Screen Shot 2020-06-29 at 14 58 45" src="https://user-images.githubusercontent.com/7663513/86039598-09d31a80-ba19-11ea-96a4-85d11a30af38.png">

## What is the expected result?

Since We don't have a design specification for multi select dates, don't let user select multiple dates

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.4.0  |
| React | `undefined` |

**Comment by diegonvs** [comment]
Hey @pat270 @marcoscv-work @eduardoallegrini, I noticed this issue can't be reproduced when using Enter key. Do you guys have any markup/a11y guidance about this issue? Is there a difference between selecting elements using enter and space key?

**Comment by pat270** [comment]
@diegonvs I'm assuming the dates are using `<button>`. The browser triggers a click event when you press space on a button. The enter key does nothing for a button.

**Comment by eduardoallegrini** [comment]
Looking at the demo I can see there's not a real JS error, the `.active` class is being assigned correctly, the problem is the `:active` status of the button. Removing `.date-picker-date:not([disabled]):not(.disabled):active,` fix it.

<img width="1440" alt="Screenshot 2020-07-01 at 08 25 08" src="https://user-images.githubusercontent.com/46778114/86210583-208e8400-bb75-11ea-937a-b6c03616d954.png">

**Comment by pat270** [comment]
Looked into it further based on @eduardoallegrini comment. I can replicate on Clay CSS. It's a webkit browser bug (happens on Chrome and Safari) when tabbing + space quickly across a list of buttons fails to remove the `:active` state. 

We should probably fix this via JS. When space is pressed we should `event.preventDefault();` or also call `blur()`when removing `.active` class .

**Comment by diegonvs** [comment]
Hey @pat270, I tried add a keyUp listener for detecting when pressing SPACE key and then `preventDefault()` for avoiding this behaviour but with this code I can select multiple dates without tabbing+spacing quickly. Also, I tried to blur the element when changing the `active` state(using a useEffect with a ref for the button) but It still being reproduced. Also, I tried to retrieve the `event.target` on the click event and then `preventDefault()` but again, no success :/

**Comment by pat270** [comment]
@diegonvs I think you need to `event.preventDefault()` on `keydown` then on `keyup` you need to fire the click event or run the active method.

Here is a simple snippet I used in the console on the storybook site:
```
document.addEventListener('keydown', function(event) {
	var key = event.keyCode || event.which;

	if (key === 32) {
		event.preventDefault();
	}
});

var evt = document.createEvent('Event');

evt.initEvent('click', true, true);

document.addEventListener('keyup', function(event) {
	var key = event.keyCode || event.which;

	if (key === 32) {
		event.target.dispatchEvent(evt);
	}
});
```

**Comment by diegonvs** [comment]
It worked @pat270! Thanks! I'll send a PR
