### ISSUE TITLE
Lexicon with Bootstrap 3.x

### ISSUE THREAD

**Issue by sunilnizar** [liferay/clay#338]
We are working on a Liferay project to migrate theme from Bootstrap 3 to Lexicon. Found that latest Lexicon is using Bootstrap Alpha version. We do have a lot of utility classes and methods from Bootstrap 3.0 that won't support in Lexicon with Bootstrap 4.

Can someone please help us to get the Lexicon with Bootstrap 3.x and not the Alpha/4.0 bootstrap.
Or please advice the workaround to use bootstrap3.x with Lexicon? Can I just replace the bootstrap 4 with the latest stable version which is Bootstrap 3.x?

**Comment by pat270** [comment]
The 1.x branch is using boorstrap 3. https://github.com/liferay/clay/tree/1.x?files=1

**Comment by duracell80** [comment]
Something to keep an eye on in relation the browsers that your audience are using ... IE9 will be dropped IE 11 in Enterprise Mode has surely bitten the dust by now, but if you're rendering as IE8 in 11 also something to research.

https://v4-alpha.getbootstrap.com/getting-started/browsers-devices/

**Comment by jbalsas** [comment]
Closing as this has been answered. Just for reference, for Liferay Portal users in upcoming versions, we are planning to offer a compatibility layer to make BS3 developments partly compatible with BS4 to ease up upgrade efforts.
