### ISSUE TITLE
BS4 compat layer - Buttons shadow

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#339]
Some shadows in buttons we don't need:

![image](https://user-images.githubusercontent.com/7963804/27594158-640b68f8-5b59-11e7-8f1e-f811692a4f6c.png)

**Comment by fernandosouza** [comment]
You say that because the shadows are not recognisable?

**Comment by marcoscv-work** [comment]
Sorry, too sort description.

The Atlas design and new "atlas 2" design has not shadows in buttons, but with the change to BS4 the shadows have encountered a way to reappear :-P

I've sent this pull to Patrick but probably this variable finally should be placed in atlas theme, but by the moment I think this file is the correct one to have the change located, at least while we are finding out the way to jump to BS4.
https://github.com/pat270/lexicon/pull/92

**Comment by pat270** [comment]
Merged at https://github.com/liferay/clay/commit/1dd86f631d9cebb4517312a7ee2d35377c759c53
