### ISSUE TITLE
BS4 compat layer - Buttons mixing of btn-default and btn-primary

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#340]
When you combine buttons they can be shown wrong,  this pattern happen a lot in liferay-portal.

btn-default & btn-primary + hover state:
![image](https://user-images.githubusercontent.com/7963804/27723291-a33a94f8-5d6c-11e7-95f7-b7d503cebe1f.png)

**Comment by marcoscv-work** [comment]
https://github.com/liferay/clay/pull/341

**Comment by yuchi** [comment]
IMHO this is the portal not respecting the BS contract. Should be fixed there, non on Clay.

**Comment by jbalsas** [comment]
Hey @yuchi, glad to see you around! 😉 

We are implementing a bs3-bs4 compat layer for liferay portal to ease up our own migration process. We plan to cover all these small changes and fix the portal side until we can get rid of everything.

**Comment by yuchi** [comment]
Hi @jbalsas, yeah sorry for not being so present anymore…

Is 7.0 going to migrate to BS4 then? I think it’s a little bit risky…

**Comment by jbalsas** [comment]
We're in a bit of a crosshairs here, but yes, the idea is to migrate to BS4.

**Comment by pat270** [comment]
This is an issue in Portal.
