### ISSUE TITLE
SVG xmlns inconsistence

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#3402]
`bold.svg`, `cards2.svg` and `decimal.svg` files start with:

```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512">
```

while the rest of the icons start with

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
```

That's causing problems using them as background images. Don't know exactly what's the difference but it's not working.

**Comment by pat270** [comment]
@carloslancha going to close, this is already fixed. 

master: https://github.com/liferay/clay/pull/3360
2.x: https://github.com/liferay/clay/pull/3361

**Comment by carloslancha** [comment]
Great! 👏 👏
