### ISSUE TITLE
v2-beta: Remove Font Awesome

### ISSUE THREAD

**Issue by pat270** [liferay/clay#342]
Bootstrap 4 dropped all icon fonts, left up to 3rd party devs to include whatever icon font they want.

**Comment by jbalsas** [comment]
Makes sense. UX has specifically asked that only designed svg icons are shipped by default, so we are also going in this direction. 

We just need to make sure we have a clear path for developers to add icon fonts and use them independently of what we ship in clay.

**Comment by yuchi** [comment]
If themes could depend on bundles then we could have FA3 and FA4 resource providers.

@jbalsas Can the new loader help on this? Are static packages’ resources available?

**Comment by jbalsas** [comment]
Yeah, I think all resources are available when bundled using the new method. In any case, it sounds like these could go as ThemeContributors, for example.

**Comment by jbalsas** [comment]
Just for clarification, we want to stop bundling the icon fonts in Clay, but we'll still figure out a way to provide them in Liferay Portal ootb.

**Comment by yuchi** [comment]
> […] these could go as ThemeContributors […]

Well, usually I thinks it’s a theme’s responsibility to bring the icon packs to the page but actually it’s more an editorial requiriment.

So from one side apps and themes should be able to “ask” for an icon pack, but also editors need to access them. Totally Out Of Topic™ but having a DDM field type “Icon” where you can choose one from the available icon packs would be totally awesome.

**Comment by jbalsas** [comment]
ThemeContributors (albeit its bad name) add resources globally independently of the applied Theme. That's why it might be a good option to make them easily available. They double as themelets, so a themelet including FA4 could make it be always available if deployed as a ThemeContributor.

Out of Topic™, where and how would you use the Icon field? Is this something that should be needed inside the WYSWYG editors as well?

**Comment by yuchi** [comment]
Out of Topic™, for example if you are writing a list of features of a product (see [this example from smc.it](https://www.smc.it/solutions/open-square-ecm#p_56_INSTANCE_fltKwgQ0yUFp)). Sometimes you have them as rasterized images, sometimes as SVG, sometimes as icons in the icon packs have in the page (typically font-awesome). Another very good case are Call to Actions and buttons (see [later in that same page](https://www.smc.it/solutions/open-square-ecm#p_56_INSTANCE_wWQaH3hPUbwe)), where icons must be either icon fonts or vectorial.

**Comment by yuchi** [comment]
The perfect solution would be an icon chooser, configurable to accept (or not) files from the DM and/or icon fonts and/or SVG icons.

**Comment by yuchi** [comment]
Other examples where such a selector would have benefitted: [click on a slice here (it’s a Web Content structure/tmpl)](https://www.axa.it/assicurazione-auto#p_56_INSTANCE_Eo5UgWk7kMs9), or look at [«Servizi Online» in this page](https://www.ulss.tv.it#p_56_INSTANCE_alNnghVfIFre), or as [_AssetCategoryProperty_ values here](https://www.ulss.tv.it/prestazioni).
