### ISSUE TITLE
JSP code example snippet tracking

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3424]
This is a place to keep an overview of our components that need to have JSP code examples.

Component | Example Location | Issue | PR
------------ | ------------- | ------------- | -------------
Alert | [LPS-112456](https://issues.liferay.com/browse/LPS-112456) | #3425 | #3427 
Application Bar | Example Location | Issue | PR
Badge | [LPS-112457](https://issues.liferay.com/browse/LPS-112457) | #3428 | #3429 
Breadcrumb | Example Location | Issue | PR
Buttons | [LPS-112458](https://issues.liferay.com/browse/LPS-112458) | #3444  | #3446 
Card | Example Location | Issue | PR
Checkbox | Example Location | Issue | PR
Color Picker | Example Location | Issue | PR
Date Picker | Example Location | Issue | PR
Drop Down | [LPS-112460](https://issues.liferay.com/browse/LPS-112460) & [LPS-112461](https://issues.liferay.com/browse/LPS-112461) | #3649 | #3650 
Dual List Box | Example Location | Issue | PR
Empty State | Example Location | Issue | PR
Form | Example Location | Issue | PR
Icon | [LPS-112464](https://issues.liferay.com/browse/LPS-112464) | #3447 | #3449
Input | Example Location | Issue | PR
Label | [LPS-112466](https://issues.liferay.com/browse/LPS-112466) | #3454 | #3455 
Layout | Example Location | Issue | PR
Link | [LPS-112467](https://issues.liferay.com/browse/LPS-112467) | #3632 | #3633
List | Example Location | Issue | PR
Loading Indicator | Example Location | Issue | PR
Localized Input | Example Location | Issue | PR
Management Toolbar | Example Location | Issue | PR
Modal | Example Location | Issue | PR
Multi Select | Example Location | Issue | PR
Multi Step Nav | Example Location | Issue | PR
Nav | Example Location | Issue | PR
Navigation Bar | [LPS-112470](https://issues.liferay.com/browse/LPS-112470) | #3456 | #3457
Pagination | Example Location | Issue | PR
Panel | Example Location | Issue | PR
Popover | Example Location | Issue | PR
Progress Bar | [LPS-112471](https://issues.liferay.com/browse/LPS-112471) | #3634 | #3635 
Buttons | Example Location | Issue | PR
Radio Group | [LPS-112472](https://issues.liferay.com/browse/LPS-112472) | #3647  | #3648
Select | Example Location | Issue | PR
Select Box | Example Location | Issue | PR
Slider | Example Location | Issue | PR
Sticker | [LPS-112474](https://issues.liferay.com/browse/LPS-112474) | #3466  | #3468 
Table | Example Location | Issue | PR
Tabs | Example Location | Issue | PR
Time Picker | Example Location | Issue | PR
Toggle Switch | Example Location | Issue | PR
Tooltip | Example Location | Issue | PR
Upper Toolbar | Example Location | Issue | PR

**Comment by bryceosterhaus** [comment]
@kresimir-coko thanks for creating this!

**Comment by kresimir-coko** [comment]
@jbalsas so I've added examples for the ones that are closed in [LPS-112371](https://issues.liferay.com/browse/LPS-112371). 
Any tips on finding the rest? I tried just searching for a couple but they didn't exist, atleast apart from the `frontend-taglib-clay-sample-web` module.

**Comment by kresimir-coko** [comment]
`<clay:checkbox />` - Exists only in `frontend-taglib-clay-sample-web`
`<clay:link />` - Exists but it's most likely an old variant as some of them have been added years ago
`<clay:dropdown-actions />` - Exists but possibly it's an old variant as some of them have been added a year ago
`` -
`` -
`` -

**Comment by jbalsas** [comment]
> Any tips on finding the rest? I tried just searching for a couple but they didn't exist, atleast apart from the frontend-taglib-clay-sample-web module.

I think it might be better to work on the new architecture information after this and then keep completing with examples... no need to do archeology for this. Some we might discard, some will have other APIs, like `Modal` or `Toast`. So let's rearrange what we have and come back to this later!

**Comment by kresimir-coko** [comment]
What constitutes `architecture information` in this context @jbalsas ? Are we talking about the architecture of our docs -> #3451 or documenting JSP architecture? Or something third?

**Comment by jbalsas** [comment]
> Are we talking about the architecture of our docs -> #3451

👆

**Comment by kresimir-coko** [comment]
Hey @jbalsas I've sent the last PR here from the list found in [LPS-112371](https://issues.liferay.com/browse/LPS-112371). 
Is there another epic, or a list of some other components that we should start adding examples of?

**Comment by kresimir-coko** [comment]
@jbalsas did we add any new components that we should document as part of this issue?

**Comment by kresimir-coko** [comment]
@brunofernandezg this issue looks like a good one to keep around, because it serves as a single source of truth on which components have examples, and which components need examples added. Maybe we can add a different status to it?

**Comment by brunofernandezg** [comment]
@kresimir-coko if you remove yourself as assignee in GitHub (I just did it) the task will automatically go back to open in Jira.

**Comment by matuzalemsteles** [comment]
I'm closing this issue because we are no longer going to add JSP snippet to the examples in the current documentation in the way it is organized today, we have a different idea for this to have a space to create documentation just for taglibs... we are tracking this in issue #4128
