### ISSUE TITLE
Update icons: align-image  icons

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3432]
Due to [LEXI-979](https://issues.liferay.com/browse/LEXI-979). Lexicon has updated the image alignment icons:

- _align-image-left_
- _align-image-center_
- _align-image-right_

![image-alignment-icons](https://user-images.githubusercontent.com/21216422/86374691-25425d80-bc85-11ea-91c6-6cc58ee2df4e.png)

Please update these icons. Find the SVG's on the ticket.
Thanks!

**Comment by pat270** [comment]
fixed by https://github.com/liferay/clay/pull/3458
