### ISSUE TITLE
Icon: paste as plain text

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3450]
Due to [LEXI-934](https://issues.liferay.com/browse/LEXI-934). Lexicon has created a Paste variation icon for CK Editor.

![paste-plain-text](https://user-images.githubusercontent.com/21216422/86460714-2d53d900-bd29-11ea-9941-d58e00134154.png)

We named it _paste-plain-text_. 

Please add it to the icon library. Find the SVG on the ticket.
Thanks!

**Comment by pat270** [comment]
@drakonux I ended up renaming to `paste-plaintext` from `paste-plain-text`.

**Comment by pat270** [comment]
fixed by #3467

**Comment by drakonux** [comment]
@carloslancha @pat270 I've added the RTL version. Find the SVG on the ticket.

![paste-plain-text-rtl](https://user-images.githubusercontent.com/21216422/87132005-8970ad00-c295-11ea-9e5c-e598781dbc51.png)
