### ISSUE TITLE
@clayui.com/css _global-functions.scss move autogenerated $lx-icons variables to separate file

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3469]
Spawned from https://github.com/liferay/clay/pull/3458#issuecomment-654632178.

> It's easier to track autogenerated things independently so one knows what can be edited manually and what shouldn't. It also helps in cases like this where simply re-running the generation scripts is enough to get back to a consistent state.

We should consider moving the autogenerated `$lx-icons` variable to a separate file. I'm thinking of placing it in the same directory `clay-css/src/scss/functions/_lx-icons-generated.scss` and `@import '_lx-icons-generated.scss';` at the top of `_global-functions.scss`?

**Comment by kresimir-coko** [comment]
Hey @pat270 I don't have much to say here except that moving autogenerated variables away from manually typed ones is always good, and especially naming the file appropriately 👍

**Comment by brunofernandezg** [comment]
@pat270 @edalgrin I added this tasks to next release milestone. Remember please to add any finished clay task to a milestone so the work is tracked on the epic. Thanks!

cc\ @bryceosterhaus
