### ISSUE TITLE
New `min-width` for Card component

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#3479]
## We need to fit 4 cards in a standard `sheet-lg`

Probably we need to set the new value on 186px (aprox).

**Comment by pat270** [comment]
@marcoscv-work `min-width: 193px` for `.card-page-item-asset` makes 4 cards fit inside `sheet-lg`. Do we want it `186px`?

**Comment by marcoscv-work** [comment]
> @marcoscv-work `min-width: 193px` for `.card-page-item-asset` makes 4 cards fit inside `sheet-lg`. Do we want it `186px`?

Of course! thanks!

**Comment by jbalsas** [comment]
Is there a way we could add a temporary workaround in `DXP` until we can merge this in? Based on the last release (which still hasn't made it, it might be a while...)

**Comment by marcoscv-work** [comment]
> Is there a way we could add a temporary workaround in `DXP` until we can merge this in? Based on the last release (which still hasn't made it, it might be a while...)

of course!! applying min-width: 193px in admin theme for example
