### ISSUE TITLE
v2-beta: Toolbar component remove, keep, or convert to flex box

### ISSUE THREAD

**Issue by pat270** [liferay/clay#348]
Not sure what to do with this. The namespace is really common and collides easily with 3rd party stuff. At the very least it should be converted to flexbox, don't see much benefit of keeping it table based.

**Comment by pat270** [comment]
Decided to remove it at 20edc5f077e93a8ccfade908fefe6857c31a26b4

**Comment by jbalsas** [comment]
Sounds like a good call to me, thanks @pat270!
