### ISSUE TITLE
SVG Icons using <use href=""> doesn't inherit color

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3495]
#3149 uses `[href]` to style link colors, we should reset these styles in `use[href]`.

<img width="129" alt="svgwrongcolor" src="https://user-images.githubusercontent.com/788266/87183370-e3c03c80-c29a-11ea-8ee5-c7ea3f991e4f.png">

**Comment by bryceosterhaus** [comment]
merged at https://github.com/liferay/clay/pull/3509
