### ISSUE TITLE
Should we collapse code examples by default?

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3502]
@bryceosterhaus @matuzalemsteles @pat270 @jbalsas 

What do you guys think, should we collapse the code examples by default, to increase visibility and discoverability across the site? Or do we keep it as is right now?

This was brought up a couple times in the past, and most recently [here](https://github.com/liferay/clay/pull/3491#issuecomment-656872363)

**Comment by jbalsas** [comment]
> What do you guys think, should we collapse the code examples by default, to increase visibility and discoverability across the site? Or do we keep it as is right now?

I don't see any harm in trying it... it's true that some code samples are pretty huge and make it hard to find the documentation. 

@drakonux might have some thoughts?

**Comment by drakonux** [comment]
I think is a good idea, the real content is your explanations and definitions. The users that need to copy/consult the code can always access it interacting by. But really, you know your users better than me and I'm not a developer...

**Comment by matuzalemsteles** [comment]
I prefer collapsed too, but I was wondering if the user doesn't understand the `expand` icon? as I'm more used to the site then there would be no problem... maybe we can add the text "CODE" next to the `expand` icon, this can help.

**Comment by bryceosterhaus** [comment]
Sounds good to me. I agree with Matu that we need to make sure its clear the user knows there are code examples to be seen, but other than that I think this would be a good change.

**Comment by pat270** [comment]
Yes good idea.

**Comment by eduardoallegrini** [comment]
Can't we use small previews with an expand button? https://codepen.io/eduardoallegrini/pen/PoZBMRY

**Comment by kresimir-coko** [comment]
@eduardoallegrini 
> Can't we use small previews with an expand button?

While it is a good idea on paper, plenty of examples won't show the meaty parts of the example above the fold, making them take up the space, but not providing any real value. 

I think that just collapsing them by default and maybe redesigning how the collapsed code example looks should be enough, just to make sure the reveal icon is very easy to find.

**Comment by pat270** [comment]
If someone actually prefers to have all code examples open, we could store the setting in localStorage and have it collapsed/expanded based on that

**Comment by kresimir-coko** [comment]
Fixed in #3523
