### ISSUE TITLE
ClayColorPicker doesn't have a small variation

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#3514]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

https://codesandbox.io/s/xenodochial-thunder-tt314?file=/src/index.js

## What are the steps to reproduce?

Placing a ClayColorPicker inside a ClayForm.Group with the small property set to true or pass the property sizing="sm" to the ClayColorPicker

## What is the expected result?

The ClayColorPicker is show in the small input variation (32px instead of 40px)

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.2.4  |
| React |         |

**Comment by victorg1991** [comment]
@marcoscv-work I think we also have to update the React component, right? At least for adding a new prop to select the variant

**Comment by jbalsas** [comment]
You're probably right, @victorg1991!

We're short on React people today, but will more than welcome a contribution! 😘 

Reopening so we don't think this is done.

**Comment by pat270** [comment]
It looks like we might need to add something. I can't seem to pass in a class to `clay-color input-group` on https://clayui.com/docs/components/color-picker.html. If you're using `form-group-sm`, we don't need to add anything to the React component.
