### ISSUE TITLE
Small visual updates for LocalizedInput

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#3518]
## What is your proposal?

It looks like both segments and web content have their own localized input, but was wondering if Clay's could have some APIs to make it resemble theirs? We're creating another admin page using the same localized input header and [Clay's current localized input](https://clayui.com/docs/components/localized-input.html) doesn't seem to cover this use case. Also would be nice in case other teams were considering to adopt it. 

![image](https://user-images.githubusercontent.com/14063502/87699590-ef53ad80-c749-11ea-8869-ffa1842ca926.png)
![image](https://user-images.githubusercontent.com/14063502/87700036-93d5ef80-c74a-11ea-8cf9-964896654f51.png)

Options:
- position icon to the left of the input
- hide selected locale subtext
- border and locale on the icon

Also, I think there's a typo in 'untranslated' in the dropdown 😅 

Thanks!

@thektan

**Comment by bryceosterhaus** [comment]
Hey @oliv-yu thanks for the proposal!

@drakonux does this fall under the lexicon specification? Wasn't sure what the configurability we wanted to provide with this design.

**Comment by drakonux** [comment]
Hey, @oliv-yu I agree DXP must have these two cases **unified using the same component**. 

However, @bryceosterhaus this variation of the [localized-input](https://clayui.com/docs/components/localized-input.html) has enough differences to be a unique component just for DXP (cc\ @jbalsas ). 

Besides, as far as I know, this component needs a deeper review (interaction and visual). 

My recommendation would be to not add it to Clay and if a DXP team wants, they can open us a request, and Lexicon will work on a definition to allow DXP to standardize the component (portal designers can also have a meeting and get an agreement about it).

**Comment by thektan** [comment]
Thanks @drakonux! I've created a lexicon request here: https://issues.liferay.com/browse/LEXI-988

**Comment by kresimir-coko** [comment]
As @drakonux said:
> My recommendation would be to not add it to Clay and if a DXP team wants, they can open us a request, and Lexicon will work on a definition to allow DXP to standardize the component (portal designers can also have a meeting and get an agreement about it).

@jbalsas Do we not add this to Clay and thus, close this issue?

**Comment by jbalsas** [comment]
Yeah, I think the goal would be to add this component to `frontend-components` in `DXP` directly rather than having it inside Clay

**Comment by kresimir-coko** [comment]
Alright, closing this then 👍 
> Yeah, I think the goal would be to add this component to frontend-components in DXP directly rather than having it inside Clay
