### ISSUE TITLE
Show only the custom color selector in ClayColorPicker React component

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#3527]
## What is your proposal?
Right now, It is not possible to show a ClayColorPicker that only shows the custom color selector without the color palette above. 
Something like this:
![Screenshot 2020-07-20 at 14 50 21](https://user-images.githubusercontent.com/11654230/87939776-d8d68a80-ca98-11ea-82e7-ff1c2a6c4563.png)

## Why would adopting this proposal be beneficial?
More flexibility in the case like me color palette is not needed

## What are the alternatives to this proposal?
Using the useNative prop in the ClayColorPicker will show the default color picker which doesn't have color palette.. but is is not ideal.

**Comment by bryceosterhaus** [comment]
@drakonux, does this fit within the lexicon definition? If so, I can add an ability to toggle that palette on/off.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, I think this seems like a reasonable request that should come at a small price.

I think ColorPicker is complex enough so that low-level components won't do to implement it, so having props to pick which features to use from it makes sense to me.

That being said... @victorg1991, are you sure you don't want the palette? This makes sense out of context, but in the context of StyleEditor (if that's where you're applying it...) maybe it would be good to have the palette populated with the colours for the primary tokens... just a thought 😉

**Comment by drakonux** [comment]
> @drakonux, does this fit within the lexicon definition? If so, I can add an ability to toggle that palette on/off.

The Lexicon team published the Color Picker time ago and it has a "mode": [custom color panel](https://liferay.design/lexicon/core-components/forms/picker-color/#custom-color-panel) and this is the [technical document](https://docs.google.com/document/d/1IUGl5VOWh6lqRa1baRoshVcytc8XbqVMkk30vRW4SM8/edit#heading=h.jkrp0t7cj15n) we currently have.  

Does it fit? It's quite similar, without the colors cell set and the feature to allow to change between panels.  But I would have to know more about the usage they are going to do, their requirements and review the definition we made.

**Comment by victorg1991** [comment]
@jbalsas I talked with Juan about it and we decided it was better to have only a custom color picker without the palette. The idea behind is that we are going to be able to reference other variables so in case the user wants the primary color it will link the current variable to the --primary variable instead of using the concrete color value of primary (choosing the color from the palette) Does it makes sense? :)

Maybe in the future, the color picker could receive a list of CSS variables and allow the user to select the variable instead of the specific color

**Comment by victorg1991** [comment]
@drakonux this mode includes a color palette at the top which wouldn't be so useful for our case :(

**Comment by drakonux** [comment]
Hey @victorg1991 I'm not saying you need it. Just saying that the component was defined in that way ;). 

Now, knowing your needs, probably the best aproach @jbalsas @bryceosterhaus should provide a way to disable the colors cell set in the component or a variation without the palette.

**Comment by bryceosterhaus** [comment]
👍 sounds good! I figured it would be easy to add, but I just wanted to verify with design first in case it was breaking any patterns they had.
