### ISSUE TITLE
Elements with hidden attribute are no longer supported?

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#3533]
Hey @pat270 I noticed that in some cases the hidden attribute that was present in the [Bootstrap reboot](https://getbootstrap.com/docs/4.5/content/reboot/#html5-hidden-attribute) is used in the portal as we removed it, is there any reason why we removed it?

I noticed that we use it in a `select` tag that we seem to need because `type="hidden"` has no effect on it, it seems to be a standard browser behavior.

**Comment by pat270** [comment]
@matuzalemsteles yeah it's removed https://github.com/liferay/clay/pull/3271#pullrequestreview-416692356. I'll add it back in. I don't think `type="hidden"` is valid on a `select` tag.

`<select hidden>` should hide the element, but because `.form-control` adds `display: block;` it wins.
