### ISSUE TITLE
@clayui/color-picker Inconsistencies in Focus Behavior

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3539]
Color Picker Default: 
- Selecting a color with `enter` or `click` closes dropdown menu and focuses dropdown toggle splotch
- Tab into dropdown menu then close with `esc`, focus is between hex value input and next element
- Tab into dropdown menu then click outside menu, focus is where user clicked

Color Picker Custom: 
- Tab into dropdown menu then close with `esc`, focus is between hex value input and next element
- Tab into dropdown menu then click outside menu, focus is where user clicked

Color Picker Native:
- Selecting a color with `enter`, focus is on dropdown toggle splotch
- Tab into menu then close with `esc`, focus is on dropdown toggle splotch
- Tab into menu then click outside menu, focus where user clicked

We should normalize where the focus is placed when closing a color picker menu via keyboard. I think it should always return to the dropdown toggle splotch when the menu closes with `esc` or `enter`.

Other color picker focus issues:
- A button with `tabindex="-1"` is still part of the tab order
- ~HSB map pointer isn't keyboard focusable (needs `tabindex="0"` or change element to `button`)~

**Comment by bryceosterhaus** [comment]
@pat270 

> HSB map pointer isn't keyboard focusable (needs tabindex="0" or change element to button)

I'm not seeing this, which element are. you taking about exactly? I am seeing that both the Hue and Gradient pointers are `<button>`

**Comment by pat270** [comment]
@bryceosterhaus I fixed that one in the mobile pull. #3577

**Comment by bryceosterhaus** [comment]
@pat270 oh perfect! Thanks. I just updated it so that the picker closes on escape and focuses the splotch https://github.com/liferay/clay/pull/3597
