### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#354]
Hi!

I'm implementing the sticker component in metal-clay but I'm having some issues with the styling. I've done following http://liferay.github.io/clay/content/badges-and-labels/ markup, but there're classes that doesn't exist like sticker-circle, sticker-default, sticker-static, etc.

Are those classes missing or do I have to use other markup?

Also I noticed that the previous .sticker had an absolute positioning by default (overwritten by .sticker-static if necessary). It would be very helpful having examples of the correct current markup.

Thx!

**Comment by Robert-Frampton** [comment]
Hey @carloslancha 

The http://liferay.github.io/clay site isn't ever going to be updated with Clay 2.0 markup/examples, it's simply there for legacy purposes.

The new electric based clay site is in the works at https://github.com/Robert-Frampton/claycss.com/tree/2.0.

@pat270 , can you share the google doc you have with Carlos that details which components are finished in Clay 2.0? The components that are listed as finished in this doc are the only ones that also have updated docs in the electric site.

**Comment by pat270** [comment]
Hey Carlos,

A few things have changed, `.sticker-default` is `.sticker-secondary` now. We've also added `.sticker-light` and `.sticker-dark` to keep it inline with Bootstrap 4's variant colors. Stickers can be positioned absolute by using the positional classes `.sticker-top-left`, `.sticker-top-right`, `.sticker-bottom-right`, and `.sticker-bottom-left`. The borders can be modified using the Bootstrap 4 border utility classes `.rounded-0`, `.rounded`, `.rounded-circle`.

You can also run the old docs site using the develop branch and it should have updated markup as well. We're still in alpha and so is Bootstrap 4 so mark up will probably change even if it's "done".

**Comment by carloslancha** [comment]
Great guys, Thx!!
