### ISSUE TITLE
Update docs on releasing individual packages

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3544]
I accidentally released `modal` without `shared` since we document to use `yarn version` for individual packages. We need to revisit this and how to properly do this with checking dependency packages.

**Comment by wincent** [comment]
It would be pretty easy to make a preflight script that ensures that any single package's dependencies are available and published prior to publishing (although it would end up being a kind of nano-Lerna, itself, which may not be a bad thing 🤷😀).

**Comment by bryceosterhaus** [comment]
Part of the problem was that I didn't realize a dependency had updated and required a new version. So even if we had a pre-flight script to verify dependencies, it would've shown that `@clayui/shared` was already published but unknown that `@clayui/shared` needed a new release and update that version in modal.

I was hoping lerna had a mechanism for this, but looks like they always tie all releases together and don't allow for _one-off_ releases.

See https://github.com/liferay/clay/pull/3554 for at least an updated checklist

**Comment by wincent** [comment]
> it would've shown that `@clayui/shared` was already published but unknown that `@clayui/shared` needed a new release and update that version in modal.

Just to check that I understand this, what you're saying is:

- `@clayui/modal` depended on version X de `@clayui/shared`.
- Newest release of `@clayui/shared` was actually X + 1.
- `@clayui/modal` actually needed later commits on master from `@clayui/shared` (ie. needed release X + 2).

Is that right?

I think the script can operate on two levels:

1. It could report that X + 1 is out and dependency should be updated. This would catch some problems (although not the one that you ran into on this occasion).
2. It could show a list of PRs merged into master-but-not-yet-published touching the dependencies (ie. `@clayui/shared`) of the package you want to release (ie. `@clayui/modal`). Given that we release often, and internal dependencies are relatively minimal inside Clay, hopefully this list wouldn't be too long. Obviously, would rely on human perception and judgement to determine whether anything in the list actually mattered and would require a release, but it still would give us a chance of catching more issues than now.

The other angle is to just forget about trying to make individual releases more robust and instead optimize the process of releasing everything at once; if you can reduce the cost low enough, then releasing everything as a batch becomes cheaper than doing a careful single-package release.
