### ISSUE TITLE
Alerts: Replace times with times-small

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3557]
Hi Clayers!

I'm updating the Figma library with the new feature [autolayout ](https://issues.liferay.com/browse/LEXI-838)and I also reviewing distances, sizes and little details. I started with [Alerts ](https://issues.liferay.com/browse/LEXI-843)and I would like to change the following:

## Proposal

- Change times icon with times-small for Alerts

## Current

![image](https://user-images.githubusercontent.com/21216422/88372630-98c42000-cd96-11ea-8a0b-d6bc435a8240.png)

14x14. I think the font size: 0.875 changes the normal size of the icon to that value.
## Expected

<img width="355" alt="12px" src="https://user-images.githubusercontent.com/21216422/88371718-df187f80-cd94-11ea-9650-9f3ed5aeb46a.png">

Using _times-small_ 12x12 (by design without changing the font-size)

**Comment by pat270** [comment]
@bryceosterhaus @matuzalemsteles We can change this in the Clay Component + docs or we can keep the icon and use padding on the close button to make it smaller in Clay CSS. Not sure which way would be safer.

**Comment by matuzalemsteles** [comment]
@pat270 when you say Clay Component, we add some style attribute? I think the best way would be to change the CSS to ensure consistency of markup and visual. When not using the components.

**Comment by pat270** [comment]
I mean changing `times` https://github.com/liferay/clay/blob/master/packages/clay-alert/src/index.tsx#L177 to `times-small`. We would have to update this in our CSS docs as well.

**Comment by pat270** [comment]
If we decide to fix this via CSS I'll use `font-size: 12px` on close button for alerts.

**Comment by pat270** [comment]
>  change the CSS to ensure consistency of markup and visual. When not using the components.

makes sense, we should fix via CSS.

**Comment by matuzalemsteles** [comment]
I see, sorry. Hmm looking closely it looks like `times-small` comes close to 12px but it looks like 10.5px on the icon, so maybe it’s better to change the font-size to `12px` in the CSS?
