### ISSUE TITLE
Alerts: Fix paddings and distances

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3558]
Just before changing a distance, probably someone can explain me that there is a good reason to have distances not multiple of 8px (maybe the Lexicon team did a visual change agreed with you or similar) so this is a question/proposal about it. 

## Proposal

- Paddings must be 16px.
- Distance between the text block and the footer must be 16px.

## Current
![image](https://user-images.githubusercontent.com/21216422/88378679-c367a600-cda1-11ea-9ea6-a64e4ab69793.png)
**Paddings**: 16px 17.5px

![image](https://user-images.githubusercontent.com/21216422/88378974-56084500-cda2-11ea-8e56-25599db8f2a3.png)
**Margin between text block and footer**: 22px 

## Expected
![image](https://user-images.githubusercontent.com/21216422/88379341-0d04c080-cda3-11ea-92e2-d6fe4c37fd8f.png)

**Paddings**
![image](https://user-images.githubusercontent.com/21216422/88379527-6bca3a00-cda3-11ea-88dd-1a143030823f.png)

**Distance between the text block and footer**
![image](https://user-images.githubusercontent.com/21216422/88379155-b0090a80-cda2-11ea-8fb4-e033e5f1162c.png)
**Note**: The line-height we use in Figma for the text block is 21px. The distance between buttons in this screenshot is wrong, it must be 16px.

**Comment by pat270** [comment]
@drakonux I can make these changes.
