### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#356]
Hi!

Alerts doesn't match with Lexicon designs. Here the documentation:
https://docs.google.com/document/d/1mR8k7TE_5s6wzn94HtM7kB3NYVItDMoi4RkKZ0yRezw/edit#heading=h.jkrp0t7cj15n

Thx!

**Comment by Robert-Frampton** [comment]
Hey @carloslancha 

A number of the new designs haven't been implemented in the Atlas theme yet. The plan was to begin work implementing the new designs in August once most of the structural changes have been made to Clay.

As the new designs are implemented we'll be closing LEXI tickets that are assigned to Frontend Infrastructure on JIRA to track our progress. So https://issues.liferay.com/browse/LEXI-153 is the JIRA issue for Alerts.
