### ISSUE TITLE
@clayui/css: Add `c-inner` functionality to modal, popover, and inline-scroller

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3583]
Users should be able to tab into boxes with overflowing content and scroll using up and down arrows. The components that need updating:
- modal
- inline-scroller (dropdown menu)
- autocomplete-dropdown-menu
- drilldown
- color-picker
- popover

**Comment by jbalsas** [comment]
> Users should be able to tab into boxes with overflowing content and scroll using up and down arrows. The components that need updating:

Tabing into a box is super weird... I'd like to see some research on how to do this before we jump to implement anything.

**Comment by pat270** [comment]
Closing this since we are taking a different route.
