### ISSUE TITLE
Localized Input Labels are broken after Drilldown update

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3591]
Localized Input Dropdown Menu Labels are broken with the Drilldown update.
<img width="274" alt="localized-input-dropdown" src="https://user-images.githubusercontent.com/788266/89606755-b0cf8100-d825-11ea-93c1-836d59e5cab9.png">
We are using the markup:
```
<div class="dropdown-menu dropdown-menu-indicator-end show">
  <ul class="list-unstyled">
    <li>
      <button class="dropdown-item">
        <svg class="lexicon-icon lexicon-icon-en-us inline-item inline-item-before" role="presentation">
          <use xlink:href="static/media/icons.6508b159.svg#en-us"></use>
        </svg>
        en-US
        <span class="label dropdown-item-indicator-end label-info">
          <span class="label-item label-item-expand">Default</span>
        </span>
      </button>
    </li>
  </ul>
</div>
```
`dropdown-item-indicator` was never intended to be used this way. It was always intended that we use the `autofit` utilities for this:
```
<ul aria-labelled-by="theDropdownToggleId" class="dropdown-menu">
  <li>
    <a class="autofit-row dropdown-item" href="#1">
      <span class="autofit-col autofit-col-expand">
        <span class="autofit-section">
          <span class="inline-item inline-item-before">
            <svg class="lexicon-icon lexicon-icon-en-us" focusable="false" role="presentation" viewBox="0 0 512 512"></svg>
          </span>
          en-US
        </span>
      </span>
      <span class="autofit-col">
        <span class="label label-info">
          <span class="label-item label-item-expand">Default</span>
        </span>
      </span>
    </a>
  </li>
</ul>
```
The `dropdown-item-indicator` pattern has been in Portal for a while now. Do we support it or can we change to using the `autofit` pattern? The problem with the indicator pattern is if there is long text that breaks to new line, the label will overlay on top of the text:
<img width="266" alt="indicator-pattern" src="https://user-images.githubusercontent.com/788266/89607041-639fdf00-d826-11ea-8a30-e4d789f78b71.png">

**Comment by jbalsas** [comment]
Hey @pat270, if it was not intended it was not intended. Pinged you at https://liferay.slack.com/archives/CL9RTSZ52/p1596799011017600 (private conversation)

This was reported and fix as [Page Editor dropdown labels have wrong size](https://issues.liferay.com/browse/LPS-118650)

**Comment by pat270** [comment]
Thanks @jbalsas ! We actually use this pattern in Clay Localized Input at https://github.com/liferay/clay/blob/master/packages/clay-localized-input/src/index.tsx#L179. I believe we copied the markup straight from Portal. I can update the component to use the autofit pattern.

**Comment by pat270** [comment]
Reopening, we need this fixed in Clay Localized Input.
