### ISSUE TITLE
We should have a centralized localStorage module

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3611]
With increasing implementations using `localStorage`, we should have a module that eliminates the site breaking when working with Local Storage.
The module should be imported in the several places where we use `localStorage` and abstracts over the check/fallback required to make it work flawlessly.
Inspired by [this Slack thread](https://liferay.slack.com/archives/G3JBR21HA/p1597231455165800)

**Comment by wincent** [comment]
![you-inspire-me](https://user-images.githubusercontent.com/7074/90114210-b4e22e00-dd52-11ea-84f6-67f75616df1c.gif)
