### ISSUE TITLE
Improve Tooltip documentation with available options for positioning

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#3612]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?

Go to Tooltip documentation https://clayui.com/docs/components/tooltip.html

## What is the expected result?

Maybe it's an improvement to add in the documentation the available options to align the tooltip. I only saw that "bottom" it's the default one. Although, in the source code I can see:

```js
export const ALIGN_POSITIONS = [
	'top',
	'top-left',
	'top-right',
	'bottom',
	'bottom-left',
	'bottom-right',
	'left',
	'right',
] as const;
```

This is only a proposal 😄 

Thanks!

**Comment by matuzalemsteles** [comment]
Makes sense, I think this is one of the flaws in our other documents as well, as our Table APIs are generated automatically through `react-docgen` yet it does not support some use cases. @bryceosterhaus @kresimir-coko maybe it's time we to start evaluating other options or thinking about merged this PR https://github.com/reactjs/react-docgen/pull/352 that adds better support, this is a long time ago but there is no return that will be merged.

**Comment by kresimir-coko** [comment]
This would be very nice, I don't know where to begin with merging the linked PR, instead I can take a look at some other options. Something that offers us both React and JSP APIs would be great to have.

**Comment by matuzalemsteles** [comment]
@kresimir-coko yeah, I'm working on it now, I'm investigating some other options to generate our API Table, for JSP things get more complicated, we would have to create a parse of the Clay taglib TLD in DXP and we would have to generate one JSON to make it easier to use here, but it would be a little manual process since this code is not in this repository.

**Comment by matuzalemsteles** [comment]
Hey guys, I'm going to close this in favor of issue #4130, let's work on improving our Table API generator to provide a better experience as well as provide more information.
