### ISSUE TITLE
ClayPanel: Panel does not Collapse/Close after second hit on Microsoft Edge W10

### ISSUE THREAD

**Issue by kevenleone** [liferay/clay#3637]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

here: https://codesandbox.io/s/agitated-cherry-r6rdt?file=/src/App.js

## What are the steps to reproduce?

1. Click on Panel to Collapse/Close

## What is the expected result?

1. The panel should Collapse/Close after hit on Panel
2. A transition slide should be shown

## Environment

| Tech  | Version |
| ----- | ------- |
| @clayui/panel  | v3.2.3  |
| React | v16.12       |
| Microsoft Edge Windows 10 |  84.0.522.63 (Latest) |

**Comment by diegonvs** [comment]
Just for additional information. It can't be reproduced on IE11(11.1016), Edge(44.18 EdgeHTML)

**Comment by diegonvs** [comment]
Also, not reproduced on Edge(85 Chromium)

**Comment by diegonvs** [comment]
It may be already fixed on Edge v85?

**Comment by pat270** [comment]
This should be supported even if it's fixed on Edge. If the CSS is modified to `transition: none` and it should still work.
