### ISSUE TITLE
ClayModal does not support zIndex

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#3643]
Currently, there's no way to open a `ClayModal` in a different zIndex. Right now, we're hardcoding `.modal { z-index: $zindex-modal}` in [`modals.scss`](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_modals.scss#L10-L20) and `.modal-backdrop { z-index: $zindex-modal-backdrop }` in [`modals.scss`](https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_modals.scss#L145-L161).

These values are by default:
- Modal backdrop: `1040`
- Modal window: `1050`

The problem is that these values are hardcoded at build time and can't change, so if there's any element with a higher `zindex` than that, modals will show underneath. 

Check https://codesandbox.io/s/fervent-gates-v61vs for an example of the issue where a different element will block both the modal backdrop and the modal window.

## What is your proposal?
Add a `zIndex` property to `ClayModal` that can overtake the default values with custom `z-index` styles

## Why would adopting this proposal be beneficial?
- It would allow developers to show modals at their z-index of choice
- This is a blocker for [Allow "Browse Server" for links and images in CKEditor](https://issues.liferay.com/browse/LPS-119207) since CKEditor will be showing a Modal on `1100` that hides `ClayModal`.

## What are the alternatives to this proposal?
- I don't see any other possibility, really...

**Comment by kresimir-coko** [comment]
@jbalsas do we need custom z-index for both the backdrop and the window, or just the window?
