### ISSUE TITLE
@clayui/color-picker Can't clear the input once a color is selected

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3651]
https://storybook.clayui.com/?path=/story/components-claycolorpicker--custom-colors

There are a few issues:

1) Try to clear the color, tabbing out always causes the color to return.
2) If there was no initial value, color picker always has `#` in the value. This is an issue in Portal under Portlet Look and Feel Configuration, changing border top color causes the other border colors to output `#`.
3) Can't use `transparent` or other css color names like `red`, `blue`, `green`.

**Comment by matuzalemsteles** [comment]
> Can't use transparent or other css color names like red, blue, green.

I think that would be the implementation of a new feature. cc @drakonux

**Comment by jbalsas** [comment]
Remember @drakonux is on leave, focused on being a good daddy! :D 

/cc @victorvalle

**Comment by matuzalemsteles** [comment]
haha I forgot 😅

**Comment by matuzalemsteles** [comment]
> If there was no initial value, color picker always has # in the value. This is an issue in Portal under Portlet Look and Feel Configuration, changing border top color causes the other border colors to output #.

@pat270 I don't think I understood this behavior well, could you tell me how I can reproduce it?

**Comment by pat270** [comment]
@matuzalemsteles at https://clayui.com/docs/components/color-picker.html if you edit the code example and use `value=""`, the input value is `#`.

<img width="813" alt="color-picker-value" src="https://user-images.githubusercontent.com/788266/91327216-199d7f80-e77a-11ea-9409-1dadca873dab.png">

**Comment by victorvalle** [comment]
> Can't use transparent or other css color names like red, blue, green.

Sorry, I think I'm not understanding well.

Are you suggesting to have an alpha value? When the color picker was designed we considered to keep it simple and have the alpha value in a separate field. Nobody has asked for that field yet. So we will see in the future what is the real need.

I've never seen a color picker where you could introduce other values than 0,1,2,3,4,5,6,7,9,A,B,C,D,E,F. So it is difficult for me to imagine people writing red to get the red color. That is really a programmer mindset as it is one of the benefits while writing code, I would say.

**Comment by matuzalemsteles** [comment]
Thanks @victorvalle! @pat270 I think we can wait a while for someone to ask for this resource and then we will be able to evaluate it better because this change is likely to have to change some things and some behaviors.

**Comment by pat270** [comment]
@victorvalle @matuzalemsteles I'm not asking for alpha channel support. We just need to be able to enter color names and supported css values into the input. We use color picker to pass in values for things like `background-color` and `border-color`. I think it's crippling for devs not to be able to pass in `transparent` or `inherit`.

I recently saw Style Books and it looks the team rolled their own because this was needed.

**Comment by matuzalemsteles** [comment]
@pat270 we are thinking of adding a new API to allow naming the colors, but it will only be for pre-defined colors, maybe we can use this to convert what was typed to hexadecimal but we would have to change the behavior of our standard input.

**Comment by pat270** [comment]
I was thinking something similar. You can see a list of CSS colors at https://developer.mozilla.org/en-US/docs/Web/CSS/color_value. For the current color picker where we show the `#` symbol, we could convert to hex.

I was thinking our default color picker should be one without `#`. See first example at https://clayui.com/docs/components/color-picker.html#css. It should accept valid values for css color properties and not convert to hex. We could match it against a list:

```
const cssColors = {
  'inherit':                 '#ffffff', // the color we show for the swatch button
  'transparent':             '#ffffff',
  'aliceblue':               '#f0f8ff',
  'antiquewhite':            '#faebd7',
  'aqua':                    '#00ffff',
  'aquamarine':              '#7fffd4',
  'azure':                   '#f0ffff',
  'beige':                   '#f5f5dc',
  'bisque':                  '#ffe4c4',
  'black':                   '#000000',
  'blanchedalmond':          '#ffebcd',
  'blue':                    '#0000ff',
  'blueviolet':              '#8a2be2',
  'brown':                   '#a52a2a',
  'burlywood':               '#deb887',
  'cadetblue':               '#5f9ea0',
  'chartreuse':              '#7fff00',
  'chocolate':               '#d2691e',
  'coral':                   '#ff7f50',
  'cornflowerblue':          '#6495ed',
  'cornsilk':                '#fff8dc',
  'crimson':                 '#dc143c',
  'cyan':                    '#00ffff',
  'darkblue':                '#00008b',
  'darkcyan':                '#008b8b',
  'darkgoldenrod':           '#b8860b',
  'darkgray':                '#a9a9a9',
  'darkgrey':                '#a9a9a9',
  'darkgreen':               '#006400',
  'darkkhaki':               '#bdb76b',
  'darkmagenta':             '#8b008b',
  'darkolivegreen':          '#556b2f',
  'darkorange':              '#ff8c00',
  'darkorchid':              '#9932cc',
  'darkred':                 '#8b0000',
  'darksalmon':              '#e9967a',
  'darkseagreen':            '#8fbc8f',
  'darkslateblue':           '#483d8b',
  'darkslategray':           '#2f4f4f',
  'darkslategrey':           '#2f4f4f',
  'darkturquoise':           '#00ced1',
  'darkviolet':              '#9400d3',
  'deeppink':                '#ff1493',
  'deepskyblue':             '#00bfff',
  'dimgray':                 '#696969',
  'dimgrey':                 '#696969',
  'dodgerblue':              '#1e90ff',
  'firebrick':               '#b22222',
  'floralwhite':             '#fffaf0',
  'forestgreen':             '#228b22',
  'fuchsia':                 '#ff00ff',
  'gainsboro':               '#dcdcdc',
  'ghostwhite':              '#f8f8ff',
  'gold':                    '#ffd700',
  'goldenrod':               '#daa520',
  'gray':                    '#808080',
  'grey':                    '#808080',
  'green':                   '#008000',
  'greenyellow':             '#adff2f',
  'honeydew':                '#f0fff0',
  'hotpink':                 '#ff69b4',
  'indianred':               '#cd5c5c',
  'indigo':                  '#4b0082',
  'ivory':                   '#fffff0',
  'khaki':                   '#f0e68c',
  'lavender':                '#e6e6fa',
  'lavenderblush':           '#fff0f5',
  'lawngreen':               '#7cfc00',
  'lemonchiffon':            '#fffacd',
  'lightblue':               '#add8e6',
  'lightcoral':              '#f08080',
  'lightcyan':               '#e0ffff',
  'lightgoldenrodyellow':    '#fafad2',
  'lightgrey':               '#d3d3d3',
  'lightgreen':              '#90ee90',
  'lightpink':               '#ffb6c1',
  'lightsalmon':             '#ffa07a',
  'lightseagreen':           '#20b2aa',
  'lightskyblue':            '#87cefa',
  'lightslategray':          '#778899',
  'lightslategrey':          '#778899',
  'lightsteelblue':          '#b0c4de',
  'lightyellow':             '#ffffe0',
  'lime':                    '#00ff00',
  'limegreen':               '#32cd32',
  'linen':                   '#faf0e6',
  'magenta':                 '#ff00ff',
  'maroon':                  '#800000',
  'mediumaquamarine':        '#66cdaa',
  'mediumblue':              '#0000cd',
  'mediumorchid':            '#ba55d3',
  'mediumpurple':            '#9370d8',
  'mediumseagreen':          '#3cb371',
  'mediumslateblue':         '#7b68ee',
  'mediumspringgreen':       '#00fa9a',
  'mediumturquoise':         '#48d1cc',
  'mediumvioletred':         '#c71585',
  'midnightblue':            '#191970',
  'mintcream':               '#f5fffa',
  'mistyrose':               '#ffe4e1',
  'moccasin':                '#ffe4b5',
  'navajowhite':             '#ffdead',
  'navy':                    '#000080',
  'oldlace':                 '#fdf5e6',
  'olive':                   '#808000',
  'olivedrab':               '#6b8e23',
  'orange':                  '#ffa500',
  'orangered':               '#ff4500',
  'orchid':                  '#da70d6',
  'palegoldenrod':           '#eee8aa',
  'palegreen':               '#98fb98',
  'paleturquoise':           '#afeeee',
  'palevioletred':           '#d87093',
  'papayawhip':              '#ffefd5',
  'peachpuff':               '#ffdab9',
  'peru':                    '#cd853f',
  'pink':                    '#ffc0cb',
  'plum':                    '#dda0dd',
  'powderblue':              '#b0e0e6',
  'purple':                  '#800080',
  'rebeccapurple':           '#663399',
  'red':                     '#ff0000',
  'rosybrown':               '#bc8f8f',
  'royalblue':               '#4169e1',
  'saddlebrown':             '#8b4513',
  'salmon':                  '#fa8072',
  'sandybrown':              '#f4a460',
  'seagreen':                '#2e8b57',
  'seashell':                '#fff5ee',
  'sienna':                  '#a0522d',
  'silver':                  '#c0c0c0',
  'skyblue':                 '#87ceeb',
  'slateblue':               '#6a5acd',
  'slategray':               '#708090',
  'slategrey':               '#708090',
  'snow':                    '#fffafa',
  'springgreen':             '#00ff7f',
  'steelblue':               '#4682b4',
  'tan':                     '#d2b48c',
  'teal':                    '#008080',
  'thistle':                 '#d8bfd8',
  'tomato':                  '#ff6347',
  'turquoise':               '#40e0d0',
  'violet':                  '#ee82ee',
  'wheat':                   '#f5deb3',
  'white':                   '#ffffff',
  'whitesmoke':              '#f5f5f5',
  'yellow':                  '#ffff00',
  'yellowgreen':             '#9acd32',
}
```

**Comment by matuzalemsteles** [comment]
Yeah, the problem with not converting to hex is that in some behaviors the user can create his own combination, so he would show the hex and at some point the name of the color, this makes verification difficult but I think we could solve it. Also if custom is enabled in any way we would have to convert it to hex.
