### ISSUE TITLE
@clayui/color-picker Should accept valid css values for the color property

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3681]
Spawned from:
https://github.com/liferay/clay/issues/3651#issuecomment-680968921
https://github.com/liferay-frontend/liferay-portal/pull/348#issuecomment-685760858

CSS Color names:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Color

Other valid values:
```
inherit
initial
unset
transparent
var(--my-custom-propery-var) // css custom properties
currentColor // on svg element
```

These should be implemented separately from `rgba` and custom color names since no conversion is needed. We can output the value straight to the browser.

**Comment by matuzalemsteles** [comment]
Yeah, I think I'm convinced that we should endure this but I still can't see what the experience would be like. For example, the user can define `black`, and then in a Custom, we would have to convert it to hex or change the experience the same would be for rgba. cc @victorvalle

**Comment by pat270** [comment]
I don't think we need to convert the color black to a hex value. Maybe we can check against an allowlist and output the value black? When we implement custom colors, we could check if black is a custom color otherwise output the default CSS Color.

**Comment by matuzalemsteles** [comment]
@pat270 I say that we would convert to hex only when the user opens the ColorPicker in the input it would still be `black` for example, if the user wants to edit the color, we need to work with hex colors internally. Does it make sense to you?
