### ISSUE TITLE
Reorder buttons ClayDualListBox

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#3682]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

* https://clayui.com/docs/components/dual-list_box.html
* https://codesandbox.io/s/clayduallistbox-content-dashboard-configuration-0ze8o

Both are examples of `ClayDualListBox` with the out-of-the-box implementation.

## What are the steps to reproduce?

You can view these results with the out-of-the-box component.

## What is the expected result?

1. When there is only one element in the "In Use" box, disable both reorder buttons.
2. When there are two elements, and the user selects the first one, disable the reorder up button.
2. When there are two elements, and the user selects the second one, disable the reorder down button.

### Actual behavior screenshots
1.
![Screenshot 2020-09-03 at 17 18 59](https://user-images.githubusercontent.com/15845466/92134270-9deea300-ee09-11ea-9a7f-4a1e531ab762.png)

2.
![Screenshot 2020-09-03 at 17 19 10](https://user-images.githubusercontent.com/15845466/92134272-9e873980-ee09-11ea-9b7a-7d553dd61417.png)

3.
![Screenshot 2020-09-03 at 17 19 14](https://user-images.githubusercontent.com/15845466/92134276-9f1fd000-ee09-11ea-82ab-468ee095b7ab.png)

I don't know if it's a bug or an improvement. But I think it would be very nice to have it.

Thanks! 😄

**Comment by dgarciasarai** [comment]
cc: @susanavr

**Comment by matuzalemsteles** [comment]
I think this would be an improvement, but it makes a lot of sense, thanks for bringing this @dgarciasarai 🙂.

**Comment by dgarciasarai** [comment]
Thanks @matuzalemsteles :)

**Comment by kresimir-coko** [comment]
Sounds like a neat improvement, gonna try and make it happen! Thanks @dgarciasarai <3
