### ISSUE TITLE
Old URLs return 404 instead of redirect

### ISSUE THREAD

**Issue by plhnk** [liferay/clay#3691]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

A number of Clay URLs have changed, resulting in broken links on the Lexicon site (and probably other places that link back to clayui.com). I used [ahrefs.com](https://ahrefs.com/broken-link-checker) to run a quick test — I'm sure there's probably a more comprehensive way to do this, I'm just adding the table below to get started.

## What are the steps to reproduce? _Navigate to a URL that has changed._

| Page | Text | Broken URL | Error | 
| --- | ---| --- | --- |
| liferay.design/lexicon/core-components/buttons/ | View in Clay | clayui.com/docs/components/buttons.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/alerts/ | View in Clay | clayui.com/docs/components/alerts.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/forms/text-input-localizable/ | View in Clay | clayui.com/docs/components/forms/css-text-input-localizable.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/forms/multi-step-form/ | View in Clay | clayui.com/docs/components/forms/multi-step-nav.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/forms/text-input-variations/ | View in Clay | clayui.com/docs/components/forms/text-input-variations.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/navigation/breadcrumb/ | View in Clay | clayui.com/docs/components/navigation/breadcrumbs.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/forms/ | View in Clay | clayui.com/docs/components/forms/form.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/slider/ | View in Clay LIFERAY DXP | clayui.com/docs/components/forms/slider.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/table/ | View in Clay | clayui.com/docs/components/table/table.html | 404 NOT FOUND |
| liferay.design/lexicon/core-components/forms/radio-check-toggle/ | View in Clay | clayui.com/docs/components/forms/checkbox.html | 404 NOT FOUND |

## What is the expected result? _That old URLs redirect you to the content you were looking for._

Its normal for URLs to change — but when they do, it's good to include redirects. [Netlify makes this pretty straightforward](https://docs.netlify.com/routing/redirects/) but there are also lots of other ways to handle it.

**Comment by matuzalemsteles** [comment]
Thanks @plhnk! I will review the links and create the redirects, we lost that when we changed the structure https://github.com/liferay/clay/pull/3117
