### ISSUE TITLE
Document how Clay builds its pages using Gatsby

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3692]
I'd like it if we had a document of how the backbone of Clay's page creation works to ease onboarding someone new on Clay.
Talking about `createPages.js`, `docs.js`, `onCreateNode.js`, etc.

The goal of this is to document steps and flow of creation in Clay rather than re-documenting Gatsby features.

We can host this documentation here on GitHub in a form of markdown page, as the goal is to make documentation developer-facing instead of consumer-facing.

**Comment by kresimir-coko** [comment]
@matuzalemsteles @bryceosterhaus I'd like to start writing this but I'm not sure where does the file need to live in our file structure in order to show up under our Github Wiki or wherever we decide it will be accessible?

**Comment by matuzalemsteles** [comment]
@kresimir-coko I don't really like the wiki but I would suggest adding it to a `docs` folder at the root level and start documenting there.

**Comment by bryceosterhaus** [comment]
`docs` folder at the root sounds good to me as well
