### ISSUE TITLE
Navigation Bar React code

### ISSUE THREAD

**Issue by nachoge** [liferay/clay#3697]
Hello,

Why there's no React code sample for the Navigation Bar. Is it pending?

Thank you!

**Comment by matuzalemsteles** [comment]
Hey @nachoge you referring to this https://clayui.com/docs/components/navigation-bar.html? I can see the examples in React.

**Comment by nachoge** [comment]
Hi,
I can not check what i wrote right now. But I think I wrote Application
bar, the one on top.

Thanks in advance!

**Comment by nachoge** [comment]
Checked, I was wrong I wrote Navigation not Application. Sorry for that. I
was referring to Application

**Comment by matuzalemsteles** [comment]
@nachoge no problem, we don't have this component yet in React, this is an exclusive component of Liferay DXP, we don't have it planned yet.

**Comment by matuzalemsteles** [comment]
Hey @nachoge let me know if I answered your question. I will close this but feel free to reopen if I have not responded.

**Comment by nachoge** [comment]
yes, you asnwered me sorry!
