### ISSUE TITLE
Should we have Insights akin to those we're writing for Frontend Infrastructure?

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3699]
## What is your proposal?

Clay is a very interesting project within Liferay and it took me some time to understand its intricacies. I believe we should have a wiki or documentation here on Github that explains some of its inner mechanisms. 

This was inspired by the Frontend Infrastructure Insights we're doing on [liferay/liferay-frontend-guidelines](https://github.com/liferay/liferay-frontend-guidelines/milestone/1).

## Why would adopting this proposal be beneficial?

It would help onboarding new developers to Clay in the future, and also help people already familiar with the systems be able to reference them when mentioning them. It would also be beneficial for anyone outside Clay requesting a feature to be able to get some context when the developers are talking about their request.

**Comment by bryceosterhaus** [comment]
I think this could be beneficial. **Are there particular mechanisms or intricacies you are thinking of?** Off the top of my head, I can't think of a ton of intricacies that are Clay specific and not React specific. I also might just be too familiar with Clay at this point though.

**Comment by matuzalemsteles** [comment]
Yeah, I think documents about some things are important to keep around, especially when new people join the project but I still can't imagine what would be documented.

I can think of a few things but they are related to the components:
- Sub portals structure
- Focus Management

These are more related to the internals of the components.

**Comment by kresimir-coko** [comment]
The [issue](https://github.com/liferay/clay/issues/3692) I opened about building pages is perfect for this.

Apart from that maybe something like:
- Going into depth with how we develop implementations of our components, like the fact that props need to be named `IProps`, `IItemProps`, casting component props to `IProps` so they show up in the API table
- Explain Clay CSS and the clay-css package, I'm still confused how all of that works and what is it's purpose, and I'm not sure if there are any specifics when working with it

When you put it like that:
> Off the top of my head, I can't think of a ton of intricacies that are Clay specific and not React specific.

Probably most of my concerns were not Clay specific 🤷

**Comment by bryceosterhaus** [comment]
Yeah I would say go for it and document anything you would see as helpful for people interacting with Clay. I think a generic `docs` folder would be great for that at the root of the project

**Comment by matuzalemsteles** [comment]
Hey guys I think we all reached a consensus on keeping some things documented and some have already been done, so I'm going to close the issue. @kresimir-coko feel free to reopen or create a new issue to discuss more about it.
