### ISSUE TITLE
Expand documentation on Charts

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3714]
Looking at ClayCharts I see that we have very little documentation on it. I think it would be beneficial to provide at least some documentation on it. At the very least some basic information even if it's just a link to `billboard.js`, or something like that. If I wanted to use the component now, I wouldn't know how to really start and use it.

I quickly looked over their documentation, and I got to a conclusion that we could provide information that leverages `billboard.js`'s docs and write something user-friendly, even if we do duplicate some of the information. 
Information like where to look for docs, some most common props, and also a list with a short description of the extra charts we do provide.

I'd do this myself but I've never worked with Charts, so I'd need some guidance if I wanted to tackle it.

**Comment by matuzalemsteles** [comment]
@kresimir-coko that would be good, although we may deprecated it soon, due to the switch to recharts, I wonder if this effort is worth it now. Probably the people who would use the charts should start with recharts.

**Comment by kresimir-coko** [comment]
@matuzalemsteles I wasn't aware of that. Then maybe that's all the documentation there should be, like a notice/warning on the Charts page.

**Comment by matuzalemsteles** [comment]
@kresimir-coko np, that was kind of quiet! But we can add warning in the documentation and maybe write a documentation explaining better the examples we have in the Storybook and how you can reach the Lexicon specification with recharts.

**Comment by bryceosterhaus** [comment]
@kresimir-coko thats probably a good idea to add a banner or notice on the clay-charts page about using recharts and possibly even pointing to the storybook demos
