### ISSUE TITLE
Expand documentation of Layout

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3715]
Now that the set of Layout components has been brewing for some time in DXP we could document them a bit better. 
We could describe some of the more common strategies and document the markup of the component so it's more consistent with all other components.

@bryceosterhaus You worked on this, perhaps you can do this, or if you don't have time, provide me with some bullet points of what to go over.

**Comment by bryceosterhaus** [comment]
Hey @kresimir-coko feel free to take this if you want. I probably wont be able to get to it till next week.

Main points are just the components and their props. You can probably glean the info from the css docs for the classes the components use
