### ISSUE TITLE
Radio Button gets slightly misaligned when selected

### ISSUE THREAD

**Issue by lucasneves91** [liferay/clay#3722]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

[LPS-121351](https://issues.liferay.com/browse/LPS-121351)

## What are the steps to reproduce?

1. Add a Form with 'Single Selection' field
2. Add 2+ options
3. Save and Publish
4. Select Option 2 and observe how the radio button is misaligned when selected

5. ## What is the expected result?
Radio Button should be aligned properly when selected

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by matuzalemsteles** [comment]
Hey @pat270 it seems that this only happens when we have Radio all inline, I can see it in the Storybook example https://storybook.clayui.com/?path=/story/components-clayradiogroup--inline but only when you click on the radio the middle one.

**Comment by pat270** [comment]
Not sure what's going on, but this is a Chrome only issue. If we add white space between each `custom-control-inline` the alignment is correct. My guess: Chrome is having trouble rendering with the `background-size` as a percentage. I can change it to a fixed size.
