### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by nachoge** [liferay/clay#3725]
Hi, 

Is there any kind of Toast (https://primefaces.org/primereact/showcase/#/toast) in clay?

It would be interesting to have a global Toast for feedback messages from the back. I know I can mimic its behavior by using <ClayForm.FeedbackItem> but would be interesting to show it for a couple of seconds and then hide it automatically.

New entries trigger the show and depending if they are permanent or not they would disappear once hided the Toast (for trivial messages). Important ones (batch tasks finished,...) would remain until the user closes them individually or automatically once a medium to long period has passed.

Is there something like that? Is it planned. If not Should I open a request?

The thing is I don't want to mix components

Thanks in advance

**Comment by bryceosterhaus** [comment]
Hey @nachoge!

We do provide toast functionality with out alert component. Check it out in our [docs](https://clayui.com/docs/components/alert.html#clayalert.toastcontainer) and our [stroybook demo](https://storybook.clayui.com/?path=/story/components-clayalert--toast)

If there is any additional functionality for that component we might need, let us know!

**Comment by nachoge** [comment]
Hi,

I didn't saw it... it's a little bit hidden. 
To prevent this kind of questions or to be able to see all components at once it would be interesting to have components and sub components available in the left pane as a tree. This is just a suggestion...

I will try it out and just in case I well give you feedback

Thank you very much!
