### ISSUE TITLE
Icon: Update Product menu icons

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3727]
Due to [LEXI-971 ](https://issues.liferay.com/browse/LEXI-971)we've updated the product-menu-open & product-menu-closed icons.

![Captura de pantalla 2020-09-28 a las 16 35 47](https://user-images.githubusercontent.com/61543739/94446265-b2c01b80-01a8-11eb-84c1-3ddc9002fb78.png)

Please replace it in the icon library.

Find the SVGs on the ticket.
Thanks!

**Comment by matuzalemsteles** [comment]
Fixed by #3731
