### ISSUE TITLE
Icon: Update icon-display-content

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3728]
Due to [LEXI-904](https://issues.liferay.com/browse/LEXI-904) we've updated the display-content icon

<img width="209" alt="Screenshot 2020-05-06 at 10 50 12" src="https://user-images.githubusercontent.com/61543739/94448999-dcc70d00-01ab-11eb-97fa-1b7c3c22a7c1.png">

Please replace it in the icon library.

Find the SVGs on the ticket.
Thanks!

**Comment by matuzalemsteles** [comment]
Fixed by #3731
