### ISSUE TITLE
Add hover information on component status labels to improve clarity

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3735]
The idea behind this being that [How to Read This Documentation](https://clayui.com/docs/get-started/how-to-read-this-documentation.html) contains the useful explanations of our component status labels, but what if we added their descriptions to the tooltips of those status labels on our components.

How it would work is basically the user would hover on the `Stable` label and a tooltip would show up with the `These components are safe for use in production but if you encounter problems, open an issue.` text.

![image](https://user-images.githubusercontent.com/24564752/94685818-40774480-032a-11eb-8564-16b1284c3e74.png)

**Comment by bryceosterhaus** [comment]
@kresimir-coko I'm not sure this is super important. I wouldn't expect anyone who comes to our docs site to not know the difference between these labels.

**Comment by kresimir-coko** [comment]
I agree it's not super important @bryceosterhaus, if you think it's not worth it we can close this issue 😄
