### ISSUE TITLE
Should we put all @clayui/form components under a Form section in the navigation

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#3736]
I feel like, for clarity, we should add all components that are a part of the `@clayui/form` package under a Form category in the navigation. I, myself, have been confused when importing packages like Select, Checkbox, Input to discover that they're under the `@clayui/form`package.

This is shown semi-prominently in those components, but when clicking around in the UI, and going straight down to the examples or API, I often find myself skipping this heading.

![image](https://user-images.githubusercontent.com/24564752/94687362-73bad300-032c-11eb-8a53-ad26062b7b8a.png)

I think that putting these child components into their parent tab, which corresponds the package they belong to, will be enough for improving that clarity and hierarchy.

**Comment by bryceosterhaus** [comment]
This is related to these conversations as well

**Comment by kresimir-coko** [comment]
I know I read about a similar thing somewhere, and it's those 2 links @bryceosterhaus, I can't find much a reasoning behind it not being nested, the only being from this [comment](https://github.com/liferay/clay/pull/3117#issuecomment-613390836):
> But feel free to do it here because I have to admit that in the Components section should have just components. i.e. **navigation** and **forms** are names created to relate the components within however a checkbox or an input doesn't have to be exclusively in a form.

I get that we don't want navigation items that don't represent components, but in our case it represents the `@clayui/form` package. I'm not married to this idea, just putting it out there 😄
