### ISSUE TITLE
Possible bug in ClayNav (or in example on the web)

### ISSUE THREAD

**Issue by nachoge** [liferay/clay#3742]
Hi, 

I'm trying to use the ClayNav. In fact, I'm looking for a Menu component I've tried the DropDown but there not a specific trigger object, let's say Menu... but that's another story

Right now In testing ClayNav....

following you example... (Basic Usage)

https://clayui.com/docs/components/nav.html

you are importing 
import {ClayNav} from '@clayui/nav';
despite of 
import ClayNav from '@clayui/nav';

-   [ ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by matuzalemsteles** [comment]
@nachoge thanks for reporting this, probably a minimal typo. I will fix this.
