### ISSUE TITLE
ClayPanel: can expanding one panel collapse all other panels in a group?

### ISSUE THREAD

**Issue by rdai10** [liferay/clay#3754]
Given the current API, is it possible to achieve the behavior where expanding one panel in a group of panels will collapse all other panels? Like the example illustrated [here](http://pat270.github.io/lexicon/v2.15.1/content/panels/#accordions-with-panels-and-collapse-plugin).

I noticed that each panel seems to be its distinct entity. While there is the `defaultExpanded` prop, it only sets the initial value for the `expanded` state. And the state management is internal to the panel component. Just want to make sure I didn't miss anything.

Thanks!

**Comment by bryceosterhaus** [comment]
@rdai10 I think you are right in seeing that we don't provide a current mechanism for that. I think we made the mistake of not thinking about how someone would control this. I will send a PR to add an API for this. Thanks for catching this!

**Comment by rdai10** [comment]
Thanks @bryceosterhaus !

**Comment by bryceosterhaus** [comment]
@rdai10 sorry this took so long to fix. This should be available in the latest clay release and also in dxp master via https://issues.liferay.com/browse/LPS-125356
