### ISSUE TITLE
Card with images: API difference between 2.x and 3.x

### ISSUE THREAD

**Issue by julien** [liferay/clay#3756]
With (Image) Card components in 2.x, we had the possibility to pass an [`aspectRatioClasses`](https://github.com/liferay/clay/blob/3bd63bb5b84a60b2cd1da4746bb05f3874f1d415/packages/clay-card/src/ClayImageCard.soy#L16) attribute to the `ClayImageCard` component that would [set those CSS classes on it's `img` element](https://github.com/liferay/clay/blob/3bd63bb5b84a60b2cd1da4746bb05f3874f1d415/packages/clay-card/src/ClayImageCard.soy#L100-L114).

With 3.x, I'm using [`CardWithInfo`](https://github.com/liferay/clay/blob/aefb430bd83de2056122ae2af3fb06cae0b2f6ae/packages/clay-card/src/CardWithInfo.tsx) to display an image and the "behaviour" has changed a bit:
We always [set the default CSS classes](https://github.com/liferay/clay/blob/aefb430bd83de2056122ae2af3fb06cae0b2f6ae/packages/clay-card/src/CardWithInfo.tsx#L135) and have no `aspectRatioClasses` prop (and additionally
we can pass [`flushHorizontal` and `flushVertical`](https://github.com/liferay/clay/blob/aefb430bd83de2056122ae2af3fb06cae0b2f6ae/packages/clay-card/src/CardWithInfo.tsx#L136-L140) which is nice).

It would be nice to add that back if you could or at least consider what we want to do about this.

I don't see [lots of usages](https://github.com/liferay/liferay-portal/search?q=aspectRatioClasses) in DXP using GitHub's search, but there might be more. 

What do you guys think?

[EDIT]: The main reason I'm asking this is because the `<clay:image-card>` tag [supports](https://github.com/liferay/liferay-portal/blob/8a63de6d679b74466e6a6367e640d1c44e32a9f8/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/liferay-clay.tld#L1688) [this](https://github.com/liferay/liferay-portal/blob/8a63de6d679b74466e6a6367e640d1c44e32a9f8/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/ImageCardTag.java#L104-L106), and we're currently making new classes that will render clay 3.x components, these new tags will (or should ideally) have the same API as the previous ones.

**Comment by julien** [comment]
Hey guys, 

I think I didn't read [this](https://github.com/liferay/clay/blob/aefb430bd83de2056122ae2af3fb06cae0b2f6ae/packages/clay-card/src/CardWithInfo.tsx#L135) line correctly. So passing `imgProps = {className: 'foobar'}` would do the same, is that correct?

**Comment by matuzalemsteles** [comment]
Hey @julien, sorry for delay! yes 😁

**Comment by julien** [comment]
@matuzalemsteles no need to be sorry and thanks!
