### ISSUE TITLE
Adapting sheet to commerce needs

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#3762]
Commerce has a request to adapt sheet component to their needs. 

Commerce product interface has multiple forms in a single screen which is convenient for their use case and users. These individual forms need of a header that allows quick identification. Lexicon has added a header definition to sheet component.

[LEXI-1032](https://issues.liferay.com/browse/LEXI-1032) collects the Commerce proposal and Lexicon answer, together with the team request validation.

Thanks!

**Comment by victorvalle** [comment]
Note: we've took the chance to improve the documentation of sheet, which was vague before. Now it collects more information and use cases but respecting the existing implementation.

**Comment by pat270** [comment]
@victorvalle sorry I missed this one. This should be no problem.
