### ISSUE TITLE
CardWithUser doesn't support a label for the sticker

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#3763]
We're currently only supporting `userImageSrc` and `userSymbol` to render'em as the children of the `Sticker`, but according to lexicon definition we should allow a label to be passed

https://liferay.design/lexicon/core-components/cards/cards-variation/#user-card

> User cards represent users. The user can be represented by their user image **or up to two initials extracted from their user name or name + surname**.

**Comment by matuzalemsteles** [comment]
@carloslancha I was starting to add support for this, but I remembered that we had removed this in v2, so I went to look in the documents, I found in the changelog that we shouldn't support this anymore. Perhaps the site’s documentation is out of date cc @victorvalle @hold-shift

https://docs.google.com/document/d/1st2moaRVphrsFrDJUz-ic26aH-V46YkQam75X6BHPY0/edit#heading=h.l82je57kortn

**Comment by victorvalle** [comment]
Hi @mateomustapic !
If you mean the text inside the sticker, I believe we don't have that anymore. We removed that due to accessibility reasons.

**Comment by carloslancha** [comment]
Hey @victorvalle  could you please update lexicon site to remove
```
User cards represent users. The user can be represented by their user image or up to two initials extracted from their user name or name + surname.
```
when you have a chance?

Thx!

**Comment by victorvalle** [comment]
Sent https://github.com/liferay-design/liferay.design/pull/831

**Comment by matuzalemsteles** [comment]
Thanks @victorvalle and @carloslancha! Well, then I will close this issue!
