### ISSUE TITLE
Why are we using `<img>` instead of `ClaySticker.Image` in `CardWithUser`?

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#3765]
https://github.com/liferay/clay/blob/master/packages/clay-card/src/CardWithUser.tsx#L120

Here we're rendering directly an image instead of using `ClaySticker.Image`. Why is this?

IMHO I think we should use it

```
<ClaySticker.Image
	alt={userImageAlt}
	className="aspect-ratio-item-fluid"
	src={userImageSrc}
/>
```

**Comment by matuzalemsteles** [comment]
@carloslancha I agree, in this case just because `<ClaySticker.Image />` was added recently compared to `CardWithUser` that was added at the beginning of Clay v3 development, I think we forgot that we used it internally. Thanks!
