### ISSUE TITLE
Collapsible ClayPanel add the class `show` to the button when open

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3766]
We have instances where we need to style the open and close button in the open state, but there is no class to hook to.

<img width="302" alt="clay-panel" src="https://user-images.githubusercontent.com/788266/97218941-94891380-1786-11eb-9550-5a7c4130ef32.png">

The only attribute that we have is `aria-expanded="true"`. It would be nice to have a class that is easier to spot.

**Comment by marcoscv-work** [comment]
And it's also good for forcing the use of the aria attribute....

![](https://media.giphy.com/media/XpASdrKTSxY6A/source.gif)

**Comment by bryceosterhaus** [comment]
@pat270 is this still needed? I just took a look and noticed we have the "collapsed" class on the button which toggles back and forth.

**Comment by brunofernandezg** [comment]
hi @pat270 @bryceosterhaus, have we made a decision about this issue?
Thanks!

**Comment by pat270** [comment]
Sorry guys I missed this one. I would say yes this is still needed. The problem is the open state for the button usually has different colors and outlines. The collapsed state generally uses the default styles. In this case, only having `collapsed`, we would need to reset the styles we added in the open state every time.

```
.panel-header { color: red; box-shadow: 0 0 4px 0 blue; }
.panel-header.collapsed { color: black; box-shadow: none; }
```
