### ISSUE TITLE
onActiveChange on ClayDropDownWithItems

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#3776]
## What is your question?

Recently I was migrating a component from 2.x to 3.x, this component receives a property called `functions` where the shape is an array containing objects shaped as 2.x API, in this case `{label: string, tooltip: string, value: string}`.  and I would not iterate whole array adding onClick functions before passing it to `items` property on ClayDropDownWithItems or maybe use a low-level composition, because the UI is simpler and I can reach the expected markup with just ClayDropDownWithItems.

The question is:

Does make sense adding `onActiveChange` to ClayDropDownWithItems?

**Comment by bryceosterhaus** [comment]
I've noticed this in a few of our high-level components where we have an internal "active" and "onChange", but we don't provide props for the user to control that. I think we could improve our API of high-levels by making sure we allow those props to be used if the user wants to check it. I believe we do something similar in `TabPane`, we have an internalActive state but also allow users to control it if they want
