### ISSUE TITLE
Clay Card Description (3.x) passes `href` attribute to `span` element

### ISSUE THREAD

**Issue by julien** [liferay/clay#3779]
During a [code review](https://github.com/liferay-frontend/liferay-portal/pull/448#discussion_r512231080), @carloslancha pointed out that in some cases, [Card.Description sets an `href` attribute on a `span` element](https://github.com/liferay/clay/blob/6b00a1e60deaa3c415dbed5227c3ca6017ac14ea/packages/clay-card/src/Description.tsx#L62) - and we're wondering if that's the correct behaviour.

**Comment by bryceosterhaus** [comment]
No, it shouldn't be setting an href on a span. We can probably update this to be 


```jsx
<InnerTag className="text-truncate" href={disabled ? undefined : href}>
```

**Comment by julien** [comment]
@bryceosterhaus thanks, I sent #3780 as a fix.
