### ISSUE TITLE
Executing a search via javascript

### ISSUE THREAD

**Issue by beall49** [liferay/clay#378]
Hi we're new to Liferay/Lexicon and we've recently implemented a search bar in a theme using lexicon styling. 

```html
<div class="form-group">
    <div class="input-group">
        <input class="form-control" placeholder="Search for..." type="text">
        <span class="input-group-btn">
            <button class="btn btn-default" type="button">Search</button>
        </span>
     </div>
</div>
```

I know there's multiple parameters that are needed for the search results popup/overlay, but we're hoping there's a way to get to them. Possibly similar to the liferay-ui objects e.g. user-icon, alerts, etc. Can we just execute the search via javascript somehow?

Do we have to implement the search portlet to do this?  ```<@liferay.search/>``` If so, are their examples of applying the lexicon styling to it?

I feel like I'm missing something simple, forgive me if I am.

Thanks

**Comment by jonmak08** [comment]
Hi @beall49,

You can do a search via javascript in Liferay, using portlet-url (https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/portlet_url.js) to construct the url and paramaters you might need to pass in.

Here is a really old blog describing how to use it https://web.liferay.com/web/eduardo.lundgren/blog/-/blogs/liferay-portleturl-in-javascript.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
For future requests regarding Liferay specific issues, you can post your questions in our forums (https://web.liferay.com/community/forums) or join our chat (https://community-chat.liferay.com/) which should be able to provide you a quicker response.

Thanks!

**Comment by beall49** [comment]
That looks perfect, I'll close this, if I have issues going forward I'll use the forums. Thanks again, appreciate it.
