### ISSUE TITLE
A click on trigger to expand ClayDropDown submits form

### ISSUE THREAD

**Issue by markocikos** [liferay/clay#3781]
Steps to reproduce:
1.  Add `<form>` wrapper to any `ClayDropDown` testing environment you have.

or, to get the case from attached gif:

1. Make sure https://github.com/brianchandotcom/liferay-portal/pull/95671 is merged (or take branch). This implements horizontal card based on Clay 3 `CardWithHorizontal`, which contains `ClayDropDown`.
2. Change [this line](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/view_entries.jsp#L334) from `<clay:horizontal-card-v2>` to `<clay:horizontal-card>`.
3. Create a new folder in journal-web.
4. Click on ellipsis to open dropdown (see gif on bottom).

What is the expected result?
- Click on trigger expands dropdown

What actually happens:
- Click expands dropdown and submits form (see gif on bottom).

Notes:
- This cannot be noticed in [storybook](https://storybook.clayui.com/?path=/story/components-claycard--cardwithhorizontal) as there is no form.
- In Clay 2 component we had [this line](https://github.com/liferay/clay/blob/2.x/packages/clay-dropdown/src/ClayActionsDropdown.js#L29) with  `event.preventDefault()`, that handled this case. In Clay 3 component, there is no such thing. [On click](https://github.com/liferay/clay/blob/master/packages/clay-drop-down/src/DropDown.tsx#L135) we are just invoking callback.
- Solutions I can think of:
  - add `event.preventDefault()`
  - pass `event` object to `onActiveChange` callback, so that form interaction can be controlled from top component
  - use something other than `button` for trigger

Environment

| Tech  | Version |
| ----- | ------- |
| @clayui/drop-down  | v3.8.0  |
| @clayui/card  | v3.5.0  |
| React |         |

![before](https://user-images.githubusercontent.com/5435511/98272288-367fdb80-1f91-11eb-8193-f0b89213723d.gif)

**Comment by matuzalemsteles** [comment]
@markocikos thanks for bringing this, I think we don't need to define `event.preventDefault()` or anything else, I think we can just switch to using `<ClayButton/>` in [`<ClayCardWithHorizontal/>`](https://github.com/liferay/clay/blob/master/packages/clay-card/src/CardWithHorizontal.tsx#L98) it will solve the problem or just set the `type` to `button`, without it, a button will trigger the submit form.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles we probably wouldn't have had this issue if we used `ClayButton` instead of `button` since we default the type to "button". 😂   😂   😂   

Might be a good opportunity for us to re-evaluate our uses of `<button>` throughout clay to make sure we always have a default type.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus yeah 😂, we probably missed something while we were building the components in the beginning and we weren't using our own components 😅 or really some were not yet ready 🤷‍♂️

**Comment by matuzalemsteles** [comment]
I will close this. Fixed by #3794 and #3795.
