### ISSUE TITLE
Time Picker spacing is broken for double digit hours and minutes

### ISSUE THREAD

**Issue by stsquared99** [liferay/clay#3783]
![Screen Shot 2020-11-05 at 10 33 52 AM](https://user-images.githubusercontent.com/5861692/98283086-f9e1bf00-1f53-11eb-8f16-1129059f1f3b.png)

| Tech  | Version |
| ----- | ------- |
| @clayui/time-picker  | v3.2.0 |

**Comment by matuzalemsteles** [comment]
Hey @pat270 could you take a look at this? I think it is related to CSS for some reason in the components it is broken but only in markup it seems to work well.

**Comment by pat270** [comment]
@matuzalemsteles @stsquared99 just FYI this is a white-space related issue. Clay CSS assumes there will be white-space between hour : time elements, but React strips white-space. I think I can make it work for both by using `display: flex`.
