### ISSUE TITLE
Vertical navigation update

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#3785]
Lexicon has updated vertical navigation.

Although a while ago we requested some changes that include some decorators we found out it is not the best right now. We are requesting an update that improves the current implementation in Liferay DXP.

This update helps the user to better identify hierarchy and position through visual states.

Please see the [Documentation](https://issues.liferay.com/browse/LEXI-789)

Thanks!

**Comment by pat270** [comment]
@drakonux should Vertical Navigation with Decorator have the blue state on `active` as well or just the undecorated?

![decorated](https://user-images.githubusercontent.com/788266/110847021-42dab480-8261-11eb-9a7d-846d6963520e.jpg)

See https://pat270.github.io/clay3-test-site/v3.10.0/content/menu-bar-vertical-decorated/ for demo, this isn't on clayui.com for some reason.

**Comment by marcoscv-work** [comment]
LG2M !!!

![image](https://user-images.githubusercontent.com/7963804/110932559-f5774980-832b-11eb-8179-e29c55d83f33.png)

**Comment by drakonux** [comment]
I think this was made when I was on paternity leave so I'm a bit out of context. I would prefer if @hold-shift answers you @pat270 and review it. 

Could you take a look?

**Comment by hold-shift** [comment]
Hey @pat270. Finally, the vertical navigation component with decorator was left as a variant we won't include in Lexicon, as @victorvalle commented in the request. The blue state will apply only for the selected item/tab in active state.
