### ISSUE TITLE
Clay Card (3.x): Default Icon for ClaySticker is "documents-and-media"

### ISSUE THREAD

**Issue by julien** [liferay/clay#3786]
Not a big issue, but I was wondering why the [value for the sticker's icon in `ClayCardWithInfo`](https://github.com/liferay/clay/blob/9270625e8bafa20c1e77ab2cbe67ebf5560d5584/packages/clay-card/src/CardWithInfo.tsx#L121) is `'documents-and-media'`.

I'm asking because looking at Lexicon's card definitions, it seems that [some cards have no sticker at all](https://liferay.design/lexicon/core-components/cards/cards-variation/#blog-card)

**Comment by carloslancha** [comment]
Actually there's a different default icon for Image cards (`document-image`) and File cards (`document-default`), so this could be considered a bug.

Also, those default icons changed last week after a conversation with @victorvalle . Victor, did you open any ticket or issue to update this? (I guess any change in docs should be followed by a jira ticket or Github issue)

https://docs.google.com/document/d/1st2moaRVphrsFrDJUz-ic26aH-V46YkQam75X6BHPY0/edit#heading=h.l82je57kortn

Thx guys

**Comment by victorvalle** [comment]
I didn't create any tickets. I thought you were adding this requirement on the fly. If I have to just let me know it.

**Comment by carloslancha** [comment]
We did it for the Tags but they need to know about it here. Don't worry about the issue, we can use this to do it. Thx!

**Comment by bryceosterhaus** [comment]
Likely was un-intentional that we had the wrong default icon. Whatever lexicon defaults to, we should as well. I see no problem updating the default icon and labeling it as a bug fix

**Comment by carloslancha** [comment]
I'll send a pr tomorrow updating the component to use correct defaults depending on displayType.

Thx @bryceosterhaus !
