### ISSUE TITLE
Component Update: Color Picker

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3787]
Lexicon has reviewed and updated the color picker documentation and specs.

This update describes the component interaction and introduces new padding values.

Please see the [LEXI-1052](https://issues.liferay.com/browse/LEXI-1052) for more info

Thanks!

**Comment by marcoscv-work** [comment]
I like the update! I think it will fix all UX issues/doubts we had after the component release

**Comment by pat270** [comment]
I believe this was fixed in https://github.com/liferay/clay/pull/3916. Feel free to reopen if not.
