### ISSUE TITLE
Making ClayDropdown.Menu width customisable

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#3790]
In commerce would like to to use the dropdown menu to show some global search results. 
The current default width is not enough and it's not customisable.  

In ClayUI.com / dropdown / markup section I found [this](https://clayui.com/docs/components/drop-down/markup.html#css-wide) but the react component doesn't handle it:
https://github.com/liferay/clay/blob/9270625e8bafa20c1e77ab2cbe67ebf5560d5584/packages/clay-drop-down/src/Menu.tsx#L256

Could we add a prop to define the preferable width for the dropdown? 
`default`, `wide` and `full` are enough for our user cases

**Comment by pat270** [comment]
@FabioDiegoMastrorilli `dropdown-wide` and `dropdown-full` were created with the assumption that the `dropdown-menu` would be nested inside a relative container like `nav-item`. Maybe it would be better to make a new modifier class on the `dropdown-menu` like `dropdown-menu-wide` and `dropdown-menu-full` since Clay Dropdown renders the markup outside whatever component calls it? It would work as is just need to pass a class to `dropdown-menu`.

**Comment by FabioDiegoMastrorilli** [comment]
@pat270 adding a modifier directing to dropdown menu would be even better! :)
I think that choosing the size via props would be more immediate and would help the component to better document itself but feel free to use the classname approach (it also looks pretty fair)

**Comment by matuzalemsteles** [comment]
@pat270 @FabioDiegoMastrorilli As DropDown renders the menu in body, could this not be a problem for him to determine the size or will it be fixed sizes?

**Comment by FabioDiegoMastrorilli** [comment]
We are ok with the fixed width which are larger than the default one.
In our scenario we would use `wide` which will expand it to 500px

**Comment by pat270** [comment]
@matuzalemsteles We could make dropdown-menu-wide `min-width: 500px` and some `max-width` or just fixed width? Then add media-queries to make it 100% when the screen width is smaller than the min-width.

/cc @victorvalle

**Comment by matuzalemsteles** [comment]
@pat270 I think we can try to add an API to disable the use of `React.createPortal` to support these cases, so `menu-wide` could be the width of its parent container. Does it work better?

**Comment by pat270** [comment]
My hunch is we will need to give both options; fixed width and disable the use of `React.createPortal`. It should cover a wide variety of use cases.

**Comment by jbalsas** [comment]
Let's not jump to disable usage of `React.createPortal` without further analysis. Dropdowns outside of portals have a number of problems and I'm pretty sure we'll be just handing a loaded gun to developers.

**Comment by matuzalemsteles** [comment]
@pat270 @jbalsas yeah, that would be a disadvantage when disabling `React.createPortal` but having it enabled can be a problem when we don’t have fixed sizes, maybe to avoid this would just be providing a range of classes with different sizes or just allowing the dev can add a class and overwrite?

**Comment by pat270** [comment]
Just sent a pr adding `.dropdown-menu-width-full`, `.dropdown-menu-width-sm`, and `.dropdown-menu-height-auto`. I decided to name it that way to follow a similar pattern to how we do `modal-height`. 

- `dropdown-menu-width-full` spans full width of the screen always
- `dropdown-menu-width-sm` fixed width of 500px at screens 767px and below spans 100%

**Comment by pat270** [comment]
@jbalsas I don't really know what `React.createPortal` does. I think it renders content outside the parent? Just curious why opt in to disable is a bad idea? It seems like we're doing a bit of hand holding and assuming devs don't know what they are doing. If a dev opts in they should know how to handle overflow and other css related issues.

**Comment by wincent** [comment]
> I don't really know what `React.createPortal` does. I think it renders content outside the parent?

Yeah, that's what it does. I am just driving by here so I don't really understand what the problem is, but I have never seen an example where rendering a dropdown or a modal in any other way was a good idea; portals exist to eliminate a large class of bugs and usability problems that can't be solved in any other way (especially in context where your "thing" may be nested inside a hierarchy that you don't fully control).

**Comment by jbalsas** [comment]
> [...] portals exist to eliminate a large class of bugs and usability problems that can't be solved in any other way (especially in context where your "thing" may be nested inside a hierarchy that you don't fully control)

There's no metric for how many bugs we had to address when dropdowns rendered within the parent (in our first iteration). I'd say this is akin to a bit of hand holding when the alternative is falling out of a cliff... sure they know better than to jump... or do they? 😂

**Comment by victorvalle** [comment]
I found this example that makes what we described in Lexicon and it was never possible to implement

https://reactscript.com/react-responsive-tabs-component/

**Comment by pat270** [comment]
Dropdowns rendered in the parent make it easier to to position and scale to all screen sizes. The only issue I had with dropdowns relative to the parent is when the parent has `overflow: auto` e.g., responsive table, vertical navigation, or sidebar.

**Comment by wincent** [comment]
Take the example that Victor shared earlier in the thread [`react-responsive-tabs`](https://reactscript.com/react-responsive-tabs-component/); it is trivially breakable by nesting it inside a "hostile" ancestor (with fixed height and `overflow: hidden`):

![Screenshot 2020-11-13 -100839-f71c4Xq9@2x](https://user-images.githubusercontent.com/7074/99051119-992c3500-2598-11eb-8ff5-cc630f837aa6.png)

Now you could argue that the solution is just to use it right and not make bad markup structure like that, but I've always felt that when you build a library for _reusability_, you need to go out of your way to ensure that it is maximally reusable (ie. robust in the face of "misuse"). Of course, it's possible to go too far in that direction, but in my experience, all the "good" libraries that I've seen or used deal with overlaid elements (modals, drop-downs, pop-ups etc) take pains to avoid this problem.

**Comment by victorvalle** [comment]
Sorry @wincent , I confused this ticket with another one. That is why I removed my answer from the thread.

I would like to discuss this when we deal with the navbar. I'm open to any solution, but I don't understand why this would not be reusable... :(

**Comment by pat270** [comment]
@wincent I agree we should take pains to avoid this problem by default. I do think we are going too far in that direction. Relative dropdowns solve a lot of alignment issues by default and don't require the browser to constantly calculate positions.

Some issues with our current implementation:
1) Dropdown Menus don't stay positioned with the trigger when resizing the browser window
2) Only supports fixed width dropdown menus (can't make it relative to it's container 2 parents above)

I'm assuming when you opt in, you are clearly making the choice for the library not to fix that for you. I don't think one method is better than the other, but there are clearly uses for both types.

With that said, the portal method can solve all use cases. We just need to write the code, but my preference is only to use JS for things I can't reasonably accomplish with CSS.

**Comment by victorvalle** [comment]
Sorry for this delay.
I think it would be important to cover the need that @FabioDiegoMastrorilli is requesting. The possibility to set a preferred width. For their case, it makes a lot of sense.
Can we have a default width of 240px (Maximum now in filter and order) and then we open the possibility to set values?

What could go wrong with this solution?
