### ISSUE TITLE
ClayDropdown.Menu panel misalignment within a ClayModal when the modal body is scrollable

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#3804]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

https://codesandbox.io/s/peaceful-bhabha-lfv6d?file=/src/index.js

## What are the steps to reproduce?

If you use ClayModal.Body as scrollable and use a ClayDropdown.Menu component within, the dropdown panel will not be realigned to the trigger element.

![Kapture 2020-11-19 at 14 42 24](https://user-images.githubusercontent.com/7663513/99703173-8cff1680-2a75-11eb-87f9-18b0802c9c9b.gif)

## What is the expected result?

Dropdown panel still aligned with the trigger element.

Using `observeRect` from '@reach/observe-rect' may solve it. As the example below:

https://github.com/liferay-frontend/liferay-portal/pull/430/files#diff-298ea5905081aa95c932d1681a7bcf60538269e3e9a96379a504259364432271R99-R101

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.8.0  |
| React |  XXXX   |

**Comment by wincent** [comment]
> Using `observeRect` from '@reach/observe-rect' may solve it.

`@reach/observe-rect` is [only a few lines of code](https://github.com/reach/observe-rect/blob/develop/src/index.ts), so if we wanted to avoid the liability of pulling in another third-party dependency (we have been burned so many times in the past) we could probably implement equivalent functionality pretty trivially.
