### ISSUE TITLE
Icon: React Technology

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3811]
Due to [LEXI-1063](https://issues.liferay.com/browse/LEXI-1063) we've created a new icon for React Technology.
![Icon-react](https://user-images.githubusercontent.com/61543739/100210786-ac7dbf80-2f0b-11eb-8c32-518f7b4a3968.png)

Please, add it to the icon library.

Find the SVG on the ticket.
Thanks!

**Comment by wincent** [comment]
@p2kmgcl mentioned that they want this for GA1, but I fail to find exactly when that is...

**Comment by victorvalle** [comment]
@wincent I believe it is by December 23rd to include mayor changes, minor till January 7th

**Comment by wincent** [comment]
Thanks @victorvalle!
