### ISSUE TITLE
Clay Card (3.x) sticker should not always be rendered 

### ISSUE THREAD

**Issue by julien** [liferay/clay#3816]
Related to what I commented in #3786, stickers [should not always be rendered in cards](https://github.com/liferay/clay/blob/bfb2529dc57c9415a5873d7b9e8b22b3d7be428d/packages/clay-card/src/CardWithInfo.tsx#L173-L198).

As an example, this should not happen:

![](https://user-images.githubusercontent.com/5572/100445207-f94ccc00-30ac-11eb-8b8c-d5330ff7d0dd.png)

**Comment by carloslancha** [comment]
@julien that's a navigation card so that problem will be fixed by using a navigation card.

Anyway, as you said [here](https://github.com/liferay/clay/pull/3817#issuecomment-734839060) we need to find a way to not render the sticker while keeping the default behavior.
