### ISSUE TITLE
[ClayCSS] Move .table-cell-expand class outside .table-autofit

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#3818]
We are upgrading the portal classes from the compat-layer
https://github.com/liferay-frontend/liferay-portal/pull/554/commits/4bf50d07972ce4fb9bbe0d50d79432b1ea8600d5
- In ClayCSS `.table-cell-expand` class works when is children of `.table-autofit`
- In Portal the equivalent class worked independently
- We suspect in Portal some `.table-cell-expand` are not children of `.table-autofit`

https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_tables.scss#L624

---

We could also remove the `%table-cell-contract` since is not used anywhere
https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_tables.scss#L140

**Comment by eduardoallegrini** [comment]
what do you think @pat270? 😄 

/cc @marcoscv-work

**Comment by pat270** [comment]
I don't think this is a good idea, adding `width: 1%` to all `th` and `td` changes the default rendering behavior of table columns. Why can't we add `table-autofit` to any place that used the class `table-cell-field` in portal? If that's not possible, I'd rather add the class `.table-cell-contract` to Clay CSS and update all uses of `table-cell-field` to `table-cell-contract` in portal.

**Comment by eduardoallegrini** [comment]
This is what I meant https://github.com/liferay/clay/pull/3823
