### ISSUE TITLE
Icon: Fieldset

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3828]
Due to [LEXI-978](https://issues.liferay.com/browse/LEXI-978) we've created an icon for the new Fieldset functionality.

![fielset](https://user-images.githubusercontent.com/61543739/100864698-a4d39300-3496-11eb-92f8-dc45c546ae07.png)

Please add it to the icon library.

Find the SVG on the ticket.
Thanks!

**Comment by pat270** [comment]
@hold-shift You linked the Lexi issue for the automatic-translate icon. I'm going to use the icon in https://issues.liferay.com/browse/LEXI-978 let me know if this is the wrong one.

**Comment by hold-shift** [comment]
Correct, that's the right one. I've updated the issue info. 
Sorry, my mistake
