### ISSUE TITLE
Icon: Arrow Right

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3830]
Due to [LEXI-1062](https://issues.liferay.com/browse/LEXI-1062) we've created a new arrow right icon to link it to "publish" metaphor

![Icon-arrow-right](https://user-images.githubusercontent.com/61543739/100877633-55e32900-34a9-11eb-815e-3ba770bb1369.png)

Please, add it to the icon library.

Find the SVG on the ticket.
Thanks!

**Comment by victorvalle** [comment]
Please set the name as "arrow-right-full"

**Comment by wincent** [comment]
Worth noting from the LEXI:

> Priority: we have a bug that is depending on this icon. Fix Pack 2

**Comment by hold-shift** [comment]
Sure, I've just updated it

**Comment by victorvalle** [comment]
@wincent in this case @emiliano.cicero opened the ticket too late for their release so the decided to go without icon. They would add it when it is ready. There is no high priority as far as I know so if you can include it in next release it would be ok, I guess.
