### ISSUE TITLE
@clayui/css Toggle Switch should be 40px by 24px

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3835]
https://issues.liferay.com/browse/LEXI-1089

Changing Toggle Switch to always be 40px by 24px, no small variation needed.

~~I got a couple requests for a `toggle-switch-sm` this week because the desktop version is too large. They don't fit too well inside smaller containers like `dropdown-menu`. I'm thinking make it the same size as the mobile version. 45px x 24px.~~ 
<img width="218" alt="mobile-toggle-switch" src="https://user-images.githubusercontent.com/788266/101177608-dbc3b900-35fc-11eb-83b1-e5cba122b576.png">
What do you think @victorvalle ?

/cc @rdai10 @oliv-yu

**Comment by victorvalle** [comment]
We have [a ticket to study that](https://issues.liferay.com/browse/LEXI-1089), we will let you know the outcome soon.

**Comment by victorvalle** [comment]
Hi @pat270 !

We've studied this and we find we could directly replace our current size, 32px, by a smaller one directly 24px.
In this [Figma](https://www.figma.com/file/KMvkbNLOa8PP9FyQLrenmI/LEXI-1089-Switch-sm-size?node-id=1%3A57) you can find and inspect the new size for each of the elements inside.

As we want a direct replacement and not creating a small version, we would like to know what will happen in certain existing situations in Portal. They also appear in the Figma file.

In case they are not well aligned who will have to make the fix? I guess the fix would be small but we want to anticipate that to the teams.

**Comment by pat270** [comment]
@victorvalle I think changing the size shouldn't cause any problems. It already shrinks to small size in mobile. There might be some minor one off vertical alignment issues.
