### ISSUE TITLE
ClayMultiSelect (3.x) is missing a helpText prop

### ISSUE THREAD

**Issue by julien** [liferay/clay#3839]
In 2.x, the MultiSelect component [used to have a `helpText` parameter](https://github.com/liferay/clay/blob/cd994a00f73063d22495f295c00f05c736ef6005/packages/clay-multi-select/src/ClayMultiSelect.js#L676-L683), this is missing in 3.x

**Comment by bryceosterhaus** [comment]
same as label comment

> @julien can you achieve this by composing it within a Form group? [See this for an example](https://storybook.clayui.com/?path=/story/components-claymultiselect--w-group)

**Comment by julien** [comment]
@bryceosterhaus thanks, that solves it.
