### ISSUE TITLE
Plus button can be a button and a link

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#384]
Plus button in management toolbar have two different behaviors:

- Creates a single type of content:
In this case the button is a link that navigates to a creation page, so we need it to be a link.

- Opens a dropdown with different types of contents to create
In this case the button is a button.

Thx!

**Comment by pat270** [comment]
@carloslancha This can already be done, do you need a markup example? Should I create a new Management Bar or add it to an existing one?

**Comment by carloslancha** [comment]
An example would be great! Do it as you prefer @pat270 thx!
