### ISSUE TITLE
ClayMultiSelect (3.x) is missing a label prop 

### ISSUE THREAD

**Issue by julien** [liferay/clay#3840]
In 2.x, the MultiSelect component [used to have a label parameter](https://github.com/liferay/clay/blob/cd994a00f73063d22495f295c00f05c736ef6005/packages/clay-multi-select/src/ClayMultiSelect.js#L722-L729), this is missing in 3.x

**Comment by bryceosterhaus** [comment]
@julien can you achieve this by composing it within a Form group? [See this for an example](https://storybook.clayui.com/?path=/story/components-claymultiselect--w-group)

**Comment by julien** [comment]
@bryceosterhaus thanks. Yes you're right, I'm going to try that and if it works, I'll close this issue.

**Comment by julien** [comment]
@bryceosterhaus works perfectly, so closing this one.
