### ISSUE TITLE
@clayui/css Chrome Tables show background color between table cells

### ISSUE THREAD

**Issue by pat270** [liferay/clay#3847]
Tables in Chrome 87 have small gaps between table cells allowing the background to show through. We can solve this by setting `background-color` on `thead`, `tbody`, and `tfoot`. This was caused by https://github.com/liferay/clay/pull/3822 and https://github.com/liferay/clay/pull/3842.

Screenshot of bug:
<img width="1247" alt="table-artifact-chrome" src="https://user-images.githubusercontent.com/788266/101840819-a8e85c00-3af9-11eb-9504-7cb804fa7aa7.png">

Edit: My browser was zoomed... lets add this anyways

**Comment by pat270** [comment]
Removing 2.x label since caption pr isn't in 2.x.

**Comment by marcoscv-work** [comment]
LGTM!
