### ISSUE TITLE
ClayMultiSelect is using a `button` instead of `ButtonWithIcon`

### ISSUE THREAD

**Issue by julien** [liferay/clay#3850]
I was wonderning why the [`MultiSelect` component renders a `button`](https://github.com/liferay/clay/blob/03e1f07a341634dbfececd97bce9bd5f3b2f5fcb/packages/clay-multi-select/src/index.tsx#L360) instead of a [`ClayButtonWithIcon`](https://github.com/liferay/clay/blob/master/packages/clay-button/src/ButtonWithIcon.tsx)?

No that it's wrong but I was just wondering why.

We're creating a java tag for this component and we'd like both the tag and our React component to be consistent when it comes to what we're rendering.

**Comment by bryceosterhaus** [comment]
@julien my guess is that it wasn't intentional. I think `ClayButtonWIthIcon` was a later abstraction and we didn't go back through existing components and update instances of buttons wrapping icons.
