### ISSUE TITLE
List group notifications

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#386]
Hey @pat270 

Blue line on the left of the list groups notifications can be associated only to a cell, not to the whole dataset. So you can have something like:

![lexicon_-_list_groups](https://user-images.githubusercontent.com/5803434/33331627-664eeff4-d462-11e7-9fea-82280051f9e9.png)

Thx!

**Comment by pat270** [comment]
I was going by the design shown on the screenshot below:
<img width="833" alt="list-group-notification" src="https://user-images.githubusercontent.com/788266/33334136-ca823f7a-d41d-11e7-8269-afdc90550449.png">

@victorvalle @juanantonLR can you guys confirm the behavior by @carloslancha?

**Comment by carloslancha** [comment]
I wrote this with @victorvalle by my side ;)

**Comment by pat270** [comment]
@carloslancha I see. Do the active and hover states stay the same?

**Comment by carloslancha** [comment]
@pat270 what do you mean the same?

**Comment by pat270** [comment]
When the checkbox is checked on both list-group-items in your screen shot, the background color should be light blue.

When hovering both they show the quick actions.

**Comment by carloslancha** [comment]
Yep, that remains the same, just like the regular behavior but with the left blue line there for the "notification" ones :)

**Comment by pat270** [comment]
Also is the blue left border color supposed to be the one shown on your screenshot or the one on my screenshot?

**Comment by carloslancha** [comment]
Yours. Mine was just a test.
