### ISSUE TITLE
I can't add a custom classname  and keep default classnames within ClayToggle component

### ISSUE THREAD

**Issue by interaminense** [liferay/clay#3860]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.14.0 |

**Comment by interaminense** [comment]
The solution would be to change the way the component adds the containerProps:

```
<span
    {...containerProps}
        className={classNames(
        'toggle-switch',
        'simple-toggle-switch',
        containerProps.className,
        {disabled}
    )}
    ref={ref}
>

**Comment by bryceosterhaus** [comment]
@interaminense good catch. I sent a fix at https://github.com/liferay/clay/pull/3861

**Comment by interaminense** [comment]
Thanks, @bryceosterhaus!
