### ISSUE TITLE
Icon: Google Drive

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3869]
Due to [LEXI-1095](https://issues.liferay.com/browse/LEXI-1095) we've created an icon for Google Drive

![icon-google-drive](https://user-images.githubusercontent.com/61543739/103543027-20fa3580-4e9e-11eb-9354-4e6279ff2791.png)

Please add it to the icon library.

Find the SVG on the ticket.
Thanks!

**Comment by pat270** [comment]
Does this need to go into 2.x as well?

**Comment by hold-shift** [comment]
Hey @pat270, I was speaking about this issue with @emiliano-cicero. Going into 3.x will be enough for now.
