### ISSUE TITLE
ClayCards clickable area

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#387]
As lexicon defines on a selectable Card (with checkbox), this can be checked only by clicking on the checkbox itself and on the image area. Right now if you click in the bottom text area checkbox is checked too, and that shouldn't happen.

https://docs.google.com/document/d/1st2moaRVphrsFrDJUz-ic26aH-V46YkQam75X6BHPY0/edit#heading=h.ujczacaa6gt0

**Comment by pat270** [comment]
This can already be done. You just need to move the `label`, `.custom-control-input`, and `.custom-control-indicator` inside `.aspect-ratio`

**Comment by carloslancha** [comment]
Hey @pat270 with that markup (if I've done it correctly) we have some issues:

- On hover only bottom part gets highlighted
![captura de pantalla 2017-12-05 a las 20 11 15](https://user-images.githubusercontent.com/5803434/33625673-9bbadcc0-d9f8-11e7-9e12-997eed71e2cd.png)

- On svg files (for example) if you click out of the svg (on the checkered background) interaction with checkbox doesn't happen.
![captura de pantalla 2017-12-05 a las 20 12 42](https://user-images.githubusercontent.com/5803434/33625730-d8a52a0a-d9f8-11e7-9f34-cedcc9d55a7b.png)

- On cards without image interaction with checkbox can only be done by clicking directly on the checkbox.
![captura de pantalla 2017-12-05 a las 20 14 14](https://user-images.githubusercontent.com/5803434/33625759-f33a2212-d9f8-11e7-90f4-690560f62969.png)

**Comment by pat270** [comment]
This is the markup I tested on beta.2 - beta.4:

```
<div class="card-type-asset form-check form-check-card form-check-top-left">
	<div class="card">
		<div class="aspect-ratio bg-checkered card-item-first">
			<div class="custom-control custom-checkbox">
				<label>
					<input class="custom-control-input" type="checkbox">
					<span class="custom-control-indicator"></span>
					<img alt="thumbnail"class="aspect-ratio-item-center-middle aspect-ratio-item-fluid" src="../../images/thumbnail_coffee.jpg">
					<span class="sticker sticker-bottom-left sticker-danger">JPG</span>
				</label>
			</div>
		</div>
		<div class="card-body">
			<div class="card-row">
				<div class="flex-col flex-col-expand">
					...
				</div>
				<div class="flex-col">
					...
				</div>
			</div>
		</div>
	</div>
</div>
```
