### ISSUE TITLE
Alerts: Review usage of the times icon for component library

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3877]
Hi there!

Due to [LEXI-728](https://issues.liferay.com/browse/LEXI-728), We are reviewing the usage of the times icon in Alerts in order to reflect in our library what is in the published working component. The usage expected should include the "times" icon at 16x16px.

**Current**

![88372630-98c42000-cd96-11ea-8a0b-d6bc435a8240](https://user-images.githubusercontent.com/61543739/103861231-621c6080-50bd-11eb-8235-1a72fd9c7df4.png)

**Expected**

Using "times" icon at 16x16px.

**Comment by pat270** [comment]
For reference #3557.

**Comment by bryceosterhaus** [comment]
@pat270 does this still need to be updated to 16px? I am also a little confused since [this issue](https://github.com/liferay/clay/issues/3557) asked for this component to use "times-small", but this one is asking us to use just "times"?

**Comment by hold-shift** [comment]
From our side, after studying the application of all the times icons on our components, that [request](https://github.com/liferay/clay/issues/3557) has been rejected. Our main goal is to homogenize its application and sizes (considering optical adjustment and future library changes to be as simple as replacing one icon with another). To achieve this, we had to finally keep the "times" icon in the alerts.

**Comment by pat270** [comment]
I think so? I'll update the icon size to 16px. It looks like that is the only thing needed to be done.

**Comment by jbalsas** [comment]
> This issue has been merged and will be released in DXP at https://https://issues.liferay.com/browse/LPS-126699

![notbad](https://user-images.githubusercontent.com/905006/107749226-2145e600-6d12-11eb-88b5-3c4e91386950.gif)

Should it say https://issues.liferay.com/browse/LPS-126701, though, rather than the epic? We will never have a commit with the epic LPS, but we will have one with the deps. I think that one might be harder to find, so this should be okay, just wondering if this would make a difference.

**Comment by wincent** [comment]
> We will never have a commit with the epic LPS, but we will have one with the deps.

Oddly enough, [this time we do](https://github.com/brianchandotcom/liferay-portal/pull/98751) (see both commit title and PR title), but probably by mistake.

**Comment by bryceosterhaus** [comment]
@wincent yeah that was my bad. I took the LPS from the milestone's name in github. I didn't realize we had a milestone ticket on Jira and then an additional "merge to DXP" ticket.

**Comment by wincent** [comment]
If I had a dime for every time I used the wrong LPS I could buy myself something nice from Starbucks by now... maybe not _Venti_ size, but at least _Grande_!
