### ISSUE TITLE
Color Picker: Review usage of the times icon for component library

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3878]
Hi there!

Due to LEXI-728, We are reviewing the usage of the times icon in Color Pickers in order to reflect in our library what is in the published working component. The usage expected should include the "times" icon at 16x16px.

**Current**
![Captura de pantalla 2021-01-07 a las 8 01 27](https://user-images.githubusercontent.com/61543739/103862183-e9b69f00-50be-11eb-8463-b6bb2c3ad2c4.png)

**Expected**
Using "times" icon at 16x16px.

**Comment by brunofernandezg** [comment]
@pat270 @bryceosterhaus should we add this issue to the milestone? thanks

**Comment by bryceosterhaus** [comment]
@brunofernandezg just did! Thanks for catching that
