### ISSUE TITLE
Labels: Review usage of the times icon for component library

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3879]
Hi there!

Due to LEXI-728, We are reviewing the usage of the times icon in Labels in order to reflect in our library what is in the published working component. The usage expected should include the "times-small" icon at 16x16px.

**Current**
![Captura de pantalla 2021-01-07 a las 8 13 05](https://user-images.githubusercontent.com/61543739/103862981-52524b80-50c0-11eb-8fea-a2ffbbd2718e.png)

**Expected**
Using "times-small" icon at 16x16px within the surrounding frame. With few exceptions, we are using this size as a base. We recommend keeping them that way to better manage a future update of the icon library without altering their proportions/path size.

**Comment by pat270** [comment]
We had discussion of this exact situation for Alerts at https://github.com/liferay/clay/issues/3557. I have no problem with this.

/cc @matuzalemsteles @bryceosterhaus

**Comment by bryceosterhaus** [comment]
I can take a look at this today

**Comment by pat270** [comment]
I ended up reverting the change made in #3557 but I can't seem to find the reason. I need to make some tweaks to the CSS to size the clickable area to be 16x16. We can swap out the icon to `times-small` or change the font size of `times` later.

**Comment by bryceosterhaus** [comment]
@pat270 yeah it looks like it needs to change from `0.875rem` on `.alert .close` to `1rem`. 

And then additionally we need to update the react components to use `times-small` instead of `times`

**Comment by bryceosterhaus** [comment]
Some testing... 
`1rem` on `times-small` results in 14x14
`1rem` on `times` results in 16x16

@hold-shift do you happen to have a list of places where `times-small` is supposed to be used over `times`?

**Comment by hold-shift** [comment]
Sure. I can only reach the use of `times-small` in the label component. Due to we are only applying it here, the decision was to unify it with the `times` icon, but it does not seem convenient since scaling the icon also scales the stroke. This icon is meant to appear inserted in 16x16px boxes too, so we need this alternate version to place it there without overlapping edges.

**Comment by bryceosterhaus** [comment]
@hold-shift so the only place we should use `times-small` is in label?

**Comment by hold-shift** [comment]
Yes, as far as I can reach. [In this Figma File](https://www.figma.com/file/tqJ2SAR9VXbvU9UelnKDk3/LEXI-728-Review-usage-of-the-times-icon-for-component-library?node-id=36%3A0), you can see the components that we manage for both icons.

**Comment by bryceosterhaus** [comment]
fixed in https://github.com/liferay/clay/pull/3882

**Comment by hold-shift** [comment]
Hello, this issue has been closed, but the icon used in the labels is still "times". The icon used in the Label component should be "times-small". Thank you

**Comment by bryceosterhaus** [comment]
@hold-shift this is fixed in v3. There are still some uses of "times" in dxp in the management-toolbar component, you can track the process of us updating them to v3 in this epic https://issues.liferay.com/browse/LPS-112468
