### ISSUE TITLE
Switch: Review component size

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3880]
Hi amigos!

[Due to LEXI-1089, ](https://issues.liferay.com/browse/LEXI-1089) we are working on standardizing the size of our switch component, and before proceeding with the change, we wanted to make sure of the impact it will cause you updating this component (from 32px to 24px height, and 56px to 48px width) will have. We are waiting for your response before proceeding with this change. Thank you!

**Comment by pat270** [comment]
Going to close this as duplicate, we have an issue for this already at https://github.com/liferay/clay/issues/3835
