### ISSUE TITLE
Add autoFocus to management toolbar

### ISSUE THREAD

**Issue by 4lejandrito** [liferay/clay#3895]
## What is your proposal?
To add the `autoFocus` property to the management toolbar component so that the search box gains focus if present.

## Why would adopting this proposal be beneficial?
At the moment we have [this piece of code](https://github.com/liferay/liferay-portal/blob/e0a21bcacb109f3e4b79e6da286d2f3b79e4f301/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/search_info.jsp#L150-L156) in Documents and Media to achieve that. It is not only ugly but also caused some recent issues and will likely break again in the future.

## What are the alternatives to this proposal?
Keep using our ugly code 😢 .

Thanks!

**Comment by bryceosterhaus** [comment]
@4lejandrito I think this is a fix that needs to be made in the DXP implementation of ManagementToolbar. If you want, you can go ahead and send a PR to the `liferay-frontend` repo and add that prop in. I believe you would just need to add it to [this component](https://github.com/liferay/liferay-portal/blob/9e4836a9e8f852fa02deb3790a71d8c0f2911b19/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/SearchControls.js) and then make it available in the taglib in [this file](https://github.com/liferay/liferay-portal/blob/ca1fd346880de3bc161e00b7710267ed70164894/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/ManagementToolbarTag.java)

**Comment by 4lejandrito** [comment]
Hi @bryceosterhaus,

We're happy to implement it just for DXP but I still think it belongs to the clay component.

Feel free to close this ticket and we will create an LPS to implement it in portal.

Thanks!

**Comment by bryceosterhaus** [comment]
@4lejandrito that should already be possible with components in Clay@v3. Our management toolbar package contains a bunch of low-level components to be composed together. If you look at [our storybook example](https://storybook.clayui.com/?path=/story/components-claymanagementtoolbar--w-low-level) of Management toolbar, you would just need to add that `autoFocus` prop to the [ClayInput](https://github.com/liferay/clay/blob/master/packages/clay-management-toolbar/stories/index.tsx#L106-L111) component use in management toolbar.

**Comment by 4lejandrito** [comment]
I didn't know that. Then it sounds much better. 

Thanks @bryceosterhaus!

**Comment by 4lejandrito** [comment]
See https://issues.liferay.com/browse/LPS-127020.
