### ISSUE TITLE
ClayPanel: The page is refreshed after click on the Header, inside a Form Tag

### ISSUE THREAD

**Issue by kevenleone** [liferay/clay#3896]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

Here: https://codesandbox.io/s/jovial-wind-bgk8k?file=/src/panel.js

## What are the steps to reproduce?
1. Click on Panel to Collapse/Close

## What is the expected result?
The page should not be reloaded inside a Form Tag

## Environment

| Tech  | Version |
| ----- | ------- |
| @clayui/panel  | v3.3.4  |
| React |  16.12.0       |

**Comment by kevenleone** [comment]
Hello Guys, @MateusCastro was looking at this bug -> https://issues.liferay.com/browse/LPS-125984

And after investigate we found a relation with the ClayPanel inside a Form Tag, as you can see on CodeSandBox, can you look at this?

Thanks!

**Comment by jbalsas** [comment]
> And after investigate we found a relation with the ClayPanel inside a Form Tag, as you can see on CodeSandBox, can you look at this?

Hello `<button type="button">` my old frieend... 🎵

**Comment by jbalsas** [comment]
Using `<ClayButton>` in https://github.com/liferay/clay/blob/master/packages/clay-panel/src/index.tsx#L118 should shield us from this... maybe we should go through components one more time and see how many rogue `<button>` usages we have in there to avoid this from re-surfacing elsewhere.

**Comment by matuzalemsteles** [comment]
> Hello <button type="button"> my old frieend... 🎵

😢

**Comment by bryceosterhaus** [comment]
@jbalsas we can't use `ClayButton` everywhere since we don't necessarily want the "btn" class in all places.

I went through and updated all rogue button elements though, I think this should be fixed now in my PR.

**Comment by jbalsas** [comment]
> @jbalsas we can't use ClayButton everywhere since we don't necessarily want the "btn" class in all places.

Makes sense!

![illallowit](https://user-images.githubusercontent.com/905006/105244805-edd7c780-5b68-11eb-9b06-7f85529e1bfa.gif)
