### ISSUE TITLE
Clicking on ClayPanel within a form may cause submission

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#3900]
-   [x ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

https://codesandbox.io/s/withered-shape-68ot0?file=/src/index.js

## What are the steps to reproduce?
1. Click on the title of the panel to expand

## What is the expected result?
It should just expand the panel, however it looks like it does a submission after expanding the panel. As a workaround, adding `onClick= {(event) => event.preventDefault()}` to ClayPanel will prevent it.

Thank you! cc: @thektan

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.3.4  |
| React |         |

**Comment by matuzalemsteles** [comment]
Hey @oliv-yu thanks for reporting this, this is related to issue #3896 I will mark this as duplicate and close. This has already been fixed and merged in Clay and scheduled for release on the 27th if you want to follow the milestone https://github.com/liferay/clay/milestone/34.

**Comment by oliv-yu** [comment]
Thank you! Oops, didn't know it was a duplicate.

**Comment by matuzalemsteles** [comment]
@oliv-yu Don't worry!
