### ISSUE TITLE
Feature Request - Alphbetical Sorting on Dropdown/up Menus

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#391]
Have the ability to order drop down menus by alphabetical order ascending or descending based on a data attribute on the element containing the dropdown-menu class. Something like aria-sortby or data-sortby="alpha-asc" (alpha-asc, alpha-desc, none) 

See GIF. 

![feature-request-clay](https://user-images.githubusercontent.com/18121278/33678990-18013146-da83-11e7-9c9a-d3284d3e1f3e.gif)

**Comment by pat270** [comment]
@duracell80 Thanks for the request, I think it would be better if this was handled by metal-clay-components. I filed a feature request there.

**Comment by pat270** [comment]
Closing this, discussion is continued on metal-clay-components.
