### ISSUE TITLE
Allow for color-picker to use both custom and default color palettes

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3910]
Lexicon specification has changed and we should allow for using both at the same time. [docs](https://docs.google.com/document/d/1IUGl5VOWh6lqRa1baRoshVcytc8XbqVMkk30vRW4SM8/edit#heading=h.7dwfrx5xjmtw)

Note the first pane
![image](https://user-images.githubusercontent.com/6843530/106037409-7c79a680-608b-11eb-9c86-592f9950c658.png)

**Comment by d80wrk** [comment]
Upvoted
