### ISSUE TITLE
Clay CSS missing dropdown arrow symbol in IE11

### ISSUE THREAD

**Issue by rolandpakai** [liferay/clay#3922]
## What are the steps to reproduce?
In Liferay:
1. Access the Liferay application using Internet Explorer 11
2. Go to Control Panel > Users > Users & Organizations > Organization
3. Create a new Organization, and check the Country field of the screen

Out of Liferay:
1. Create a select html tag with form-control class
2. Check the select dropdown arrow symbol using Internet Explorer 11

## What is the expected result?
The dropdown menu's arrow icon is being displayed

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v2.21.1  |
| Liferay | 7.1.x/7.2.x  |

## Root Cause
In clay 2x The -ms-expand display:none property is causing the dropdown arrow dissaperence in IE11.
https://github.com/liferay/clay/blob/2.x/packages/clay-css/src/scss/components/_forms.scss#L288-L290

In clay 3x we are using background-color: transparent; border: 0; properties here:
https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_forms.scss#L310-L313

The changes was inroduced here: 
https://github.com/liferay/clay/commit/e7e854f8f844c0e888255ba5a24758780ae1d6b7
https://github.com/liferay/clay/commit/7383992e6a84e89cdfb7ef4305f12d66a5b06f1e

## Jira ticket
https://issues.liferay.com/browse/LPS-127635

**Comment by rolandpakai** [comment]
https://github.com/liferay/clay/pull/3923

**Comment by pat270** [comment]
@rolandpakai 2.22.2 should be available for use now. See #3929

**Comment by rolandpakai** [comment]
Thank you @pat270
