### ISSUE TITLE
ClayCard List

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#393]
We need card lists to be lists (in the same way list groups are).

We found that replacing `<div class="row">` with `<ul class="list-unstyled row">` and each card `<div class="col-lg-3 col-md-4 col-sm-6">` with `<li class="col-lg-3 col-md-4 col-sm-6">` do the trick, but we want to be sure about it.

Thx!

http://pat270.github.io/lexicon/content/test-card-view-template/

**Comment by yuchi** [comment]
My 2cents: a `row` should not be anything else or margins/padding will break too easily. (Notice: non-flex experience here)

**Comment by pat270** [comment]
@carloslancha, I agree with @yuchi we shouldn't use Bootstrap's grid for this. It doesn't size or break well in all screen sizes with varying items and side navigations that we have in Portal. I'll add something (don't know what to call it) to layout the cards for you.

**Comment by carloslancha** [comment]
Perfect, thanks @pat270 and @yuchi !
