### ISSUE TITLE
Loading icons

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#394]
Hey guys,

After a talk with @victorvalle :

· We do not need "loading-icon-linear", so we will have only the dotted version which is currently in 'develop' branch.
· About sizes, we only need XS and SM.

**Comment by pat270** [comment]
@marcoscv-work what sizes should XS(20px), SM(40px) and Regular(40px) be?

**Comment by marcoscv-work** [comment]
Hey @pat270 ! the sizes are 20px and 40px, actually, you can size-name as you think is better
