### ISSUE TITLE
A component returning a link or a button, based on props

### ISSUE THREAD

**Issue by markocikos** [liferay/clay#3940]
See start of discussion in https://github.com/liferay-frontend/liferay-portal/pull/795

> @markocikos do you think it would be helpful for this PR and other teams if we exposed a more general `LinkOrButton` component from Clay? We could expose it from an existing package.

@bryceosterhaus I just went through 37 uses of `<ClayLink>` in dxp, there is 
-  one more use with the same Link / Button pattern, in [NavigationBar](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/NavigationBar.js#L34-L49)
- two uses with very similar solutions that could (and probably should) be refactored to the same pattern, [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/components/data_renderers/ActionsDropdownRenderer.js#L185-L212) and [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/data_set_display/data_renderers/ActionsDropdownRenderer.js#L287-L319).

So, there is a use for it outside of `<ManagementToolbar>` component, meaning it would in theory be useful to have it in Clay.

But, I am not sure about usefulness of a more general component, and what would be its API. In https://github.com/liferay-frontend/liferay-portal/pull/795 we are benefiting from few opinionated parts of implementation:
- `href` decides if the component is a link or a button. In [ActionsDropdownRenderer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/data_set_display/data_renderers/ActionsDropdownRenderer.js#L32-L34) we are checking an explicit declaration: `actionItem.target === 'link'`. This could imply that we want something like `linkOrButton` prop in a general solution.
- We support `symbol` that overrides `children`. A more general component may want to support an icon left or right of `children`.
- `disabled` prop sets component to `button`, even if `href` is set. This is because a link is not disabled by setting the `disabled` attribute, so it cannot fall under `otherProps`. Old component had this logic and it is supported in CSS. Does this make sense to enforce in general case? I tend to think yes, but I'm not sure.

> Another option would be to create a new helper/util package that is intended to be consumed? Unlike @clayui/shared, where we explicitly state its for internals.

I guess it depends on your intended use of `@clayui/shared`. If it's just for internal components, and we are making a new components to be consumed in DXP, then it would make sense to me to create a new package. Something like `clay-link-or-button`.

That name <LinkOrButtom> is also a bit awkward, maybe some wordsmith can come up with a better one :slightly_smiling_face:  I was considering `<Control>` in PR, but it may be too general.

/cc @julien @ambrinchaudhary @jonmak08

**Comment by wincent** [comment]
> > Another option would be to create a new helper/util package that is intended to be consumed? Unlike @clayui/shared, where we explicitly state its for internals.
> 
> I guess it depends on your intended use of `@clayui/shared`. If it's just for internal components, and we are making a new components to be consumed in DXP, then it would make sense to me to create a new package. Something like `clay-link-or-button`.

It seems like there are already too many Clay packages (41 core packages at last count), which brings considerable overhead and is one of the reasons why [people have had trouble tracking what's happening in Clay](https://github.com/liferay/clay/issues/3849) and why we still have [some work to do](https://github.com/liferay/clay/issues/3939) making our communication easier for others to digest. Before creating yet another package (whether it be a "shared" grab-bag package, or a specific `clay-link-or-button` package), I'd suggest looking for an existing package that this variant could be rolled into (ie. `clay-link` or `clay-button`, probably — yes this would mean that one of them would have to depend on the other, but that's probably fine, right?).

Just for comparison, one pretty popular React-based UI framework is [material-ui](https://github.com/mui-org/material-ui/) (65.3k stars at the time I write this, and [> 1.6M weekly downloads of the core package](https://www.npmjs.com/package/@material-ui/core)). Their [full package list is here](https://github.com/mui-org/material-ui/tree/next/packages), but all you need to get started is a `yarn add @material-ui/core`. That main package depends on 4 other `@material-ui` dependencies. I know it's difficult to put the genie back in the bottle at this point, but there's definitely something to admire and learn from in that project.

**Comment by bryceosterhaus** [comment]
> I'd suggest looking for an existing package that this variant could be rolled into (ie. clay-link or clay-button, probably — yes this would mean that one of them would have to depend on the other, but that's probably fine, right?).

Totally agree, and I don't think having one dependent on the other is a big issue.

> Their full package list is here, but all you need to get started is a yarn add @material-ui/core

I've been thinking more about this lately as well and I want to experiment with this a bit and see if I can come up with something that is both simple for consuming devs but also easy for managing and working on clay.

**Comment by matuzalemsteles** [comment]
> Their full package list is here, but all you need to get started is a yarn add @material-ui/core

One thing to add about this is that it is quite common among the UI Framework that I see. Keeping each component in a package was also something inherited from the early versions of 2.x or something well before that.

I'm just listing some UI frameworks that I know of that follow this line of having a package for all components:

- [Carbon Design System](https://github.com/carbon-design-system/carbon/tree/master/packages/react)
- [Base Web](https://github.com/uber/baseweb)
- [Blueprint](https://github.com/palantir/blueprint/tree/develop/packages/core)
- [Ant Design](https://github.com/ant-design/ant-design)
- [Evergreen](https://github.com/segmentio/evergreen)

There are others but I ended up forgetting the name 🙂, some use a little of the idea of having the core package and some other component packages but very minimal (4 to 5) outside the core.

**Comment by markocikos** [comment]
I tend to agree with all of you, but here is an argument from perspective of an enterprise customer: updating a monolith package is risky. He may want to update `<ClayLink>` with sexy new API, but updating `@clayui/core` may cause issues elsewhere. But, if he can update just `@clayui/link`, chances for bugs are much lower.

**Comment by bryceosterhaus** [comment]
Material-Ui looks to essentially have a [mono package](https://github.com/mui-org/material-ui/tree/next/packages/material-ui/src) and then a few other packages that bring in "extras." If we used the same structure, I think all the react components would be in a single clay package and then css would be in a separate package. 

@wincent you're right that its hard to "difficult to put the genie back in the bottle at this point", and maybe we should re-evaluate this whenever we go for v4. Looking back a the start of v3 and seeing where we are now, I probably would've opted for a monolith since our main consumer is DXP and thus will _always_ take every component. When we initially were thinking through this, I think we were keeping commerce and AC in mind when they were separate projects outside of DXP. However, since then Liferay has moved more towards monolith.

@markocikos do you happen to know of any customers or any projects outside of DXP that might be using only a few clay packages and wouldn't want all of clay? I know we created it with that in mind initially, but I'm not sure it was actually needed.

Anyways, one option to get the best of both worlds would be to create an additional package that contains all the others. So we could do something like `import {ClayLink} from '@clayui/core';`. But this is more work and maintenance overhead.

**Comment by markocikos** [comment]
> @markocikos do you happen to know of any customers or any projects outside of DXP that might be using only a few clay packages and wouldn't want all of clay? I know we created it with that in mind initially, but I'm not sure it was actually needed.

No, I imagine everybody would want all of Clay... initially. I am talking about upgrading Clay, once the customer's project is in production, or even in late development. Then it becomes valuable to be able to cherry-pick only useful updates / bugfixes. I have quite a few personal experiences where a large mono-product was updated and caused problems. Familiar examples would include jQuery, CKEditor and DXP itself.

**Comment by wincent** [comment]
> I have quite a few personal experiences where a large mono-product was updated and caused problems. Familiar examples would include jQuery, CKEditor and DXP itself.

The thing is, our "monolith" should be pretty safe to use as a whole. If we are making risky changes to any part of it, we're doing something wrong.

I also caution against catering for a use case that is only hypothetical (enterprise customers picking and choosing isolated Clay components) when we _know_ that our core use case, and the one which we spend the vast bulk of our time servicing, is DXP.

**Comment by markocikos** [comment]
@julien Yeah, I think this is ok to close. We can revisit it again, if usages in DXP grow. In any case, I think we concluded that link-or-button should not be a dedicated component, but an extension of either `clay-link` or `clay-button`.
