### ISSUE TITLE
Wrong CSS built value for col-form-label

### ISSUE THREAD

**Issue by giulioz** [liferay/clay#3946]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

ClayUI complies to a wrong css calc expression for the `col-form-label` class in padding values, since it uses this variable in the sum, that has four items:

https://github.com/liferay/clay/blob/144c39de6a3053878af0bb41f86146594beda8ef/packages/clay-css/src/scss/variables/_forms.scss#L10

Sum performed here:

https://github.com/liferay/clay/blob/1debe8bcc2894db5ae751fc06fe771a43d195817/packages/clay-css/src/scss/components/_forms.scss#L634

As you can see in the compiled `lib/css/base.css` it compiles to a wrong value:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/1353142/108985699-9cec4f00-7691-11eb-8116-c3d482fd4e26.png">

This breaks build using the latest `react-scripts`:

```
Creating an optimized production build...
Failed to compile.

Parse error on line 1:
0.375rem + 0.0625rem 0.0625rem ...
---------------------^
Expecting end of input, "RPAREN", "ADD", "SUB", "MUL", "DIV", got unexpected "REMS"
CompileError: Begins at CSS selector undefined
```

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.235.0  |
| React |  17.0.0 |

**Comment by giulioz** [comment]
A CodeSandbox to reproduce the issue is [this](https://codesandbox.io/s/clay-css-bug-wfurg?file=/src/App.js), even though to reproduce it you need to download the zip and perform a `yarn build`

**Comment by pat270** [comment]
Thanks for the report @giulioz! Just sent a fix in.
