### ISSUE TITLE
Evaluate how we release 2.x 

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3948]
Conversation started at https://github.com/liferay-frontend/liferay-portal/pull/814

> @wincent 
> I'd take the opposite stance. I'd rather know that "vX.Y.Z" of Clay means "the set of Clay packages that we know work well together", and liferay-portal always will have the latest (ie. the last-known/best-working version of every Clay package). We have a global changelog, so if I care to know the details, I'd look at that. Furthermore, when we update in liferay-portal, we take care of updating the version numbers in every module, so there's no burden for the consumers; they don't even need to know an update happened (especially because we don't make breaking changes). The counterscenario is that you wind up with what we currently have in v3, which is a bunch of different version numbers (as I reported here, there are 39 different Clay v3 packages and 23 distinct v3 version numbers at once in liferay-portal) — that seems much more confusing.

I like the idea of being able to think "this set of Clay packages work well together", and bumping all versions at the same time is one way to accomplish that. When thinking about that though, it makes me think that devs want a singular "all-in-one" package, rather than multiple segmented packages. Which luckily for our case, 2.x has that in the `clay` package. So maybe instead of providing every individual package to DXP we just provide `clay` and that way its all based off a single version.

**Comment by wincent** [comment]
> When thinking about that though, it makes me think that devs want a singular "all-in-one" package, rather than multiple segmented packages. Which luckily for our case, 2.x has that in the `clay` package. So maybe instead of providing every individual package to DXP we just provide `clay` and that way its all based off a single version.

That would be a nice simplification, and in line with [what we were discussing over here](https://github.com/liferay/clay/issues/3940#issuecomment-780635320).

**Comment by jbalsas** [comment]
> I like the idea of being able to think "this set of Clay packages work well together", and bumping all versions at the same time is one way to accomplish that. When thinking about that though, it makes me think that devs want a singular "all-in-one" package, rather than multiple segmented packages. Which luckily for our case, 2.x has that in the clay package. So maybe instead of providing every individual package to DXP we just provide clay and that way its all based off a single version.

I wouldn't consider this for the `2.x` branch since it would require us reworking a lot of stuff in our older branches for very little gain. It would be interesting for `3.x` if that's the direction we want to take, but doing it for `2.x` sounds like unnecessary overhead.

**Comment by wincent** [comment]
I think @antonio-ortega's [thread from yesterday](https://liferay.slack.com/archives/C3JBR21HA/p1614152549135600) is interesting to take into consideration here. Support likes the granularity of individual updates, but the incidental complexity is killing them. (To be clear, both options "suck", but in different ways.)

**Comment by jbalsas** [comment]
> I think @antonio-ortega's thread from yesterday is interesting to take into consideration here. Support likes the granularity of individual updates, but the incidental complexity is killing them. (To be clear, both options "suck", but in different ways.)

I thought this was a separate option:
- Release all packages every time (I actually thought this was the case for `2.x` but I see we have different versions too)
- Release packages independently
- Do whatever but consume packages from a single place `clay` rather than from `clay/foo` and `clay/bar`

I'm all in favour of releasing all packages with the same version and dropping `^` for `2.x` but not for the change from imports which would require code changes.

I'm happy to explore `@clayui/core` and `@clayui/components` or somethings like that in our `3.x` version if we feel it's a good approach that simplifies our workflows!! :)

**Comment by wincent** [comment]
> * Release all packages every time (I actually thought this was the case for `2.x` but I see we have different versions too)

Yeah, [you are not alone](https://liferay.slack.com/archives/C3JBR21HA/p1614062212048500).

**Comment by bryceosterhaus** [comment]
> Release all packages every time (I actually thought this was the case for 2.x but I see we have different versions too)

I'm cool with doing this if we think its the path of least resistance and is clearest for people consuming it. I just need to update the release docs for the 2.x branch which would tell the dev to explicitly declare what minor/patch version it should be. So we wouldn't use the --conventional-commits flag.

As for v3, I am happy to explore some options moving forward to see what might be beneficial for us. I am all for the approach of helping ourselves that simplify our work and make it easier for people to use what we make

**Comment by bryceosterhaus** [comment]
Closing since we seem to agree on delivery for 2.x, updating all packages to the same version at once. This is reflected in the 2.x release docs.
