### ISSUE TITLE
Implement the Vertical Bar component from Lexicon

### ISSUE THREAD

**Issue by corbinmurakami** [liferay/clay#3959]
## What is your proposal?
Implement the [Vertical Bar component](https://liferay.design/lexicon/core-components/vertical-bar/) from Liferay Lexicon

**Comment by pat270** [comment]
@corbinmurakami The CSS is there 7.3.1 GA2 (Clay CSS 3.8.0). We just need to implement a js component for it. You can see a demo at https://pat270.github.io/clay3-test-site/v3.8.0/content/slideout/. Fixed positioned vertical bars should be relatively easy to implement, just need to add the right classes on open, close, and transition-end.

**Comment by corbinmurakami** [comment]
I see, thanks for letting me know. Is there anything blocking the creation of the js component? And do you want to keep this same issue open for that work?

**Comment by matuzalemsteles** [comment]
I'm closing this issue because it's duplicated with issue #2903, I'll keep #2903 so we can work on it and you can track the progress there.
