### ISSUE TITLE
hr icon is incorrect size

### ISSUE THREAD

**Issue by john-co** [liferay/clay#3961]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
no

## What are the steps to reproduce?

1. Go to https://clayui.com/docs/components/icon.html
2. Search for `hr`
3. Compare the size with icon used for [indeterminate checkbox](https://clayui.com/docs/components/checkbox.html#indeterminate)

## What is the expected result?
The icon library for hr icon is the same size as the indeterminate checkbox icon.
![Checkbox Review](https://user-images.githubusercontent.com/35235266/109552682-f801b580-7a86-11eb-88ec-8694bf0b7395.png)

see LEXI review: https://issues.liferay.com/browse/LEXI-1128

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.1.0  |
| React |         |

**Comment by pat270** [comment]
Going to close this one, I accidentally fixed it in https://github.com/liferay/clay/pull/3971
