### ISSUE TITLE
Multiple Select | Dual Listbox components review

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3970]
Hi! Due to [LEXI-1130](https://issues.liferay.com/browse/LEXI-1130), we request a change to the "multiple select" component so the styles follow the [dual-listbox documentation. ](https://docs.google.com/document/d/1S1YeFlqmUqtivxe4bNDv8sN2ZYwczJ9KYOSUSO5a1hE/edit)

![Select Review](https://user-images.githubusercontent.com/61543739/109952657-5de87a00-7cdf-11eb-91d7-857562b64c4c.png)

The selected item should apply $primary-d2 background and $white font color.

Please, follow the ticket or the figma document for more info.

Thanks!

**Comment by pat270** [comment]
@hold-shift We have a problem. Dual List Box uses the HTML `select[multiple]` element.  Example below:

```
<select class="form-control" multiple>
    <option>Option 1</option>
    <option>Option 2</option>
    <option>Option 3</option>
    <option>Option 4</option>
</select>
```

The browser doesn't let us style much on the `option:checked` element. We can change the background-color using a `background-image` hack at most. To implement the checked style, we will need to create our own select multiple component that reimplements all the features provided by the default HTML select (unless I can find a clever hack).

@bryceosterhaus @matuzalemsteles

**Comment by matuzalemsteles** [comment]
@pat270 yeah, I think we wouldn't be able to manipulate via JavaScript, normally these native components don't give us a lot of flexibility. That's what we did with TimePicker, we had to re-implement it from scratch 😢.

**Comment by pat270** [comment]
The select element does everything we want, just can't style `option:checked`.

**Comment by hold-shift** [comment]
I think we're going to put this on hold for now then. The expected behavior for the checked state was to be styled as reflected in the documentation, but if it cannot be controlled, and the change to our own select multiple component is too complex, it is up to you to decide if it is worth it or not.  From our side, it is not a drama since the current component is styled liked that, although it is possible that we will return to this point in a future iteration.

**Comment by pat270** [comment]
I tinkered with this a little more today. The best I can do right now is have it styled properly in Chrome and FF. The hacks don't work in Safari. I'm not sure how you feel about it only working in certain browsers, but this is doable with little changes.

**Comment by pat270** [comment]
Closing this, going to use the new mentioned issue to continue discussion.
