### ISSUE TITLE
[Date Picker] Date Range

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3986]
Hi Clay team,

Due to [LEXI-1127](https://issues.liferay.com/browse/LEXI-1127) team-tango has requested a new feature for the date picker component. 

![Date Range](https://user-images.githubusercontent.com/21216422/111257792-11286b80-861c-11eb-8c27-532cdca4c9ee.png)

I said feature because I can't say if it's a feature or a variant. We documented it as a variant because it has two parts to introduce the date but except that it's just a change in the behavior of selecting dates. However, you must guide us and decide what this will be. 

Please review the definition added to the original [date picker document](https://docs.google.com/document/d/1iPFtX7Zku7N-sElSfpGSBlfpYvMu4ATCkVVCU_oB3a4/edit?usp=sharing).

ps. We would like to introduce some improvements about input masking BUT we don't want to propose those changes now because team-tango didn't request those changes and we don't want to slow down the development of this request. If you say it would be good to propose it soon please let us know and we will work as soon as possible to introduce new changes in the main component. 

ps2. Besides we would like to renew all the definition doc so we plan to update it on [LEXI-975](https://issues.liferay.com/browse/LEXI-975)

**Comment by pat270** [comment]
For the highlighted items, will we have hover and active (mousedown) states for it?

**Comment by drakonux** [comment]
Yeah, exactly the same no changes, as they were a no highlighted element. 

PS. We plan to move the current definition doc to Confluence. So we will review everything in deep to have a more clear definition.

**Comment by matuzalemsteles** [comment]
Hey @drakonux, answering a few things:

- Mask: Well I think this is really important with the addition of range but it is not mandatory, so we can leave it to implement later because we will probably have to spend a little more time on it.
- Variant: I think we can keep it as a component variation, we did the same for Time Picker. In the end, in the component, we will just add a few more props to activate this variation.

About the behaviors described in the document I seem clear, thanks @drakonux!

**Comment by wincent** [comment]
So it seems we have clarity on the requirements here, based on what I read above. Shall we add this to the next (or an upcoming milestone) so that Tango folks can have an idea of when this is going to get underway and into liferay-portal?

cc @brunofernandezg

**Comment by matuzalemsteles** [comment]
Hey @wincent I'm going back to Infra from tomorrow but still part-time until the end of the migration, I don't know if this will be ready by April 7th, maybe move to the 21st milestone so I can review all the pending, @diegonvs is also coming back with a lot of time...

**Comment by diegonvs** [comment]
Hey @drakonux @hold-shift,

What will happen when the user clicks on the dot button?

![image](https://user-images.githubusercontent.com/7663513/113342346-c2115480-9304-11eb-929e-30617b52fe41.png)

By default it will select the current Date.

What do you expect for the date range?

I would suggest focusing on the start date but it will break the logic for non-date-range usages, which is focusing on the current date.

**Comment by matuzalemsteles** [comment]
I'm just going to reopen this because @diegonvs is working on the component. #4008

**Comment by brunofernandezg** [comment]
> I'm just going to reopen this because @diegonvs is working on the component. #4008
> 
> EDIT: Thinking better of the track on Jira, I will create another issue.

Really appreciate it. no one ever had thought in Jira before  😭 Thanks.
