### ISSUE TITLE
[Date Picker] Collapse on Selection

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#3990]
(I swear) I've searched here: [https://clayui.com/docs/components/date-picker/api.html](https://clayui.com/docs/components/date-picker/api.html) but I still not sure if there is one for what I'm asking for. 

## What is your question?
I would like to know if there is one property to collapse the calendar when a date/date range is selected.

For example, in a use case where it's important to preview information before selecting a date. The date picker could work better when a user selects a date/date range, holding the calendar expanded because this helps users to explore different dates and see the chart info changing at the same time until the user decides the final date and clicks outside of the calendar. 

And in other cases, when the user selects a date, it's better to collapse the calendar immediately as the HTML5 input type date currently does.

**Comment by matuzalemsteles** [comment]
Hey @drakonux,

"(I swear) [...]" 😂

Answering your question, yes I agree with you, it is possible, by default when a date is selected the Date Picker is kept expanded, but if the developer wants to close the Date Picker when selecting a date, he will have to control the state of the component, to this, it uses the `expanded` and `onExpandedChange` properties and can add its rules.

See the two examples:
- [Default behavior](https://storybook.clayui.com/?path=/story/components-claydatepicker--default)
- [Closes when the date is selected](https://storybook.clayui.com/?path=/story/components-claydatepicker--w-custom-expand)

**Comment by drakonux** [comment]
Nice Matu! 😇 thanks for the answer
