### ISSUE TITLE
[Date Picker] Date Range with Menu and Extension Point

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#3994]
Due to [LEXI-1127](https://issues.liferay.com/browse/LEXI-1127) and following #3986, to give a complete answer to Tango team about the possibilities offered by the date picker component, we would like to know if with the current components Clay team can currently assemble a solution such as the AC Team to select a date range.

The interaction flow would include:

1. Borderless button that would trigger a dropdown and change its text depending on the item selected in it.
2. Dropdown with 2 lines of text.

In the next image, you can see the proposed solution with Lexicon components. 

![Date-Range-AC](https://user-images.githubusercontent.com/61543739/111620046-86e03300-87e6-11eb-8be3-0e363f7e0966.png)

Adding the AC solution to finish providing context.

![111308455-fd502a00-865a-11eb-9c1d-c571a2b88871-1](https://user-images.githubusercontent.com/61543739/111619970-7334cc80-87e6-11eb-8d03-df14ca2af175.gif)

**Comment by matuzalemsteles** [comment]
Hey @hold-shift,

Some things that Clay can support in this flow, well the Tango team will have to make a composition of our components to reach the final result.

- Date Range - We do not have it yet, we will have to work on it for the ticket that was recently opened #3986
- The Borderless button for triggering DropDown is possible to do this today (See example https://codesandbox.io/s/quick-start-clay-finale-forked-xcfh2?file=/src/index.js)
- The DropDown items with title and description I am not sure if the CSS can reach this case, even if it is not the component it allows you to add more cases without depending on Clay's CSS in this case. @pat270 you probably know better than me, if we can get to that case.

**Comment by pat270** [comment]
@matuzalemsteles The `dropdown-item` can contain multiple lines of text. There is no height restriction.

**Comment by hold-shift** [comment]
Great, this information and the work you are doing on #3986 and #3989 is pretty complete for the Tango team to know what possibilities the date-picker offers in order to design the best solution that fits its use case. Thanks a lot!
