### ISSUE TITLE
Unespected behaviour ColorPicker component on DropDown

### ISSUE THREAD

**Issue by garofalog** [liferay/clay#4001]
![](https://user-images.githubusercontent.com/67319631/112338122-d16a1f80-8cbe-11eb-91ce-80f2e6120773.gif)

**Description**
Hello you all,
i'm working on SHOP BY DIAGRAM component, [here](https://github.com/liferay-commerce/liferay-portal/pull/842) the pr as a draft.
Clicking on dropdown and selecting the color from ClayColorPicker (contained in the DrowDown), i'm losing the focus on DropDown so this collapse while the ColorPicker popup keep staying open.

**Expected Behaviour**
Selecting the color (clicking out of drowdown itself, but in a dropdown-contained-component) the dropdown component should not collapse.

Thank you

**Comment by matuzalemsteles** [comment]
Hey @garofalog, sorry for the delay.

I think this may be related to clicking outside DropDown that makes it close and Align does repositioning the Color Picker. Probably the Portal nesting did not work very well or is really the problem of the click outside DropDown, I will investigate this later. Thanks @garofalog!

**Comment by garofalog** [comment]
Hi @matuzalemsteles, doesn't think this due to the Portal because I'm using it in a static environment not yet integrated in Liferay. I guess it's only an issue about focusing out of drop-down component and an unexpected behavior on colorPicker-color-choice-popup positioning. The link to my draft pr is in the previous comment. Thank you

**Comment by matuzalemsteles** [comment]
Hey @garofalog, sorry for the confusion when I meant Portal I was referring to `React.createPortal` 😅, DropDown, and ColorPicker are using to render in the body but respect a nesting of Portals when they are being used inside each other to try to correct problems like this click outside.

**Comment by matuzalemsteles** [comment]
Hey @garofalog we fixed this in the Cascading Menu #4102 implementation, I made an example in the storybook for you to check out https://codesandbox.io/s/quick-start-clay-finale-forked-hug55?file=/src/index.js. Let me know if you need anything else, I'll close the issue and if it still reproduces, feel free to open it again.
