### ISSUE TITLE
isLoading prop on multi select component

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#4017]
In a new implementation we would like to use a multi select as an autocomplete.

During the fetch we would like to notify the user that something is going on by displaying a loading indicator. 
The visual feedback should be the same as a normal autocomplete (a loading indicator on the right)

My proposals are 2:

1. adding a prop which might be called `isLoading` to a multi select
2. allowing the autocomplete component to show multiple values by passing them via prop (transforming it in a multi select)

**Comment by matuzalemsteles** [comment]
Hey @FabioDiegoMastrorilli, if I understand correctly you want to do something similar like the example of the autocomplete https://storybook.clayui.com/?path=/story/components-clayautocomplete--w-async-data?

> allowing the autocomplete component to show multiple values by passing them via prop (transforming it in a multi select)

This was not very clear to me, could you explain it better?

**Comment by FabioDiegoMastrorilli** [comment]
Yes, you got it right! :) 
I'll try to explain it better by sharing some designs:

What you see here can be created by using an Autocomplete component so when the user starts typing something, a spinner will be visible so he will understand that there is some data fetching going on.
![image](https://user-images.githubusercontent.com/44569796/115212590-f8badd80-a100-11eb-9975-aa564a1218fe.png)

The difference is that, when you click on a result, the selected value will be visible in the input (the way it looks in a multi select components):
![image](https://user-images.githubusercontent.com/44569796/115212847-3cade280-a101-11eb-963c-4b12d7bdc918.png)

Due to these requirements, in order to achieve these UIs, we can work on adding something on the multiselect component (to let it show the spinner - the quickest solution) **OR** on the Autocomplete (by passing a list of values so it can show them as labels within the input).

Maybe the `Autocomplete` component can wrap a `Multiselect` so we call it by using `Autocomplete.Multiselect`.

Hope I explained myself better :)

**Comment by bryceosterhaus** [comment]
Makes sense to me that we should provide this. I think the best route would be to provide an async mechanism for `Multiselect`'s `sourceItems` prop. This way this component both handles hard-coded data and async data. If its async data, we would automatically handle the loading indicator for the user.

I can investigate it this week

**Comment by matuzalemsteles** [comment]
Hmm yeah, this can be interesting @bryceosterhaus instead of providing an `isLoading` API if `sourceItems` is async we can do this internally.

@FabioDiegoMastrorilli I think it doesn't make much sense to provide `Autocomplete.Multiselect` because `MultiSelect` fits more like a high-level component of Autocomplete more for another purpose, so we have a separate component despite using it underneath, usually, components in the same namespace are the low-levels.

**Comment by FabioDiegoMastrorilli** [comment]
Perfect! Thank you, guys :)
