### ISSUE TITLE
New Icons: order-list-up & order-list-down

### ISSUE THREAD

**Issue by hold-shift** [liferay/clay#4021]
Hi! due to [LEXI-1176](https://issues.liferay.com/browse/LEXI-1176) we have designed new icons to signal ordering states to be applied on the Management Toolbar to indicate the different states of the component.

![Icon-order-list-up](https://user-images.githubusercontent.com/61543739/115737844-cf15e680-a38c-11eb-9e97-de93653d2725.png)     

   ![Icon-order-list-down](https://user-images.githubusercontent.com/61543739/115737846-cfae7d00-a38c-11eb-9c1e-a54cb7deec72.png)
   
These new icons should be applied on the Management Toolbar instead of the current ordering arrows.

Please, follow the ticket for more info and don't hesitate to ping me in case you have any doubts.

Thanks!

**Comment by jbalsas** [comment]
![lovingit](https://user-images.githubusercontent.com/905006/115739750-151b7c00-a386-11eb-9cd5-6f7b9914e7b2.gif)
