### ISSUE TITLE
Add the new order-list icons to the Management Toolbar

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4023]
The introduction to `order-list-up` and `order-list-down` were introduced in the Lexicon request by issue #4021 which adds the new icons to the `@clayui/css` package but we still need to update the Management Toolbar.

The Management Toolbar component does not deal directly with these actions because it is implemented as a low-level, so teams can compose the Management Toolbar in different variations without having to configure an API, so we just updated our examples to use the new icons.

- Update the Management Toolbar documentation on [clayui.com](https://clayui.com/docs/components/management-toolbar.html)
- Update the Management Toolbar Storybook and [Templates](https://storybook.clayui.com/?path=/story/demos-templates--list-page)

**Comment by jbalsas** [comment]
> The Management Toolbar component does not deal directly with these actions because it is implemented as a low-level, so teams can compose the Management Toolbar in different variations without having to configure an API, so we just updated our examples to use the new icons.

Hey @matuzalemsteles, just wanted to note here that we (Infra) own our own implementation of High Level Management Toolbar that [uses the icon](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/FilterOrderControls.js#L77-L88) so I think it should be considered as part of this effort when the new clay version gets merged ;)

**Comment by matuzalemsteles** [comment]
@jbalsas Oh yeah, thanks Chema! I'll take care of that when the release comes out.

**Comment by dsanz** [comment]
In addition to the Management Toolbar, I found a couple of places wherewe should _consider_ updating this too:
* [<liferay-frontend:management-bar-sort>](https://github.com/liferay-frontend/liferay-portal/blob/ac20f44435beca679ba84170d0d91bad39821ea6/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/management_bar_sort/page.jsp#L43-L72) uses 2 buttons to switch order. Interaction here seems a bit different as buttons signal the action of setting an order, not the current ordering.
* [dataset management bar](https://github.com/liferay/liferay-portal/blob/40d130bfe5f2abbfd1f2dbbe4317959a86cc78f0/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/data_set_display/views/table/TableHeadCell.js#L93-L108) mimics the "original" management bar with two separated arrow icons to offer per column order options. This is a bit tricky as more than one column may offer sort buttons, meaning that there are cases where sort is not defined for a given column.

@jbalsas as both cases seem connected with these icons, but have their own specificities, we may want to see what to do. I'm leaning towards doing a quick check with design to consider the cases one by one before moving forward.

**Comment by jbalsas** [comment]
I think we can update them all, but yeah, wouldn't hurt pinging @drakonux and @hold-shift. They're usually hyper-responsive and I'm sure they can give us a straight answer right away ❤️
