### ISSUE TITLE
ClayProgressBar takes dynamic space for the progress value

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#4024]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?

* ClayProgressBar demo: https://codesandbox.io/s/clayprogressbar-demo-z6x24

![Screenshot 2021-04-26 at 16 15 56](https://user-images.githubusercontent.com/15845466/116097731-b23e2380-a6aa-11eb-9cfb-29bd1e031585.png)

## What are the steps to reproduce?

Use the default API to create a progress bar with the Clay component ClayProgressBar (out-of-the-box behavior).

## What is the expected result?

The bar takes more or less space depending on the number/s or image in the right side (see attached screenshot). This means that if we have a progress that continuously change (because it's updating the progress value), the user experience is that the component has a glitch.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.x  |
| React | 16.12.0 |

**Comment by matuzalemsteles** [comment]
Makes sense, @pat270 could you take a look at this?

**Comment by jbalsas** [comment]
@drakonux, @hold-shift could you provide guidance on UX expectations for the observed behaviour?

**Comment by drakonux** [comment]
Sure @jbalsas 

- The bar must remain fixed with the same size, thus the set (bar + text/icon) too. 
- The check-circle-icon and the text percentages have to be left-aligned.

![Frame 534](https://user-images.githubusercontent.com/21216422/116377283-4cb87700-a811-11eb-8380-981126f27189.png)

**Comment by pat270** [comment]
Sorry I missed this one. I'll send a fix today.
