### ISSUE TITLE
ClayPanel small version

### ISSUE THREAD

**Issue by dgarciasarai** [liferay/clay#4025]
## What is your proposal?

Create a way to use a small version of `ClayPanel` to use in limited spaces such as sidebars.

## Why would adopting this proposal be beneficial?

Avoid having CSS styles in several places to add a small version of a ClayPanel. In this moment, for example for sidebars, we have custom CSS using `.sidebar-sm.*`. Also, we have a CSS class to remove the padding for the component with `panel-group-flush`.

* ClayPanel demo: https://codesandbox.io/s/claypanel-demo-p8sne?file=/src/App.js

![Screenshot 2021-04-26 at 16 58 37](https://user-images.githubusercontent.com/15845466/116104355-abb2aa80-a6b0-11eb-95b4-fa4267627065.png)

I saw in several places in the portal that we have custom components doing the same as the ClayPanel and maybe we can migrate/update those to use the proper ones from Clay. Several are placed in side sidebars or info sidebars.

## What are the alternatives to this proposal?

As we have in the Pagination Bar component, I'd like to use the ClayPanel with a CSS class such as `panel-sm` or adding `small` in the attributes to make it small (font-size, spacing, icon size, etc).

The alternatives now is to use the ClayPanel as it is, add the `panel-group-flush` CSS class and use it but I don't know if the icon has the right size for sidebars or it's calculated in the theme.

Thanks!

**Comment by matuzalemsteles** [comment]
hey @dgarciasarai I think the idea of adding a new `small` API to the component of `<ClayPanel />` is totally valid but I am still a little confused, the `panel-group-flush panel-group-sm` is not covering the case of use for using a `small` variant for Panel? should still be smaller or not cover the use case in the sidebar?

**Comment by dgarciasarai** [comment]
Hey @matuzalemsteles, I'm using as you proposed:

```js
<ClayPanel
    className="panel-group-flush panel-group-sm"
    collapsable
    displayTitle={
        <ClayPanel.Title>
            <ClayLayout.ContentRow>
                <ClayLayout.ContentCol
                    className="align-self-center panel-title"
                    expand
                >
                    {title}
                </ClayLayout.ContentCol>
                <ClayLayout.ContentCol>
                    <ClayBadge
                        displayType={
                            total === 0 ? 'success' : 'info'
                        }
                        label={displayValue}
                    />
                </ClayLayout.ContentCol>
            </ClayLayout.ContentRow>
        </ClayPanel.Title>
    }
    displayType="unstyled"
    key={key}
    showCollapseIcon={true}
>
    ...
</ClayPanel>
```

And seems very likely we need. The only thing that is **not** working fine is the `font-size`. I saw in the CSS file:

```css
// Panel Group Sm

$panel-group-sm: () !default;
$panel-group-sm: map-deep-merge(
	(
		title-font-size: 0.75rem,
	),
	$panel-group-sm
);
```

I don't know if I'm looking in the right place but the font size should be `0.75rem` (12px) and I have `0.875rem` (14px). Maybe it's not applying well the `panel-group-sm` CSS class? 🤔 

Mentioning the CSS experts @marcoscv-work @edalgrin 🍀 

Thanks for the help!

**Comment by marcoscv-work** [comment]
The generated markup looks like is not following the correct div/class order, the correct class order is:

1º `.panel-group-sm`
2º `.panel`
3º `.panel-title`

**Comment by dgarciasarai** [comment]
Yes @marcoscv-work! I was missing the `<ClayPanel.Group>` wrapping the panel 😄  Thanks!

**Comment by matuzalemsteles** [comment]
Oh I see. Well, I'm going to reopen this just to create the new `small` API for ClayPanel.

**Comment by dgarciasarai** [comment]
Ok, make sense. If you want to use a ClayPanel small, without grouping, this approach won't work. Thanks for that new `small` API 😄
