### ISSUE TITLE
Unexpected scrollbar when opening modal

### ISSUE THREAD

**Issue by orsolyaDekany** [liferay/clay#4034]
## What are the steps to reproduce?
1. Start Liferay Portal
2. Go to categorization --> categories 
3. Create a vocabulary
4. Create a web content and go to categorization
5. Open the created vocabulary
6. Move your cursor to the top or bottom and see a scrollbar shows up:

![2](https://user-images.githubusercontent.com/69793575/116406283-c7dd5580-a830-11eb-9809-35088c0274c1.gif)

If categories are added to the vocabularies (7-8 at least), the scrollbar seems to be duplicated:

![scrollbar](https://user-images.githubusercontent.com/69793575/116405301-c8c1b780-a82f-11eb-9368-fdf0eded2716.gif)

## What is the expected result?
No unexpected scrollbar

## Environment
@clayui/modal": "3.8.5

## Description:
Reproducable: Master, 7.3.x
Not reproducable: 7.2.x

7.2.x - "@clayui/modal": "3.2.0"
Master - "@clayui/modal": "3.8.5"

The issue is caused in Liferay themes and it caused by **overflow-y property is set to auto** value in Modal component.
https://github.com/liferay/clay/blob/%40clayui/modal%403.8.5/packages/clay-css/src/scss/components/_modals.scss#L6

```
.modal-open {
	overflow: hidden;

	.modal {
		overflow-x: hidden;
		overflow-y: auto;
	}
}
```
This was implemented in modal "3.6.0" for the first time with this [commit](https://github.com/liferay/clay/commit/c2a4de8e26d44215d2e3f45e3849a5571c38b686): "Absorb Bootstrap's _modal.scss into Clay CSS _modals.scss"

I was looking for the history why this change was added to Modal, but could not find anything that could explain the implementation of it.

I will send a PR, can you please review it?

**Comment by matuzalemsteles** [comment]
Hey @pat270 do you remember the reason for that? or maybe it’s a collision side effect with other properties in DXP that can cause it?

**Comment by pat270** [comment]
These styles were always in Clay via Bootstrap (https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/bootstrap/_modal.scss#L7-L15). We just moved those styles into Clay CSS and stopped using Bootstrap's source.

**Comment by orsolyaDekany** [comment]
Thanks for your answer.
Looks like this PR solves the issue: https://github.com/liferay/liferay-portal-ee/pull/23639/files

I close this issue.
