### ISSUE TITLE
No visualization tooltip

### ISSUE THREAD

**Issue by john-co** [liferay/clay#4048]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
No

## What are the steps to reproduce?
1. Hover over display view button in portal

Current State
No tooltip

## What is the expected result?
Tooltip: Open the view options menu
![visualization_tooltip](https://user-images.githubusercontent.com/35235266/117372147-ed481000-ae7d-11eb-97fa-de2e40b4245c.png)

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.27.x  |
| React |         |

**Comment by matuzalemsteles** [comment]
Hey @john-co Clay only provides the low-level components of the Management Toolbar, so the logic responsible for assembling the Management Toolbar is on the DXP side, you can take care of moving this issue to Jira and we can prioritize the changes there.

**Comment by julien** [comment]
Hey guys, 
Just a thought: maybe we could(/should) document how Clay is being used in DXP, not sure it belong here but I think it would definitely help clear some doubts.

**Comment by julien** [comment]
:facepalm: I actually forgot [that](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/clay-css-3-intro.md) and especially [this](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/frontend_taglib_clay.md). 

To be more precise, maybe what we could do is specify which (Clay) components are being "wrapped" in DXP in the `frontend-taglib-clay` module, and "why", just to help others figure out where to ask when it comes to bugs, new features, etc... Does that make more sense :smile: ?

**Comment by brunofernandezg** [comment]
Any documentation would be ver useful :)

**Comment by matuzalemsteles** [comment]
Hey @julien I think it makes sense, we just have to keep it updated so that it doesn't get depreciated quickly.

**Comment by julien** [comment]
@matuzalemsteles sure, that's the idea. 
I also think that it will give us a broader view of which components are used and how they are being used in DXP.
