### ISSUE TITLE
management toolbar -  bold for search keywords

### ISSUE THREAD

**Issue by john-co** [liferay/clay#4050]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

Current State
![no_bold](https://user-images.githubusercontent.com/35235266/117373978-2766e100-ae81-11eb-95a9-7d1753587887.png)

Expected State
![bold_results](https://user-images.githubusercontent.com/35235266/117373976-26ce4a80-ae81-11eb-88a4-62f93f66a864.png)
X results for <strong>"#keywords"</strong>

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by ambrinchaudhary** [comment]
I think this issue should be moved to liferay-portal, as thee logic is there https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ResultsBar.js#L34-L34

**Comment by john-co** [comment]
Thanks @ambrinchaudhary, created https://issues.liferay.com/browse/LPS-131892
