### ISSUE TITLE
Management Toolbar - After numbers of search results bar are capitalized

### ISSUE THREAD

**Issue by john-co** [liferay/clay#4051]
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Current State
14 of 42 Selected
42 Results for my search

Expected State
14 of 42 selected
42 results for "my search"

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by ambrinchaudhary** [comment]
I think this issue should be moved to liferay-portal, as the logic is there: https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/SelectionControls.js#L176-L176 and https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ResultsBar.js#L34-L34

**Comment by john-co** [comment]
Thanks @ambrinchaudhary , created https://issues.liferay.com/browse/LPS-131893
