### ISSUE TITLE
Icon: Chatbot 

### ISSUE THREAD

**Issue by ghost** [liferay/clay#4057]
Hi! Due to [LEXI-1186](https://issues.liferay.com/browse/LEXI-1186), we need to add the chatbot icon to the library. 

![Icon-chatbot-test-01](https://user-images.githubusercontent.com/61543739/117832470-ce7abc80-b275-11eb-9ccf-ca105bccb23c.jpg)

Please, find the SVG icon following the ticket. 

Thanks!

**Comment by hold-shift** [comment]
Great! it makes perfect sense since it is a recurring action. I'll use it the next time. Thank you!
