### ISSUE TITLE
Dropdown.Section is not documented on ClayDropDown API docs

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#4095]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?

Go to https://clayui.com/docs/components/drop-down/api.html#dropdown and search for ClayDropdown.Section API

**Comment by julien** [comment]
@diegonvs I checked that and you're right it's missing
However, when I add 

```mdx
## DropDown.Section

<div>[APITable "clay-drop-down/src/Section.tsx"]</div>
``` 
to the [api-dropdown.mdx](https://github.com/liferay/clay/blob/d639da89b4ac9eddb66a0b5270da046c4da6565d/packages/clay-drop-down/docs/api-dropdown.mdx) file, nothing happens. I'm not sure why, so I'll see if I can do anything about it.

**Comment by diegonvs** [comment]
Hey @julien, This error comes from https://github.com/reactjs/react-docgen/pull/352 I guess. Taking a look deeply I saw they already merged a solution in the end of last year(here: https://github.com/reactjs/react-docgen/pull/464). Would be interesting to bump the version of `react-docgen` here and see if it solves :p

**Comment by julien** [comment]
> This error ...

The funny thing is that there is no error, but sure, I'll update that package and see what happens

**Comment by diegonvs** [comment]
> I'll update that package and see what happens

![](https://media0.giphy.com/media/3o7btVfCuDKHlF5flC/giphy.gif)

**Comment by julien** [comment]
@diegonvs I'm still seeing this

![2021-05-31-17:34:08](https://user-images.githubusercontent.com/5572/120215820-7b71a500-c236-11eb-9156-74cbb92de195.png)

And what's a bit more "scary" is this 

![2021-05-31-17:36:17](https://user-images.githubusercontent.com/5572/120215992-bb388c80-c236-11eb-869b-c4d16af67069.png)



that's the only thing happening for me after updating to `react-docgen: 5.4.0`
