### ISSUE TITLE
Cascading Menu

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#4097]
![dropdown-multi-level](https://user-images.githubusercontent.com/21216422/119687693-b1ceaf00-be47-11eb-9f81-799f394de55b.gif)
_credits @hold-shift_

## What is your proposal?
Due to [LEXI-1196](https://issues.liferay.com/browse/LEXI-1196) we propose to develop a Cascading Menu, an evolution/addon of the Dropdown Menu. Please review the proposal: [Figma file](https://www.figma.com/file/uTmPPMQ8UfWQyKIepyZ3p9/lexi-1196-cascading-menu?node-id=0%3A1), [definition doc](https://docs.google.com/document/d/1gnFu8Fwb_JEl1Lat_THfzXN9vkCJ7Q4f6zM82ioj1Wo/edit?usp=sharing). 

## Why would adopting this proposal be beneficial?
This would help product designers to use the proper Dropdown Menu depending on the scenario. For example, a Cascading Menu is designed for contextual menus with many actions (recommended for just 1 level) and a Drill Down Menu for deep hierarchies (2+ levels or navigation).

## What are the alternatives to this proposal?
Currently, product designers are using a Drill Down Menu which is a multilevel solution too but it doesn't work well because a Cascading Menu is the most known pattern for a nested level. 

## Deadline
The echo-team requested to have this for **DXP 7.4 GA2** (see LEXI ticket)

**Comment by pat270** [comment]
@matuzalemsteles @julien I think we can achieve this without additional CSS since the dropdown-menus are in React Portals. Let me know if this isn't the case, I can look into it.

**Comment by matuzalemsteles** [comment]
hey @drakonux, should we allow it to have more than one level? I know it is recommended only for one level just thinking about whether we can add this limit to the implementation level as well. Why are we likely to have less work to implement

**Comment by drakonux** [comment]
In this case, **It makes no sense to allow more than 1 submenu**. We want to avoid a tunnel interaction as much as possible, and with just one level, we have more or less control. 

So just one level is a good idea, and if it also helps, the development is a win-win.

**Comment by matuzalemsteles** [comment]
Thanks @drakonux, well, I imagine that this probably has to go before the release officially scheduled for the 2nd, I think we may have to cut a release earlier, probably Friday so that the teams can use it and not stay on top of GA2. I'm going to work on it.

**Comment by julien** [comment]
Hey @drakonux, if the deadline is for DXP 7.4 GA2, I think sending now is a bit "late".

That said I also agree with @pat270 that we don't need additional CSS and that it might be possible to create this component based on our existing dropdown components. So we might be in time, I'm just not 100% sure.

**Comment by drakonux** [comment]
I mean from our side there is no pressure to release the cascading menu at the time requested. I think team-echo just wanted to use it for 7.4 GA2 but I think as you said it's too late. 

From our side, we just wanted to see it implemented in the short term (before 7.5 would be great xD). Because not having this component will induce product designers to use the other multilevel solution we already have (the drill-down menu). And as I commented, we would like to preserve the usage of the drill-down just for deep hierarchies
