### ISSUE TITLE
[DropdownWithDrilldown] The order of the menus affects the behavior of the component

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#4110]
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
I have two menus: mainMenu and addItemsMenu (this is the child menu). If the child menu is placed first in the object received in the props menus (as shown in the code), the following behavior occurs:
```
<ClayDropDownWithDrilldown
   initialActiveMenu="mainMenu"
   menus={{
	addItemsMenu,
	mainMenu,
   }}
   trigger={
   ...
>
```

https://user-images.githubusercontent.com/9701095/120442820-51c79380-c386-11eb-8188-3c50c80f5345.mov

## What is the expected result?
https://user-images.githubusercontent.com/9701095/120442853-5b50fb80-c386-11eb-9d85-8ee94def0178.mov

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.x |

**Comment by julien** [comment]
@veroglez thanks for reporting this.

Are you passing the menus like this because of an eslint rule expects objects keys to be sorted alphabetically? 
While we work on a solution to fix this, I'd suggest disabling the linter for those line and passing them in the order you want them to appear.

Just so you know, nothing is controlled on the component's side, so what you pass gets rendered in the order you pass it, taking into account that these "menus" are using a flex layout and that we are using CSS transitions for the animation.

**Comment by veroglez** [comment]
Thanks for the reply @julien, I'm waiting for an easy solution to be found.

**Comment by julien** [comment]
No worries, as for the easy solution, it's as simple as 

Pass the items in the order you want them to rendered, taking into account the transition.

So if the first menu item is a child of the second menu item, then you need to change that.

I've also had a quick chat with @matuzalemsteles about this via Slack, and we both think that adding logic to filter the items (like sorting the `menus` array to make sure menus with "children" are always rendered before their "child" menu) is adding unnecessary complexity to the component, but we might come up with something, in the meantime, the easy solution should fix your problem.

**Comment by julien** [comment]
I also talked with @drakonux about this issue, one important point that came up during our conversation is that in the case of having only one level of interaction (which is the case here), Lexicon recommends using the cascading variant of the dropdown component rather than the drilldown variant.

**Comment by matuzalemsteles** [comment]
Hey @julien maybe what we can do here is make it explicit in our documentation that menu order should be important here.
