### ISSUE TITLE
Add CSS to TreeView Component

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4111]
The Lexicon team has developed a new component to handle TreeView that covers many use cases as well as deprecating Vertical Navigation and using TreeView instead. We must implement it on Clay's side, initially, the epic is under analysis but we can start the CSS development and later investigate how we will create the component and solve some problems that led to its creation.

- [Epic](https://issues.liferay.com/browse/LPS-133328)
- [Spec](https://docs.google.com/document/d/1fggZBRGAIkGPbnkRrGEUOT0hHpkF-YjFmREee0XCoI0/edit)

**Comment by matuzalemsteles** [comment]
Hey @pat270 Yes, I think the idea is that with TreeView I can build a Vertical Navigation since the item can add anything inside and compose.

> I'll create a completely separate component for it and it will most likely live in Cadmin. I don't see a reason to include it in Clay CSS.

Are you saying a new component for Vertical Navigation based on Tree View?

**Comment by matuzalemsteles** [comment]
Hmm, I think I get it, so let's create a new component for the Tree View, right?

**Comment by pat270** [comment]
Yes, new one.
