### ISSUE TITLE
Taglib for ClayPaginationBar component

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#4143]
## What is your proposal?
Due to [LPS-131189](https://issues.liferay.com/browse/LPS-131189) we propose to develop a taglib for the ClayPaginationBar component.

## What are the alternatives to this proposal?
Currently, the only existing pagination taglib is `<liferay-ui:page-iterator>`, but for us it is not the right solution and it is not according to the proposed design [here](https://issues.liferay.com/browse/LPS-123825).

**Comment by brunofernandezg** [comment]
After talking to @matuzalemsteles this should be a change in Portal and not in Clay. We will close this issue as discarded and track the request in the following LPS:
https://issues.liferay.com/browse/LPS-134549
