### ISSUE TITLE
Components shouldn't have spritemap as a required prop

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/clay#4153]
When using `ClayIconSpriteContext` we no longer need to pass `spritemap` to individual components that are children to the `ClayIconSpriteContext`. This isn't reflected in the way our API is built for some of our components.

Some components, like `CardWithInfo`  and `CardWithHorizontal` have the `spritemap` prop set as required, which should be not required.

Whoever tackles this issue needs to go through the documentation on [the website](https://clayui.com/) and change the `required` state of the `spritemap` prop from `true` to `false`.

**Comment by bryceosterhaus** [comment]
Fix for this should already be merged and available in the next release. https://github.com/liferay/clay/issues/4139
