### ISSUE TITLE
Offer alignmentPosition for Dropdown within Pagination, PaginationBar

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#4165]
## What is your proposal?
To specify which direction the dropdown will open in relation to the pagination bar with an `alignmentPosition` property.
To work with:
- ClayPaginationWithBasicItems
- ClayPaginationBarWithBasicItems

## Why would adopting this proposal be beneficial?
The search team is using ClayPaginationWithBasicItems on the bottom of a search results list inside a fixed sidebar. When the main page allows more scrolling down, the pagination dropdown would actually open downward and not be visible, so we think it would be helpful to just be able to define the dropdown to always be above.

## What are the alternatives to this proposal?
Not sure if there is an alternative to this, I suppose it would just require customizing one's own pagination bar.

Thank you!

cc: @thektan

**Comment by matuzalemsteles** [comment]
Hey @oliv-yu sorry for delay, yes, I think that would be a viable option for that and it is a good proposal to add the API to these components. The weird thing is that DropDown should automatically reposition when it's out of space, I'll check that out.

**Comment by oliv-yu** [comment]
Thank you @matuzalemsteles!! Looking forward to the add 😺. Not sure if it helps, but here's a CodeSandbox for the scenario I was mentioning https://codesandbox.io/s/eloquent-darkness-g8lms. The Dropdown does reposition! It's just that when the Panel in the main page opens, the Dropdown perceives that it has more space.

**Comment by matuzalemsteles** [comment]
Oh I see, Perfect CodeSandbox helps a lot, now I understand the problem. It looks a lot like a `dom-align` alignment system error.
