### ISSUE TITLE
@clayui/color-picker label has 4px space

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4173]
The `label` element text is slightly misaligned in Clay Color Picker due to a hidden input that is 4px by 4px. We should add `position: absolute;` to the hidden input so the input doesn't take that space.

![color-picker-space](https://user-images.githubusercontent.com/788266/126423299-87cf866e-3e84-49ac-83d9-89644272c7a8.jpg)

Credit to https://github.com/lfrsales/73-formed-theme/blob/master/src/css/formed/widgets/forms.scss#L104-L106. I was trying to figure out the reason for that style.

**Comment by matuzalemsteles** [comment]
Hey @pat270 in that case wouldn't it be better to just put a `display: none;` instead of `position: absolute` in that case? could it cause any side effects?

**Comment by pat270** [comment]
No idea, I assumed it did since we are inlining `visibility: hidden`. Maybe it would be better to use `<input type="hidden" />` and remove those inline styles.

**Comment by matuzalemsteles** [comment]
It makes sense, I think this is better
