### ISSUE TITLE
alignElementRef prop in Clay Tooltip

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#4197]
Good morning Clay Team! 

I've found myself in a very rare scenario where I would like to use a React clay tooltip positioned at the bottom of an HTML element which is not currently managed in react. 

A bit more of context: 
I've react wrapper that contains an svg entirely managed by D3 via a class Instance and some react components whose state change based on some user interactions with the svg.

A working example is this dropdown menu:
![image](https://user-images.githubusercontent.com/44569796/127636790-4d3a394e-cd52-4460-972b-ca962df9e714.png)

It works well thanks to its `alignElementRef`. I update that prop every time a user clicks on the menu icon altogether with the `active` prop in order to force its repositioning.

My goal now is showing a tooltip every time there's a mouseover on the node description when there's more than one role but there's no room to show the entire list:
![image](https://user-images.githubusercontent.com/44569796/127638497-c8efa985-d395-47dd-8b0f-57fefa28ed7e.png)
 
The quickest and cleanest way I though is reusing the dropdown menu approach but I need the same `alignElementRef` prop.

Is it possible to implement it? 
(or/and) 
Do you have any suggestion about how to deal with what we currently have?

Thank you <3

**Comment by matuzalemsteles** [comment]
Hey @FabioDiegoMastrorilli this is quite interesting, well to do the same for `Tooltip` we would have to change some things like add the `dom-align` to do the repositioning of the element, currently, it is not controlled so we let the developer handle it manually but in that case, the `TooltipProvider` couldn't solve the problem? it looks at all elements that contain `title` in the React component tree, as this case is a d3 component it might not work but we have the `TooltipProvider` in the DXP that looks for any element in the DOM that contains `title` and with the scope of `lfr-tooltip-scope`, by default the taglib `react:component` already adds this scope.

**Comment by julien** [comment]
Thanks for the update @FabioDiegoMastrorilli. Don't hesitate to close issues you open next time if you know they're no "valid".
