### ISSUE TITLE
Dropdown menu with lists markup is not looking correctly

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#425]
Dropdown menu markup should be compatible with lists markup to improve semantics. We are currently using <ul> lists in dropdown-menu, we tried to use "list-unstyled" to reset the ul native styles but it does not look like the best option.

Examples in components:
clay-dropdown/demos/
clay-card/demos/

![image](https://user-images.githubusercontent.com/7963804/35050077-3eef5ec8-fba2-11e7-9422-1fc4ce2f81b3.png)

![image](https://user-images.githubusercontent.com/7963804/35050139-6c1716de-fba2-11e7-956f-de3e38bbedb3.png)

**Comment by pat270** [comment]
Pattern for `dropdown-menu` with `ul`, `li`:
```
<ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Edit</a></li>
    <li class="dropdown-divider></li>
    <li><a class="dropdown-item" href="#">Save</a></li>
</ul>
```

**Comment by carloslancha** [comment]
Hey @pat270 

Could you please give us the complete markup in both cases (ul - li and divs), with search form, alert, etc...? Just to be sure we're not messing it up ;)

Thx!!

**Comment by carloslancha** [comment]
Label this as `next release`
