### ISSUE TITLE
Request to include a clay Dropdown select component.

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4271]
Liferay's data engine / forms includes a custom implementation of dropdown select that is roughly based on the Clay dropdown component. I propose that Clay considers owning a dropdown select component that meets the requirements of the data engine team in order to standardize the html and styling of the component throughout Liferay and anywhere Clay may be used. 

Key features should be researched but must include:
- Placeholder
- Non-Shadow-Dom stylable Dropdown List.

**Comment by julien** [comment]
Hey @ethib137, 

Could you please add more details about this new component?
For example, where it is located and what it looks like. 
We usually create new components based on specifications written by Lexicon, so in this case we'd need to know exactly how the component should look and behave. I think that the best thing to do would be to communicate with Lexicon about this new component.

Thanks

**Comment by ethib137** [comment]
Hey @julien, 

This is the dropdown select that is rendered any time you create a form using data-engine/ddm. This would include Liferay Forms, Web Content Structures, Documents & Media Document Types, and any other place ddm is used.

![Screen Shot 2021-09-16 at 4 32 02 PM](https://user-images.githubusercontent.com/1609196/133613558-ea754428-d45d-41b0-ad2d-afd669a05c89.png)

I figured since this is used throughout Liferay that there was likely already Lexicon Guidelines for it. If not, I'll move this request to Lexicon first.

Thanks.

**Comment by julien** [comment]
Hey @evan thanks for the additional information, I'll have a look at those.

We've got `Select` and `SelectWithOptions` in the @clayui/form package which mostly does what you need, and I guess that's what is defined in by Lexicon. 

I just have a few doubts, because the `<select>` element doesn't have a `placeholder` attribute it doesn't support it - there are various ways to get around this but they're mostly "hacks", so that is something to be aware of. Concerning the "Non-Shadow-Dom stylable Dropdown List." I still need to understand that part, but I think it's the behavior that our `SelectWithOption` has. I know I'm repeating myself, but my advice would be to talk to Lexicon first.

**Comment by ethib137** [comment]
Hey @julien,

What currently exists in DDM is not using the default `<select>` element. They are using some hacks, but my hope with bringing this to clay was that those "hacks" could be standardized by Clay. It's better that we have one way that we "hack" selects than many ways.

My point about "Non-Shadow-Dom stylable Dropdown List", was just to indicate that we couldn't just use the default `<select>` element, since it's options are rendered as shadow dom which limits how they can be styled.

Let me know if there is anything else I need to clarify.

**Comment by julien** [comment]
Hey @ethib137 , thanks it's all clear. 

Now that I understand everything, I think we could  try to use our exiting `SelectWithOptions` component and get a descent result, have a look [here](https://storybook.clayui.com/?path=/story/components-clayselect--with-low-level-apis-composition) when you can and tell me what you think. One thing that might be needed is a new `placeholder` prop, but I don't think that would mean lots of changes.

**Comment by ethib137** [comment]
Hey @julien, 

The `SelectWithOptions` component is still using the default `<select>` shadow-dom for the dropdown options. Are you saying that we would still use the shadow-dom, or are you suggesting that the component would be updated to use new html elements for rendering the dropdown select options? 

I'd be very happy to be proved wrong, but I don't think the shadow dom will provide the styling flexibility needed to match what is currently being used by DDM in portal.

**Comment by julien** [comment]
You're right @ethib137 it still does. 

Well if we really need something different (I haven't seen any visuals of what we need), then we might need a 
new component (we aren't going to change the markup of the existing ones) so I think that before doing anything on Clay's side this is something that must be discussed with Lexicon.

**Comment by matuzalemsteles** [comment]
Hey guys, I think this would have to be passed on to the Lexicon team as a proposal, Lexicon recommend using Native Select so we don't have an implementation for that, it would also be necessary to check the cases of other products other than necessarily use DDM behind the scenes.

This DDM case is very old so I wouldn't take into consideration if it's the best option to adopt as a standard instead Lexicon can base it on and check the behaviors, expected look, and accessibility cases for example.

**Comment by pat270** [comment]
This case mostly resembles ClayDropDown. In the first example on [ClayDropdown](https://clayui.com/docs/components/drop-down.html/#composing):

```
const Component = () => {
    const [active, setActive] = useState(false);

    return (
        <div className="form-group">
            <ClayDropDown
                trigger={
                    <label className="form-control-label">
                        <span className="form-control-label-text">Select an Option</span>
                        <input className="form-control-select form-control" placeholder="Choose an Option..." readonly type="text" value="" />
                    </label>
                }
                active={active}
                onActiveChange={setActive}
                menuElementAttrs={{
                    className: 'my-custom-dropdown-menu',
                    containerProps: {
                        className: 'dropdown-menu-react-portal-div',
                        id: 'dropdownMenuReactPortalDiv',
                    },
                }}
            >
                <ClayDropDown.ItemList>
                    <ClayDropDown.Group>
                        {[
                            {href: '#disabled', label: 'Choose an Option...'},
                            {href: '#A', label: 'A'},
                            {href: '#B', label: 'B'},
                        ].map((item, i) => (
                            <ClayDropDown.Item href={item.href} key={i}>
                                {item.label}
                            </ClayDropDown.Item>
                        ))}
                    </ClayDropDown.Group>
                </ClayDropDown.ItemList>
            </ClayDropDown>
        </div>
    );
}

render(<Component />)
```

We can get pretty close. We just need to implement changing the `value` on the `readonly` input when you select an item from the `dropdown-menu`. There are some minor bugs, hitting enter on the readonly input doesn't open dropdown menu. Seems easy enough to work around. I like this, select elements are notoriously hard to style.

**Comment by ethib137** [comment]
Thanks for the input everyone... I'll go ahead and create a Lexicon ticket for this and share it here. 

From my perspective there are two equally good outcomes from this. One is that we end up with a Clay custom Select input that can be used by DDM. The second option is that DDM would be refactored to use the existing native Clay select input. I just don't think it's helpful to have a custom select implementation that isn't standardized by Clay.

**Comment by ethib137** [comment]
https://issues.liferay.com/browse/LEXI-1231

**Comment by matuzalemsteles** [comment]
@ethib137 I agree, thanks for the contribution!
