### ISSUE TITLE
ClayCard labels seem very close to each other (missing horizontal space)

### ISSUE THREAD

**Issue by julien** [liferay/clay#429]
From this screenshot, it seems that when there are several labels in the `ClayCard` component; they are very close one to each other.

![ClayCard](https://user-images.githubusercontent.com/5572/35149461-727a7af0-fd16-11e7-8770-89af918f1447.png)
 
We should review this

**Comment by pat270** [comment]
The spacing between labels and badges or any inline component depends upon whether or not white space is added between components. Soy strips white space by default, but I'm sure there will be cases in portal where we don't use this plugin that will have white space between labels. I think we should add white space between the labels and some margin to achieve the 8px spacing between labels.

**Comment by yuchi** [comment]
You can explictly add spaces in Soy by using the [`{sp}` special character](https://developers.google.com/closure/templates/docs/commands#specialcharacters).

Personally I believe the card part should either use inline-blocks or floated elements, but not a mix of the two.

**Comment by julien** [comment]
Hey @yuchi, thanks for the heads up. I know about `{sp}` special character, but just wanted to know if this was the expected result.

**Comment by carloslancha** [comment]
I'm on it 👍
