### ISSUE TITLE
[Alert] Inline Actions

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#4294]
## Proposal

![One line](https://user-images.githubusercontent.com/21216422/134490126-eed2285a-db13-4595-b106-c863a5942ae5.png)
Please read:

- [LEXI-1232](https://issues.liferay.com/browse/LEXI-1232)
- [Inline actions for Alerts ](https://liferay.atlassian.net/l/c/5WgL2bmr)

## Why would adopting this proposal be beneficial?
Most of the alerts used in DXP have two or more lines, mainly because the max-width set constrains them. Providing this option will allow product teams to have wider alerts with actions.

Besides, the Dialect team requested this for their use cases. 

## What are the alternatives to this proposal?
We recommend to not use inline actions when there are more than two lines, in that case to use block actions is a better choice. 

**Responsive Behavior**
Could we change an alert with inline actions to block actions when the screen space is narrowed?

**Comment by pat270** [comment]
@drakonux It sounds like there are two types of alerts we need to modify?

https://clayui.com/docs/components/alert.html#using-with-claybutton
We just need to remove `<ClayAlert.Footer>` from that example and get the spacing correct.

https://clayui.com/docs/components/alert.html#using-with-toastcontainer
If we are able to remove/customize the class `alert-notifications` from  https://github.com/liferay/clay/blob/e91895f788381be22112ad3e98a755a7992ff448/packages/clay-alert/src/ToastContainer.tsx#L30 
Toast Alerts will grow based on the content inside. It will max out at the edge of the browser window and break to new line if the content is too long. 

I think we already have the components to do what they want. We just need to mix, match, and add a little CSS to work out all the details. The contents of https://clayui.com/docs/components/alert/markup.html#css-alert-lists looks like what is outlined in the confluence doc.

**Comment by drakonux** [comment]
Yes, we would like to provide two options for alerts. 

The idea is to allow product teams to set a maximum width of the alerts depending on their context. So, DXP should set a maximum for Alerts if they want to keep them in control. 

About my comment about the responsive behavior @pat270 if it's feasible to have that?

**Comment by pat270** [comment]
@drakonux yes we can do everything you want.

**Comment by drakonux** [comment]
I want it all!

![](https://media2.giphy.com/media/1YaUX9Zy2q3XbzDd2b/giphy.gif)

Talking seriously, the point is. That responsive behavior is something we should deliver with the component, or should we let product teams manage it?

**Comment by pat270** [comment]
@drakonux I think we can deliver responsive behavior reasonably. If they are picky about it, the product team can manage it.
