### ISSUE TITLE
Should ClayCard be renamed?

### ISSUE THREAD

**Issue by julien** [liferay/clay#430]
In the [`clay-card`](https://github.com/liferay/clay/tree/master/packages/clay-card) package,  should the [`ClayCard`](https://github.com/liferay/clay/blob/master/packages/clay-card/src/ClayCard.js) component be renamed  to `ClayBaseCard` or `ClayCardBase` ?

This is more a question than an issue, but @carloslancha and I were wondering what the rest of the team thought about it.

**Comment by julien** [comment]
@carloslancha thanks for the feedback. I can take care of it if you want.

**Comment by carloslancha** [comment]
Nice @julien !

**Comment by carloslancha** [comment]
Resolved by https://github.com/liferay/clay/pull/443
