### ISSUE TITLE
Slider initial state doesn't look consistent with provided value.

### ISSUE THREAD

**Issue by FabioDiegoMastrorilli** [liferay/clay#4311]
Hi guys, I'm having some problems with the slider.

I'm creating a Slider instance within a clay dropdown:
```
<ClaySlider
	max={100}
	min={10}
	onValueChange={updatePinsRadius}
	showTooltip={false}
	step={10}
	value={pinsRadius}
/>
```
The initial value in `pinsRadius` is `20` so the slider hand shouldn't start from the beginning but what I see is:

![image](https://user-images.githubusercontent.com/44569796/135083990-764b6bc8-9c42-43a9-883c-1892ef5938eb.png)

The internal state where we should find some number shows: NaN. 
This is a screenshot from my debugger.
![image](https://user-images.githubusercontent.com/44569796/135084281-c32fd83f-e52d-4785-8cce-6a08fa869c37.png)

Thanks a lot! :)
Fabio

**Comment by matuzalemsteles** [comment]
Hey @FabioDiegoMastrorilli thanks for reporting it, I've tested this case but I can't reproduce it, see my example in codesandbox https://codesandbox.io/s/quick-start-clay-finale-forked-h09ui?file=/src/index.js.

I can only reproduce the case where the progress bar doesn't show but I think this is related to the case DropDown starts rendering but hidden in the DOM and the slider needs to be visible to do the bar calculations, we have to investigate a solution to that.

**Comment by john-co** [comment]
Closing issue since inactive for more than 6 months. Please reopen if still an issue and can provide further steps to reproduce.
