### ISSUE TITLE
Allow configuring the reordering of any side in DualListBox component

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4312]
Currently the component implemented in React of DualListBox does not allow configuring the reordering, this is enabled by default only for the left side but some time ago the configuration was requested to modify the sides, for more context see #3985.

The purpose of this "issue" is to allow you to choose which side will have the reordering so it allows the team to choose depends on the context.

**Comment by carloslancha** [comment]
As @drakonux said [here](https://liferay.slack.com/archives/CNBG06JS3/p1632842772027200?thread_ts=1632840681.023200&cid=CNBG06JS3) there's no use cases to make this reversible, we just need to switch current SelectBoxes

**Comment by matuzalemsteles** [comment]
@carloslancha just changing the reordering to the right side would be a breaking change because we would be changing the behavior now and whoever is using it will breaking change their behavior, I just see a use case in DXP using `ClayDualListBox`, if we want to adopt the right side as default we would have to keep left as default for reordering for now and add a property to change and in v4 make it default.

**Comment by carloslancha** [comment]
In this case I don't see it as a breaking change but a fix, since, as Lexicon asked, this component should work in the other way, not to provide an API to choose the side, so there's no need of a new API with defaults.

cc @julien

**Comment by matuzalemsteles** [comment]
> Also, if there's only one use case, we can talk with them to inform them about this change.

Yeah, if that's the case with DXP I don't see a problem but Clay is open so I don't know if we should just trust that.

> In this case I don't see it as a breaking change but a fix, since, as Lexicon asked, this component should work in the other way, not to provide an API to choose the side, so there's no need of a new API with defaults.

Hmm, I think this is not a fix because this was an improvement request to change behavior, DualListBox was developed like this in its first interaction, it would be a fix if when this component was designed by Lexicon and the default position was the right side instead of the left side which is not true, this component was written 2 years and older than that too and a few months as the issue reported by @drakonux was asked the possibility to add the team "choice" but as we talked yesterday just stay the `right` position.

I think even if it was a "fix", we can't just change a behavior in the same version, people are expecting that behavior, and changing it suddenly becomes a breaking change.

**Comment by nhpatt** [comment]
> people are expecting that behavior, and changing it suddenly becomes a breaking change.

TBH people is the DXP usage :) :(

**Comment by matuzalemsteles** [comment]
Yeah, I'm also considering other users since Clay is public and there is a certain incentive to be used. For example, it's safe to tell the Liferay Cloud team to update Clay's components from version 3.0.0 to the latest version.

Also, this can happen to backport to old versions, if we don't follow the versioning, we will break with the semver policy, so if the developer updates Clay 3.36.0 to 3.36.1, he will see a break, because he is seeing behavior that was not expected in the past version and stopped being in the next version.

Fixes in future versions some fix that needs to go to an old version of Liferay, we couldn't do that without first updating these behaviors in the old version. I don't consider it safe to do in this case, because it's not considered a fix but a behavior change that should follow for a future major version, just like we do with any changes to our other components.

**Comment by nhpatt** [comment]
You are right... but it depends too. If we consider it a fix, as the normal behaviour outside of liferay is usually the other way around... we could change it as a fix.

Clay is public but is a library to serve Lexicon/DXP needs, that is our main user in terms of size and importance too. We can not weight other user with the same scale as DXP. I don't consider Liferay Cloud a good example because they should try to follow Lexicon needs too.

I'm not against allowing to configure the DualListBox, as it's not a big change. But I do not want to lose sight of what is the main client/customer of Clay.

**Comment by carloslancha** [comment]
What @nhpatt said.

+ I'm not against allowing to configure DualListBox, I'm against adding no needed features/complexity to the components.

Clay provides such a huge collection of components that allow the user to compose what they need if some particular component, defined by Lexicon, doesn't fill their needs. Having that option + an API that also allows to configure everything is just too much IMHO.

Your use case fits what Lexicon define? Nice, this is your high level component. Your use case doesn't fit what Lexicon define? Ask yourself why not and, if you really need it different, compose it with these other not so high level components.

**Comment by matuzalemsteles** [comment]
Well, I guess that would be another discussion but what I'm most concerned about here is breaking the semver versioning we've followed, let's consider this a fix? why would this be considered a fix? Well that won't add complexity but just a way to avoid causing a breaking, add something like a `reoder="right"`.

The Liferay Cloud example is just an example that will work for any case, the same for DXP, just an example.

> Your use case fits what Lexicon define? Nice, this is your high level component. Your use case doesn't fit what Lexicon define? Ask yourself why not and, if you really need it different, compose it with these other not so high level components.

Well, I would really love things to be in the style that teams really use what is defined without changing or customizing anything, for example, I saw a case in DXP of a DropDown with very different Cards than we have with Navigation, the problem with that is that doesn't seem like something real to me that we're going to be able to achieve, not just adding it on the component side and not allowing anything, that's because new products evolve and new cases will emerge, Lexicon is a foundation, and on the component side we have that follow this.

**Comment by julien** [comment]
I agree with @carloslancha and @nhpatt in the sense that since we describe clay as "A Web Implementation of Lexicon Experience Language" we should follow what Lexicon says. Now if the change doesn't assume lots of work, I agree that we could configure the "reordering", but is it something we (or our users) are really going to need? 

Another point to really have in mind is that our priority is DXP, and for their use case they need reordering on the right. What if we changed this right now as a fix, and if someone later one ask for "configurable reordering" we can think about it.
