### ISSUE TITLE
Accessibility change request, remove IE7 CSS rules starting with * in Alloy Font Awesome, affected file /o/classic-theme/css/font-awesome.css

### ISSUE THREAD

**Issue by joseluisbango** [liferay/clay#4314]
[x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
I can't provide an example via codesandbox.com

## What are the steps to reproduce?
In order to reproduce, you need to run this accessibility tool OAW described on [LPS-133314](https://issues.liferay.com/browse/LPS-133314)

The tool seems to not like this CSS rules that starts with * made specially for fixing IE7 issues:

- *margin-right
- *line-height

This style comes from Clay v1 library in [alloy-font-awesome/scss/_mixins-alloy.scss](https://github.com/liferay/clay/blob/1.x/src/fonts/alloy-font-awesome/scss/_mixins-alloy.scss#L34) and [alloy-font-awesome/scss/_icons-alloy.scss](https://github.com/liferay/clay/blob/1.x/src/fonts/alloy-font-awesome/scss/_icons-alloy.scss#L27).

https://github.com/liferay/clay/blob/1.x/src/fonts/alloy-font-awesome/scss/_icons-alloy.scss#L27

## What is the expected result?
Have a clean accessibility report when using OAW tool which is owned by the Government of Spain and is used by any public institution to report and verify the validity of their site requested by law.

## Environment

| Tech  | Version |
| ----- | ------- |
| Liferay DXP  | 7.0.x  |
| Clay  | v1.x  |

**Comment by pat270** [comment]
@joseluisbango you can find your changes on `lexicon-ux@1.0.33`

**Comment by joseluisbango** [comment]
Hi @pat270, I can see v1.0.33 in npmjs, but I can't find it [in Nexus](https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/webjars/com.liferay.webjars.lexicon/) yet. I get this error:
```
Could not find com.liferay.webjars:com.liferay.webjars.lexicon:1.0.33.
     Searched in the following locations:
       - file:/path/to/portal/.m2/com/liferay/webjars/com.liferay.webjars.lexicon/1.0.33/com.liferay.webjars.lexicon-1.0.33.pom
       - file:/path/to/portal/.m2/com/liferay/webjars/com.liferay.webjars.lexicon/1.0.33/com.liferay.webjars.lexicon-1.0.33.jar
       - https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/webjars/com.liferay.webjars.lexicon/1.0.33/com.liferay.webjars.lexicon-1.0.33.pom
```
Thanks!

**Comment by pat270** [comment]
@joseluisbango I'm going to figure out why it didn't publish. I'll get back to you.
