### ISSUE TITLE
Final adjustments and behavior in TreeView

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4389]
Since the TreeView moves into a phase of more performance testing and we have practically all the features implemented, we need to make some adjustments to the component before making it public.

- [x] Add an API to enable and disable DnD 
        (#4396)
- [x] In multi-selection
   - [x] Select nested nodes that are not expanded 
          (#4401)
   - [x] ~If a node that is async is selected, select its children when loading~
- [x] For asynchronous loading of Node, deal with the case of an error or when returning an empty value
       (#4418)
    - [x] For error: we must somehow signal the user or suppress the error
    - [x] For void: this can signal that the Node is not asynchronous, that's because we use a strategy to invoke the method if the Node doesn't have a rendered group, we just deduce that it can be an asynchronous Node.
- [x] Add the option to add Actions to Node
       (#4421)

:warning: Some of these issues are easier to solve, others may take a little longer, we can also create a separate issue if necessary.

**Comment by julien** [comment]
@matuzalemsteles I edited the description to make it more fancy :rofl:

**Comment by matuzalemsteles** [comment]
@julien haha, thanks Julien, it got better.

**Comment by brunofernandezg** [comment]
Test comment to force sync. Ignore
