### ISSUE TITLE
Add option to use Indicator Start in ClayAlert

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#4408]
I'm proposing this because right now, when using ClayAlert component with "feedback" variant, it does not have the option to style it with [Alert Indicator Start](https://clayui.com/docs/components/alert/markup.html#css-alert-indicator-start). Adding `alert-indicator-start` class manually makes it work, but it would be great to have a prop for that, or maybe, as suggested by @matuzalemsteles in https://issues.liferay.com/browse/LEXI-1215, adding the class to feedback alerts by default could be enough.

## What is your proposal?
Add the option to style ClayAlert component "feedback" variant with Alert Indicator Start.

## Why would adopting this proposal be beneficial?
We would have the option to use ClayAlert component with that style without adding the CSS class manually

## What are the alternatives to this proposal?
Add `alert-indicator-start` manually

**Comment by matuzalemsteles** [comment]
Hey @pat270 I saw your comment on that, what problems do you see with making this class by default in the `<ClayAlert variant="feedback" />`?

**Comment by pat270** [comment]
@matuzalemsteles I don't think it will cause any issues. The only thing I remember it was used for messages in sidebars which are fixed width anyway.
