### ISSUE TITLE
@clayui/css: Mixin `clay-css` check if parameter is a map if not don't do anything

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4420]
We are currently writing `setter(map-get($the-map, the-key-name), ())` every time we pass a parameter to the `clay-css` mixin. This is a workaround for a `map-get` error if the parameter is not type map. We should perform this inside the `clay-css` mixin so we don't repeat it everywhere.

**Comment by brunofernandezg** [comment]
Test issue to force sync. Ignore
