### ISSUE TITLE
Card Image Aspect Ratio 

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4446]
Why does Card.AspectRatio have a backgroundImageAspectRatio prop that adds a class to style a background image but it doesn't include a way to set the background image? How was this intended to be used?

https://github.com/liferay/clay/blob/master/packages/clay-card/src/AspectRatio.tsx#L20

**Comment by julien** [comment]
> Why doesWhy does Card.AspectRatio have a backgroundImageAspectRatio prop that adds a class to style a background image but it doesn't include a way to set the background image? have a backgroundImageAspectRatio prop that adds a class to style a background image but it doesn't include a way to set the background image?

The only usage I found of  `ClayCard.AspectRatio` is in [`CardWithUser`](https://github.com/liferay/clay/blob/7a20ca1ef053db683e917fe9b4257fe2390749b6/packages/clay-card/src/CardWithUser.tsx#L129-L142), and it doesn't seem like the `backgroundImageAspectRatio` prop is ever used. Looking back at [when](https://github.com/liferay/clay/blame/7a20ca1ef053db683e917fe9b4257fe2390749b6/packages/clay-card/src/AspectRatio.tsx#L20) this was added, maybe @diegonvs has more information.

**Comment by matuzalemsteles** [comment]
Yeah, Card components are very difficult to compose due to exclusive and very dependent markup, you would have to add some extra markups if you want to use it outside of the Card.

For example:

```jsx
<ClayCard.AspectRatio>
	<div className="aspect-ratio-item-center-middle">
		<ClaySticker ... />
	</div>
</ClayCard.AspectRatio>

<ClayCard.AspectRatio>
	<div className="aspect-ratio-item aspect-ratio-item-center-middle aspect-ratio-item-fluid card-type-asset-icon">
		<ClayIcon ... />
	</div>
</ClayCard.AspectRatio>

<ClayCard.AspectRatio>
	<div className="aspect-ratio-item aspect-ratio-item-center-middle aspect-ratio-item-fluid card-type-asset-icon">
		<img className="aspect-ratio-item aspect-ratio-item-center-middle" />
	</div>
</ClayCard.AspectRatio>
```

I had in mind for us to work on trying to improve the Card components to further abstract the markup complexity, but it's very difficult because depending on the use case the markups change a lot.

**Comment by julien** [comment]
@ethib137 does this last answer from @matuzalemsteles answer your question or can we close this issue?

**Comment by ethib137** [comment]
Hey @julien, sorry for the slow reply... 

I definitely agree that improving the Card component would be helpful, and that it's complex to do it well. Is there a ticket for this created that I could follow and possibly comment on with suggestions?

Regarding the AspectRatio prop `backgroundImageAspectRatio`, I didn't really get an answer for how it is supposed to be used. It seems like we're not really sure. With a prop called `backgroundImageAspectRatio`, I would expect to have an additional prop that would let me set the background image. But since we don't, I think it would be best to either add a prop to set the background image or remove the `backgroundImageAspectRatio` prop. What do you guys think?

**Comment by matuzalemsteles** [comment]
> I definitely agree that improving the Card component would be helpful, and that it's complex to do it well. Is there a ticket for this created that I could follow and possibly comment on with suggestions?

Yeah, we don't have an explicit issue for that yet, but if you have some ideas that would be great.

> Regarding the AspectRatio prop backgroundImageAspectRatio, I didn't really get an answer for how it is supposed to be used. It seems like we're not really sure. With a prop called backgroundImageAspectRatio, I would expect to have an additional prop that would let me set the background image. But since we don't, I think it would be best to either add a prop to set the background image or remove the backgroundImageAspectRatio prop. What do you guys think?

Yeah, you can use it to define but you'll have to explicitly add the `img` to the `children` of the component, this really isn't very intuitive but it's because of the different markup possibilities the Card has, as I added in the comments above.

Some other examples, `children` may have a `span`, `div`, `checkbox`, `img` component directly or indirectly with some wrapper. There are some strategies we could do to abstract this, but we would have to rethink the ClayCard implementation a bit along with markup changes to simplify some cases and decouple some ClayCard-only classes.

For example, have something like this:

```jsx
<Image aspectRatio="3/2" bg="cover"  src="..." />
```

or keeping AspectRatio out of ClayCard plus abstracting the extra markups that need to be added depending on what component is defined in `children`.

**Comment by ethib137** [comment]
Hey @matuzalemsteles, thanks for your response. 

> Yeah, you can use it to define but you'll have to explicitly add the img to the children of the component, this really isn't very intuitive but it's because of the different markup possibilities the Card has, as I added in the comments above.

I don't think it works this way. The [backgroundImageAspectRatio](https://github.com/liferay/clay/blob/master/packages/clay-card/src/AspectRatio.tsx#L46) prop adds a class to the container such as `aspect-ratio-bg-cover`. This class will only style a background image that is applied to the container. It won't ever style an image inside of the container. Therefore, the only way to get this prop to do anything would be to provide a way to add a background image to the container of `ClayCardAspectRatio`. 

This is why I think we either need to remove this prop or add another prop that will let you add a background image to the container of `ClayCardAspectRatio`. Does that make sense?

**Comment by matuzalemsteles** [comment]
Ohh yeah, I understand now. You're right, this API doesn't make sense without `img` support. Well, I don't think this API would be AspectRatio's responsibility, it probably makes more sense for a component like `Image` that we thought of creating later.

**Comment by ethib137** [comment]
Would it be helpful to create a ticket to remove this prop, or at least deprecate it? If so, I'd be happy to create a ticket for it.

**Comment by matuzalemsteles** [comment]
I think it makes sense to remove this property rather than discontinue it because even if someone else is using it won't have any effect, so I think it's safe to remove it.

**Comment by ethib137** [comment]
Will be fixed by: https://github.com/liferay/clay/issues/4510
