### ISSUE TITLE
@clayui/date-picker: Not possible to reset selected days in calendar when setting value to empty string

### ISSUE THREAD

**Issue by vincentvandyck** [liferay/clay#4470]
Hello,

Not sure if this is a bug, question or change request.
I'm currently using the date-picker component, and there is one functionality that seems to be either not working or missing.

When I want to _reset_ the date value from outside of the component, the actual value of the input gets reset, but the selected days in the calendar remain selected. The _setDaysSelected_ function does not seem to be called when the value is changed to an empty string value. This seems to cause a temporary disconnect between the input value and the visual state of the calendar.

I think a fix could be to have the _inputChange_ function also count an empty value as a valid date, instead of only checking the format of the date.

Some extra information on my setup and a visual of the problem:

![calendar-days-not-resetting](https://user-images.githubusercontent.com/22026097/144389350-865c3b4c-e387-4296-be00-dc969f802902.gif)

simplified code used
```js
<div>
    <ClayDatePicker
        /* ... */
        onValueChange={(value) => { setValue(value); }}
        range
        value={value}
    />
    <Cross
        onClick={() => { setValue(''); }}
    />
</div>
```

Let me know if I'm doing something silly, missing something obvious, or can provide extra information on this.

Thanks!

**Comment by julien** [comment]
Hi @vincentvandyck,

Thanks for submitting this issue. I think what you mention makes sense, clearing the input's value should also reset the selected day.  Feel free to open a pull request if you want to, otherwise we can work on it.

**Comment by matuzalemsteles** [comment]
Hey @vincentvandyck, this is because passing an empty value is not a valid date, so the Date Picker's empty state behavior is to pass the current date to the Date Picker.

So what we can do here is if the value is empty, we leave the current date being checked.

**Comment by julien** [comment]
> so the Date Picker's empty state behavior is to pass the current date to the Date Picker.
> So what we can do here is if the value is empty, we leave the current date being checked.

I don't understand what you mean

**Comment by matuzalemsteles** [comment]
To clarify the Date Picker validates the value of the input, that is, it is necessary that a valid date is passed so that we can extract the information and add it to the Menu, as it is not a valid date we ignore it because the user can still be typing the date, then it is normal to be invalid.

In other words, the Date Picker's empty state is to leave the Date picker with the date of the selected day, even when it has no value. We follow the behavior of Lexicon this is also similar to native type. You can pass the empty value but we will not leave any dates unchecked in this case.

**Comment by julien** [comment]
> To clarify the Date Picker validates the value of the input, that is, it is necessary that a valid date is passed so that we can extract the information and add it to the Menu, as it is not a valid date we ignore it because the user can still be typing the date, then it is normal to be invalid.

Yes, that's very clear I understand how the component works, what I didn't understand is the solution you're proposing.

**Comment by matuzalemsteles** [comment]
On second thought and reading again I think we can't do anything with this case maybe just follow the initial behavior, as we can't leave no date selected in DatePicker, what we can do here is when it's empty, leave the current date selected as is the initial behavior. Currently leaving empty after a date is already selected we do nothing, we can do this by checking if the value is empty.

**Comment by julien** [comment]
@matuzalemsteles just so you know, @sergiojimcos is going to work on this one.

**Comment by matuzalemsteles** [comment]
Thanks @julien! if something is not clear yet, I can try to describe it more.
