### ISSUE TITLE
[Multi Step Nav] If the last step has a long title, the divider continues to nowhere

### ISSUE THREAD

**Issue by rodrigopaulino** [liferay/clay#4507]
https://clayui.com/docs/components/multi-step-nav.html

The steps to reproduce using the Clay sandbox first example is to simply change the title of the fourth step to a long one.
The actual result is the following:

<img width="855" alt="Screen Shot 2021-12-15 at 19 54 35" src="https://user-images.githubusercontent.com/11450348/146277517-02aa0a8e-1886-47f7-b656-a604c788f77f.png">

The title is not aligned in the center of the icon and the divider keeps going to no step.

The expected result should be for the divider to not be render after the last step and the titles to be in aligned with the center of the icon.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.41.0  |
| React |         |

**Comment by pat270** [comment]
Hey @rodrigopaulino, the example doesn't say, but we don't support centered text for the top and bottom. It's one or the other. The title is a space is reserved for longer descriptions that should break to a new line. Also the last item shouldn't have a title in it.

If you need centered text on the top you can use the `subTitle` attribute and `<ClayMultiStepNav className="multi-step-indicator-label-top">`.

If you need both, we can talk to the Lexicon team about adding it in their specs https://liferay.design/lexicon/core-components/forms/multi-step-form/.

**Comment by rodrigopaulino** [comment]
Hi, @pat270. Thanks for answering.

What do you mean by "the last item shouldn't have a title in it"?

Also, I believe the bigger issue here is not even the title not being centered, but the divider keep existing after the last step.

Lexicon has really straight forward instructions about how a multi step form should be designed. Don't you think the logic of the children of the ClayMultiStepNav (Title, Divider, Indicator) could be handled inside the ClayMultiStepNav component? And clients would only need to call one component that receives a list of items.

This is just an idea. Let me know what you think.

**Comment by matuzalemsteles** [comment]
Hey @rodrigopaulino what @pat270 is saying is that if your implementation needs both titles you will have to choose one or the other so it can be truncated, otherwise use subtitle as title so it can truncate the text and center it.

What we can do here is add a `ClayMultiStepNav` support API to change whether the subtitle should be rendered on the bottom or top.

We can't handle this internally because it depends on each implementation, if the two titles need to be truncated we should ask Lexicon for more details on this implementation.

We already have a component that you can pass just the `items` and it will do the rest but this is a high-level `<ClayMultiStepNavWithBasicItems />` component that doesn't allow much customization if you need to.

**Comment by rodrigopaulino** [comment]
Hi, @matuzalemsteles. Thanks a lot for taking the time to answer this.

I could use the `subTitle` to center my text, no problem, but I couldn't put it on top of the icon, even with @pat270's suggestion (`<ClayMultiStepNav className="multi-step-indicator-label-top">`). On the first screenshot of the [Lexicon page](https://liferay.design/lexicon/core-components/forms/multi-step-form/) shared by @pat270, there's an example (Current Step) of a center aligned text on top of the icon, but I can get the component to work that way.

I really appreciate the effort here. Thanks guys.

**Comment by matuzalemsteles** [comment]
@rodrigopaulino yeah, by default `<ClayMultiStepNav />` is adding the subTitle to render on the bottom, when adding the class together it will really break like I said if that's not a problem just using the subTitle we can add this API to toggle. Let me know what you think.

**Comment by rodrigopaulino** [comment]
Thanks again, @matuzalemsteles. For our use case, we need to keep the title (or subTitle for development purposes) on the top of the icon as Lexicon shows. 😊

**Comment by matuzalemsteles** [comment]
yeah, I'll think of something to improve this.

**Comment by rodrigopaulino** [comment]
Thanks a lot for your collab, guys! 🙏🏻
