### ISSUE TITLE
ClayDropdown is not being aligned in the best way

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#452]
ClayDropdown is not being aligned correctly, just aligning in a single position in all use cases by ignoring the boundaries of the screen.

<img width="279" alt="screen shot 2018-01-24 at 18 09 50" src="https://user-images.githubusercontent.com/13750819/35357273-cd6c4df2-0131-11e8-8bfc-fa44d27c5143.png">

**Comment by carloslancha** [comment]
@matuzalemsteles could you try take care of this? Thx!

**Comment by matuzalemsteles** [comment]
hey @carloslancha, This problem happens because the `.dropdown-menu` is not visible on the screen for `metal-position` to get `clientHeight` and `clientWidth`.

With the implementation of `Portals` the `syncExpanded` is called before the `show` class is added so that we can see `clientWidth`...

We can solve this with css by changing `display: none` to `visibility: hidden`, but I do not know if it is viable to use it. Another way would be to give the `Align.align` API a **width** and **height** to start, I don't know if it would be ideal.

@Robert-Frampton Do you have any thoughts on this?

**Comment by matuzalemsteles** [comment]
Fixed in #482.
