### ISSUE TITLE
"CSS Variables" should be called "SASS Variables" when NOT referring to CSS Custom Properties

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4520]
Hey team, given the prevalence of CSS Custom properties and the fact that they are often referred to as CSS Variables, we should no longer use "CSS Variables" to refer to SASS Variables. 

There may be other places where this is used in this way, but here is one example: https://clayui.com/docs/css/index.html
> This file should contain all your Clay CSS Variable overwrites.

https://sass-lang.com/documentation/variables

**Comment by julien** [comment]
thanks for reporting @ethib137, please feel free to submit a pull request. I'll let you discuss this one with @pat270

**Comment by ethib137** [comment]
Thanks @julien... Yeah I'll see what @pat270 thinks, and send a pull request if he agrees. :)

**Comment by pat270** [comment]
I can see how this is confusing. We can change it to Clay CSS Sass Variables?

**Comment by ethib137** [comment]
@pat270 sounds good to me.... Here's a pull request: https://github.com/liferay/clay/pull/4555

**Comment by matuzalemsteles** [comment]
Oh weird, apparently Github didn't close this issue after the PR was merged. I will close this manually.
