### ISSUE TITLE
[Tree View] Expand on Check

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#4523]
## Proposal
Clay Tree View's new feature allows users to expand parents nodes when checked automatically.

![Expand on Check](https://user-images.githubusercontent.com/21216422/147139257-5976fbe9-52b7-4a2e-9941-46d8a67ba347.png)

**Behavior**
When a user checks a parent node, it expands, showing its child nodes. However, it doesn't collapse when a user unchecks it.

## Considerations
- It is not required.
- The property is disabled by default.

## Why would adopting this proposal be beneficial?
The Tango and Echo teams performed user tests for features related to the current DXP Tree View component. For example, they've detected that users expect a node to be expanded once they check it. So we could assume they requested it because users would like to verify if the child nodes were checked when they checked the parent node.

**Comment by julien** [comment]
Hey @drakonux :dragon: this seems like a reasonable proposal :+1:
