### ISSUE TITLE
TreeView: don't export as UNSAFE_TreeView

### ISSUE THREAD

**Issue by julien** [liferay/clay#4528]
In https://github.com/liferay/clay/commit/3939f07b9df6ba39116ec1291a30caf2b0ea514b we decidedto export the `TreeView` component as `UNSAFE_TreeView`. 
There's no real advantage to doing this since it's still exported and
it makes the import statements look "ugly" when using it.

**Comment by matuzalemsteles** [comment]
This is really to make it look "ugly" and cause the effect of discouraging and flagging the component is unstable until we tested it in most use cases and would remove it until we have the component stable 🙂. Temporarily you could rename the component name via import, just like I were doing in the documentation.

**Comment by julien** [comment]
> This is really to make it look "ugly" (this is intentional) and cause the effect of discouraging and flagging the component is unstable until we tested it in most use cases and would remove it until we have the component stable slightly_smiling_face.

You mean like [this](https://github.com/facebook/react/blob/80bff5397bf854750dbe7c286f61654ea58938c5/src/umd/ReactUMDEntry.js#L21-L22)?  I personally think that doesn't avoid anyone from using it. I've seen much uglier code and I've had to use it; what I mean is that, doing that doesn't discourage me at all. 

Additionally, since **we knew** that we were going to integrate the TreeView in DXP, and we also knew that we were going to do it ourselves, what's the point? I don't like copying "stuff Facebook does" just for the sake of it, and unless it's clearly explained, the only thing this causes is confusion. If you have an idea, please talk about it and make it "official".
