### ISSUE TITLE
TreeView: Don't use async/await

### ISSUE THREAD

**Issue by julien** [liferay/clay#4529]
In the `TreeViewItem` component we're using [`async/await`](https://github.com/liferay/clay/blob/f91633f0371a42e86fbf9a59716d4104c4f9506a/packages/clay-core/src/tree-view/TreeViewItem.tsx), but 
since we can't use that in [liferay-portal](https://github.com/liferay/liferay-portal), we should avoid it.

This (imo) is another good reason why we should move Clay inside DXP (see #3849), because it would
also make us realize (or remember) these kind of things in advance instead of living in our own "Clay world"

**Comment by bryceosterhaus** [comment]
@julien could you provide a bit of context as for "why" we can't use async/await in portal?

**Comment by bryceosterhaus** [comment]
I would expect it should be okay to use in liferay-portal, unless I forgot about something, which is pretty likely.
![Screen Shot 2022-01-06 at 3 06 27 PM](https://user-images.githubusercontent.com/6843530/148464998-834fff18-e1b1-4bc6-8c6d-2e23208c1880.png)

**Comment by julien** [comment]
Hey @bryceosterhaus thanks for looking into this. I'll post more details in a bit, but basically I was getting errors about "regenerator runtime". Stay tuned for more.

**Comment by julien** [comment]
I just tested again, and you are right: in DXP if you use async/await with no problem. 

The problem comes from "here" (the way we build/transpile in Clay), when using this component and deploying the module I'm seeing this:

![](https://user-images.githubusercontent.com/5572/148969930-c097d5d2-a0a6-4801-8cd3-537c6abb8a33.png)

And here's a more "detailed" view of line 158

![](https://user-images.githubusercontent.com/5572/148970197-290cb6b5-e5e5-4db3-bf58-a1d2ba49b05a.png)


So maybe we're missing a babel plugin and that's just it. What do you think @bryceosterhaus?

**Comment by julien** [comment]
@bryceosterhaus this is what I tried

```
yarn add --dev -W @babel/plugin-transform-runtime
yarn add -W @babel/runtime
```

Add  '@babel/plugin-transform-runtime' to the "plugins" in our  [babel.config.js](https://github.com/liferay/clay/blob/c5cf8a7be5987a68ea90ad8fd4a7ef04f34bb6e9/babel.config.js#L24) file.
Rebuilt the clayui/core package, and I don't see anymore errors.

If that sounds good, I can send a PR with all that + re-adding all the "async/await" stuff I removed, because I actually preferred it :joy:.

**Comment by bryceosterhaus** [comment]
Ah I see, yeah my guess would be that we had something in Clay that is transpiling async/await stuff because at the time of adding it, we didn't support it. 

We might consider auditing our build a bit to make sure we aren't over-doing it when it comes to transpiling for older browsers.

**Comment by matuzalemsteles** [comment]
Oh, this is really bad going back to using Promise instead of async/await. I thought we were already supporting this in DXP. Actually, Clay is already transpiling to work in older browsers but polyfill is not being added in DXP, we can also stop transpiling but this will only work in newer browsers. Since we don't support IE11.

**Comment by julien** [comment]
Hey @matuzalemsteles, did you read my previous comments?

> Oh, this is really bad going back to using Promise instead of async/await

Well it's not **that** bad to be honest, it's just a matter of using the correct babel plugins (in my opinion).
async/await works in DXP, what doesn't work is consuming Clay's transpiled async/await code in DXP.

> I thought we were already supporting this in DXP.

Have you ever tried it though? (Using a Clay component that uses async/await and seeing it work in DXP)?

> we can also stop transpiling but this will only work in newer browsers. Since we don't support _IE11._

For me that wouldn't be an issue, but we need to make sure that's OK in DXP 7.3 (where Clay 3.x is used).
