### ISSUE TITLE
Add to ClayPopover the possibility to close the popover when clicking outside it

### ISSUE THREAD

**Issue by claraizquierdo** [liferay/clay#4536]
## What is your proposal?
We need the ability to close a ClayPopover component when the user clicks outside it or its trigger. Maybe it can be implemented with a new property (with boolean value) so that we can decide when to use the feature and when not.

## Why would adopting this proposal be beneficial?
We will avoid repeating code for closing Popovers when clicking outside them. We have a custom solution implemented [here](https://github.com/liferay/liferay-portal/blob/26e845edf5cd512add4b1509c558617d203cef58/modules/apps/comment/comment-taglib/src/main/resources/META-INF/resources/discussion/js/components/ReplyPopover.js#L35) and we will also need to add it in the Content Dashboard.

## What are the alternatives to this proposal?
We implemented an alternative using a custom hook (https://github.com/liferay-frontend/liferay-portal/pull/1793), but implementing it in the component seems cleaner.

**Comment by drakonux** [comment]
@julien, ok, we've added a new property to the component to enable closing the popover clicking outside. And about the trigger? Are we providing that way of closing the popover too?

**Comment by julien** [comment]
@drakonux the trigger is used to toggle the popover's visibility which we haven't changed, so I don't understand what you are asking for here.
