### ISSUE TITLE
Move charts demos to claycss.com

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#456]
Currently, we host some docs on about our charting solution in https://hosting-metalcharts.wedeploy.io

We should migrate that into the website for consistency and easiness

/cc @julien, @matuzalemsteles

**Comment by julien** [comment]
@jbalsas Ok I'll be doing that.

Do you know how to configure an `electric` project inside a lerna repo? 
`electric` can't seem to find the dependencies ?
