### ISSUE TITLE
@clayui/drop-down: ClayDropDown doesn't open if I pass a fragment as trigger

### ISSUE THREAD

**Issue by tinycarol** [liferay/clay#4560]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/damp-shape-zkdvs?file=/src/index.js

## What are the steps to reproduce?
* Use ClayDropDown
* Pass a React fragment that has two children inside as a `trigger` prop
* Click on the trigger
* See that the dropdown doesn't open

## What is the expected result?
* The dropdown opens

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.43.x  |
| React |  16.8.4  |

# Extra info
I need to pass two children as trigger to show/hide them depending on screen size (need a ClayButtonWithIcon on mobile and ClayButton with text in bigger screens), which requires that I wrap them in a fragment. I got it working by handling the ClayButtonWithIcon logic manually, but it would be nice to support fragments.

**Comment by matuzalemsteles** [comment]
Hey @tinycarol this is a very interesting case, we need some element to add the `onClick` events, to add fragment support we wouldn't be able to do that without knowing where we should add the event or the reference element to position the Menu.

What you can do here and what I would recommend would be to create a component with `forwardRef` that wraps the two elements that you are going to trigger, so you will get the `onClick` method that you can add to the two elements, the `ref` too it is necessary to be able to calculate the position of the Menu, in this case, it doesn't work for all elements, you would need to add it to the parent element of the two buttons.

```jsx
const ButtonWithMobile = React.forwardRef(({onClick, ...}), ref) => (
  <div ref={ref}>
    <ClayButton onClick={onClick}>I do open</ClayButton>
    <ClayButton onClick={onClick}>I do open</ClayButton>
  </div>
));

<ClayDropDown
  active={active}
  onActiveChange={setActive}
  trigger={<ButtonWithMobile />}
>
  ...
</ClayDropDown>
```

**Comment by matuzalemsteles** [comment]
Hey @tinycarol could you tell if this issue is still needed did the solution added above solve your problem?

**Comment by tinycarol** [comment]
Hi @matuzalemsteles! Sorry for the delay, the previous solution solved it :) Thanks for your help!
