### ISSUE TITLE
ClayUI v2 site returns a 404 error

### ISSUE THREAD

**Issue by brunofernandezg** [liferay/clay#4574]
https://v2.clayui.com/  returns a 404 error

**Comment by julien** [comment]
This was fixed by @bryceosterhaus (thanks again), in https://github.com/liferay/clay/commit/055df832fba6c63218be1354c62243db1753d089.

We have a `gh_pages`  branch based on the `2.x` branch that uses GitHub pages to display the site.

**Comment by bryceosterhaus** [comment]
Still need to fix the http/https issue. I'm not sure where the site was previously hosted, maybe @matuzalemsteles will know more

**Comment by matuzalemsteles** [comment]
Just putting what I put in the thread in slack:

From what I remember we always used `gh-pages`, we only adopted the use of Netlify with the new Clay v3 version.

We have clay v2 documentation using `gh-pages`, probably someone deleted the branch. https://issues.liferay.com/browse/LRITA-15216
