### ISSUE TITLE
TreeView: only show expander when a node has children

### ISSUE THREAD

**Issue by julien** [liferay/clay#4581]
Currently, when using the TreeView component, the "expander" icons are always visible
even when a node has no "children", which looks wrong.

![](https://user-images.githubusercontent.com/5572/149778044-40ccf328-4450-46b5-8c51-3e7d2e994a45.png)

I would expect that nodes without children don't show the expander icon and aren't "expandable"

**Comment by victorg1991** [comment]
This will be a nice addition :D
