### ISSUE TITLE
TreeView: review "nestedKey" prop

### ISSUE THREAD

**Issue by julien** [liferay/clay#4584]
In order to render a nested tree, I'm seeing that it's required to pass
the `nestedKey` prop. Maybe we should add a default value [here](https://github.com/liferay/clay/blob/fcd74499535f3fcd25bba70727449dbee60ae565/packages/clay-core/src/tree-view/TreeView.tsx#L83).

@matuzalemsteles tell me what you think when you get a chance.

**Comment by matuzalemsteles** [comment]
I don't see a problem with adding since we have the `nestedKey` prop that can change, that's because in some places in DXP the property names are different depending on the application, `children` is just a more common term for us.

**Comment by julien** [comment]
@matuzalemsteles take out the "nestedKey" prop in the stories (before this change) and look at what happens: nested node aren't rendered
