### ISSUE TITLE
4 new icons request from the Echo team

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#4586]
Hey team, 
I have a request from Echo and need to include some SVG icons into the system. Even though the request is for 5 icons, we recommended using one that is already available for one of the cases, so in the end the total number of new icons is 4. 

Here's the ticket: [LEXI-1268](https://issues.liferay.com/browse/LEXI-1268) 

List of icons with possible Metaphors/tags:

**corner-radius**
tags: border radius, smooth corners, rounded corners

**font-family**
tags: text, editor, style 

**font-size**
tags: text, editor, size, style

**shadow**
tags: effect, light

I'm also attaching the zip file containing the SVGs
[LEXI-1268.zip](https://github.com/liferay/clay/files/7890559/LEXI-1268.zip)

**Comment by julien** [comment]
Thanks @emiliano-cicero we'll work on that soon :smile:
