### ISSUE TITLE
TreeView: Give options to customize expanders and nodes

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#4589]
## What is your proposal?
It would be cool if the component could get some props like `nodeClassName`, `expanderClassName` or something like that, so we can customize them without overwriting the treeview classes. 
For the expanders, currently the component gets an `expanderIcons` prop in which you can pass a `<ClayIcon />` with a `className`, but in the case of the + button, it's not getting the classes properly (maybe this is a bug).
For the nodes, you define the markup of it, but it would be cool if we could add some class to the `<li class="treeview-item" />`.

## Why would adopting this proposal be beneficial?
We could adapt the style of nodes and expanders without overwriting the treeview classes in our CSS, making our styles independent in case in some moment the treeview classes change.

## What are the alternatives to this proposal?
The alternative is using the treeview classes in our CSS.

**Comment by julien** [comment]
Hey @sandrodw3,

Thanks for bringing this up.

> (maybe this is a bug).

It isn't, and as far as I know, with this new TreeView component we'd like to achieve of consistency in the UI (@drakonux will correct me if I'm wrong) so you "expander" icons should be icons and not buttons. I'm not saying we won't work on these changes, but  so far that's what I've understood. 

As for the nodes themselves you can actually put any kind of content you want, so you should be able to use the classes you need. We can discuss about passing extra classes to the "list"  items (`<li class="treeview-item" />`).

**Comment by julien** [comment]
Sorry, I don't know why I closed this :joy:

**Comment by julien** [comment]
> Thanks a lot for your fast answer smiling_face_with_three_hearts

No worries 

Now I understand what you mean, and I think that it's a totally acceptable change. I'll have a look at that and notify you when it's ready.

**Comment by julien** [comment]
Hey @sandrodw3 for the `<li class="treeview-item">` used by the [TreeView](https://github.com/liferay/clay/blob/bc208f3afc08cd55f7eb2344938851feac762abb/packages/clay-core/src/tree-view/TreeViewItem.tsx) item component, that's already [possible](https://github.com/liferay/clay/blob/bc208f3afc08cd55f7eb2344938851feac762abb/packages/clay-core/src/tree-view/TreeViewItem.tsx#L89) (unless I didn't understand you correctly). 

```jsx
<TreeView
	items={[
		{
			children: [
				{name: 'A'},
				{name: 'B'},
			],
			name: 'One',
		},
		{
			children: [
				{name: 'C'},
				{name: 'D'},
			],
			name: 'Two',
		},
		{
			children: [
				{name: 'E'},
				{name: 'F'},
			],
			name: 'Three',
		},
	]}
	nestedKey="children"
>
	{(item) => (
		<TreeView.Item className="parent-list-item">
			<TreeView.ItemStack>
				<Icon symbol="folder" />
				{item.name}
			</TreeView.ItemStack>
			<TreeView.Group items={item.children}>
				{(item) => (
					<TreeView.Item className="nested-list-item">{item.name}</TreeView.Item>
				)}
			</TreeView.Group>
		</TreeView.Item>
	)}
</TreeView>
```

**Comment by sandrodw3** [comment]
Hey @julien! You are right! That's already possible 🥰
In our case, what I wanted was to disable the background color change on hover for the nodes. I just checked that style is applied to the `<div class="treeview-link" />`, that is the first child of the `<li class="treeview-item custom-class" />`.

So I guess for that I could do this if I don't want to use `treeview-link` class:
```
.custom-class {
   div:first-child:hover {
       myCssRule;
    }
}
```

And for the expanders, it would be great to be able to add classes aswell.

**Comment by julien** [comment]
@sandrodw3 thanks again for the feedback ... 
Maybe we could do the following

- Add `expanderClasses` and `listItemClasses` as "props" (`Array<string> | string`) 
- If you pass those props they will override the existing classes

That said, I just want to be sure that removing the default classes for those things (`treeview-item`) isn't going to break anything design wise. Do you think that could work?

**Comment by sandrodw3** [comment]
@julien thanks for the idea 🥰
I have some questions:
- Which elements would get those classes? I guess for the expander will be the `<button class="component-expander" />`, right? And what about the list items? If we are going to add them to the `<li class="treeview-item" />` maybe it's not necessary, as we already can do it the way you described before. What do you think?
- Why do you think we should override the default classes? For my use case, I think it would be enough to add the custom classes without removing the default ones. For example `<button class="component-expander custom-expander-class" />`.

**Comment by julien** [comment]
@sandrodw3 seems like I wasn't understand you correctly. So all we need is to be able to pass "extra" css classes to the expander icons, right?

**Comment by sandrodw3** [comment]
Hey @julien it probably was my fault, I didn't explain well 😅

Yes, I meant that, passing extra classes to the expanders and the list items. 

For the list items I hadn't figured out that it was already possible, like you said yesterday, so maybe we don't need to do anything for it.

And for the expanders, I think it would be more useful to add the extra classes to the button (the `<button class="component-expander" />`), not to the icon. What do you think?

Thanks and sorry for the confusion 🥰
