### ISSUE TITLE
@clayui/css: Treeview rename `.treeview-item.disabled` to `treeview-item-dragging`

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4593]
~We can still click on links, check form elements, and collapse/expand items inside `.treeview-item.disabled`.~

We should reserve the `disabled` class for disabling pointer-events on links and buttons. `treeview-item-dragging` will highlight the node that is being dragged.

**Comment by brunofernandezg** [comment]
Test comment. Ignore
