### ISSUE TITLE
Add more tests to FocusScope to increase coverage

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4621]
Bryce even added some tests for this component to cover the Portals use case, but we have other edge cases, like in #4617, it would be interesting to build more tests for this component, how to handle shift+tab and the focus features using the arrow keys which is also provided.

Some scenarios in mind that we might want to add:

- Interactions with shift+tab
- Move focus using right, left, up, and down arrow keys
- Move focus outside the React tree. This is more the case of DXP when we render only DropDown for example and we need to return the focus control to the browser to the closest element, this has two scenarios, a component that uses `React.Portal` and a second that doesn't use it

**Comment by sergiojimcos** [comment]
Hey @matuzalemsteles! I'm going to start working on this issue. I will take a view of all the tests scenarios that you have mentioned. I think the last one is a little bit confused but if I have any doubt I will ask you, as well as if I have any idea for new test cases I will included it.
