### ISSUE TITLE
clayui.com move CSS Framework docs to the main nav

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4630]
We should remove the CSS Framework section and move the contents into the main flow of the nav. Our component docs have Example, Markup, and API tabs and the CSS Framework separation is no longer needed. We should move:

|Old Section|New Section|
|---|---|
|SCSS|Get Started?|
|Color|Components|
|Grid|Components|
|Typography|Components|
|C Kbd|Components|
|Utilities|Utilities (Create a new section under components)|

**Comment by matuzalemsteles** [comment]
@pat270 this makes sense to me, ideally, we also want to have equivalent components on the React side, mainly for Color and Typography, for Grid we already have some equivalents with Layout but I think we can deliver more value here.

Moving SCSS to the Get Started section is a good move.
