### ISSUE TITLE
@clayui/date-picker: Time is not being correctly sent on the field input

### ISSUE THREAD

**Issue by rebsilva** [liferay/clay#4638]
Hello guys, hope you are doing well!

I'm opening this issue because it seems that the solution of [this issue](https://github.com/liferay/clay/issues/4608) I've opened before didn't cover all the cases. The input of the time value on the date picker is changing correctly, but if I click on a date after that, it still sends the wrong value. For example, if I type `02/02/2022 05:00 PM` on the input field and open the date picker modal, the time input is with the correct value; but if after that I click on a date, it will send the wrong time value as `02/02/2022 17:00 PM`. Also if I do the same steps but with the date and time `02/02/2022 12:00 AM` it sends to the field input the value `02/02/2022 00:00 AM`.

Also a new behaviour is occurring that if I type a date on a language that doesn't use AM/PM, like for example `02/02/2022 13:00` and click on another date on the date picker, it will send to the input the value `02/02/2022 13:00 PM` that isn't a valid hour. If i put `03/02/2022 02:22` and click on another date on the date picker, it will send `03/02/2022 02:22 AM` to the input.

A video of these two behaviours can be seen [here](https://drive.google.com/file/d/1mXA5kORmRZPKcrekNL9YXVqDEqc99BhS/view?usp=sharing).

If need more info or help with anything let me know, thanks!

## Is there an example you can provide via codesandbox.com?

You can test both scenarios here: https://codesandbox.io/s/cranky-platform-47ldv?file=/src/index.js

## What are the steps to reproduce?

_For the first scenario (AM/PM language case):_

1. Type or paste on the field input a date and time like `02/03/2022 09:00 PM`
2. Click on the date picker icon to open the modal
3. Click on any other date
4. Close the modal and observe the value on the field input

_For the second scenario (adding AM/PM case):_

1. Remove the `use12Hours` prop from the `ClayDatePicker` in the code to simulate a language that doesn't use AM/PM
2. Type or paste on the field input a date and time like `02/03/2022 13:00`
2. Click on the date picker icon to open the modal
3. Click on any other date
4. Close the modal and observe the value on the field input

## What is the expected result?

_For the first scenario (AM/PM language case):_
The value on the field input should be the new date with `09:00 PM` and not `21:00 PM`.

_For the second scenario (adding AM/PM case):_
The value on the field input should be the new date with `13:00` and not `13:00 PM`. The same is happening with AM values: If i put `01:00` it will show `01:00 AM`.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | 3.45.1  |
| React |  v17.0.2  |

**Comment by matuzalemsteles** [comment]
Thanks @rebsilva for reporting this again, I probably forgot to add the same solution for the other actions. I'll add this issue to our release on the 9th, if this is urgent, please let me know.
