### ISSUE TITLE
Props "Small" in EmptyState component

### ISSUE THREAD

**Issue by BarbaraCabrera** [liferay/clay#4641]
## What is your proposal?

Implement a new props small in EmptyState component.

## Why would adopting this proposal be beneficial?

For the moment it will be used in admin cases, but it is not excluded that it will be used in public sites as well. Also, this was defined in [[LEXI-668](https://issues.liferay.com/browse/LEXI-668)] the (03/Oct/19) for team-tango.

**Comment by sergiojimcos** [comment]
Hi @matuzalemsteles! I will be in charge of this issue!

**Comment by pat270** [comment]
The only difference is the size of the image?

**Comment by sergiojimcos** [comment]
Hi @pat270! In this case the proposal affects the **size of the image** as well as some properties that contains this component like the **title**, **description** and that's all.
