### ISSUE TITLE
Adds the possibility to add `onChange` to Checkbox in TreeView

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4652]
Currently adding the `<Checkbox />` in the TreeView component abstracts the need to add `onChange`, `checked`, `indeterminate` and `disabled`, this works OOTB inside the TreeView but there are some cases inside the DXP that we need know when the Checkbox has been selected to invoke a method passing the item to store the data of the selected items so you don't have to traverse the tree in search of information.

The improvement here would be to be able to call `onChange` and also to be able to override the default behavior to allow for more configuration options.

**Comment by julien** [comment]
@matuzalemsteles I'll have a look at the pull request, but I wanted to say that I think we have the same issue with the `onItemsChange` prop.
