### ISSUE TITLE
Adds component implementation to handle typography

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4659]
This issue is closely related to #4131 which was created to explore components that can handle Layout and Typography but creating a new issue to speak only Typography as a final result, also related to the solid components foundation milestone, an [early draft of this proposal was created](https://paper.dropbox.com/doc/Clay-strategy-and-solid-foundation--BbotH1zwFFyNH3O2ZUep~D0CAg-UbYmJiDGPSVzuxZVPUgYl#:uid=307103685146520898353527&h2=Solid-foundation) and displayed 8 months ago on our Slack channel.

Since we had a breakthrough with typography after issue #4604 and PR was merged #4616 we have a much closer look at what components in React might look like.

Considering now the possibilities of #4616, I suggest that we can implement two different components and with different proposals, `<Heading />` and `<Text />` both with semantic usage, `Heading` more aligned to the `h` tag and `Text` aligned using the paragraph.

Both of these components are not new, many of them are used in other component and design system libraries like [Braid Design System](https://seek-oss.github.io/braid-design-system/foundations/layout), [Base Web](https://baseweb.design/components/heading/), [Adobe Spectrum](https://react-spectrum.adobe.com/react-spectrum/Text.html), [Evergreen](https://evergreen.segment.com/foundations/layers)... to create visual consistency and uniformity across the platform.

### `<Heading />`

| Name | Type | Description |
|-------|------|-------------|
| level | 1 / 2 / 3 / 4 / 5 / 6 | Sets heading level, h1 through h6. |
| weight | `lighter`/ `light` / `normal` / `semi-bold` / `bold` / `bolder` | Weight of the font |

Heading can also help deliver an interesting accessibility system with the `<ClayProvider />` to manage scaling and semantically nested levels. For example, if there is a heading being declared above the tree with `level="2"` and a heading being declared later below, it must respect the accessibility of setting the `level` to `"3"` if it is defined with a higher value for example. This is just an idea that we can explore.

### `<Text />`

| Name | Type | Description |
|-------|------|-------------|
| size | 1...11 | Sets the font size according to scale. |
| weight | `lighter`/ `light` / `normal` / `semi-bold` / `bold` / `bolder` | Weight of the font |
| italic | boolean |
| truncate | boolean |
| color | lexicon colors | Set a color for the Text |

Text is to be used for paragraph cases, for example, it can be used everywhere even in Clay's own components, it allows you to set the size according to the available scale, weight, truncate the text, and set the text color with available Lexicon colors.

Apparently, we don't have all the color possibilities available for the text but it would be interesting, for example, we could use `<Text />` in the input validation.

```jsx
<ClayForm.Group className="has-error">
  <label htmlFor="Feedback Input">Name</label>
  <ClayInput
    id="Feedback Input"
    placeholder="Enter some text..."
    type="text"
  />

  <ClayForm.FeedbackGroup>
    <ClayForm.FeedbackItem>
      <ClayForm.FeedbackIndicator
        spritemap={spritemap}
        symbol="exclamation-full"
      />
      <Text size="3" color="red">This is a description of the error!</Text>
    </ClayForm.FeedbackItem>
  </ClayForm.FeedbackGroup>
</ClayForm.Group>
```

I see a great opportunity for us to try to use the utility more than defining the color and size of the text in the class of each component, this also helps to reduce the amount of CSS and better creates a uniform system when we need to change the base size 4 for example, it scales easier. I believe we already have this because we are using Sass variables.

**Comment by julien** [comment]
@matuzalemsteles thanks for opening this - I think a really important point we should focus on is use a shared "vocabulary" between lexicon and clay, our variables should have the same names in order to avoid confusion.
I'm pinging @pat270 just so he can also comment about this.

**Comment by matuzalemsteles** [comment]
> I think a really important point we should focus on is use a shared "vocabulary" between lexicon and clay

Yeah, I agree! In this case, I think we don't have a vocabulary, at least from the Lexicon part about typography, only a few nomenclatures, like weight, but I think the vast majority of nomenclatures are on our side.

We are probably close to `Heading`, but Lexicon uses `Paragraph` and we are using `Text` here, in which case we would technically provide more options than Lexicon's `Paragraph` which is only used for long text for example, in a blog, in the Text scenario it is to be used in all scenarios, whether in the title of the sidebar, anywhere that has a component and also allows different scales so that the `h1` tag is not always used, for example, as discussed in the issues. But I think we're close cc @liferay-lexicon.

**Comment by julien** [comment]
@matuzalemsteles thanks for the additional information. Let's see if we can try to improve that - and establish a plan in our next meeting with Lexicon.

**Comment by pat270** [comment]
I can see this being useful for React developers. These scaling components will make development and bug fixing quicker. I'm on the fence about consistency though. On one hand we have a fixed set of text properties which will provide consistency over declaring the CSS yourself, but we will also have text utilities that exist in a component because it fits. I'm not trying to call anyone out, just noticed a few bug reports / feature requests in the Fragment area about the use of utility classes.

My biggest concern is the over use of utility classes in OOTB components. It doesn't provide any meaningful way to target a specific element inside a component via CSS or even JS without access to the source.

I think we might be able to make it work if we adopt `1-x` slots for all our utilities and limited usage. It doesn't have to be increasing or decreasing, just a namespace to store font sizes, weights, padding, margin, width, height. Our color names shouldn't be red, blue, green, rather ambiguous names like we already have with Bootstrap. We could even adopt `1-x` slots for colors.

This provides an escape for developers to use CSS to escape our strict utility rules with something like: 

```
.form-feedback-indicator.text-color-1 { color: green; }
````

Which makes more sense than:

```
.form-feedback-indicator.text-color-red { color: green; }
````

**Comment by matuzalemsteles** [comment]
> My biggest concern is the over use of utility classes in OOTB components. It doesn't provide any meaningful way to target a specific element inside a component via CSS or even JS without access to the source.

I think I agree with you on this, because actually in OOTB components we have a certain consistency but I am concerned because we offer the possibility that people can change the text size of each component using sass variables, without respecting the scale, so it could set the size according to each component if we didn't allow this I think this would be more consistent with the scale and easier to maintain.

> I think we might be able to make it work if we adopt 1-x slots for all our utilities and limited usage. It doesn't have to be increasing or decreasing, just a namespace to store font sizes, weights, padding, margin, width, height. Our color names shouldn't be red, blue, green, rather ambiguous names like we already have with Bootstrap. We could even adopt 1-x slots for colors.

This is really tricky to deal with because we want people to be able to customize but allowing customization can hurt the scale of change or consistency, it's also an escape to UI consistency. But I understand that people want it but for a DS this is really a problem.

For the color names, I think we should only have colors that can be easily reasoned out instead of having numbers in this case, I think colors are harder to keep in mind and identify what will be visualized when numbers are used, this is less when we talk about size for example for font size.

**Comment by sergiojimcos** [comment]
Hey @matuzalemsteles! I'm going to start working on this issue. I will take a look of all the documentation before start developing both components.

**Comment by pat270** [comment]
@sergiojimcos yes we have colors at https://clayui.com/docs/css/content/typography.html#css-contextual-texts and sizes at https://clayui.com/docs/css/utilities/markup-text.html#css-text-sizes.
