### ISSUE TITLE
Parent nodes should be expanded when any of its child is expanded

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4661]
Right now if you have a 3 level tree for example, you need and you want to expand the grandChild node, you need to pass the key of all the parents or the node won't be expanded. This behaviour it's not ideal since the selected node is unnoticeable.

## Is there an example you can provide via codesandbox.com?

https://codesandbox.io/s/vibrant-kapitsa-u3ttn?file=/src/index.js

## What is the expected result?

In the codesandox above name1 node and child1 node should be expanded, showing that grandchild1 is selected.

**Comment by julien** [comment]
@victorg1991 makes sense, we will fix this
