### ISSUE TITLE
Accessibility change request: avoid adding content from CSS

### ISSUE THREAD

**Issue by joseluisbango** [liferay/clay#4683]
## Is there an example you can provide via codesandbox.com?
I can't provide an example via codesandbox.com

## What are the steps to reproduce?
In order to reproduce, you need to run the accessibility tool described on [LPS-133314](https://issues.liferay.com/browse/LPS-133314) ([OAW](https://administracionelectronica.gob.es/comunidades/verPestanaMas.htm?idComunidad=accesibilidad#.YKZABKj7SHv), owned by the Government of Spain, used by m/any public institutions).

The tool throws some errors in `clay.css` when using `content` + pseudoelements `:after`/`:before`:

| Attribute(s)  | File |
| ----- | ------- |
| `content: "Browse"`  | `clay-css/src/scss/bootstrap/_custom-forms.scss`  |
| `content: attr(data-browse)` |  `clay-css/src/scss/bootstrap/_custom-forms.scss`|
| `content: attr(data-label-min)` / `data-label-max` | `clay-css/src/scss/variables/_range.scss` |
|`content: attr(data-multi-step-icon)` | `clay-css/src/scss/components/_multi-step-nav.scss` |
| `content: attr(data-label-on)` / `data-label-off` | `clay-css/src/scss/components/_toggle-switch.scss` |
|  `content: normal` | `clay-css/src/scss/components/_multi-step-nav.scss` |

**Steps**:

1. Start a DXP Bundle
2. Search for the aforementioned attributes in http://localhost:8080/o/classic-theme/css/clay.css

## What is the expected result?
No content is added from CSS. The accessibility tool does not complain about it.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v1  |
| Clay  | v2  |
| Clay  | v3  |

**Comment by pat270** [comment]
We can't delete these OOTB. What we can provide is a way to unset it via variables, meaning Sass won't output the properties in the CSS file. They will need to set the variables themselves in their theme.

**Comment by joseluisbango** [comment]
Hi @pat270!

Apparently, when you use a `content: none `it does not complain about it.

I've created a quick HTML file (see below) and changed between `content: none` and `content: normal` to test if there were any differences in the OAW test results:
- `content: none` no errors
- `content: normal` known error about creating content from style sheet

The file used:

```<!DOCTYPE html>
<html>  
 <head>
  <style>
   p::before { 
    content: "Test -";
   }
   p#oaw::before { 
    content: none;
   }
  </style>
 </head>
 <body>
  <p>This is an example</p>
  <p id="oaw">And a test for OAW</p>
 </body>
</html>
```

**Comment by joseluisbango** [comment]
By the way, I have updated the issue description and added versions 1 and 3 too. If we change this, it would be better to change it for all versions in order to avoid future problems

**Comment by pat270** [comment]
@joseluisbango Thanks for confirming.
