### ISSUE TITLE
@clayui/color-picker Color Picker should accept invalid Hexadecimal?

### ISSUE THREAD

**Issue by leticia-maciel** [liferay/clay#4694]
## What is your question?
Hi guys, I had encountered a scenario while testing but I don't know if it's expected behavior or a bug. Can you guys help me?

We're using Color Picker on Forms component and we noticed that it's possible to save an invalid hexadecimal color like `#FFFFFFaaaaaa`.

> ![image](https://user-images.githubusercontent.com/77082869/155596478-a6bae6b5-235a-42da-9488-573ef32a2ac3.png)

Even though on the menu dropdown it's set as `#FFFFFF`, the invalid hexadecimal is still being saved.

> ![image](https://user-images.githubusercontent.com/77082869/155597190-a88bcdaa-88c8-42cd-bf08-88bf6578618e.png)

Obs: I also noticed that is not possible to write invalid hexadecimal on the dropdown menu input field, which would help us in this case.

This was already reported? Is this a bug or expected behavior? Is possible for us prevent to saving this kind of invalid hexadecimal?

Thanks in advance!

**Comment by matuzalemsteles** [comment]
Hey @leticia-maciel, normally the input components allow you to control the state and do validation to integrate for example with a Formik, this is similar for the Date Picker as well. In this specific case I think we should correct it on our side, also looking at the documentation we are not validating correctly the color typed by the user and converting after the user types in the input.

I'll convert the issue to a bug and add it to our next release! Thanks!
