### ISSUE TITLE
ClayDropdown: Render dropdowns only after being open the first time

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#4708]
Currently, with the way ClayDropdown works, the dropdown-menu div is always rendered, and it's hidden or shown by CSS. In terms of performance, this has caused us some problems in Liferay portal when using a lot of dropdowns at a time. For example, in Pages administration, each page item has two dropdowns, so in sites with a lot of pages, a lot of dropdowns are being rendered and it's causing bad performance issues.

## What is your proposal?
My proposal is to render the dropdown-menu div only after the first time the trigger is clicked.

## Why would adopting this proposal be beneficial?
It woud help avoiding performance problems.

**Comment by sandrodw3** [comment]
I sent a PR with my proposal here: https://github.com/liferay/clay/pull/4709 🥰

**Comment by julien** [comment]
@sandrodw3 thanks for reporting this issue **and** submitting a fix. I'll have a look as soon as I can (Matu is currently on PTO)

**Comment by sandrodw3** [comment]
np @julien! 🥰
I also sent a temp solution to fix the performance in our module, so I'm not in a hurry with this. Thanks!

**Comment by julien** [comment]
@sandrodw3 good to know :muscle:, that said the quicker this gets in Clay and DXP, the better :-)
