### ISSUE TITLE
The Clay Tabs component should not always include either the nav-tabs or nav-underline classes.

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#4751]
## What is your proposal?

Currently the tabs component forces the inclusion of either the `nav-tabs` or `nav-underline` class. You can see this [here](https://github.com/liferay/clay/blob/master/packages/clay-tabs/src/index.tsx#L43-L44). The api should be updated so that it's possible to have neither of these classes applied.

## Why would adopting this proposal be beneficial?

This would allow for rendering an unstyled version of the tabs component that could be fully restyled. This would also make it possible to create additional displayTypes of tabs, without having to override the styles added by either the `nav-tabs` or `nav-underline` classes.

**Comment by matuzalemsteles** [comment]
Hmm makes sense to me, I think in this case this could have been a `displayType` with the default value, to avoid a breaking change now, I think we can have `displayType` for that purpose, in case you don't want to use any style just set ` displayType={null}`, I just have to check a way to still keep this default behavior for compatibility.

**Comment by sergiojimcos** [comment]
Hey @matuzalemsteles! I am going to assign this issue and start working with it.
