### ISSUE TITLE
Explore using visual tests for components in the storybook

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4802]
Our QA team is evaluating adding this to our CI but using ocular, the problem is that the tool is very simple and requires a lot of work from the QA team to update and maintain the baselines as well as it can slightly increase the time of the CI in DXP, we want to try using this outside the DXP repository and using it directly in Clay we can have a better tool to analyze visual tests and it will be easier to maintain, as well as being part of the component development process.

Our QA team is also interested in this move to bring this to Clay.

**Comment by bryceosterhaus** [comment]
I previously looked into https://www.chromatic.com for the clay repo. I remember it working well as I think it hooked into storybook. The main drawback was cost if I remember correctly.

**Comment by matuzalemsteles** [comment]
Oh I see, I'll go back and look at that again and see if we get anything or look for other alternatives that might work.
