### ISSUE TITLE
Add "info button" to ClayManagementToolbar

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#481]
New feature required by UX: https://docs.google.com/document/d/1y67UAnbUzL5WLAkPMQbkqgGw3_5e7-JMEPVYdC48qE0/edit?ts=5a692baa#

**Comment by pat270** [comment]
Hey Carlos, is this issue requesting a markup demo for the info button with sliding panel?

**Comment by carloslancha** [comment]
Hey @pat270! I create the issue to implement that feature in the existing component, but would be great to add a markup to the demo to be sure we do it correctly. Thx! :D
