### ISSUE TITLE
Color picker null state icon

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#4812]
This icon is needed for the [color picker Null state](https://issues.liferay.com/browse/DESIGN-1112) when a color is Undefined. 

**Metaphors**
line, diagonal, slash, null, empty

[LEXI Ticket](https://issues.liferay.com/browse/DESIGN-3618)

[diagonal-line.svg.zip](https://github.com/liferay/clay/files/8512194/diagonal-line.svg.zip)

**Comment by matuzalemsteles** [comment]
I will create a follow-up issue because we also need to add this functionality to ColorPicker.
