### ISSUE TITLE
Replace Lerna with another alternative

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#4829]
Lerna is officially not being maintained anymore, it has come over the years without many updates or bug fixes, it was recently updated that it is no longer being maintained. We need to look for other alternatives for this, we currently use lerna a lot to generate changelog, cut version and publish packages.

We also used it for build but it was always very slow, we can try using [Turborepo](https://turborepo.org) to handle the build part and using [Changesets](https://github.com/changesets/changesets) to handle versioning and changelog. Consequently, we can have a much faster build compared to before, so the CI can run faster too, this also impacts #4822.

- [Turborepo: Migrate from Lerna](https://turborepo.org/docs/guides/migrate-from-lerna)

**Comment by matuzalemsteles** [comment]
[Lerna announced yesterday that it is officially with a new official maintainer](https://github.com/lerna/lerna/issues/3121), the company [Nrwl](https://nrwl.io/) will be maintaining and it is also the same company behind [nx](https://nx.dev/).

![](https://user-images.githubusercontent.com/13750819/167175024-0eb2f3d0-bf0b-4334-b12c-70fd8fa3d5f1.png)

Some things I investigated about it, Turborepo has already been merged and has had significant improvements in our CI, at least 2x faster, it will also improve local development for those who are using the build that is less frequent.

Changesets are a very different workflow to what we do today, switching to it requires us to change our workflow, for example, to cut a new version and create changelogs, the changesets do not use commit tracking using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for this, the flow is quite different and quite interesting I think, you create logs of the changes you are making, for example when sending a PR of a change you also send an automatically generated file using the Changesets CLI, defining which file should change version following the [semver](https://semver.org/) and the change description, at the end when cutting a new version it takes all these logs, generates the changelog and sets the version and deletes these log files.

I think switching to this now would require all people contributing to Clay to switch to this stream and follow suit, otherwise, it would be a big problem. As we have news that Lerna has a new official maintainer I think it is safe to keep Lerna for now just to publish and cut the Clay package version and we will be using Turborepo only for the build pipeline which is much faster.

Following this I'm closing this PR we can come back with it if needed.

**Comment by juristr** [comment]
I know this issue is closed. But as of today Lerna even got at least 5x faster than Turbo 😉
All details here: https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700?source=friends_link&sk=6c827ec7c9adfc1c760ff2e3f3e05cc7

**Comment by matuzalemsteles** [comment]
Oh this is great, thanks @juristr for sharing!
