### ISSUE TITLE
ClayInput readOnly property is removing FormGroup status styles

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#4841]
When a `ClayForm.Group` has a status `className`, for example `has-success`, and a `ClayInput` inside it has `readOny` property, the input loses the success styles.

## What are the steps to reproduce?
Go to https://clayui.com/docs/components/form.html#validation, and in the first example, add `readOnly` to the input.

## What is the expected result?
The expected result is that the input becomes read only but it keeps success styles.

**Comment by matuzalemsteles** [comment]
Hmm this is an interesting use case, @sandrodw3 do you have any examples of this being used together? This sounds a little confusing to me when you have a read-only input that succeeds.

**Comment by sandrodw3** [comment]
Yep! Not for success but for warning, we have one, but it's true that maybe this use case is a bit specific:

![image](https://user-images.githubusercontent.com/2444936/166485045-6c5ced82-8f9f-49d1-b74d-b57214bae5f6.png)

It's a vocabulary selector, the input is read only and it shows the name of the selected vocabulary. You can use the button on the right to change the vocabulary and it becomes warning when the vocabulary does not have any category. We have this pattern repeated also in other modules.

As I said, maybe this case is too specific. I also understand if you think it's not worth to fix it, so feel free to close the issue in that case.

Thanks @matuzalemsteles! 🥰

**Comment by pat270** [comment]
@sandrodw3 This was done on purpose for the reason @matuzalemsteles stated. It didn't make sense to have states on an input you can't change. We can remove those overwrites if you want. There is no official Lexicon definition for readonly inputs.

**Comment by matuzalemsteles** [comment]
Yeah, maybe for success this doesn't sound very good it's a bit confusing, I understand this case of the warning because it is interacting with another component and they are related, so helps to understand the reason to add a warning in the read-only. Well, I'm fine with removing those overwrites.

**Comment by pat270** [comment]
Leaving success, but allowing styles for the other states doesn't sit right with me. An alternative where we won't need to change any behavior is to use:
```html
<div class="form-control"></div>
```
instead of an `input`.

**Comment by matuzalemsteles** [comment]
Hmm seems like a viable option too, I'm not sure if this semantically can cause any problems related to accessibility, I don't think so but something to keep in mind.

**Comment by sandrodw3** [comment]
Um, that's a good idea, and it solves our problem 🥰

I don't think it will cause any accessibility problem, as our input was not interactable anyway, but I'll keep an eye on it.

I guess we can go with this option and close this issue. Thanks a lot @pat270 @matuzalemsteles ❤️

**Comment by pat270** [comment]
@sandrodw3 glad it worked any we don't have to do anything 😆 . You could associate the label to the button.

**Comment by matuzalemsteles** [comment]
That's good, I'm going ahead and closing this, but feel free to open this again in case you run into another issue.
