### ISSUE TITLE
@clayui/date-picker using defaultValue does not create a selection in the dropdown

### ISSUE THREAD

**Issue by NemethNorbert** [liferay/clay#4856]
**Issue description**:
[LPS-153209](https://issues.liferay.com/browse/LPS-153209)
If we are creating the date picker with a defaultValue, or simply provide a value to a controlled date-picker component the selection in the dropdown always shows only the current date.
This is also true when we are using the date picker in range mode or when we use it in single selection.

**Codesandbox.com example**:
https://codesandbox.io/s/relaxed-keldysh-coh9in?file=/src/App.js

**Reproduction steps**:
1. Create a date-picker component with @clayui/date-picker
2. Set it's value and defaultValue in range mode
3. Click on the right end side of the input field ( I was not able to import the icons.svg in the sandbox, but the button is there)

**Expected**: The value we provided is available as a selection
**Actual**: The selection defaults to the current day

Once we manually select something, even if we just type it the date picker selection works

**Comment by matuzalemsteles** [comment]
Hey @NemethNorbert Thanks for reporting this, I'll take a look and fix it.
