### ISSUE TITLE
Update Loading Indicator

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#4870]
## What is your proposal?
We have a [request ticket](https://issues.liferay.com/browse/DESIGN-678) to update the Loading Indicator. 
I've been able to explore different solutions for a new loading indicator and my proposal is to split it into 2 types: 
- Circle: a simple circle spinner for small cases like buttons, inputs, table rows, etc.
- Squares: a spinner made with 2 squares for bigger cases such as cards, pages, sidebars, etc. 

The idea is to keep the current sizes, making the Circle available for 10px and 16px, and the Squares for 32px and 64px. 
Here's some [documentation](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/2024374574/DESIGN-678+Loading+Indicator+Update) that might help.
I've also prepared a [codepen prototype](https://codepen.io/EmilianoCicero/pen/MWQaaVM) of the squares spinner. (The circle one should be easier since it only turns of 360 degrees but if you need it I could do it too.)

## Why would adopting this proposal be beneficial?
We will be updating an element that feels a bit old now and also include some branding aspects into the system with the Square indicator. 

## What are the alternatives to this proposal?
The only alternative would be to keep it as it is.

**Comment by matuzalemsteles** [comment]
Well, in theory, this would be a breaking change but considering that this is a visual improvement it might make sense to change it now independently. I think here we will need to update the component as well and add the new variation.

**Comment by pat270** [comment]
Can you clarify change independently? I'm assuming it means keep the dots and add the new indicators as variants.

**Comment by matuzalemsteles** [comment]
Oh I think I'm understanding this as no longer having the loading indicator with dots and replacing it with the proposal, apparently, the ticket opened was with the intuition of replacing instead of creating a new variation.

From what I understand the `circle` type will be the new dots and now we will have the `square` variation.

**Comment by emiliano-cicero** [comment]
Just for clarification, it would work as the last message from @matuzalemsteles: 
- The Circle type replaces the dots and will be used only for 10px and 16px cases
    - This change is required since the dots were not that good for small components
- The Squares type is a new variation that should cover 32px and 64px cases
    - This variation was included to have some details from the Liferay's brand inside the system
    
Also, I was the one that made the old Dots and there was no specific requirements at the time, nor people requesting them to be with that particular shape so I don't think anyone will care. If anything this change should improve the overall loading perception.
