### ISSUE TITLE
Expose input ref in MultiSelect to be able to focus it from the outside

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4915]
Currently there is not a way to grab a ref to the internal input in the multiselect component. Sometimes you may need to focus the input manully, but without a ref you'd to rely on an ugly querySelector. It will be to expose a new prop for doing that, or even reusing the ref property

**Comment by matuzalemsteles** [comment]
We can move the ref that is in the container to the input, I think it makes more sense in fact for this component than having a ref in the container.
