### ISSUE TITLE
@clayui/css: Negative margin utilities have no value

### ISSUE THREAD

**Issue by pat270** [liferay/clay#4922]
###### clay.css
```css
.mt-n1,
.my-n1 {
  margin-top: !important;
}
```

We use the `math-sign` function to get the opposite value for negative utilities. 

https://github.com/liferay/clay/blob/f1106e376a0287572b41439187e1f304b9f9a4e5/packages/clay-css/src/scss/components/_utilities.scss#L362-L388

The math sign function only checks if the type is `number` or `string` and returns a `null` value if it's any other type.

https://github.com/liferay/clay/blob/f1106e376a0287572b41439187e1f304b9f9a4e5/packages/clay-css/src/scss/functions/_global-functions.scss#L97-L107

The `$spacers` map has values of type `list` for anything greater than 0. 🤔 

https://github.com/liferay/clay/blob/f1106e376a0287572b41439187e1f304b9f9a4e5/packages/clay-css/src/scss/atlas/variables/_globals.scss#L199-L236

We need to remove the trailing comma in `($spacer * #,)` values. The trailing comma is added by prettier during `yarn format`. The parenthesis for spacer values are used to group together the math function, but prettier mistakes it as a map key value pair.

**Comment by georgel-pop-lr** [comment]
@matuzalemsteles please let me know when this gets into liferay-portal in master, so I can back port to 7.3.x, thanks.

**Comment by matuzalemsteles** [comment]
@georgel-pop-lr we are going to cut the release today, we will be using the ticket https://issues.liferay.com/browse/LPS-155577 to update the packages in master.
