### ISSUE TITLE
Clay Tooltip gets unwanted outline on focus

### ISSUE THREAD

**Issue by beltranrengifo** [liferay/clay#4937]
Hi team! As we discussed, the popover gets outlined if any kb key is pressed.
 1. [Open Clay's SB](https://storybook.clayui.com/?path=/story/design-system-components-popover--default) 
 2. Click on the popover
 3. Press any key in the kb

## What is the expected result?
I wonder if the popover should get outlined or not.

If yes, are this the proper styles?
If not, how should the component handle the focus?

## Environment

Current version

![image](https://user-images.githubusercontent.com/19485114/174579787-4d7d18d5-6fcc-4e0e-9d89-005b1b9f5b6e.png)

**Comment by beltranrengifo** [comment]
cc @drakonux @emiliano-cicero 
maybe we should move the conversation here

**Comment by emiliano-cicero** [comment]
As commented in slack, I believe that a component such as a tooltip or a popover shouldn't get the focus state at all. These components are meant as helpers, to provide more info to the user. 
To translate this to a common scenario this is what I think should happen: 

**Actors**
- Button with the help icon
- Popover with a title and text

**Interaction**
When the user activates the help button, the popover will open but the button should keep the focus. 
When the user activates the help button using a screen reader, it should just read the content of the popover as extra information.
IF the user moves from the help button (tab/click elsewhere) the popover will close.

**Complex popover**
It could be possible to extend the popover in a way that it has more actions (even though, for those cases I would generally recommend using a Modal). For those cases the Popover should never get the focus state either. The way to handle this should be by using the focus trap inside the popover directly and only allow to move back to the interface when the popover is closed. But the focus will be always reserved for its child interactive components, never the popover itself. 

**Focus style**
We're currently having conversations to avoid showing the focus style when using a mouse to interact with the interface, and only show it when users navigate using the keyboard.

**Comment by matuzalemsteles** [comment]
> When the user activates the help button, the popover will open but the button should keep the focus.
> When the user activates the help button using a screen reader, it should just read the content of the popover as extra information.

These two scenarios are a little conflicting for us, there is no way to know that the button has been activated by a screen reader, the behavior is actually different here where the focus is, the screen reader will do the reading, to read the content of the popover we need to move the focus from the button to the popover like we do today.

**Comment by pat270** [comment]
Lexicon Popovers allow content to to overflow.
![lexicon-popover](https://user-images.githubusercontent.com/788266/175548290-f226de1f-b44a-40a8-a6fc-ba495cea4b91.jpg)
We need to shift the focus to the popover to make it scrollable with the keyboard. The `focus-visible` pseudo class (modern browsers only) will only show an outline if you press a keyboard button like up arrow or down arrow. It doesn't show when we focus it via js.
