### ISSUE TITLE
The required field icon is not aligned correctly

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#4938]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/incorrect-alignment-required-icon-vzv1jf

<img width="209" alt="asterisk2" src="https://user-images.githubusercontent.com/9701095/174631856-7aebaa05-9387-4638-9c71-c6204d163f1b.png">

## What are the steps to reproduce?
The asterisk indicating that the field is required is not correctly aligned. It seems that the `vertical-alignment: middle` of the `.lexicon-icon` class is overriding the `vertical-alignment: super` of the `.reference-mark` class.

<img width="500" alt="asterisk" src="https://user-images.githubusercontent.com/9701095/174629529-0aafeed9-8bef-44f8-bfc5-f94b9262d34c.png">

## What is the expected result?
The asterisk should be top aligned.

**Comment by pat270** [comment]
@veroglez Thanks for reporting this. We can add vertical alignment for `label .reference-mark`.

This css component can be used with text or svg's. The originial intent was for the text or svg to be nested inside `reference-mark`.

```
<span class="reference-mark">*</span>
<span class="reference-mark">[1]</span>
<span class="reference-mark">
    <svg></svg>
</span>
```

**Comment by veroglez** [comment]
Thanks so much @matuzalemsteles!
