### ISSUE TITLE
Enable chart background "patterns" on demand

### ISSUE THREAD

**Issue by julien** [liferay/clay#495]
At the moment in [clay-charts](https://github.com/liferay/clay/blob/develop/packages/clay-charts), if the default [patterns are available](https://github.com/liferay/clay/blob/develop/packages/clay-charts/src/ChartBase.js#L75-L81); they are used as "background patterns" (or tiles). 

We should change this behaviour, so that patterns are only used if one activates them.
We could add an `useTiles` option for example.

@matuzalemsteles if you're interested you can have a look at it, and if you need help feel free to ask me.

**Comment by matuzalemsteles** [comment]
hey @julien I can take a look at this. 🙂

**Comment by julien** [comment]
@matuzalemsteles great, thanks.
