### ISSUE TITLE
ClayMultiSelect placeholder doesn't have the same padding than a normal input in small variant

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4955]
![Screenshot 2022-06-24 at 14 27 52](https://user-images.githubusercontent.com/11654230/175535721-86731027-ecaf-4a36-aab2-4be9ccfb2941.png)

I believe placeholder for the ClayMultiSelect should be the same one than a standard input in the small variant

## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/brave-wave-2c32c3?file=/src/

**Comment by pat270** [comment]
@victorg1991 this is a feature 🍿  (https://github.com/liferay/clay/issues/4911#issuecomment-1155351022).  We can discuss it here with @emiliano-cicero.

**Comment by victorg1991** [comment]
I checked the message but it wasn't any reference about the placeholder there. Shouldn't we keep consistency in the placeholder @emiliano-cicero ?

**Comment by pat270** [comment]
I agree with if there is no label, the text/placeholder should align. I personally would like it if the padding was kept the same as small input (easier for me 😅 ).

**Comment by leolohmann** [comment]
@liferay-lexicon (another test - please ignore it)
