### ISSUE TITLE
Browser icon for Echo team

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#4960]
Hey team, I have a request from the Echo team for a new icon that represents the Browser feature in the page editor.

## Link the DESIGN Jira Issue.
[DESIGN-3761](https://issues.liferay.com/browse/DESIGN-3761)

## Additional Info
Icon Name: hierarchy
Metaphors: browse, layers, elements, rectangles, list, order, sequence

## Attach the SVG.
[hierarchy.svg.zip](https://github.com/liferay/clay/files/9009696/hierarchy.svg.zip)

**Comment by leolohmann** [comment]
@liferay-lexicon just a mention test. please ignore it.

**Comment by leolohmann** [comment]
@drakonux

**Comment by leolohmann** [comment]
@emiliano-cicero
