### ISSUE TITLE
Better DragAndDrop support in TreeView

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#4984]
Currently, if you enable the drag and drop in the tree view and perform some move, the `onItemsChange` prop is called passing the new list of items. 

## What is your proposal?
Apart from return the whole list (that may server for some cases) it will be nice to indicate what item has been moved, and also to which parent. T
## Why would adopting this proposal be beneficial?
This will make easier to know exactly what changed, without having to compare both old and new list.
## What are the alternatives to this proposal?
Maybe adding a new prop for this purpose, but it seems overkill

**Comment by matuzalemsteles** [comment]
@victorg1991 thanks for the feedback, I'm thinking of adding a new API specifically for this so we don't change the definition of `onItemsChange`, something like `onDrop`. What do you think?

**Comment by victorg1991** [comment]
Yeah maybe extending the props are better :) `onDrop` feels a bit generic, following the same pattern as other props, `onItemRename` for example... maybe `onItemMove` ?

**Comment by matuzalemsteles** [comment]
Yeah makes sense
