### ISSUE TITLE
New tooltip behavior

### ISSUE THREAD

**Issue by carolrodmar** [liferay/clay#4991]
## Context
We are currently improving the interaction to live-edit a text fragment in Page Editor. This improvement includes the use of a tooltip that will inform users that a fragment is editable.  

## Our need
What we would need is that the tooltip is shown close to the cursor (Image attached). Something similar to what Jira does in its ticket descriptions (Video attached). If we use the tooltip as it is, the interaction and the tooltip get out of context. Could you study this to see if we can cover this new behavior?   

<img width="543" alt="Image" src="https://user-images.githubusercontent.com/89843928/179214019-6b4bb348-439c-45fa-bbcc-e7924fe90730.png">

https://user-images.githubusercontent.com/89843928/179214072-ebb7ac2a-3e31-40a9-8dca-00b9a67ed2f8.mov

## Previous discussion with Lexicon
We opened a thread discussing about this for you to have a look:
https://liferay.slack.com/archives/CKT3L1G58/p1657097834908479

cc\ @mateo-hermosin @drakonux

**Comment by matuzalemsteles** [comment]
Hey @carolrodmar I think this is possible, we will probably have some functionality limitations here but I think this is ok for this behavior. My thought is that we can show the tooltip near the mouse inside the element that has declared the `title` attribute and this behavior can be configured via an API.

**Comment by carolrodmar** [comment]
Thanks for your quick answer @matuzalemsteles 

That sounds good. Do you know when this could be available?

**Comment by matuzalemsteles** [comment]
@carolrodmar I'm going to work on it this week, so it should be available in Monday's release.

**Comment by marcoscv-work** [comment]
Hey! I'm pretty sure this new tooltip is not accessible:
https://github.com/liferay/clay/issues/4976

My suggestion is something like move the tooltip to the enter mouse point but not follow the pointer, something closer to the native tooltip, like the JIRA example (it fails when you change the line in titles with multiple lines)

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work I believe this should be fixed with #5023. Let me know what you think!

**Comment by marcoscv-work** [comment]
That looks amazing, thanks @matuzalemsteles
