### ISSUE TITLE
TreeView with dynamic items: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by iouomo** [liferay/clay#4995]
Hi!
Test it please.

Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/vigilant-merkle-be6ci5

## What are the steps to reproduce?
Get the example from https://clayui.com/docs/components/treeview.html#dynamic and paste it to a sandbox.

## What is the expected result?
TreeView with dynamic items.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.65.1 |
| React | v16.8.4 |

**Comment by matuzalemsteles** [comment]
Hey @iouomo thanks for reporting this issue, this is a typo in the documentation, when you have a Group inside an Item, it is necessary to wrap the current node with `TreeView.ItemStack` as in the Nested example in the documentation, I will update this example in the documentation to avoid misunderstanding.

I also noticed that there are some errors in the rendering of your example, I recommend checking this codesandbox https://codesandbox.io/s/sweet-wind-0ut2so?file=/src/App.js

**Comment by iouomo** [comment]
@matuzalemsteles Thank you!
