### ISSUE TITLE
Tree Data with @clay components

### ISSUE THREAD

**Issue by iouomo** [liferay/clay#5001]
Hi!

Is it possible to create a tree-view table with search using clayUI components? Something like this:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/26546404/179954461-10429dbe-93dc-4278-85a5-0dc0566d38ee.png">

Any ideas?

**Comment by matuzalemsteles** [comment]
Hey @iouomo unfortunately, we don't have any way to support this kind of table, I believe you could try adding some classes to customize in the first column that could add padding if it is the child of some element but I think that would be a lot of work to create something like that and would also depend on the data depth of a row so maybe you would have to avoid using `<table />`.

**Comment by matuzalemsteles** [comment]
I'm closing this issue, let us know if the last comment answers your question and feel free to reopen or create another issue, Thanks!
