### ISSUE TITLE
Wrong padding in dropdown

### ISSUE THREAD

**Issue by susanavr** [liferay/clay#5010]
## Is there an example you can provide via codesandbox.com?
No.

## Some context
Tango team was including icons in dropdowns and my dear frontenders had warned me that the padding of the dropdown panel is not the same in the Design System (which is 16px) and in the component (which is 20px from border to the icon).
According to this [technical documentation](https://docs.google.com/document/d/1eZkT4XZuA7KfxcgQUwdMdlJxfeUeKNtJ_gjFSQdPRTg/edit?usp=sharing) it should be 16px. I think it would be great to pair both design and development components.

## What are the steps to reproduce?
Anywhere where there is a dropdown, for example: 
1. Go to applications menu > Applications > Content Dashboard.
2. Hover over one table row.
3. Click on the ellipsis icon of one of the table rows.
4. The dropdown displays. 

## Actual result?
<img width="664" alt="front-end" src="https://user-images.githubusercontent.com/32902604/180989163-cfdc9b1d-5e5a-4fd5-89e6-0142e11f1603.png">

## What is the expected result?
<img width="579" alt="Captura de pantalla 2022-07-26 a las 12 54 35" src="https://user-images.githubusercontent.com/32902604/180989887-767fe425-d32d-463e-969f-af98d64a2971.png">

[The padding](http://g.recordit.co/7bRph5vzuo.gif)

## Environment
Master

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by pat270** [comment]
@susanavr thanks! We can change it to 16px.
