### ISSUE TITLE
Allow ClayTreeView user to customize drag and drop to forbid some drop actions

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#5011]
As we try to migrate some trees from the portal, we found an specific case where the drag and drop have to be limited because not all nodes can be children of other nodes. More context here: https://issues.liferay.com/browse/LPS-157740 

## What is your proposal?
For migrating this usage to the ClayTreeView it will be needed to decide if the drop action is valid or not. Not sure how we can do it, maybe a prop that receives the dragged item and the target drop and return false/true depending on the dragging being valid.

**Comment by victorg1991** [comment]
I believe this was not a requirement in the initial TreeView proposal. Pinging @liferay-lexicon since we probably need some designs here :)

**Comment by matuzalemsteles** [comment]
Hey @victorg1991 we can use the `onItemMove` API for this purpose, if we return a boolean we can avoid dropping the item on a specific node.

Maybe we just need some visual behavior to tell the user that the item can't be dropped on that node. Maybe we would have to create a specific API for that too, something like `onItemHover` that is called whenever the item is on a specific node so we could for example set the disabled state in advance before the item is dropped on the node, this is different of `onItemMove`.

**Comment by emiliano-cicero** [comment]
We've defined a Drag&Drop pattern from Lexicon but it's true that it doesn't cover error cases where the system could have invalid targets. From our part @matuzalemsteles I think we can extend that pattern if you create a ticket. 

In the meanwhile for the specific case, I believe it should be Echo to provide the solution for this tree view implementation. As always, we can help Echo's designers from the shadows as the dark knights we are. 😂

**Comment by carolrodmar** [comment]
Hi guys, let´s put this issue on hold for now. We have opened a ticket to test these behaviors before implementing anything. We will get back to you when we have results and actions to take :)

**Comment by matuzalemsteles** [comment]
@victorg1991 I see, ok. Hmm that might be an option too, I'm not sure you would have all the information to tell if an item can be `draggable` maybe in some cases yes where you don't need to know where the item is going, I think it's two good options to have. I'll work on it this week!

**Comment by sandrodw3** [comment]
ci:reopen
