### ISSUE TITLE
Dropdown lose the focusing order when it closes

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5022]
Dropdown focus is lost when you select a dropdown option by keyboard:

1- Go tot he dropdown menu by keyboard tabulation
https://clayui.com/docs/components/drop-down.html/#composing

2- Open the dropdown menu and navegate to an option, then press enter

3- Now you can pulse the tab key and see the focus on the browser url insted of the next element focusable

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work for this scenario I think the best option here would be to return the focus to the button what do you think? I think trying to focus on the next closest element will have to do a lot to figure it out and it might not be good enough yet. What do you think?
