### ISSUE TITLE
Do we need role="presentation" for not semantic elements like divs?

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5027]
Do we need role="presentation" for not semantic elements like divs? just asking :-D

<img width="659" alt="image" src="https://user-images.githubusercontent.com/7963804/183053317-f55e7fb8-3d8a-4ccb-b334-0d9b325640f1.png">

If we remove the `role=presentation` we have a `generic` wrapper:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/7963804/183053761-46e6ac25-e3eb-40f9-89bc-4155e21319a6.png">

But `generic` is not adding semantic meaning: https://developer.chrome.com/blog/full-accessibility-tree/#ignored-and-uninteresting-nodes.

If this is considered a beneficial, why don't we apply this pattern to the rest o divs?

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work I also think it doesn't really make sense i don't remember why I added it but I think we should add some action so the screen reader can read but i think in readers like JAWS or NVDA if the element is out of `role="menu"` it's very likely that it won't read and skip, so maybe we have to rethink that or the markup somehow or change the actions. Any idea?

**Comment by marcoscv-work** [comment]
I think we could just simplify the markup as much as possible and review the accessibility readability, probably we could looking for the use of `role=presentation` in testing or something and delimitate their use

**Comment by marcoscv-work** [comment]
Looks like we are not creating a task about this, probably implemented in another task?

**Comment by matuzalemsteles** [comment]
I think it still persists at least for the cases you cited, I think we can use this issue to change it in those cases.

**Comment by marcoscv-work** [comment]
_In order to close old questions/issues with a conclusion_:
- Cases will be added to each component when needed some role="presentation" adjustment
