### ISSUE TITLE
Update the visual states of the vertical navigation

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#5046]
## What is your proposal?
Update the current state of the vertical navigation. 
[Lexicon Ticket](https://issues.liferay.com/browse/DESIGN-4229)
[Figma Mockup](https://www.figma.com/file/kIcC5tvX6R78i79DcJCSXc/design-4229-correct-styles-for-vertical-navigation?node-id=2%3A1338)

## Why would adopting this proposal be beneficial?
The current state of the vertical navigation uses the $Primary color for the active text making it visually the same as a link and is confusing.
There is also an LPS bug that will be fixed: [LPS-160349](https://issues.liferay.com/browse/LPS-160349)

## What are the alternatives to this proposal?
This should be a quick win, any other alternative is not really beneficial.

**Comment by pat270** [comment]
This should be no problem.
