### ISSUE TITLE
New 24px Button + Rounded property

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#5081]
## What is your proposal?
Include a new 24px button size. To avoid breaking changes, this variant will be named XS Button since there is already a Regular (40px) and Small (32px), in the next major version it would be nice to have this size for the buttons renamed to: Small, Regular, and Large. 
We will also allow having a property for Rounded buttons. Ideally, we won't be providing a free border-radius but only allowing 2 styles:
- Smooth (Default of 4px, what we currently have)
- Rounded (fully rounded buttons) 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/27729173/189160267-b121a4b0-64af-4960-b10d-ca6b098d75d3.png">

**The rounded property should also be allowed for bigger buttons for consistency** 

## Why would adopting this proposal be beneficial?
We have a product team request from Echo and we've also analyzed the usage in portal finding another case from the Tango team, and more in general in Portal. Also, this is something that Dialect found missing in Lexicon/Clay buttons. 

## What are the alternatives to this proposal?
none

## More info
[Request from Echo ](https://issues.liferay.com/browse/DESIGN-4172)
[Documentation](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/2121269264/DESIGN-4172+New+24px+Button+Variant) (I'm still working on this but the specs and technical aspects are covered, I need to fill out the usage recommendations for designers).
[Figma file](https://www.figma.com/file/nTRgW4NlyqPJc2rtdmLNdg/design-4172-new-button-variant?node-id=65%3A3538)

**Comment by matuzalemsteles** [comment]
> in the next major version it would be nice to have this size for the buttons renamed to: Small, Regular, and Large.

It's makes sense to me, let's add this to the `BREAKING_CHANGE.md` document to track things that will change for the major version.
