### ISSUE TITLE
Improve ClayTreeView "load more" functionality

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#5096]
As we are migrating our trees in portal (in this case, specificly the Pages Tree in the product menu), we have found that the current "load more" functionality doesn't exactly fit our requirements. As far as I could see, it allows loading some item's children when expanding it. I think it's very useful, but it does not solve the case of having many items at the same level.

## What is your proposal?
In my opinion, the current "load more" works more like a "load children on expand". It would be great if we could display a certain number of items (for example 20), and then, with a "load more" button, load 20 more, and so on.

## Why would adopting this proposal be beneficial?
It would improve performance in cases in which you have many items at the same level, as you could load them little by little.

**Comment by matuzalemsteles** [comment]
hey @sandrodw3, this is interesting and it's a great resource for that, I think this is more of a functionality related to supporting data paginated like we just offered for `useResource` https://clayui.com/docs/components/data-provider.html#infinite-loading.

**Comment by sandrodw3** [comment]
Hey @matuzalemsteles! I'm attaching a video to show how we are doing it right now in our tree. We have a maximum of 20 children at the same level and when there's more than that, a "Load more results" button appears and 20 more items are requested to the server when clicking it.

In case you want to take a look at the logic, it's done in `liferay-portal/modules/apps/layout/layout-taglib/src/main/resources/META-INF/resources/layouts_tree`. Please tell me if you need any help or more detail on any specific point.


https://user-images.githubusercontent.com/2444936/190995032-50fcd97e-28f9-488d-bf2d-8607dc3f8fe0.mov

**Comment by matuzalemsteles** [comment]
@sandrodw3 oh thanks Sandro for sharing more details, I'll take a look at the code to understand how the data pagination system is working.

I think we could implement it the same way we did for `useResource`. I will study the possibilities and share.

**Comment by sandrodw3** [comment]
> @sandrodw3 oh thanks Sandro for sharing more details, I'll take a look at the code to understand how the data pagination system is working.
> 
> I think we could implement it the same way we did for `useResource`. I will study the possibilities and share.

Cool! Thanks a lot @matuzalemsteles 🥰
