### ISSUE TITLE
Update mobile icons

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#5107]
Hey guys, I'm here to request an update to 4 mobile icons, I updated the generic smartphone icon and 3 more related icons that use the smartphone element. 
Since this is an update there are no requests for naming or metaphors. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/27729173/191984480-879742b4-a1cb-4a38-b74e-d08903ac0848.png">

## Link the LEXI Jira Issue.
https://issues.liferay.com/browse/DESIGN-762

## Attach the SVG.
[mobile-icons.zip](https://github.com/liferay/clay/files/9647413/mobile-icons.zip)

**Comment by pat270** [comment]
@emiliano-cicero can we get the svgs centered in the viewbox? There are minor alignment issues in `mobile-device-rules`, `mobile-landscape`, and `mobile-portrait` icons. Hopefully this screenshot helps.

![viewbox](https://user-images.githubusercontent.com/788266/192044885-2ca0831b-2d9a-4b93-9e87-df074d805328.jpg)

**Comment by emiliano-cicero** [comment]
hey @pat270, that's weird, it never happened before! I'll try to fix that and upload the files again.

**Comment by emiliano-cicero** [comment]
hey @pat270, I've updated the description of this request with the new zip file. It should be ok but let me know if it doesn't work, thanks!

**Comment by pat270** [comment]
@emiliano-cicero Thanks for the update, these are good!
