### ISSUE TITLE
Title of Heading's color picker is not clear 

### ISSUE THREAD

**Issue by DiegoHu97** [liferay/clay#5155]
**Steps to reproduce:**
1. Add a Heading fragment into a content page
2. Navigate to the Styles panel of Heading fragment
3. Hover on the color pick icon of Background Color and Border Color
The title shown is not clear, It only represents numbers and the user may not know what it is.
<img width="287" alt="LPS-166043" src="https://user-images.githubusercontent.com/91208451/197566323-b8143f82-90ed-45e9-b496-4a5b897b3248.png">

## What is your proposal?
My proposal contains two things (choose one):

1. The first one, that the number that appears as a title, we add the symbol "#", because this way the user knows that it is an RGB colour.
2. Secondly, the title could contain the name of the field in question. For example, if the field is "Text", the title should be "Text Color", or if it is "Background", the title should be "Background Color".

## Why would adopting this proposal be beneficial?
This proposal allows us to give clarity to the user, as the numbers represented by the current title do not give us information and can be confusing for the user.

## What are the alternatives to this proposal?
I think that this is the best way we can raise the issue.

**Comment by pat270** [comment]
We can add the `#` symbol by default.

For 2, I think the best we can do is add a property that passes a custom title to the color swatch. The DXP teams would have to update their color picker uses. We can't predict how/where it will be used.
