### ISSUE TITLE
When focusing on elements with tooltip in sequence the alignment is not updated

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#5159]
This is happening in some scenarios in DXP, when there are several elements in sequence with tooltip. Watch the video below showing the example.

https://user-images.githubusercontent.com/13750819/197852285-0483250b-2eb2-48a9-9922-3732d0e75c77.mov

This is probably happening because the tooltip doesn't disappear, which resets the positioning and other properties, when it moves focus to another element it will just update the tooltip data, it doesn't change for example the `isOpen` state of the tooltip that calls `useEffect` to recalculate the positioning of the tooltip relative to the element.

**Comment by marcoscv-work** [comment]
Funny one :-P 

Thanks @matuzalemsteles for review the component in DXP
