### ISSUE TITLE
Tab panel get always focus to ensure you get into selected tab in next tabulation

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5163]
Tab panel get always next focus into the tab, in order to ensure you get into selected tab in next tabulation, and this is great when the tab does not contains focusable items but this is not always needed, if we are sure we will have focusable items inside the panel we could deactivate this extra big area focussed.

https://user-images.githubusercontent.com/7963804/198249233-dc2624d5-f604-49d0-8b45-8410a105c403.mov

Could we add this behaviour as component props?

# Whats the improvement here?

We could avoid the extra focus, extra no needed info and the heavy visual load:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/7963804/198250950-e5cb15d0-8f5e-44ce-8c2b-f41d135f49d3.png">

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work I think this makes sense, just tagging here @drakonux @emiliano-cicero to check this, I think it's good to add these types of behaviors later to the documentation, if you guys agree I'll be opening a ticket for the Lexicon.

**Comment by drakonux** [comment]
Yeah, @matuzalemsteles, please create the DESIGN ticket, and we will document it properly.
