### ISSUE TITLE
Vertical Bar: focus style bug inside the panel

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#5185]
With an external focus border, the result is that the sidebar has a focus that is hidden on top, and the right part goes off the container, probably because of the shadow. 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/27729173/200615254-3abaa14c-382e-4a3e-92ee-9858312f0c4a.png">

The vertical bar seems to also be customized to be buttons instead of our tabs, as a result the focus is a bit different than what it should be. 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/27729173/200615439-49154621-0220-4f1a-8d63-5a59348ab93b.png">

## Is there an example you can provide via codesandbox.com?
no

## What are the steps to reproduce?
1. Create a new page in portal
2. Open the page with the page editor to edit it 
3. tab inside the interface until you reach the vertical bar 
4. press Enter to access one of the options, it will focus the sidebar

## What is the expected result?
The focus border in this case should be set as inside of the container and not outside in order to fit the sidebar. 
The color of the focus should also be $primary-l1 instead of $primary.
The vertical bar should use tabs instead of buttons to provide a squared item as defined by Lexicon (with also an inner border to avoid hiding parts when focusing).

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/27729173/200615111-f56b8363-9dc2-40a5-8c83-933045974035.png">

Here's a [Figma](https://www.figma.com/file/i2GxPzLgF22A0VJE8kfSY2/vertical-bar-and-panel-focus-bug?node-id=1%3A2) mockup. 

## Environment
Master

| Tech  | Version |
| ----- | ------- |
| Clay  | v?.?.?  |
| React |         |

**Comment by pat270** [comment]
@emiliano-cicero I don't think this is a Clay issue. The page editor vertical bar is a custom implementation and doesn't conform to the markup provided by Clay (https://clayui.com/docs/components/vertical-bar.html).

**Comment by pat270** [comment]
I was going to close this one, but looks like we need to add some styles for focus around the sidebar.
