### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by zenorocha** [liferay/clay#520]
<img width="210" alt="screen shot 2018-02-06 at 2 40 44 pm" src="https://user-images.githubusercontent.com/398893/35888201-c0a4eb28-0b4b-11e8-85fa-66200049a583.png">

**Comment by matuzalemsteles** [comment]
hey @zenorocha, I'm closing this once already fixed. Thanks!

<img width="258" alt="screen shot 2018-09-04 at 16 05 34" src="https://user-images.githubusercontent.com/13750819/45052162-630bd600-b05c-11e8-80f3-b0a64a3e1cef.png">
