### ISSUE TITLE
Select Box selections are a bit difficult to distinguish 

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#5200]
Some users have been suggesting that the selections inside SelectBox are a little hard to see. Is it possible to change the contrast a little? Thanks for reading! 👋 

<img width="985" alt="Screen Shot 2022-11-15 at 9 23 17 AM" src="https://user-images.githubusercontent.com/14063502/201985465-0af2ecae-1952-4ec0-94e9-f262f68346b2.png">
<img width="988" alt="Screen Shot 2022-11-15 at 9 24 42 AM" src="https://user-images.githubusercontent.com/14063502/201985754-715d1369-45c5-4cc9-9b76-3d094d89d088.png">

**Comment by pat270** [comment]
I think we can change it to any color we want with some CSS hackery. We just need some colors from @liferay-lexicon.

**Comment by pat270** [comment]
Had a chat with Emiliano and this is what we will be changing it to:

> we can keep what we had, it should be Dark at 6% on hover
> then active Light-D2 for the box to have more contrast
> and the blue 004AD7 for selection
