### ISSUE TITLE
Add gap utility classes to Clay CSS

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/clay#5218]
[As discussed on Slack](https://app.slack.com/client/T03BTCQAJ/threads).

## What is your proposal?

Adding `gap-*`, `row-gap-*` and `column-gap-*` utility classes (similar to `m-*` and `p-*`). They should follow the same spacing values than our existing classes (`gap-0`, `gap-1`, etc.).

https://developer.mozilla.org/en-US/docs/Web/CSS/gap
https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap
https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap

## Why would adopting this proposal be beneficial?

When using flex layouts (and [grid, since it has a nice support](https://caniuse.com/css-grid)) you can use `gap` property to specify space between elements, instead of adding some margin to individual elements, converting this:

```
<div class="d-flex">
  <button class="mr-2" />
  <button class="mr-2" />
  <button />
</div>
```

into this:

```
<div class="d-flex gap-2">
  <button />
  <button />
  <button />
</div>
```

which is much more easy to write and read.

## What are the alternatives to this proposal?

This proposal is just an improvement to bring modern CSS to utility classes (and potentially adding grid too in the future).

We already have alternatives to that: most Clay components already add all needed spaces between elements, and using margins (with if statements in loops) just works.

**Comment by marcoscv-work** [comment]
I think it's a good idea and really useful for final user since is something common in for example some page editors, that's true that is something closer to CSS grid concept but we have what we have :-D

**Comment by pat270** [comment]
@p2kmgcl @marcoscv-work do we need gaps all the way up to 10? I feel like 5 (48px) should be the maximum.

**Comment by p2kmgcl** [comment]
> @p2kmgcl @marcoscv-work do we need gaps all the way up to 10? I feel like 5 (48px) should be the maximum.

I agree we might never use a gap greater than 5, we can add more steps if the future if someone finds a realistic use case :sweat_smile:
