### ISSUE TITLE
Pagination Items per page dropdown does not match with the actual items pagination type

### ISSUE THREAD

**Issue by pedro-oliveira446** [liferay/clay#5219]
https://clayui.com/docs/components/pagination-bar.html

In the Pagination bar component of clay, the selected item is always the first by default. Wouldn't the correct thing to do be to select the item that is currently on the page?

The following LPS was opened about this : [LPS-168099](https://issues.liferay.com/browse/LPS-168099)

Evidence : [ActualResult_Nov09_LPS-168099.mp4](https://issues.liferay.com/secure/attachment/476647/476647_ActualResult_Nov09_LPS-168099.mp4)

**Comment by matuzalemsteles** [comment]
Hey @pedro-oliveira446 this is not a selection it's just the focus that will jump to the first item of the element, this follows the accessibility recommendations of https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links.html.

This component does not specify the selected state within the Menu, it just reflects the button so far.

**Comment by pedro-oliveira446** [comment]
Got it @matuzalemsteles , thanks for the explanation.
