### ISSUE TITLE
Suggestions about accessibility warnings in Button with Icon

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5249]
## What is your question?

First of all, thank you very much for introducing accessibility warnings for the Button with Icon. It's very cool because thanks to this, quite a few warnings have been found on the portal.

I'm working on solving the warnings that exist in the page editor and I have noticed 2 things:

One of them is about the message that it's announce in the warning: 
`Button Accessibility: Component has only the Icon declared. Define an 'aria-label' or 'title' attribute (consult your design team) that labels the interactive button that screen readers can read.` 
It's understood that adding `aria-label` or `title`, the warning will disappear. But only the `aria-label` is taken into account in the code. Could it be modified to make it less confusing for the developer?

Another question that has arisen to me is, why is the `aria-labelledby` attribute not taken into account? Its purpose is the same as `aria-label`, the only thing that changes is that it can be used to reference another element. In fact, if an element has both attributes, the `aria-labeled` attribute will take precedence ([info here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby)). Do you think we could contemplate this attribute?

Again, thank you very much for this! 😄

**Comment by marcoscv-work** [comment]
Totally true for both cases, `aria-labelledby` can provide the same than `aria-label` and the error message can be improved, thanks @veroglez

**Comment by matuzalemsteles** [comment]
Thanks @veroglez, yeah for accessibility only `aria-label` is required for SRs but title can also be added will depend on each use case, I'll make it clearer in this message and add `aria-labelledby` as an alternative to label the element. Thanks for the feedback.

I'm going to convert this issue as an improvement so I can improve this.
