### ISSUE TITLE
@clayui/css: Bootstrap's spinner is broken due to property sorting

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5252]
We sort CSS properties.  `border-right-color` should be declared after `border`.

https://github.com/liferay/clay/blob/1c912cab8b751ef5adc133540e277b1248eb9e19/packages/clay-css/src/scss/components/_spinners.scss#L13-L14

**Comment by jotchon** [comment]
Sorry @pat270!  Thank you for fixing this!
