### ISSUE TITLE
Item table from a picklist is not responsive

### ISSUE THREAD

**Issue by vngoliveira** [liferay/clay#5254]
https://clayui.com/docs/components/table.html

Hello! This [LPS-170325](https://issues.liferay.com/browse/LPS-170325) is related to a problem with responsiveness, but talking with a colleague I notice it's a clay problem because other tables have the same problem. 

Evidence: [evidence](https://user-images.githubusercontent.com/92388363/208135529-2840f5cf-f866-4319-b4eb-693cb5f4eb47.mp4)

**Comment by pat270** [comment]
@vngoliveira I don't think this is related to Clay. Those tables look like it uses Frontend Dataset (FDS)? The source for that is located in DXP. It looks like the table column widths need to be updated on window resize.

**Comment by vngoliveira** [comment]
@pat270 It's in FDS. I will try to update this. 
Thank you for your help!

**Comment by pat270** [comment]
No problem, I'll close this issue for now. Feel free to re-open/file a new issue it if you find anything else.
