### ISSUE TITLE
Select input dropdown opens upward in system settings

### ISSUE THREAD

**Issue by vngoliveira** [liferay/clay#5277]
[LPS-165581](https://issues.liferay.com/browse/LPS-165581)

Hello! In this bug, the dropdown always opens upward, but we need that it opens downward too. I think it is a Clay bug like in this [LPS-146491](https://issues.liferay.com/browse/LPS-146491). Could you help me, please?

**Comment by pat270** [comment]
@vngoliveira I don't think this is a Clay issue. At https://github.com/liferay/liferay-portal/blob/b215d5fb258ea887fb51a1ffd510b9d68b9e8272/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Select/Select.es.js#L429, it's setting `alignmentPosition={0}`. According to https://clayui.com/docs/components/drop-down/api.html#dropdown.menu that would fix the menu to always be aligned top center.

**Comment by vngoliveira** [comment]
Thank you, @pat270!
