### ISSUE TITLE
Pagination: number of page can be a picker and improvement of its description

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5287]
https://storybook.clayui.com/?path=/story/design-system-components-paginationbar--default

<img width="302" alt="image" src="https://user-images.githubusercontent.com/7963804/211307610-4f8c013a-2d5d-4761-88ab-7592dff65b8e.png">

1. Could we use picker for this page selector instead of a dropdown?
It woudl make more sense.

2. Could we add aria-descriptionby and get the text of number of pages?
- For example, for this case screen reader would read
  - <img width="302" alt="image" src="https://user-images.githubusercontent.com/7963804/211307610-4f8c013a-2d5d-4761-88ab-7592dff65b8e.png">
  - <img width="424" alt="image" src="https://user-images.githubusercontent.com/7963804/211309025-4d5e4f6b-7993-4404-9782-9515b51e6293.png">
  - then:
  - <img width="424" alt="image" src="https://user-images.githubusercontent.com/7963804/211308171-1d6ef3f1-63de-4931-939c-f6c6ccc82a0b.png">

This last one for me is an improvment but is comming from a DXP issue:
https://issues.liferay.com/browse/LPS-168946

**Comment by matuzalemsteles** [comment]
Makes sense @marcoscv-work, I think this would be an improvement that makes sense for pagination.

**Comment by matuzalemsteles** [comment]
This issue is related to #5284.

**Comment by marcoscv-work** [comment]
@matuzalemsteles could you move forward the DXP issue when clay version get to DXP?
https://issues.liferay.com/browse/LPS-168946

**Comment by matuzalemsteles** [comment]
@marcoscv-work yes of course.

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work I think to resolve the ticket https://issues.liferay.com/browse/LPS-168946 we will need the help of Frontend Infra, the Pagination that is used on the page is the taglib of `liferay-ui:search-container` with YUI 😅
