### ISSUE TITLE
Custom checkbox not correctly contrast

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5289]
https://clayui.com/docs/components/checkbox/markup.html#css-custom

Custom checkbox not correctly contrast

![image](https://user-images.githubusercontent.com/7963804/211626122-4ad6a1c1-7788-4845-87c4-70a5a2da75ab.png)

<img width="737" alt="image" src="https://user-images.githubusercontent.com/7963804/211625586-c2883a4a-2c99-4966-9f3f-1dbefe2601d6.png">

Suggestion: Make the border darker

**Comment by pat270** [comment]
@marcoscv-work @emiliano-cicero can I move up the gray spectrum until it passes the contrast ratio check?

**Comment by marcoscv-work** [comment]
I think is a good idea, in that way @emiliano-cicero can be focused in another issues, thanks @pat270

**Comment by emiliano-cicero** [comment]
hey @pat270, yeah, we can use $Secondary, my concern about this is more the global impact for this change when applied to multiple elements such as the list or a table. 
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/27729173/211796434-5bcc605a-3083-425e-bc7c-67fdabc6d596.png">

Maybe we should start considering a setting for a high-contrast theme with all these, what do you think?

**Comment by pat270** [comment]
@emiliano-cicero we can adjust the checkbox borders by component if you like. If the checkbox is likely to be on top of an image or dark background we can default to the old border color?

> Maybe we should start considering a setting for a high-contrast theme with all these

I like this idea. I think once DXP has the infrastructure to easily find and apply themes, we can implement this.

**Comment by emiliano-cicero** [comment]
> @emiliano-cicero we can adjust the checkbox borders by component if you like. If the checkbox is likely to be on top of an image or dark background we can default to the old border color?

Nah don't worry about it, I don't think it's necessary to change for the card only. In the end, it will be more or less the same, is just the first impact on lists and tables that will be a bit hard visually, but it's required.

> I like this idea. I think once DXP has the infrastructure to easily find and apply themes, we can implement this.

Perfect!

**Comment by marcoscv-work** [comment]
High contrast theme sounds good! but finally it would be the default one :-P
