### ISSUE TITLE
Controlled VerticalBar: animation for panels don't work? 

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#5292]
## What is your question?
Before opening a bug, I prefer to ask a question in case I am doing something wrong. 

I am using a controlled VerticalBar component, but there is no animation when the active panel changes, and the div dissapears inmediatelly (because the [unmountOnExit](https://github.com/ambrinchaudhary/clay/blame/master/packages/clay-core/src/vertical-bar/Panel.tsx#L81) is set) 

https://user-images.githubusercontent.com/8373764/211804180-dae40955-fea6-4f0d-9b40-aa664cc729d6.mp4

This does not happen if I change it to uncrontrolled VerticalBar, but this is not an option in our case. 

Could there be an issue with the timeout parameter [here](https://github.com/ambrinchaudhary/clay/blame/master/packages/clay-core/src/vertical-bar/Panel.tsx#L79-L79)? I guess it is returning 0, because I do not see any of this classes in the dom element (but I see some of them if I make it uncontrolled)
```
                        classNames={{
				enter: 'c-slideout-transition c-slideout-transition-in',
				enterActive: 'c-slideout-show',
				enterDone: 'c-slideout-show',
				exit: 'c-slideout-transition c-slideout-transition-out',
			}}
```

Anyway, it would be great to be able to configure this timeout parameters. In our case in KB we need to set different animation durations (see [prototype](https://www.figma.com/proto/wbAfx5biJhZaIFuuK0PiA5/Improve-KB-navigation?page-id=0%3A1&node-id=96%3A85681&viewport=-65%2C-504%2C0.35&scaling=min-zoom&starting-point-node-id=79%3A81073&show-proto-sidebar=1)) and know this is not possible, so I must set KB animations same like the VerticalBar (`{enter: 300, exit: 200}` I guess) to not have strange movements

**Comment by pat270** [comment]
@ambrinchaudhary can I take a look at the code you have? I'm having a hard time replicating it.

**Comment by ambrinchaudhary** [comment]
@pat270 The code is in https://github.com/liferay/liferay-portal/blame/master/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/js/components/VerticalBar.js#L137, and if you want to test it in portal, you must enable `feature.flag.LPS-156421=true` and go to KB

**Comment by pat270** [comment]
@ambrinchaudhary I'll take a look. Thanks!

**Comment by matuzalemsteles** [comment]
I took a look at this and submit a PR that fixes this issue #5298

**Comment by ambrinchaudhary** [comment]
Thank you very much @matuzalemsteles!

**Comment by matuzalemsteles** [comment]
This PR just hasn't implemented the possibility to configure the duration of the animation because we need to change it via CSS using css variables or sass variables. I think the duration time should be the same for all teams, is there any reason why this time is different for your case?

**Comment by ambrinchaudhary** [comment]
> I think the duration time should be the same for all teams, is there any reason why this time is different for your case?

Yeah I agree with you, time should be the same whereever you use the component. I don't think there is a special reason to change it in our case, I guess our designer just took the current page editor as an example, but I don't think it is a big deal to use current verticalBar animation.

**Comment by matuzalemsteles** [comment]
Got it, anyway we can update the duration of the animation at any time if the Lexicon changes to reach everyone in a consensus, also this component should be updated soon by the Lexicon because the documents are out of date since it was created.
