### ISSUE TITLE
Add option to disable aria-current in navigation components

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#5307]
## What is your proposal?
My proposal is adding the possibility to disable `aria-current` attribute in navigation components, such as `ClayNavigationBar` and `ClayVerticalNav`. The reason is that sometimes, we have two different navigations in a page, for example we can have a `ClayNavigationBar` and then a `ClayVerticalNav`. As it's incorrect to have two `aria-current="page"` in the same page, it would be great to have the option of disabling it in one of the navigations.

## Why would adopting this proposal be beneficial?
Because we would have a way to avoid the problem of having two different `aria-current="page"`.

**Comment by marcoscv-work** [comment]
It makes sense, especially if it comes from a real LPS in DXP: 
https://issues.liferay.com/browse/LPS-168383
