### ISSUE TITLE
@clayui/navigation-bar: btn-unstyled and link-unstyled shouldn't be there

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5314]
There are extra classes on `nav-link` that shouldn't be there. The classes are `btn-unstyled` and `link-unstyled`. These classes have been there for a while so this might be a breaking change. If it's not that bad, we should try and remove these.

![navigation-bar-classes](https://user-images.githubusercontent.com/788266/213766106-dcb99f97-d372-421a-ae73-d3e1f6c3a7e2.jpg)

**Comment by matuzalemsteles** [comment]
I think if removing these classes doesn't cause any visual regression, we can dismiss it as a breaking change.
