### ISSUE TITLE
text-underline is gone

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5326]
Testing https://github.com/liferay/clay/pull/5288

I see that text-underline does nothing, after looking for that class, looks like is not anymore

**Comment by pat270** [comment]
@marcoscv-work I renamed it to `text-decoration-underline`. I feel like we had a discussion about the naming, but I don't remember the details exactly. I'll add `text-underline` back.

**Comment by marcoscv-work** [comment]
It is ok for me if it exist with another name, I think the confusion because in this table I read `text-underline`
https://github.com/liferay/clay/pull/5288

<img width="599" alt="image" src="https://user-images.githubusercontent.com/7963804/215218565-27a8cdb7-03f5-4cb3-a86d-a2fab9957a79.png">
