### ISSUE TITLE
`ClayAutocomplete` sometimes does not display `notFound` message

### ISSUE THREAD

**Issue by markocikos** [liferay/clay#5327]
## Is there an example you can provide?

You can see this bug in Clay storybook: https://storybook.clayui.com/?path=/story/design-system-components-autocomplete--default

https://user-images.githubusercontent.com/5435511/215126374-b16a2d79-dfff-4647-9e77-e20f31704fb3.mp4

## What are the steps to reproduce?

1. Make sure `messages` prop is set.
2. Make sure  `defaultItems` prop is not set.
3. Write something that will end up with no result.

## What is the expected result?

`No Results Found` message in dropdown menu, like in other storybook examples.

**Comment by matuzalemsteles** [comment]
Thanks @markocikos for reporting this, it must be because we're not adding the empty state when the content is static, but that won't be an issue when it's dynamic. I'll think of some ways to do this for static.

**Comment by matuzalemsteles** [comment]
Closing this issue, this has been fixed in the implementation of PR #5479.
