### ISSUE TITLE
tbar color contrast 

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5340]
https://storybook.clayui.com/?path=/story/design-system-components-managementtoolbar--default
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/7963804/216339247-e76f9902-c05d-441a-a9e9-e65f8e524eb5.png">

tbar contrast need to be adjusted:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/7963804/216339020-11b63463-422f-449c-81d5-f6c59af24067.png">

cc @emiliano-cicero 

Comming from a DXP Issue:
https://issues.liferay.com/browse/LPS-168144

**Comment by pat270** [comment]
@marcoscv-work The current colors for `subnav-tbar-primary` pass the contrast ratio test.

```
background-color: #b3cdff
color: #272833
```

The contrast ratio is 9.1. I think whatever they're using to test is picking the wrong color. We don't use `#6A536D` in Atlas.  The colors listed in the issue looks like the colors were picked from a screenshot.

**Comment by marcoscv-work** [comment]
Closed as not reproducible, thanks @pat270
