### ISSUE TITLE
ClayAlert: Secondary type does not have the proper color with cadmin

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5342]
I'm using `ClayAlert` with the new type `secondary` and when it's implemented inside of an element with the class `cadmin`, the styles are wrong.

<img width="500" alt="Screen Shot 2023-02-02 at 5 04 10 PM" src="https://user-images.githubusercontent.com/9701095/216379830-d63391b6-c21b-411d-9d84-8da0d87ba344.png">

According to the Clay example it should have the following styles:

```
background-color: #f7f8f9;
border-color: #d3d6e0;
color: #6b6c7e;
```
<img width="1000" alt="Screen Shot 2023-02-02 at 5 05 01 PM" src="https://user-images.githubusercontent.com/9701095/216379894-27c414c8-8909-4744-998e-8070a4873c68.png">

**Comment by pat270** [comment]
Thanks for this @veroglez !
