### ISSUE TITLE
Allow Resize in <VerticalBar.Panel> 

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/clay#5348]
## What is your proposal?

In portal we want to add the ability to resize the VerticalBar panel. Currently this is not possible as we cannot pass any other props to the `<VerticalBar.Panel>` component

## What are the alternatives to this proposal?
I think the quick way to allow this would be to add the posibility to pass at least `className` and `style` attributes in the  `<VerticalBar.Panel>`  component. 

The other option is to add this resize feature to the Clay component, which makes sense from my point of view.

**Comment by matuzalemsteles** [comment]
Hi @ambrinchaudhary thanks for creating an issue about this, I think for us to better understand if we can create an API that provides this OOTB could you provide your use cases? if you have a Figma it would be great.

**Comment by ambrinchaudhary** [comment]
Hi @matuzalemsteles, this is the story that describes the resize need in Knowledge Base, where we are using the VerticalBar ([LPS-156211](https://issues.liferay.com/browse/LPS-156211). There is a [Figma](https://www.figma.com/file/eYdALYoOnfl5ftxUjftLst/LPS-127216-Design%3A-research-modernization-of-knowledge-base?node-id=829%3A534455) linked. Basically, we want to add the same resize functionallity that we have on the Page Editor (although this is not a Clay VerticalBar)

**Comment by matuzalemsteles** [comment]
Hey @ambrinchaudhary I see, I think it would make sense to have this OOTB functionality, especially since we can implement accessibility as well.

cc @emiliano-cicero  @marcoscv-work what do you think?

**Comment by emiliano-cicero** [comment]
@matuzalemsteles I agree, this can be provided OOTB with the sidebar component. Resizing should be a valid option as long as there is an overflow of items horizontally.

**Comment by marcoscv-work** [comment]
We would need to provide rules to avoid collapsing the horizontal space, for example (I'm improvising) make one sidebar resizable only when we have screen more than 1280px, if we are using two sidebars we would need more than 1600px to make them resizable, etc.
