### ISSUE TITLE
`ClayAutocomplete` support for any HTML in dropdown items

### ISSUE THREAD

**Issue by markocikos** [liferay/clay#5351]
## What is your proposal?

Currently, dropdown items [must be plain text](https://github.com/liferay/clay/blob/master/packages/clay-autocomplete/src/Item.tsx#L14), `ReactText` to be precise.

Proposal is for `ClayAutocomplete` to support any HTML. For matching, we could use `element.innerText`, or something similar. I imagine wrapping of letters with `<strong>` might be tricky.

## Why would adopting this proposal be beneficial?

For our ongoing development in DXP, we would love to be able to have custom HTML in autocomplete dropdown. Something like this:
![screen](https://user-images.githubusercontent.com/5435511/216663031-4717b47c-56cd-4262-b247-eef9a3e9d463.png)

I am not sure if this is possible with current `ClayAutocomplete` API and implementation. I tried several hacks but ultimately failed.

/cc @ugeortiz

## What are the alternatives to this proposal?

Github has this kind of autocomplete behavior, when you search with `t` on repo `Code` page. You get an autocomplete dropdown with links. Within them, there is a `<marked-text>` element with text modifications. It may be that they don't have full HTML support, but require something like a special markup in item children HTML.

**Comment by matuzalemsteles** [comment]
Hey @markocikos, from what I understand you would want to have both, for example the value match and also add any other React element in the right component?

As an alternative now you use your custom component instead of the `<ClayAutocomplete.Item />` which adds its own markup, I think we can provide a component that can just handle the highlight of the corresponding text with the value typed in the input.

**Comment by ethib137** [comment]
Hey @markocikos, on a different note, the extra text you're adding currently does not meet [accessibility requirements for contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html). If you need some help picking colors that meet these accessibility requirements, let us know and we'll be happy to help. 😄

**Comment by ugeortiz** [comment]
Thanks @ethib137 that's my fault, totally true. We will fix it in the implementation.

**Comment by markocikos** [comment]
@matuzalemsteles 
 
 > you would want to have both, for example the value match and also add any other React element in the right component

Yes, I would like to match all text within HTML markup. 

It wouldn't be required for our case, but I could imagine even a more flexible API, where component would match only text within specially marked elements. So you could have, for example, two elements with business-relevant content, and one with descriptions that you don't want to match. Component prop could be something like a CSS class for elements with texts to match.

> As an alternative now you use your custom component instead of the <ClayAutocomplete.Item /> which adds its own markup, I think we can provide a component that can just handle the highlight of the corresponding text with the value typed in the input.

I could not make a custom component work, maybe I missed a way? This is what I tried:
- a `map`ped array of elements, a React fragment, or a single element. All of this breaks the autocomplete component.
- `defaultItems` and `{(item) => CustomComponent}`. This does not break component, we get a render of dropdown. Default items needs to be strings, which was awkward with multiple matching, but it's possible to concatenate matched in default item and split in item render. But, with this approach:
  - text highlighting does not work
  - selection of items prints `[object Object]` and similar in input, if there is anything more complex then a single element

**Comment by matuzalemsteles** [comment]
@markocikos I see, I think we can handle this by creating a new generic `<TextHighlight />` component that just handles text highlight that can be used anywhere.

To add custom HTML or any other element to the component you can use `DropDown.Item` in your render composition, the `Autocomplete.Item` component is basically a `DropDown.Item` with text highlighting.

```jsx
<Autocomplete
  aria-labelledby="clay-autocomplete-label-1"
  defaultItems={['one', 'two', 'three', 'four', 'five']}
  id="clay-autocomplete-1"
  messages={{
    loading: 'Loading...',
    notFound: 'No results found',
  }}
  placeholder="Enter a number from One to Five"
>
  {(item) => (
    <DropDown.Item key={item}>
      <Layout.ContentRow>
        <Text size={3}>{item}</Text>
      </Layout.ContentRow>
      <Layout.ContentRow>
        <Text size={2}>Description</Text>
      </Layout.ContentRow>
    </DropDown.Item>
  )}
</Autocomplete>
```

In my case, my custom item would look like this:

![Screen Shot 2023-02-07 at 3 47 01 PM](https://user-images.githubusercontent.com/13750819/217374082-0b0b052e-bb86-45b2-af3d-c2e0f248b561.png)

I'm going to use this issue to create the new `TextHighlight` component, it will be a component part of the `@clayui/core` package https://clayui.com/docs/components/text.html.

So considering my example above with the new component, you could compose it this way.

```jsx
<DropDown.Item key={item}>
  <Layout.ContentRow>
    <TextHighlight>{item}</TextHighlight>
  </Layout.ContentRow>
  <Layout.ContentRow>
    <Text size={2}>Description</Text>
  </Layout.ContentRow>
</DropDown.Item>
```

**Comment by matuzalemsteles** [comment]
Also looking now more at your image example, it seems to be more of a Picker component than an Autocomplete or a mix of the two 😅

**Comment by markocikos** [comment]
`</TextHighlight>` component looks great! :sparkles:
