### ISSUE TITLE
Adding an extra label to links when `target="_blank"` is present

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5355]
### And, what about add an optional icon to make more visual? (patter sometimes we follow in portal)

It could improve the experience and operate in a more predictable way.

[WCAG 2.1 - 3.2 Predictable](https://www.w3.org/TR/WCAG21/#predictable)
Make Web pages appear and operate in predictable ways.

**Comment by matuzalemsteles** [comment]
We can also add in ClayLink but to handle translation we will have to provide an API to configure message. I hope to be able to work on this soon to remove this technical limitation of Clay in dealing with translation, a way of trying to communicate with the Liferay languages #4784.

**Comment by marcoscv-work** [comment]
Thanks! please rename/close/or convert to task, feel free
