### ISSUE TITLE
IE: Tabbing through the document focuses SVG elements

### ISSUE THREAD

**Issue by pat270** [liferay/clay#536]
Clay SVG's need the attribute `focusable="false"`

**Comment by matuzalemsteles** [comment]
hey @pat270 `focusable="false"` is for all use cases? ClayIcon?

**Comment by pat270** [comment]
@matuzalemsteles, yes I think so. Anytime you would want it to be focusable, it would be wrapped in a button, anchor, or the element would have `tabindex="0"`. The only case I can think of (where you don't want `focusable="false"`) is if you bind a js user event directly to the svg.

**Comment by carloslancha** [comment]
Let's just add a param `focusable` to the state with default value `false`, just in case we need it to be `true` in some case ;)

**Comment by matuzalemsteles** [comment]
Thanks @pat270 for the clarifying!

@carloslancha, sound good.
