### ISSUE TITLE
TreeView: It has to be clicked twice to expand nodes with asynchronous request

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5367]
Hi guys! 

In the Echo team we have a bug related to the TreeView component (https://issues.liferay.com/browse/LPS-173559). The bug is the following: when we have many children, loaded asynchronously, and the parent is clicked to be opened, the children are loaded but the node is not expanded. You have to click a second time to expand the node. We were not sure if this was a problem with the TreeView or the component implementation.

I've done some research on the Storybook with the TreeView and it seems that it's also failing in the Clay component itself. I took the `AsyncLoad` example and added `expandedKeys` and `cursor` in the async request, this being the added code:
```
export const AsyncLoad = () => {
	const [expandedKeys, setExpandedKeys] = useState<Set<React.Key>>(
		new Set(['0'])
	);
	
	
	return (
	<TreeView
		defaultItems={ITEMS_DRIVE}
		expandedKeys={expandedKeys}
		nestedKey="children"
		onExpandedChange={(keys) => setExpandedKeys(keys)}
		onLoadMore={async (item, cursor: number = 1) => {
			// Delay to simulate loading of new data
			await new Promise((resolve) => {
				setTimeout(() => resolve(''), 1000);
			});

			const newCursor = cursor + 1;

			return {
				cursor: newCursor <= 3 ? newCursor : null,
				items: [
				{
					id: Math.random(),
					name: `${item.name} ${Math.random()}`,
				},
				{
					id: Math.random(),
					name: `${item.name} ${Math.random()}`,
				},
				{
					id: Math.random(),
					name: `${item.name} ${Math.random()}`,
				},
			]};
		}}
	>
		{(item) => (
			<TreeView.Item>
				<TreeView.ItemStack>
					<Icon symbol="folder" />
					{item.name}
				</TreeView.ItemStack>
				<TreeView.Group items={item.children}>
					{(item) => (
						<TreeView.Item expandable>
							<Icon symbol="folder" />
							{item.name}
						</TreeView.Item>
					)}
				</TreeView.Group>
			</TreeView.Item>
		)}
	</TreeView>
)};
```

https://user-images.githubusercontent.com/9701095/217831587-98c0604e-7e80-40fd-8168-e7fc39e518b6.mov

I don't know if this problem is something not contemplated or there is something that I'm doing wrong. Can you verify it?

Thanks in advance!

**Comment by matuzalemsteles** [comment]
Hey @veroglez Thanks for reporting this, I would say this is indeed a bug. I will convert this to a bug so we can fix this soon.
