### ISSUE TITLE
clayui.com: do we still using Popper.js?

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5393]
## Do we still using Popper.js?

https://github.com/liferay/clay/blob/master/clayui.com/content/docs/components/markup-application-bar.md?plain=1#L16-L18

**Comment by pat270** [comment]
On [clayui.com](https://clayui.com/docs/components/drop-down/markup.html#css-actions) the markup examples are relying on popper.js. We don't use it in DXP.

**Comment by marcoscv-work** [comment]
Thanks @pat270 !
Then I suppose we still using popper.js in clayui.com so in that case we can close this question! :-D
