### ISSUE TITLE
Vertical navigation and Navigation Bar - Mobile / 400% zoom version

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5397]
[Vertical Navigation](https://clayui.com/docs/components/vertical-nav.html)
[Navigation Bar](https://clayui.com/docs/components/navigation-bar.html)

In the past we decided to show the [vertical navigation](https://clayui.com/docs/components/navigation-bar.html) mobile version of the menu as a dropdown menu but actually is not a dropdown menu, it still being a navigation, here the **first issue**, users can misunderstand what is happening.
**The second one** is that the menu is positioning over the content and it can be overlapping content even when we get out of the menu (it is normal because was launched by a toggle button).

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7963804/221548950-dd0e4230-e007-44f5-84bf-8a30a13c468a.png">

Technically, in mobile/400%zoom, the whole menu is hidden and a button appears, the button is a toggle button with open/close state so when you open the menu the show/hide state does not depends on if the focus is in the menu or no, thats the reason we need to change the positioning absolute and set the width to 100%:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7963804/221549079-45f164f1-e23d-4358-a3ec-50a0c3028c5a.png">

Same solution for [Navigation bar](https://clayui.com/docs/components/navigation-bar.html) in mobile / 400% zoom version (it already has width 100%):
<img width="436" alt="image" src="https://user-images.githubusercontent.com/7963804/221549663-81944be0-681b-4543-b0d3-ee6331f7d616.png">

**Comment by pat270** [comment]
@marcoscv-work I'm not quite understanding what needs to be done here. You want the menus to be wider?

We can remove the max-width property on Vertical Navigation in mobile to increase the menu width, but Vertical Navigation and Navigation Bar are both limited by the parent container's width and padding-x.

**Comment by marcoscv-work** [comment]
> @marcoscv-work I'm not quite understanding what needs to be done here. You want the menus to be wider?
> 
> We can remove the max-width property on Vertical Navigation in mobile to increase the menu width, but Vertical Navigation and Navigation Bar are both limited by the parent container's width and padding-x.

@pat270 sorry for the delay.

Just some CSS changes. This menu doesn't need to be positioned absolutely, it needs to be positioned relative, and then use the full width available, so it doesn't overlap content when the menu is opened since those kinds of menus can stay open.

From this:
![image](https://user-images.githubusercontent.com/7963804/223086444-e9254af2-2bb0-4432-8103-d1c356a539fb.png)

To this:
![image](https://user-images.githubusercontent.com/7963804/223086501-8f94fa50-4a44-460f-a7bf-48121bcc3436.png)

(see how the content stop being overlapped and use all width)

Same solution for [Navigation bar](https://clayui.com/docs/components/navigation-bar.html) in mobile / 400% zoom version (it already has width 100%):

**Comment by pat270** [comment]
@marcoscv-work thanks for the images! It's more clear now.
