### ISSUE TITLE
Navbar vs Tabs - style update

### ISSUE THREAD

**Issue by emiliano-cicero** [liferay/clay#5398]
## What is your proposal?
Update the tabs to a different style in order to differentiate them from the Navbars (and also merge all the current Tabs styles into the new one). 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/27729173/221958044-d5061d11-2162-469c-9876-60e39c48136f.png">

More details in the [Confluence Page](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/2284388363/Tabs+vs+Navbar)

## Why would adopting this proposal be beneficial?
This change should increase affordance for the components, making it easier for the user to understand the differences between a navbar and a tab. 

## What are the alternatives to this proposal?
none

## Info
[Jira ticket](https://issues.liferay.com/browse/DESIGN-5044)
[Figma file](https://www.figma.com/file/SIjiYx5WXdh1WxaFXKLzhZ/Untitled?node-id=1%3A17836&t=1sUrSYoo8vKWNciS-1)
[Confluence page](https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/2284388363/Tabs+vs+Navbar)

**Comment by pat270** [comment]
There are some semantic issues with this. I checked DXP and it looks like most of the tabs that I could find in sidebar are using something close to tab markup. On Clay, we are using [navigation-bar in sidebar](https://clayui.com/docs/components/markup-sidebar.html#css-variation) so it collapses to fit on smaller screens.

Would it be better to have a tab style nav that works in both instead of limiting this style to `nav-tabs`?

**Comment by marcoscv-work** [comment]
Hey @pat270 changes are required for DXP:
https://issues.liferay.com/browse/LPS-168387

So we needed the DXP and clay tabs to look in the new format, if after applying the changes in clay you need a task to apply them in DXP you can use LPS-168387, if you consider teams are doing something bad with the component/styles, we can ask for fixing that part

The idea with this change (the documentation is not ready yet) is to have only this style for the tabs, we do not use the rest of the tabs style and we can eliminate them, so if we consider it a good option we can assign this new style as the default

**Comment by matuzalemsteles** [comment]
A doubt about that @emiliano-cicero @marcoscv-work  should we still support the old style? otherwise we can remove the old style and remove the APIs to change the component's style.

**Comment by marcoscv-work** [comment]
We don't need to support the old style, actually we only have one so if we can drop styles let's go to drop
