### ISSUE TITLE
Provide a public focusScope component

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#5409]
## What is your proposal?

Provide a public <FocusScope> component that can handle the following scenarios:

Everything inside FocusScope is part of the trap
```
<FocusScope trap loop>
    <Button 1>
    <Button 2>
    <Button 3>
    <Button 4>
</FocusScope>
```

Only part of the content inside FocusScope is part of the trap
```
<FocusScope trap loop>
    <Button 1>
    <FocusScope.Trap>
        <Button 2>
        <Button 3>
    </FocusScope.Trap>
    <Button 4>
</FocusScope>
```

## Why would adopting this proposal be beneficial?
Managing focus properly is key for accessibility and can be important to include in compositions of Clay components. 

## What are the alternatives to this proposal?
- We could encourage users to manually control focus when needed.
- We could create compositions as part of the Clay Library anytime a new composition of focus scope is needed.

Neither of these options feels ideal.

**Comment by veroglez** [comment]
Working on it! (waiting for access as a collaborator to assign it to me)
