### ISSUE TITLE
Add Flag of Cambodia

### ISSUE THREAD

**Issue by mrtonylim** [liferay/clay#5418]
Due to (https://issues.liferay.com/browse/DESIGN-5160)  We need to add flag of Cambodia. Could you add it to Clay? SVG will be added to this ticket when ready.

**Comment by emiliano-cicero** [comment]
Adding the zip with the SVG for this flag icon. 

[cambodian-flag.svg.zip](https://github.com/liferay/clay/files/10968461/cambodian-flag.svg.zip)

**Comment by mrtonylim** [comment]
Language Code "km-KH"  https://www.iso.org/obp/ui/#iso:code:3166:KH (flags-km-KH.svg)

**Comment by brianwulbern** [comment]
Do we need to wait for a Clay upgrade before the new flag png/svg is usable in liferay-portal?

**Comment by matuzalemsteles** [comment]
We need to add the icon to the clay-css package and later cut a release and add it to DXP. I must cut a release today to add the icons.

This so you can use it with the ClayIcon component or any other component that depends on it, just like in taglib.
