### ISSUE TITLE
Accessibility improvements for Card components

### ISSUE THREAD

**Issue by sandrodw3** [liferay/clay#5425]
## What is your proposal?
My proposal is to improve the API of card components, adding the possibility of specifying some attributes to improve accessibility.

Specifically, we would like to be able to specify:
- An `aria-label` for the Card title (in all Card variant components)
- A `title` for the sticker (in the variants that have it)

## Context
To give more context, this is our use case:

![image](https://user-images.githubusercontent.com/2444936/225858921-d5e5de39-41d6-423d-8be0-9be611055cc1.png)

The check sticker indicates that this item is marked as default, and we would like to show a tooltip announcing it when hovering the icon by specifying a `title` for it. At the same time, we would like to add an `aria-label` to the card title so it also announces the item is marked by default when someone is navigating through the content of the page with the screen reader.

## Why would adopting this proposal be beneficial?
We would improve the accessibility capabilites of Card components, providing more optiones to describe them.

Do you guys think this is something we could add?
Thank you!

**Comment by matuzalemsteles** [comment]
@sandrodw3 makes sense to me, we can add these properties.

**Comment by marcoscv-work** [comment]
We guys, Have you evaluated the use of `aria-selected` / `aria-current` ? Not tested but it could probably help to SR if the aria fit in card markup/roles

**Comment by matuzalemsteles** [comment]
@marcoscv-work Hmm interesting we can evaluate this, I think `aria-selected` would need to be inside an ARIA role group right? I think for that we would have to do something on the DXP side as well.

**Comment by sandrodw3** [comment]
Hey @matuzalemsteles, what do you think we would need to do on the DXP side? If I can help with something just let me know.

I think @marcoscv-work's idea is good, maybe we can add that for selectable cards, apart of the improvements I suggested 😄

Thanks guys!

**Comment by liferay-peds** [comment]
LPS ticket: [LPS-182244](https://issues.liferay.com/browse/LPS-182244)
