### ISSUE TITLE
Add polling_interval option to Charts

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#544]
Just an idea...

Following the development of allowing a url in https://github.com/liferay/clay/issues/526, we could also add later an `interval` or `pollingInterval` property so we could refetch and update the data every Xms to show realtime-like graphs 😉 

/cc @julien?

**Comment by julien** [comment]
@jbalsas definetly sounds like a good option to have for charts 👍

**Comment by julien** [comment]
Pull requested submitted to https://github.com/liferay/clay/pull/550
