### ISSUE TITLE
[Multi Step Nav] Create a New Error State

### ISSUE THREAD

**Issue by drakonux** [liferay/clay#5444]
## What is your proposal?
Due to [DESIGN-5143](https://issues.liferay.com/browse/DESIGN-5143) we would like to create a new state for the Step.

<img width="800" alt="Error State" src="https://user-images.githubusercontent.com/21216422/228770094-f003036d-5392-40f2-835e-8b3510ad1d1e.png">

## Why would adopting this proposal be beneficial?
We need to add a new Error state to allow users to give feedback when a problem or action is required. 

## What are the alternatives to this proposal?
Instead of creating a specific state for the Step, allowing users to customize the icon and background color via API provides a more flexible way of covering their cases (error, warning, others...) 

cc\ @ethib137 @liferay-lexicon

**Comment by marcoscv-work** [comment]
Please, if we can provide in the implementation example: tooltips to the steps and include one with an error message in the error step would be great

**Comment by matuzalemsteles** [comment]
Just a question about this, do we need to create something that allows to customize the indicator or just create an error variant?
