### ISSUE TITLE
Beta Button & Badge Variant

### ISSUE THREAD

**Issue by ethib137** [liferay/clay#5446]
In order to accommodate for the new [BETA Indicator](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2312110481/Identifying+BETA+Features+in+the+product) feature in Liferay, I propose that we create new variants of the button and badge components that will add the correct colors for a beta-button and a beta-badge. I don't think we need to create the BETA Indicator component in Clay. This can be a portal composition of Clay components. 

What do you all think, does that seam like a reasonable way to handle this feature?

I would expect Clay to provide two new classNames, one for buttons (.btn-beta) and one for badges (.badge-beta). The button styling will need to handle Default, Hover, and Active states. The badge styling will only have a default state since it has no interaction.

**Comment by pat270** [comment]
I think we can base this solely on `badge`. Badges can be anchors and buttons. We can create a `badge-inverse-info` variant and a `badge-lg` size?

**Comment by matuzalemsteles** [comment]
I think badge use cases is a link inside the badge https://clayui.com/docs/components/badge/markup.html#css-links-inside, but I think this should be just for the badge itself.

**Comment by pat270** [comment]
@matuzalemsteles I chatted with @ethib137 and we came to decide that we will add `btn-beta` and `badge-beta` variants. They will have no relation to each other, one is for interactive (btn-beta) and the other is a static indicator (badge-beta).
