### ISSUE TITLE
sheet-title can contain an "add button" right aligned

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#547]
Here an example with what lexicon needs by BS helpers (so we need to it in clay in a correct way): 
To consider, the button should be top aligned when title has more than one lin:

https://codepen.io/marcoscv/full/zRwbpQ

![image](https://user-images.githubusercontent.com/7963804/36094004-d1623402-0fec-11e8-86ab-9c044b0d2f68.png)

Approved by Lexicon ( @victorvalle )

**Comment by victorvalle** [comment]
[Related issue
](https://issues.liferay.com/browse/LEXI-273)
