### ISSUE TITLE
Dropdown inside the modal does not scroll properly

### ISSUE THREAD

**Issue by oliv-yu** [liferay/clay#5475]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/dry-wood-s8xly5

## What are the steps to reproduce?

1. In the code sandbox, open the Clay modal.
2. Click on "Click Me" to open the Clay dropdown.
3. Scroll down inside the modal with the dropdown still open.

## What is the expected result?
While the contents of the modal will scroll, it looks like the dropdown remains in the same place.

## More details
QA on Search team had filed this bug https://issues.liferay.com/browse/LPS-181781. The dropdown is part of the configuration of the searchbar settings, behind a feature flag. I wasn't sure if there was a solution for this other than on the Clay side? Please let me know if there's anything I can do, thank you!

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.92  |
| React | -- |

**Comment by oliv-yu** [comment]
@matuzalemsteles hi! Just wanted to ask about the progress on this issue? I noticed it gets added and removed to milestones 😅

**Comment by matuzalemsteles** [comment]
Hi @oliv-yu yeah, I'm working on it today, I didn't want to delay this week's release any longer so I just moved on to the next release.
