### ISSUE TITLE
empty-state component need to accept reduced-motion images and totally stop animations by using a non-animated version

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5477]
**How to fix / recommendation**:

- Add a new prop: `ReducedMotionImgSrc` (or similar name)
- If reduced-motion is activated use `ReducedMotionImgSrc` instead of `imgSrc`
  - If `ReducedMotionImgSrc` is not present dont show image.
- The same behavior if `c-prefers-reduced-motion` class is globally present

Related to:
https://github.com/liferay/clay/issues/5476

If we need examples for documentation we already have no-animated gif versions for the example we use in clayui.com:
https://raw.githubusercontent.com/liferay-peds/liferay-portal/6995a5ebc3d81edee7037fc4cb192bef7b4daf96/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/images/states/success_state_reduced_motion.gif

**Comment by matuzalemsteles** [comment]
I think it would be harder to do this with `c-prefers-reduced-motion` so it's better to have it working with the implementation that was done based on JS. #5468

**Comment by marcoscv-work** [comment]
> Just throwing out ideas, we can add an image utility class or a display class that will hide animated images and show unanimated images based on the `c-prefers-reduced-motion` class. The only downside would be that we would have to render two `img` tags.
> 
> ```
> <div class="c-empty-state c-empty-state-animation">
>     <div class="c-empty-state-image">
>         <div class="c-empty-state-aspect-ratio">
>             <img alt="Alternative Text" class="aspect-ratio-item aspect-ratio-item-fluid d-none-reduced-motion" src="/images/success_state.gif" title="Hello World!" style="" />
>             
>             <img alt="Alternative Text" class="aspect-ratio-item aspect-ratio-item-fluid d-block-reduced-motion" src="/images/success_state_unanimated.gif" title="Hello World!" style="" />
>         </div>
>     </div>
> </div>
> ```

Sounds good to me, then the responsibility will be on the developer side providing two images

**Comment by matuzalemsteles** [comment]
Good idea @pat270, seems better to go with this solution.

**Comment by marcoscv-work** [comment]
Then we just waiting for this solution to go ahead with: https://issues.liferay.com/browse/LPS-168263
