### ISSUE TITLE
Focus area in modals with center property includes more than just itself.

### ISSUE THREAD

**Issue by larissacribeiro** [liferay/clay#5493]
## Example in codesandbox.com
https://codesandbox.io/s/modal-focus-error-8sh4zl?file=/src/index.js

## Steps to reproduce

1. In the code sandbox, open the Clay modal.
2. Press enter.
3. See that the focus area includes more than just the modal.

## Expected result

- For the focus area to include just the modal.

**Comment by larissacribeiro** [comment]
@matuzalemsteles Yes, indeed! But the focus borders are bigger than the modal, and that just happens with centered modals, as you can see in the image bellow.
![image](https://user-images.githubusercontent.com/82094673/234719624-5cd440e5-84e5-493a-8328-14cdb33c379a.png)

if I remove the center property of the modal, then the focus is just around itself, and not bigger than it.
![image](https://user-images.githubusercontent.com/82094673/234719613-42dfe209-647c-411f-960f-0cf4cee97745.png)

is it still a expected behaviour?

**Comment by matuzalemsteles** [comment]
@larissacribeiro yeah this could be a bug for centralized. @pat270 what do you think? we could remove the outline or add the focus like we do the other elements, in theory we only want this for the SR but I think it's good to signal to the user that the focus has been moved too.

**Comment by marcoscv-work** [comment]
Yeah, is important to don't lose the focus effect

**Comment by ethib137** [comment]
This definitely looks like a bug... We probably need a way to make the modal container that receives focus stay the same size as the modal itself.

**Comment by pat270** [comment]
Can we move the focus and aria attributes to `modal-content` instead of `modal-dialog`?

**Comment by marcoscv-work** [comment]
From my side, if we move all of them, in theory it is possible

**Comment by matuzalemsteles** [comment]
I think it wouldn't be a problem to move all the ARIA attributes to `modal-content`, I'll do some tests and send a PR to make sure it doesn't break anything.
