### ISSUE TITLE
Can't Disable Clay Autocomplete

### ISSUE THREAD

**Issue by bnheise** [liferay/clay#5495]
## What are the steps to reproduce?
Use ClayAutocomplete.
Try to disable it.
Observe that you cannot.

## What is the expected result?
Any input should have the option to disable. Autocomplete does not provide it. This is a serious usability issue.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | all  |
| React |  all       |

**Comment by matuzalemsteles** [comment]
Hey @bnheise could you show an example of how you are using Autocomplete? I made this example in Codesandbox and I can see Autocomplete disabled https://codesandbox.io/s/quick-start-clay-finale-forked-9kjj42?file=/src/index.js, it is also possible to make the Input disabled if you are using the old composition version by adding the `disabled` property to the `Autocomplete.Input` component.

**Comment by liferay-peds** [comment]
Hey @bnheise , 

Thanks for opening this issue! If the question persist... Can you open a PTR or a bug with Clay component in LPS project? It will be a pleasure to help you with this problem :) 

For now, we'll close this issue, but feel free to re-open if necessary 😄

**Comment by liferay-peds** [comment]
@matuzalemsteles , can you please close this issue?
