### ISSUE TITLE
@clayui/table : Can we edit default "No data found" message

### ISSUE THREAD

**Issue by amberkamboj77** [liferay/clay#5497]
Right now, when no data do display, clay UI table shows this message 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/97463982/235587518-5544dea7-b648-4f99-8fe2-c191d62305b7.png">

**Comment by matuzalemsteles** [comment]
@amberkamboj77 I think this is related to the FDS which is not a Clay component but a composition of Clay components that is maintain in the DXP, I think you can clear this doubt on the Slack channel of the Frontend Infra team #t-dxp-frontend-infra that takes care of that component.
