### ISSUE TITLE
Modal doesn't allow for dynamically growing height.

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#5528]
[internal slack thread](https://liferay.slack.com/archives/C049XG98GQL/p1684154954349929)

The `scrollable` prop for the react component adds the `inline-scroller` class, but that caps the max height at 320px. Ideally there would be a way to dynamically grow the height of the modal and make it scrollable, either the modal content or the entire modal window. 

See below for what I imagine it to work like. I was able to achieve this by simply adding `overflow: scroll;` on the `modal` class. At first I don't have that style enabled and you can see the content get cut off, but then by adding overflow I am able to scroll the entire modal down

https://github.com/liferay/clay/assets/6843530/070ba451-4396-4fa9-960e-91bbefd12285

cc @pat270

**Comment by pat270** [comment]
@bryceosterhaus Sorry I took so long to look at this. If you don't set `scrollable` it should work like you expect. I was making the modal grow to the height of the browser window then having the `modal-body` scroll when it reached full height when I re-read this.

**Comment by bryceosterhaus** [comment]
In order to get it to work I had to add `overflow-auto` on ClayModal component
