### ISSUE TITLE
@clayui/css: Add utilities for globally set/disable text underline, letter spacing, truncating, focus borders

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5546]
https://issues.liferay.com/browse/LPS-178191

These are related to the accessibility menu. We need to:

- Show underline effect in all Links
- Reduce motion / animations
- Increased text spacing
- Disable / Enable Ellipsis texts
- Disable / Enable Focus double border style

**Comment by pat270** [comment]
@marcoscv-work how should we handle buttons that are links to other pages? Should they be underlined? This also applies to badges, cards, labels, multi step, etc

![anchor-buttons](https://github.com/liferay/clay/assets/788266/7a425d1e-d40e-46a3-ad8c-ba68fa77fa7d)

Should the icons be underlined?
![multistep](https://github.com/liferay/clay/assets/788266/32907515-c482-4f8b-9087-1572e0776ac6)

**Comment by marcoscv-work** [comment]
I think so, underline for all links! it's a way to simplify the visually message of "this thing is a link".
Of course we can review this pattern in a future when we get real feedback of users will use this option

**Comment by ethib137** [comment]
Focus Outline removed from the scope of this issue.
