### ISSUE TITLE
Add extra util classes for background colors

### ISSUE THREAD

**Issue by victorg1991** [liferay/clay#5568]
Currently, we have some background css classes like `bg-warning`, `bg-success` but there are other clay colors that are not included like `orange`

Would it be possible to include these classes? Currently I'm working on a story [figma](https://www.figma.com/file/gHUmoRO2cqYwBqu5k3X4EV/LPS-179532--Configure-which-fragments-are-automatically-mapped-to-form-containers?type=design&node-id=39-194214&t=j39pyc3z65N8EOvU-0) where I need to set the background of a sticker specifically to orange, and it seems a bit cumbersome to write custom css just for that

Thanks!

**Comment by pat270** [comment]
@victorg1991 we could add them. Are the colors you are looking for listed at https://liferay.design/lexicon/foundations/color/#chart-colors?

/cc @emiliano-cicero @drakonux

**Comment by victorg1991** [comment]
Yes :) The one I need is the `orange` one
