### ISSUE TITLE
@clayui/css: Cadmin `c-prefers-*` classes depend on `.cadmin`

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5581]
In cadmin, `.c-prefers-*` classes are qualified by the `.cadmin` class. This is not the way it was meant to be used. It shouldn't depend on `.cadmin`.

https://issues.liferay.com/browse/LPS-187861

**Comment by ethib137** [comment]
If this is the case, then is there any reason to the styles for `.c-prefers-*` to the normal themes. These would always be redundant since the c-admin styles are loaded on every page, right?

**Comment by pat270** [comment]
@ethib137 it wouldn't style the page for guest users since you need to be logged in for cadmin to be applied.

**Comment by ethib137** [comment]
Oh true! I keep forgetting that about cadmin. Thanks.
