### ISSUE TITLE
The dropdown keeps open after first tabbing

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5592]
Is this the expected behaviour?

https://github.com/liferay/clay/assets/7963804/7496e530-278a-41eb-963d-e6ff281beb3e

I was working with portal and I really feel this is a little bit weird, I think we should close the dropdown as soon as se move the focus out of the dropdown, after the first tabbing

**Comment by matuzalemsteles** [comment]
Hi @marcoscv-work I was a little confused with the behavior actually, you are saying that when clicking on the button to open the menu and pressing tab the focus goes back to the trigger, in this case we should close the menu, right?

**Comment by marcoscv-work** [comment]
I mean, when we open the dropdown the focus goes to the first item, that's perfect:
<img width="292" alt="image" src="https://github.com/liferay/clay/assets/7963804/91a81c14-609c-4ef3-b7bb-d285028a633d">

if then, we leave the dropdown by pressing tab key and the focus goes to the trigger button, the dropdown should close, now it still open until the next tab when you are leaving the trigger button:
<img width="300" alt="image" src="https://github.com/liferay/clay/assets/7963804/701aca54-83d3-483a-b126-a8560e93f5b3">

**Comment by marcoscv-work** [comment]
Probably is better if when we tab being in the dropdown, the focus goes directly to the next focusable element, not to the trigger (now it's like the focus is going back).
Example:
https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/

**Comment by matuzalemsteles** [comment]
Oh I see, it makes sense. I don't remember very well why we left this behavior when tabulating inside the menu the focus returns to the trigger, this behavior is different in components like Picker for example, it makes sense to follow this behavior. I will convert this issue as an improvement and I will use this issue to fix this.
