### ISSUE TITLE
Custom element for each item in Vertical Navigation component

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5596]
## What is your question?

We are implementing the Clay Vertical Navigation component in DXP by replacing the custom code of the portal, and there are certain examples where each element has an icon or label to its right (see the attached images).

<img width="200" alt="Screen Shot 2023-06-21 at 2 42 45 PM" src="https://github.com/liferay/clay/assets/9701095/4f0d80b1-4fc7-441c-9e3d-af4d82db7597">
<img width="200" alt="Screen Shot 2023-06-21 at 2 43 05 PM" src="https://github.com/liferay/clay/assets/9701095/f0ede076-5c74-4a00-93fa-e79bb8460fcb">
<img width="200" alt="Screen Shot 2023-06-21 at 2 46 27 PM" src="https://github.com/liferay/clay/assets/9701095/40c70f2f-2bc3-42c7-9b8a-5043d519c8fb">

Would it be possible to implement in the Vertical Navigation component that it receives a custom element so that it can be painted right after the item? 

Thanks in advance!

**Comment by pat270** [comment]
@veroglez I think we can add this. I suppose implementation is the issue. It would be nice if we could pass in custom markup to the link.

**Comment by matuzalemsteles** [comment]
Hi @veroglez, yes this is possible using composition based API allows you to render any element inside the item. Create an example in codesandbox showing more or less how you can use it to get to your example https://codesandbox.io/s/quick-start-clay-finale-forked-gkyhhj?file=/src/index.js.

**Comment by veroglez** [comment]
Perfect! thanks so much guys!

**Comment by pat270** [comment]
We can update the docs to clarify this feature.
