### ISSUE TITLE
Autocomplete's dropdown items shows not consistent behavior if the item's title actually include "+"

### ISSUE THREAD

**Issue by 000benniu** [liferay/clay#5597]
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/quick-start-clay-finale-forked-r3nr5p?file=/src/index.js

## What are the steps to reproduce?
1. Click the input box, input 2 to trigger the search.
2. Input backspace to delete the input number, trigger the full input list.

## What is the expected result?
The matched list shows same contexts as the full input options.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.91.0  |
| React |  v16.14 .0 |

## Capture
<img width="1455" alt="image" src="https://github.com/liferay/clay/assets/79882831/f6029d53-c080-4e44-a76f-7ade30ee0bf2">

**Comment by 000benniu** [comment]
This happens when we want use this function for a country code (+1, +55)

I think this related to this part of code.
https://github.com/liferay/clay/blob/d57531f0e7926ca84773fcb013d388726cde1a0e/packages/clay-autocomplete/src/Item.tsx#LL121C1-L121C1

**Comment by matuzalemsteles** [comment]
Hi @000benniu thanks for the report and for finding where the problem is.
