### ISSUE TITLE
Unable to access TreeView when items are updated

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5600]
Hi guys!

In DXP we are using the TreeView component for a category tree. In this case, the items in this tree are the results of the search input above. When the results change, the tree is updated. This is where the problem really comes, the `tabindex="0"` that the first element have is lost and it's impossible to reach it by keyboard navigation. An example of this case is shown in the following video.

https://github.com/liferay/clay/assets/9701095/4cf7268c-01e1-46f9-841c-e513d9a3745d

I have tried to do a similar simulation in Storybook, and the same thing happens. There is a button that removes the first element of the tree. When the first element has `tabindex=0` and is removed, the `tabindex` of the next element is not updated, therefore it's impossible to access the tree again (I share the video and code below).

https://github.com/liferay/clay/assets/9701095/1a79f58f-5f46-4082-8491-ff43157d0f5f

```
export const Test = () => {
	const items = [
		{
			id: 1,
			name: 'Animals',
		},
		{
			id: 2,
			name: 'Vegetables',
		},
		{
			id: 3,
			name: 'Minerals',
		},
		{
			id: 4,
			name: 'Plants',
		},
	];

	const [newItems, setNewItems] = useState(items);

	return (
		<>
			<Button
				onClick={() => {
					setNewItems(newItems.slice(1));
				}}
			>
				remove first category
			</Button>

			<TreeView
				items={newItems}
				selectionMode="single"
				showExpanderOnHover={false}
			>
				{(item) => (
					<TreeView.Item>
						<TreeView.ItemStack>
							<Icon
								symbol="categories"
							/>
							{item.name}
						</TreeView.ItemStack>
					</TreeView.Item>
				)}
			</TreeView>

			<Button displayType="link">other focusable element</Button>
		</>
	);
};

```

With this in mind, is it possible to recalculate the `tabindex` of the items when they are updated?

Thanks in advance!

**Comment by matuzalemsteles** [comment]
Hi @veroglez sorry for the delay in answering this, yes that would be possible. I'm going to convert this issue to a bug for I can use to fix.

**Comment by veroglez** [comment]
Thanks for checking this @matuzalemsteles!
