### ISSUE TITLE
TreeView: Actions do not open by Enter key with JAWS

### ISSUE THREAD

**Issue by veroglez** [liferay/clay#5628]
Hi guys!

Testing the TreeView component with JAWS it seems that there is a bug when opening the actions using the `enter` key, the dropdown doesn't open like the rest of the dropdowns. The focus returns to the main item. Could you take a look?

Thanks in advance!

https://github.com/liferay/clay/assets/9701095/8775e95c-fefe-4ae8-b688-21cdd48bbff4

cc: @marcoscv-work

**Comment by matuzalemsteles** [comment]
Hey @veroglez thank you for that. I think this is related to the same Drag and Drop bug, see my comment on this in the issue https://github.com/liferay/clay/issues/5385#issuecomment-1459188149.

JAWS has some rules to follow the exact behavior of the ARIA attribute which some things do not allow customizing or adding new behaviors that the ARIA attribute does not specify, this for example does not allow navigation via keyboard with Drag and Drop for example only if we migrate to use the ARIA `treegrid` attribute that would need to reimplement the component engine. I believe this behavior is related to this but I will investigate further.

**Comment by liferay-peds** [comment]
LPS Ticket: https://liferay.atlassian.net/browse/LPS-190180
