### ISSUE TITLE
@clayui/css Cadmin modal doesn't have overflow-y: auto

### ISSUE THREAD

**Issue by edalgrin** [liferay/clay#5639]
The `cadmin` CSS overrides the `.modal-open .modal { overflow-y: auto }` and the scrollbar is not shown

## No-cadmin behavior

![1](https://github.com/liferay/clay/assets/46778114/1627c6d7-befa-4c2e-a07b-c46c1966b64b)

## Cadmin behavior

![1a](https://github.com/liferay/clay/assets/46778114/28fdf7ac-aa95-458d-ac6e-6739bfb9d872)

## What are the steps to reproduce?

- Go to the https://clayui.com/docs/components/modal.html
- Add some content to make the Modal overflow
<img width="1440" alt="image" src="https://github.com/liferay/clay/assets/46778114/d9f0fed3-666a-4cc0-b429-88b5e410ab09">

- Open the modal
- Add `cadmin` class to the parent `<div>`

![1a](https://github.com/liferay/clay/assets/46778114/28fdf7ac-aa95-458d-ac6e-6739bfb9d872)

## What is the expected result?

- It's possible to scroll the page

**Comment by edalgrin** [comment]
Possible related bug https://github.com/liferay/clay/issues/5528

**Comment by pat270** [comment]
@edalgrin thanks for the Cadmin reference. I was stumped on why this was happening in DXP.
