### ISSUE TITLE
@clayui/modal Enable modal-dialog-scrollable

### ISSUE THREAD

**Issue by edalgrin** [liferay/clay#5643]
I'm not sure if this request is related to this old discussion https://github.com/liferay/clay/issues/4113 but after 2 years, it seems like we need this functionality again.

I'm working on a bug https://liferay.atlassian.net/browse/LPS-188817, that leads to a change in the ClayModal behavior.

We need to create a modal window (.modal-dialog) that uses all the space available in the viewport and set the content (.modal-body) to occupy the remain space between the modal-header and modal-footer, to have the buttons and the title always visible. 

<img width="1440" alt="image" src="https://github.com/liferay-frontend/liferay-portal/assets/46778114/de21adce-e47f-468c-96c4-e69bb27d9ce2">

We have something similar in ClayModal.Body API (`scrollable`) but it's limited to a fixed height. It was 120px and now is 350px so I was trying to add this new behavior in the DXP side with some CSS flex-box properties and it's doable. But I noticed we already have what we need in ClayCSS (more precisely in Bootstrap) but we cannot access it from the ClayModal API. The CSS class is called `.modal-dialog-scrollable` and it should be applied to the `.modal-dialog` and it works exactly how we need. https://getbootstrap.com/docs/5.3/components/modal/#scrolling-long-content

## What is your proposal?

- Add `scrollable` to the ClayModal component that add `.modal-dialog-scrollable` to the modal-dialog.
- Evaluate if keeping `scrollable` in the ClayModal.Body still makes sense.

## Why would adopting this proposal be beneficial?

- We need it.

## What are the alternatives to this proposal?

- Duplicate code we already have from ClayCss to DXP. https://github.com/liferay-frontend/liferay-portal/pull/3537

/cc @dsanz @ugeortiz

**Comment by pat270** [comment]
@edalgrin I might be misunderstanding the issue, but we have `size="full-screen"`. It will make it expand to the edges of the viewport and the body will have a scrollbar if content overflows. It looks like the screenshot:

![modal-full-screen](https://github.com/liferay/clay/assets/788266/575b3aa5-87c4-43bb-9a83-d4c6f37ccf49)

**Comment by edalgrin** [comment]
Hey @pat270 , yes I think it's very similar to that but I'm not sure it's what we need. @ugeortiz?

**Comment by dsanz** [comment]
Ideally, we'd like to be able to have scrollable behavior in modals not rendered full-screen. DXP use case for this is the data set field mapping modal, where user needs to go through a potentially long list of fields and select which ones wants to map. As opposed to other scrollable modals such as permissions, this list is not wide enough to be rendered full width

**Comment by pat270** [comment]
@dsanz @edalgrin we also have the class `modal-height-full`. You can set the width via `size="md"` and add the `className` to `ClayModal`. It would look something like:
```
<ClayModal
    className="modal-height-full"
    size="md"
>
```

One thing I noticed is we're not adding `overflow: auto` for `modal-height-full`. I can add it through this issue.

**Comment by edalgrin** [comment]
Hey @pat270 yeah I tried also that one, and we talked about it, the problem with it is the height doesn't have to be **always** full, if the body content is short, the height must be short as well.

In any case, taking a look at the ClayModal component code, I noticed I can use either the `size` or the `status` to set a custom class in the modal-dialog, in our case `modal-dialog-scrollable` which is working but it feels like a "wrong" workaround.

<img width="720" alt="image" src="https://github.com/liferay/clay/assets/46778114/981f4098-d0f9-46a9-ad72-4f8a5cf06f05">
<img width="1440" alt="image" src="https://github.com/liferay/clay/assets/46778114/d6b11302-3201-41f8-ab27-7ffd124d5ea7">

**Comment by matuzalemsteles** [comment]
@edalgrin We have the `inline-scroller` which can be configured in `Modal.Body` the `scrollable` property, wouldn't that be enough?

```jsx
<ClayModal observer={observer}>
  <ClayModal.Header>Documents</ClayModal.Header>
  <ClayModal.Body scrollable>
    <p>Do you want to save your documents?</p>
  </ClayModal.Body>
  <ClayModal.Footer
    last={
      <ClayButton.Group spaced>
        <ClayButton
          displayType="secondary"
          onClick={() => onOpenChange(false)}
        >
          Cancel
        </ClayButton>
        <ClayButton onClick={() => onOpenChange(false)}>
          Save changes
        </ClayButton>
      </ClayButton.Group>
    }
  />
</ClayModal>
```

In theory the footer and header should not be included within a scroll just its content. Is there any specific reason for this?

**Comment by edalgrin** [comment]
Hey guys, I'm not sure this fix is working because I don't have DXP updated and in the Clayui website is not working either, but from the code https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/variables/_modals.scss#L284 it looks like the modal will always take the viewport height available as its height, which is not the required behavior.

If the content inside the modal-body is a few lines, the modal should be shorter:
<img width="1440" alt="image" src="https://github.com/liferay/clay/assets/46778114/5eb9fbcc-5a2a-46ec-a86e-2d3dd33d3d23">
if the content is several lines, the modal-body will expand until it reaches the viewport height and then the scroll inside of it will start working
<img width="1439" alt="image" src="https://github.com/liferay/clay/assets/46778114/f8a9c2a7-001e-476d-b266-7ed1059789ae">

**Comment by edalgrin** [comment]
Actually, it does! I'm going to test it on our ticket, thanks!
