### ISSUE TITLE
Additional notes in the getting started section

### ISSUE THREAD

**Issue by jpcchaves** [liferay/clay#5697]
Hello! I'm a new hire at Liferay, and I recently completed the basic Liferay training, where I had to use Clay to create a React application with Clay.

Since I have more experience in React and frontend development than my fellow new hires, it was relatively easy for me to resolve the issues that arose in the "Getting Started" section.

I'm wondering if I can contribute to Clay's documentation by adding two notes in the "Getting Started" section, where the most issues occurred. These notes would be as follows in the how-to-use-clay.md file:

```
> **_Important Note: Be Mindful of the Asterisk:_**
> When using the `@clayui/*` command for installation, it's crucial to remember that the asterisk (*) is a placeholder. It's not a valid package name on its own. To install a specific Clay package, you must replace the asterisk with the name of the package you require.
>
> For instance, if you want to install the "Clay Button" package, the correct command would be:
> 
> ```shell
> npm install @clayui/button or yarn add @clayui/button
```

```
<div class="clay-site-alert alert alert-warning">
	<strong class="lead">Warning</strong>
	To ensure that Clay functions correctly, please remember to import the CSS package from @clayui/css into your React entrypoint component, as demonstrated in the example below.
</div>
```

**Comment by matuzalemsteles** [comment]
Hey @jpcchaves We are using Jira for tickets right now so the bot is automatically closing issues but feel free to contribute and we support that, it would be a good addition.
