### ISSUE TITLE
Unable to select pages from the ellipsis dropdown in Clay Pagination

### ISSUE THREAD

**Issue by Dominik-Jurt** [liferay/clay#5723]
There seems to be a problem with the ellipsis of the Clay pagination component. When clicking on the ellipsis, the dropdown with all available pages opens however nothing happens after clicking on a page number. The onActiveChange property is not triggered in this case.

## What are the steps to reproduce?

    - Include the @clayui/pagination component in your project.
    - Set up a Clay Pagination component with a sufficient number of pages to trigger the ellipsis.
    - Open the dropdown by clicking on the ellipsis.
    - Attempt to click on any page number within the dropdown.
    
Code examples can be found on https://clayui.com/docs/components/pagination.html or this issue can be directly tested on https://storybook.clayui.com/?path=/story/design-system-components-paginationbar--with-items&args=ellipsisBuffer:2;totalItems:2110

## What is the expected result?

When using the Clay Pagination component and clicking on the ellipsis to open the dropdown with additional pages, the dropdown opens correctly. However, upon clicking on the individual page numbers within the dropdown, nothing happens. The active page does not change.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.106.1  |
| React |  18.2.0  |

**Comment by ethib137** [comment]
Hey @Dominik-Jurt thanks so much for reporting this. I created a new ticket for it in our Jira instance [here](https://liferay.atlassian.net/browse/LPS-202099).
