### ISSUE TITLE
Onclick not happening on Pagination ellispsis drop-down 

### ISSUE THREAD

**Issue by Abineshk** [liferay/clay#5724]
Onclick is not happening on Pagination ellispsis drop-down

Onclick of any item in drop-down the page doesn't change

## What are the steps to reproduce?
Use ClayPaginationBarWithBasicItems to create pagination bar.
Make more pages to create ellipsis drop-down. 
Try to click on any item on inside drop-down the page doesn't change.

## What is the expected result?
Ellispsis drop-down click should change the page in pagination bar

## Environment
Both local and production is not working 

Latest version of clay.

I have identified the issue check Item.tsx file in @clayui/core under node_modules of clay-pagination. It is not having onclick in the As type component

**Comment by ethib137** [comment]
Hi @Abineshk , thanks for reporting this. It looks like this is the same issue that was [described here](https://github.com/liferay/clay/issues/5723), so we created [this ticket](https://liferay.atlassian.net/browse/LPS-202099) for it.
