### ISSUE TITLE
Test throwing exceptions

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#579]
In our components there're some params that are required. In those cases if the param is not passed the component throws an exception.

If we test that like in https://github.com/metal/metal-clay-components/blob/master/packages/clay-alert/src/__tests__/ClayAlert.js#L207 tests passes but in console appears the expected error.

Should we test those cases? If yes, we have to update all our tests with this and find out a way to hide those errors from the logs (like stubbing console.error). If not, we need to remove those tests from ClayAlert and ClayNavbar.

**Comment by julien** [comment]
Hey @carloslancha,

I'm not sure how we want to do that but maybe we could use something like 

```javascript
global.console = {
	error: jest.fn(),
	warn: jest.fn(),
};
```

And include it in our tests when needed.
