### ISSUE TITLE
When Modal opens the focus goes to the title

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/clay#5840]
There is a new example patter on WCAG 2.2:
https://www.w3.org/WAI/WCAG22/Techniques/html/H102

Example 1: A dialog to sign up to a mailing list
"In this example the h1 element will receive focus because it has a tabindex="-1" attribute"

I think it will probably fit well with clay modal since we had some reports from some browsers and SR combination where user has not a correct read, moving the focus to the heading the SR will read the title correctly for sure.

**Comment by ethib137** [comment]
Thanks @marcoscv-work ! This makes to me. Did you open an LPD ticket for this?

**Comment by marcoscv-work** [comment]
https://liferay.atlassian.net/browse/LPD-31019
