### ISSUE TITLE
Getting started section of the website

### ISSUE THREAD

**Issue by azzazzel** [liferay/clay#604]
Hi team,

I love the new website and especially the components library and the SOY /  WEB COMPONENTS / HTML snippets. It really makes me want to start playing with it. 

And here is the issue - there is nothing that tells me how to actually start using Clay. The "Get started" link  answers the what and why but it does not really help start a project with it or start using it in existing project. I think you should invest in real get started page that explains (ideally for all SOY /  WEB COMPONENTS / HTML case) how to start a new project and how to start using Clay in existing projects. That is, what to download, what build tools can be used, what to configure, what imports need to go where, ...

**Comment by carloslancha** [comment]
Hey Milen!

Yep, for sure we need to invest in that. I think when we have ready a couple more of pieces, like the CDN and distributable files we will start working seriously on this kind of doc. Thanks a lot for the feedback!

Meanwhile if you need help setting up a project just let us know your requirements and we will gladly try to help you 😄

**Comment by ChrisLynch42** [comment]
Having the same issue.  I added the css link and script tag and the results do not look like your component examples.  I can make it work by not including clay.js and including bootstrap though.  I have attached a couple of examples.
[index-not-work.html.txt](https://github.com/liferay/clay/files/2064975/index-not-work.html.txt)
[index-work.html.txt](https://github.com/liferay/clay/files/2064976/index-work.html.txt)

**Comment by matuzalemsteles** [comment]
hey guys, I think we can close this. We have a [Getting started](https://clayui.com/docs/getting-started/introduction.html) session now available.

**Comment by jbalsas** [comment]
Agreed, closing! 👍
