### ISSUE TITLE
ClayImageCard needs to add and remove active class on check

### ISSUE THREAD

**Issue by pat270** [liferay/clay#649]
Since the Lexicon team moved the clickable area to the image, we need to add and remove the `active` on check.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@pat270, @matuzalemsteles, please reopen in the context of our `3.x` components if still relevant!

Thanks!
