### ISSUE TITLE
Add consistency in events

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#668]
We need to return the result of the emits to provide the option of preventing it

**Comment by 4lejandrito** [comment]
Hi :)

I want to do this:

```javascript
Liferay.componentReady(
  '<%= randomNamespace + "socialBookmarksDropdown" %>'
).then(
  dropDown => {
    dropDown.on('itemClicked', event => {
      event.preventDefault();
    });
  }
);
```

But I can't because event is a plain object:
```javascript
{
  active: false,
  disabled: false,
  href: "the href of my link",
  label: "the label of my link"
}
```

I'll have to use a dirty workaround setting a javascript href for the moment.

**Comment by 4lejandrito** [comment]
https://github.com/liferay/clay/pull/695?

**Comment by carloslancha** [comment]
Working on this, thx for letting us know your case!

**Comment by diegonvs** [comment]
This issue was resolved?

**Comment by carloslancha** [comment]
Yep ;)
