### ISSUE TITLE
Change claycss.com to clayui.com

### ISSUE THREAD

**Issue by zenorocha** [liferay/clay#671]
https://github.com/liferay/clay/tree/master/packages/claycss.com
https://github.com/liferay/clay/search?utf8=%E2%9C%93&q=claycss.com&type=

**Comment by yuchi** [comment]
Please keep redirects from the previous domains.

**Comment by zenorocha** [comment]
Yep, working on it ;)

**Comment by yuchi** [comment]
😘

**Comment by zenorocha** [comment]
Redirects in place.
