### ISSUE TITLE
Watch script doesn't working on clayui.com

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#696]
Hey guys, when i tried execute `npm run watch` script to make a modification on clay website, i get that error: 
<img width="668" alt="screen shot 2018-03-05 at 13 49 05" src="https://user-images.githubusercontent.com/7663513/36988022-7f2d4ef6-207c-11e8-9c21-f31690743d9b.png">

I noticed that `icons` path on `electric.config.js` it's wrong for current clay css implementation. I've done the modification and i've got the same error: 
<img width="677" alt="screen shot 2018-03-05 at 13 49 41" src="https://user-images.githubusercontent.com/7663513/36988256-34a2a1c8-207d-11e8-9f08-df839a6a59d6.png">

I've deleted `claycss.json` and performed `npm run config` to configure default path for clay css.

**Comment by diegonvs** [comment]
@jbalsas @matuzalemsteles

**Comment by carloslancha** [comment]
Hey @diegonvs running `npm run web` from the root folder should automatically runs the watch on clayui.com

**Comment by diegonvs** [comment]
Hey @carloslancha still doesn't working for me and @matuzalemsteles
