### ISSUE TITLE
Card stickers are not rounded

### ISSUE THREAD

**Issue by julien** [liferay/clay#718]
Hi,

It seems that the stickers in cards are not "rounded".

Here's a screenshot when integrating the new `UserCard` in portal.

<img width="210" alt="clay_user_card_new" src="https://user-images.githubusercontent.com/5572/37330879-b3fa08b4-26a2-11e8-933a-d5de8eb38c0c.png">

**Comment by matuzalemsteles** [comment]
hey @julien, I'm closing this once this has been fixed that in https://github.com/liferay/clay/pull/724

**Comment by julien** [comment]
Thanks @matuzalemsteles yes this was solved at while ago ;)
