### ISSUE TITLE
ClaySticker must accept any style value

### ISSUE THREAD

**Issue by julien** [liferay/clay#721]
At the moment `ClaySticker` [only accepts a list of defined styles](https://github.com/liferay/clay/blob/develop/packages/clay-sticker/src/ClaySticker.js#L135-L145) and it should accept any value.

**Comment by matuzalemsteles** [comment]
Hey guys, are we still in need of this?

**Comment by diegonvs** [comment]
Closing due inactivity, don't hesitate to open when having a question.
