### ISSUE TITLE
Reorganize clay-css and clay npm packages

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#837]
In order to fully leverage cdns like https://unpkg.com/ or https://www.jsdelivr.com/, we need to have a nice npm package published.

There's still some confusion with the current `clay` package, as it pretty much brings only css.

For these reasons, I'm proposing:
- Rename `clay` to `clay-css`
- Create a `clay` package that exposes the compiled css and js bundling all components and resources

Unless someone heavily disagrees, I'll send a PR with these changes later ;)

/cc @matuzalemsteles, @julien, @carloslancha, @pat270 

Fair warning, @bryceosterhaus, @mthadley, as this might affect you... what are you currently using and how?

**Comment by julien** [comment]
@jbalsas I'm totally OK with that proposition.

**Comment by mthadley** [comment]
We are bundling the CSS from the current `clay` package. More specifically, we are depending on the `includePaths` export from the package, and passing that to `sass-loader`.

So for us, this would be a breaking change, and we would need to instead depend on this new `clay-css` package. Thankfully, this seems like it wouldn't be much trouble for us to fix.

**Comment by jbalsas** [comment]
Would it might make sense for this `clay` distributable package to include sources... specially `scss` and `ES+` which could be rebundled from the different individual packages, or is it better to assume the breaking change? 

After all, you won't be needing the rest of things in there...

**Comment by mthadley** [comment]
I don't think the breaking change is a big deal for us. Also, it should lead to a more cleanly organized set of packages, right?

**Comment by jbalsas** [comment]
That's what I think, yeah... we will have:
- `clay` -> For distribution purposes only and usage through cdn
- `clay-css` -> CSS framework and implementation
- `clay-*` -> UI components (js + soy + webcomponents)

Does that make sense? Is there any other way this would be more easily understandable?

**Comment by jbalsas** [comment]
This has been done and published as `rc.12` to verify. @mthadley, can you guys check if switching to `clay-css` keeps working the same way for you?

Thanks!
