### ISSUE TITLE
clay-css `.close` utility default height and width

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#857]
I noticed that for [`.close`](https://github.com/liferay/clay/blob/b72c30ca7dfd48ce00c4af0b236e37ae39cf61c8/packages/clay-css/src/scss/variables/_utilities.scss#L14) we set a default height and width. Is this intentional? It is causing issues for us when creating the tags input list seen [here](http://pat270.github.io/lexicon/content/form-elements-input-groups/#form-control-tag-group-with-contenteditable-elements)

The `.close` class is distorting the padding and making it look like 
![screen shot 2018-04-26 at 3 30 26 pm](https://user-images.githubusercontent.com/6843530/39335175-c79c13c6-4966-11e8-8f41-95d3c9ab9b3d.png)

**Comment by mthadley** [comment]
@bryceosterhaus Does this specifically happening when rendering the tags input inside of a modal?

**Comment by pat270** [comment]
@bryceosterhaus @mthadley I ended up adding alternative markup for close buttons at https://github.com/liferay/clay/issues/777. The issue should be fixed if you update to v2.0.0-rc.12 and use the `label-item` pattern.

**Comment by mthadley** [comment]
Thanks @pat270!

@bryceosterhaus Since you are updating to the new `clay-css` anyways, can you see if that fixes it?

**Comment by bryceosterhaus** [comment]
Got it working with latest clay
