### ISSUE TITLE
Icon Button needs to show a tooltip on hover

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#858]
Button icon needs to have a tooltip to specify the action. It was not documented but we didn't expect it to be removed, sorry.

**Comment by carloslancha** [comment]
What button icon? Where? Do we have docs for this? Thx

**Comment by victorvalle** [comment]
[Here](https://docs.google.com/document/d/11tjPCtfBql9sOXWP711rTLNn1-WQyG1t5JBJuCwRHgU/edit?usp=sharing)

**Comment by matuzalemsteles** [comment]
hey @carloslancha the `ClayTooltip` solves this? we can close this issue.

**Comment by carloslancha** [comment]
Yep, closing
