### ISSUE TITLE
Management Toolbar Sorting button appears enabled when toolbar is disabled

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#869]
The asc / desc order button is enabled however there is no element to order yet.
See [State 1: Disabled](https://docs.google.com/document/d/1y67UAnbUzL5WLAkPMQbkqgGw3_5e7-JMEPVYdC48qE0/edit?usp=sharing)

Wrong:
<img width="1114" alt="screen shot 2018-05-04 at 10 23 09" src="https://user-images.githubusercontent.com/21121115/39620988-641aee6c-4f8d-11e8-82aa-07b5cefcae58.png">

**Comment by carloslancha** [comment]
This is not a clay issue but a portal one, it's working fine out of portal.

![image](https://user-images.githubusercontent.com/5803434/39624121-670491ea-4f98-11e8-9376-d2a38f6e8e3a.png)

**Comment by victorvalle** [comment]
@carloslancha is it a team bug or a frontend infra bug?

**Comment by carloslancha** [comment]
@victorvalle not sure, you can open a jira ticket to us to review it

**Comment by carloslancha** [comment]
Hold on @victorvalle I'm taking a look to be sure about this

**Comment by carloslancha** [comment]
Referenced pr should fix this.
