### ISSUE TITLE
Mangagement toolbar: search field disabled state

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#870]
The search box is disabled however it looks like is enabled. 

The placeholder must appear in disabled color

See [State 1: Disabled](https://docs.google.com/document/d/1y67UAnbUzL5WLAkPMQbkqgGw3_5e7-JMEPVYdC48qE0/edit?usp=sharing)

Wrong:
<img width="1114" alt="screen shot 2018-05-04 at 10 23 09 copy" src="https://user-images.githubusercontent.com/21121115/39621130-e92309c8-4f8d-11e8-8628-d9dce4c2ca6e.png">

**Comment by carloslancha** [comment]
@pat270 could you please take a look on this?
