### ISSUE TITLE
Add support for additional action and filter dropdowns in ManagementToolbar

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#875]
Different applications are starting to need different actions inside the management toolbar. It might be interesting to allow for additional action dropdown menus.

For example:

<img width="1356" src="https://user-images.githubusercontent.com/922631/39630615-bc6ecc40-4fa7-11e8-8440-bb598bb5d476.png">

/cc @victorvalle, is there another way this should be implemented?

**Comment by matuzalemsteles** [comment]
hey @victorvalle, Do you have any updates on this?

**Comment by carloslancha** [comment]
Removing from milestone, this feature is not needed right now.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

Thanks!
