### ISSUE TITLE
filter and order status in management bar

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#877]
Filter and order can be disabled only when the original dataset is empty. If the dataset gets empty after search or filter action it must not be possible to disable it as it would won't be possible to return to a previous filtering state.

**Comment by carloslancha** [comment]
@victorvalle Management Toolbar doesn't care about previous dataset. What I understand here is that you want management toolbar to be able to disable filters dropdown separate from the rest of the bar. Is that right? Do we have docs for that? Thx.

**Comment by victorvalle** [comment]
Please review the [documentation] (https://docs.google.com/document/d/1y67UAnbUzL5WLAkPMQbkqgGw3_5e7-JMEPVYdC48qE0/edit?usp=sharing)

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@victorvalle, @matuzalemsteles, please reopen if you think this is still relevant in the context of our `3.x` components.

Thanks!
