### ISSUE TITLE
checkbox status in management bar

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#878]
the checkbox must be disabled whenever the current dataset has zero results. The current dataset can be the original one or a filtered one.

**Comment by carloslancha** [comment]
Where can we reproduce that?

**Comment by victorvalle** [comment]
Documents and media, last pull from @4lejandrito

**Comment by carloslancha** [comment]
@victorvalle if management toolbar is disabled or not must be passed on the component initialization
