### ISSUE TITLE
Update Documentation with Browser Support Matrix

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#888]
Browser support matrix.

**Comment by matuzalemsteles** [comment]
hey @duracell80, Thanks for the report. We will be adding this information to our `README.md` or Docs to make it clear. But we are currently supporting the following browsers.

[Consider](https://github.com/liferay/clay/blob/master/packages/browserslist-config-clay-components/index.js#L2-L10):
```
  last 2 Chrome versions
  last 1 Edge versions
  last 2 Firefox versions
  last 1 Opera versions
  last 2 Safari versions
  last 1 ChromeAndroid versions
  last 2 iOS versions
  Firefox 52
  IE 11
```
