### ISSUE TITLE
Feature Request : Social Sharing Bar

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#889]
Taking this as an example:
https://codemyui.com/social-sharing-follow-button-animation/

Could a new component be created called a "social share bar" that had some modern touch to it with animations? Just anything really that isn't a drop down menu would be awesome.

![social-share-bar](https://user-images.githubusercontent.com/18121278/39886698-d58c9970-5455-11e8-8563-5288f5801212.gif)

**Comment by victorvalle** [comment]
Hi @duracell80 ! I understand your point here. I just want to highlight that for social sharing we contemplate up to 10 options if I'm not wrong in our share portlet. In this case, that portlet is not something under the control of Lexicon or Clay. This is something under Collaboration Team and what they want to do with the social share portlet.
