### ISSUE TITLE
Feature Request : Success / Fail Feedback Inline

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#891]
Rather than the spa loading line and then a success or fail banner that goes away. So when hitting "save" or "publish" ... indicate on the button directly that the action is taking place, offer feedback in the button and if needed use a "tooltip" to explain further if the action failed or succeeded.

https://codemyui.com/submit-button-loading-animation-click/

![submit-button-more-modern-than-success-banner](https://user-images.githubusercontent.com/18121278/39887128-04e44302-5457-11e8-91e9-91c460f234ff.gif)

**Comment by duracell80** [comment]
People press buttons repeatedly if they don't see an immediate effect of their action.

https://psychology.stackexchange.com/questions/4423/why-do-people-press-elevator-call-buttons-repeatedly?rq=1

**Comment by kresimir-coko** [comment]
We haven't gotten any further information on this in the last 6 months, @victorvalle are we going to pursue this or not, so I can close it?

**Comment by drakonux** [comment]
Hey, @kresimir-coko this could be a good improvement for buttons. Some product teams are already doing it. The principle is the same as enabling switch buttons, avoid repetitive interactions. 

So from our side, we could include the variation and documentation in Lexicon but this should come from a product-team with a request ticket cc\ @victorvalle

**Comment by kresimir-coko** [comment]
@drakonux Has there been any development regarding this feature?

**Comment by drakonux** [comment]
Hey as far as I know no, @kresimir-coko sadly Lexicon hasn't received any request or proposal to define this feature yet... 

Anyway, I asked internally in the [slack channel ](https://liferay.slack.com/archives/CKT3L1G58/p1594290881011100)... to know if a team has already developed this feature.

**Comment by kresimir-coko** [comment]
@drakonux any updates here? Has Lexicon defined this feature?

**Comment by victorvalle** [comment]
There is no definition for this. I've seen it working in some modals so far. But it is not a Lexicon pattern.

**Comment by bryceosterhaus** [comment]
Going to close this issue and defer to Lexicon team for if/when a pattern is ever established
