### ISSUE TITLE
Feature Request : Slider / Carousel

### ISSUE THREAD

**Issue by duracell80** [liferay/clay#894]
There seems to be no carousel in Clay. "Stories" are the new sliders, it might be retro, but it's still fashionable.

https://sociallysorted.com.au/social-media-stories-story-format/
https://www.socialmediatoday.com/news/the-rise-of-the-story-format-infographic/516143/

The format is not just for tweens, it can be used for article and trending digests ...
https://news.sky.com/story/the-sky-news-digest-what-it-is-and-how-to-get-it-10639420

**Comment by marcoscv-work** [comment]
You can use BS4 carousel:
https://getbootstrap.com/docs/4.1/components/carousel/
