### ISSUE TITLE
Add label to checkbox on Management Toolbar

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#899]
We need to provide a visual clue to accompany the checkbox when filter dd-button, order and search are not in the configuration. Otherwise, it doesn't have enough visual presence.
label = "Select"

**Comment by carloslancha** [comment]
@victorvalle  Could you please detail this more? Thx

**Comment by victorvalle** [comment]
@carloslancha let me know if this example helps

![image](https://user-images.githubusercontent.com/21121115/40417911-3c32451e-5e81-11e8-8eba-a30ae6ef91ea.png)
