### ISSUE TITLE
Toast Alert needs to be placed at the bottom left and default auto closing time set to 8 secs

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#910]
Please set alert toast to be appear at the bottom left corner of the screen and 8 secs closing time for automatic close ones

**Comment by carloslancha** [comment]
As far as I know the position of the toast alert is not defined by the component but by where is used.

About the closing time, where is that documented?

Thx!

**Comment by jbalsas** [comment]
The position is set in `clay-css` -> https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/components/_alerts.scss#L142-L157

About closing time, not sure where it was, but we're currently employing 5s (maybe following the old pattern?) -> https://github.com/liferay/clay/blob/master/packages/clay-alert/src/ClayAlertBase.js#L37

**Comment by carloslancha** [comment]
Oh, ok, is about that class then, not about the component.

About closing time I asume we're following the "old" patter, what I mean is... where's the new one documented? 😅

**Comment by victorvalle** [comment]
lexicon-system/2.0/admin/patterns/alerts/system-messages/documentation/alerts-lexicon-documentation

**Comment by pat270** [comment]
@victorvalle where should the alert be positioned on small screens? At the bottom still?
