### ISSUE TITLE
SVG Title Attributes Override HTML Title attribute in 1.x

### ISSUE THREAD

**Issue by gregory-bretall** [liferay/clay#926]
I found that a change was made for Clay 2.0.3 that adds the pointer-events: none CSS class to various different files. This prevents the SVG title attribute from overriding the HTML Title attribute of its parent and to fix this issue, the change should be backported to Clay 1.x. 

Original issue can found here: https://github.com/liferay/clay/commit/0bec1327688a0fdafb4cb242535d6163a654c9dc

**Comment by gregory-bretall** [comment]
Fix for 1.x can be found here: https://github.com/liferay/clay/pull/927

**Comment by pat270** [comment]
Merged to 1.x, Thanks!
