### ISSUE TITLE
Clayui.com https://clayui.com/docs/getting_started/introduction.html

### ISSUE THREAD

**Issue by ChrisLynch42** [liferay/clay#962]
This isn't working in Edge, Firefox 60.0.1 or the latest Chrome.  OS is Win 10.   Getting "Error: Namespace "goog.string" already declared." in console.  If there is a more appropriate place to report this please let me know.

**Comment by ChrisLynch42** [comment]
A screenshot
![introduction](https://user-images.githubusercontent.com/1685804/40802822-bcf10e38-64e4-11e8-9513-1150eeab0a10.png)

**Comment by ChrisLynch42** [comment]
This works find in Firefox 60.0.1 on Fedora 28.  Is no one checking this from Windows 10 at all?

**Comment by matuzalemsteles** [comment]
hey @ChrisLynch42, Really this page is broken. Maybe it was when we was generating the pages with Electric ... It has to be fixed.

> This works find in Firefox 60.0.1 on Fedora 28. Is this being checked from Windows 10 regularly?

We do not regularly test in Win 10 unfortunately, but it's supposed to work regardless of the operating system.

Thanks!

**Comment by bryceosterhaus** [comment]
btw, `Error: Namespace "goog.string" already declared.` is a typical error if metal.js is imported more than once. It happens when there are multiple instances of IncrementalDOM

**Comment by jbalsas** [comment]
Yes, as hinted by @matuzalemsteles attempt at a fix, the electric is failing to properly escape the cdn snippet which is causing metal to be included twice.

This has been actually fixed in later versions, so I suspect electric is also using an older one that might be playing here. 

We're considering how to proceed :(

**Comment by matuzalemsteles** [comment]
This has been fixed at https://github.com/liferay/clay/pull/1040.
