### ISSUE TITLE
Some icons don't have the proper viewport 0 0 512 512

### ISSUE THREAD

**Issue by jbalsas** [liferay/clay#979]
We currently have some icons that don't follow our guidelines regarding the `viewport` attribute:

| icon | viewport |
| --- | --- |
| add-role | 0 0 22 23.68 |
| calendar | 0 0 511.4 512 |
| date | 0 0 511.4 512 |
| download | 0 0 384 512 |
| dynamic-data-list | 0 0 448 512 |
| flags-et-EE | 0 0 32 24 |
| flags-th-TH | 0 0 32 24 |
| format | 0 0 448 512 |
| list-ol | 0 0 16 16 |
| mark-as-answer | 0 0 416 448 |
| mark-as-question | 0 0 416 448 |
| mobile-landscape | 0 0 384 288 |
| mobile-portrait | 0 0 384 288 |
| remove-role | 0 0 22 23.68 |
| reply | 0 0 320 255.9961 |
| share | 0 0 448 448 |
| tablet-landscape | 0 0 416 352 |
| tablet-portrait | 0 0 352 416 |
| trash | 0 0 384 513 |

@pat270, can you take care of normalizing these, please? It is causing some rendering issues when used in combination with other things :D

**Comment by emiliano-cicero** [comment]
[trash-svg.zip](https://github.com/liferay/clay/files/2089215/trash-svg.zip)

Hey @marcoscv @jbalsas I included the trash svg, could you try if it work?

**Comment by emiliano-cicero** [comment]
[fixed-icons.zip](https://github.com/liferay/clay/files/2090625/fixed-icons.zip)

@jbalsas @marcoscv these are all the fixed icons and flags from the list, excluding the trash that was included in the previous comment. 
Thank you in advance!

**Comment by jbalsas** [comment]
Thanks a lot @emiliano-cicero!! @pat270, could you process these when you have time? You know better than us the changes needed for them to follow our guidelines 👍

**Comment by emiliano-cicero** [comment]
hey @pat270, I inverted the name of the "add-role" and "remove-role" to "role-add" and "role-remove", this way the icons will be close to each other. Thanks!

**Comment by pat270** [comment]
@emiliano-cicero @jbalsas The rename would be a breaking change, you guys ok with that?

**Comment by jbalsas** [comment]
Not really, no 😂 

The pattern is also `add-*` and `remove-*`, which makes more sense from the usage point of view, so I think I'd rather keep it.

**Comment by emiliano-cicero** [comment]
@jbalsas @pat270 if is a problem or you want to avoid secondary changes, we can move the rename for the 7.2
