### ISSUE TITLE
Dropdown have to close when clicking an iframe in Firefox

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#984]

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, are you sure about this? Seems to be working fine for me... 🤔

**Comment by matuzalemsteles** [comment]
hey @jbalsas, Maybe I expressed wrong the title of the issue 😅, sorry for that. We have the case that when it is clicked inside the iframe the dropdown it has to be closed. This happens only in Firefox. It seems that the `blur` event does not work as expected in Firefox.

**Comment by jbalsas** [comment]
Ah, okay, makes sense. Just FYI, I added some additional changes in Portal that cause dropdown to be destroyed on `navigations` and `portletRefresh`, so this is likely not a big issue anymore.

**Comment by matuzalemsteles** [comment]
Great, we can work on this later. 🙂
Thanks!

**Comment by kresimir-coko** [comment]
Hey @matuzalemsteles is this bug still reproducible?

**Comment by matuzalemsteles** [comment]
Outside of DXP this must still happen, I have to check again. But since this is 2.x, we can think about whether we should start archive 2.x issues.

**Comment by jbalsas** [comment]
> We can think about whether we should start archive 2.x issues.

Let's do that... we can reopen if customers or Support report issues, but let's wrap up `2.x` and only fix critical issues that have a reported impact on customers.

**Comment by matuzalemsteles** [comment]
Perfect looks good to me!

**Comment by bryceosterhaus** [comment]
> archive 

Does this mean close? Wasn't sure if there is a GH feature I am missing.

**Comment by jbalsas** [comment]
> > archive
>
> Does this mean close? Wasn't sure if there is a GH feature I am missing.

Just shred it

![shred](https://user-images.githubusercontent.com/905006/92017044-7806c700-ed53-11ea-9de6-1cc491f79e33.gif)

**Comment by bryceosterhaus** [comment]
![](https://media.giphy.com/media/l3q2TVcIyAepSHUvS/giphy.gif)
