### ISSUE TITLE
Must render a ClayButton when `href` is not passed in ClayNavigationBar

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#985]
We have a use case in Forms that it does not use `href` to do the navigation but listening to the `itemClicked` event to handle.

If we pass `#` to the href, the senna will navigate. And if href is empty, we will not have the cursor `pointer.`

I'm not sure if in this case we should render a Button, let me know your thoughts so I can proceed.

**Comment by jbalsas** [comment]
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@matuzalemsteles, please reopen if you think this is still relevant in the context of our `3.x` components.

Thanks!
